/** Declaration file generated by dts-gen */

declare function compromise(str: string, lexicon: any): any;
declare namespace compromise {
  const version: string;
  function verbose(str: any): void;
  function tokenize(str: string): any;
 }
export = compromise;
