let arr = [
  ["absolute/adjective", "The view from the top of the mountain is absolutely breathtaking."],
  ["accommodating/adjective", "He is always accommodating to his guests."],
  ["advanced/adjective", "The company offers advanced training programs for employees."],
  ["amazing/adjective", "The sunset over the ocean looked absolutely amazing."],
  ["amusing/adjective", "The comedian's jokes were incredibly amusing and had everyone in stitches."],
  ["anarchist/adjective", "He is known for his anarchist views."],
  ["anarchist/adjective", "The anarchist community promotes non-hierarchical structures."],
  ["anarchist/adjective", "The novel explores the complexities of anarchist philosophy."],
  ["anarchist/adjective", "She attended an anarchist conference in the city."],
  ["annoying/adjective", "The loud music was really annoying."],
  ["annoying/adjective", "The constant interruptions during the movie were annoying."],
  ["back/adjective", "I need a back pillow for my chair."],
  ["back/adjective", "He injured his back while lifting heavy boxes."],
  ["back/adjective", "After a long day of work, I have a sore back."],
  ["back/adjective", "She put her books on the back shelf."],
  ["blind/adjective", "They trained a guide dog to assist the blind."],
  ["boring/adjective", "I find history classes to be boring and uninteresting."],
  ["bright/adjective", "The sun is shining bright in the sky."],
  ["bright/adjective", "He wore a bright orange shirt to the party."],
  ["british/adjective", "The British flag is called the Union Jack."],
  ["british/adjective", "She has a British accent and lives in London."],
  ["british/adjective", "I love British music, especially The Beatles."],
  ["british/adjective", "He is studying British history at university."],
  ["caring/adjective", "My mother is always caring and supportive."],
  ["caring/adjective", "The doctor provided caring and empathetic treatment."],
  ["challenging/adjective", "Learning a new language can be challenging."],
  ["challenging/adjective", "Solving complex math problems can be challenging."],
  ["challenging/adjective", "Playing chess against a skilled opponent can be challenging."],
  ["challenging/adjective", "Skiing down a steep slope can be challenging."],
  ["chewy/adjective", "The cookies were soft and chewy."],
  ["chewy/adjective", "The steak was too tough and not chewy enough."],
  ["chewy/adjective", "The candy bar had a deliciously chewy texture."],
  ["chewy/adjective", "The bread was stale and not chewy at all."],
  ["close/adjective", "We're getting close to the finish line."],
  ["closed/adjective", "Please keep the window closed during the meeting."],
  ["closed/adjective", "The shop is closed on Sundays."],
  ["closed/adjective", "The park will be closed for maintenance tomorrow."],
  ["cold/adjective", "She wore a warm coat to protect herself from the cold."],
  ["commercial/adjective", "I saw a commercial for a new car on TV."],
  ["commercial/adjective", "The shopping mall has many commercial stores."],
  ["compelling/adjective", "The book's characters are compelling and relatable."],
  ["compelling/adjective", "The artist's work is visually compelling and unique."],
  ["complex/adjective", "The instructions for assembling the furniture were complex."],
  ["complicated/adjective", "Understanding the instructions can be complicated for beginners."],
  ["complicated/adjective", "Finding a solution to this problem will be complicated."],
  ["confusing/adjective", "The instructions for this game are confusing."],
  ["confusing/adjective", "The road signs in this town are confusing."],
  ["confusing/adjective", "The new computer program is confusing to use."],
  ["confusing/adjective", "I find the English language confusing sometimes."],
  ["continuing/adjective", "The company offers continuing professional development programs."],
  ["convenient/adjective", "This hotel is conveniently located near the airport."],
  ["counterfeit/adjective", "The painting turned out to be a counterfeit."],
  ["crowded/adjective", "The subway is always crowded during rush hour."],
  ["crowded/adjective", "The beach was crowded with tourists on a sunny day."],
  ["cunning/adjective", "The fox used cunning tactics to catch its prey."],
  ["cunning/adjective", "The thief used cunning methods to steal the valuable painting."],
  ["cunning/adjective", "With his cunning smile, he convinced them to trust him."],
  ["daring/adjective", "The movie was filled with daring stunts and action."],
  ["dark/adjective", "She was afraid of walking in the dark."],
  ["dedicated/adjective", "I am dedicated to helping people in need."],
  ["disappointing/adjective", "The food at the restaurant was disappointing, it lacked flavor."],
  ["disappointing/adjective", "The concert was disappointing, the singer was off-key."],
  ["disappointing/adjective", "The weather on our vacation was disappointing, it rained every day."],
  ["double/adjective", "The cake recipe calls for double the amount of sugar."],
  ["drunk/adjective", "He was so drunk that he couldn't walk straight."],
  ["drunk/adjective", "She regretted getting drunk at the party last night."],
  ["drunk/adjective", "He acted foolishly while he was drunk."],
  ["drunk/adjective", "I don't like being around drunk people."],
  ["dry/adjective", "After the swim, I used a towel to dry myself."],
  ["early/adjective", "I wake up early every morning."],
  ["early/adjective", "Her flight was delayed, arriving early evening."],
  ["early/adjective", "The bakery opens early in the morning."],
  ["elderly/adjective", "It is important to provide care for the elderly."],
  ["empty/adjective", "The room is empty, there are no chairs or tables."],
  ["empty/adjective", "The glass was empty, so I refilled it with water."],
  ["endearing/adjective", "Her warm smile and kind nature are truly endearing."],
  ["endearing/adjective", "The character's quirky behavior makes them endearing to the audience."],
  ["enduring/adjective", "The ancient ruins are enduring symbols of history."],
  ["even/adjective", "He wasn't even tall enough to ride the roller coaster."],
  ["even/adjective", "She couldn't even solve the simplest math problem."],
  ["even/adjective", "I can't believe we lost even after trying so hard."],
  ["even/adjective", "The concert tickets are expensive, but it's even more expensive to buy them from scalpers."],
  ["faint/adjective", "She felt faint after running for an hour."],
  ["fair/adjective", "She has fair hair and blue eyes."],
  ["fair/adjective", "He always plays fair in sports."],
  ["free/adjective", "The restaurant gave us free dessert after the meal."],
  ["fried/adjective", "The fries are crispy and fried to perfection."],
  ["fried/adjective", "He likes his eggs fried with bacon."],
  ["gold/adjective", "The necklace is made of pure gold."],
  ["gold/adjective", "The Olympic medals are made of gold."],
  ["gold/adjective", "I bought a pair of gold earrings."],
  ["greasy/adjective", "The pizza had a greasy layer on top."],
  ["greasy/adjective", "He wiped his hands on a greasy cloth."],
  ["greasy/adjective", "Her hair became greasy after not washing it."],
  ["greasy/adjective", "The mechanic had greasy hands from working on the car."],
  ["gross/adjective", "His behavior towards others was grossly inappropriate."],
  ["half/adjective", "I ate half of the pizza for lunch."],
  ["half/adjective", "She spent half of her salary on clothes."],
  ["half/adjective", "He is only half awake in the morning."],
  ["half/adjective", "The painting was only half finished."],
  ["holy/adjective", "The holy book is sacred to believers."],
  ["holy/adjective", "The holy man blessed the crowd with peace."],
  ["holy/adjective", "The holy site is a place of worship."],
  ["holy/adjective", "The holy water is used for baptisms."],
  ["innocent/adjective", "The puppy looked innocent with its big, round eyes."],
  ["innocent/adjective", "The accused pleaded innocent in court."],
  ["insane/adjective", "The roller coaster was insanely fast."],
  ["inspiring/adjective", "His speeches are always inspiring and motivate me."],
  ["inspiring/adjective", "The sunset over the ocean was truly inspiring."],
  ["inspiring/adjective", "The art exhibition was filled with inspiring works."],
  ["instant/adjective", "The internet provides instant access to information."],
  ["instant/adjective", "Coffee machines make instant coffee in seconds."],
  ["involved/adjective", "She was involved in a car accident."],
  ["involved/adjective", "He is involved in several community projects."],
  ["involved/adjective", "The teacher keeps the students involved in the lesson."],
  ["involved/adjective", "She is highly involved in her job."],
  ["known/adjective", "He is known for his great cooking skills."],
  ["known/adjective", "The city is known for its rich history."],
  ["known/adjective", "This book is known for its captivating story."],
  ["late/adjective", "She arrived late for her meeting."],
  ["late/adjective", "He always turns in his assignments late."],
  ["late/adjective", "The train was running late due to heavy rain."],
  ["late/adjective", "I stayed up late studying for the exam."],
  ["latter/adjective", "He visited Paris and London, but chose the latter for his vacation."],
  ["latter/adjective", "The former CEO retired, and the latter took his place."],
  ["latter/adjective", "I have two options: the former is boring, the latter is exciting."],
  ["lazy/adjective", "The cat lazily stretched out on the couch."],
  ["least/adjective", "His least favorite color is yellow."],
  ["least/adjective", "The least expensive option is the basic package."],
  ["least/adjective", "She is the least skilled player on the team."],
  ["least/adjective", "The least crowded time to visit is early morning."],
  ["left/adjective", "The driver checked his left mirror before turning."],
  ["left/adjective", "My left shoe is missing!"],
  ["less/adjective", "This job requires less experience than the other."],
  ["less/adjective", "I prefer using less sugar in my coffee."],
  ["less/adjective", "He had less money after buying the new car."],
  ["less/adjective", "I feel less tired after a good night's sleep."],
  ["long/adjective", "She has long, blonde hair."],
  ["lush/adjective", "The rainforest is home to many lush plants."],
  ["lush/adjective", "She walked through the lush green meadow."],
  ["maximum/adjective", "You can add a maximum of three items to your cart."],
  ["mean/adjective", "The kids were being mean to each other."],
  ["medium/adjective", "He has a medium build and is quite strong."],
  ["moral/adjective", "It is important to have strong moral values."],
  ["moral/adjective", "The movie explores complex moral dilemmas."],
  ["more/adjective", "She wants to learn more about history."],
  ["most/adjective", "She is the most beautiful girl I have ever seen."],
  ["most/adjective", "This is the most interesting book I have read."],
  ["most/adjective", "It was the most delicious meal I have ever tasted."],
  ["most/adjective", "He is the most talented musician I know."],
  ["narrow/adjective", "Her waist looked narrow in the dress."],
  ["offensive/adjective", "His comments about her appearance were offensive."],
  ["offensive/adjective", "The movie contains offensive language and violence."],
  ["offensive/adjective", "She found his behavior towards her offensive."],
  ["official/adjective", "He was given an official warning for breaking the rules."],
  ["open/adjective", "I left the window open for fresh air."],
  ["pale/adjective", "He looks pale because he is sick."],
  ["pale/adjective", "Her pale blue eyes sparkled with excitement."],
  ["patient/adjective", "He waited patiently for his turn to speak during the meeting."],
  ["pointy/adjective", "The princess wore a pointy hat to the party."],
  ["pointy/adjective", "The mountain peak had a pointy shape."],
  ["pointy/adjective", "The witch's nose was long and pointy."],
  ["pointy/adjective", "The pencil has a pointy tip."],
  ["populous/adjective", "The city center is always crowded with the populous."],
  ["potential/adjective", "She has the potential to be a great leader."],
  ["potential/adjective", "The team has shown great potential this season."],
  ["potential/adjective", "He has the potential to become a successful entrepreneur."],
  ["potential/adjective", "The new technology has the potential to revolutionize the industry."],
  ["pricy/adjective", "The hotel room was pricy but luxurious."],
  ["pricy/adjective", "Eating at that restaurant can be pricy."],
  ["pricy/adjective", "This brand of shoes is known to be pricy."],
  ["promising/adjective", "The new restaurant in town has promising reviews."],
  ["public/adjective", "The museum is open to the public."],
  ["racist/adjective", "I don't tolerate racist comments."],
  ["racist/adjective", "She was accused of making racist remarks."],
  ["racist/adjective", "We need to address the issue of racist behavior."],
  ["racist/adjective", "He was criticized for his racist beliefs."],
  ["routine/adjective", "I have a daily routine that helps me stay organized."],
  ["routine/adjective", "She went through her morning routine before going to work."],
  ["routine/adjective", "I find comfort in my evening routine of reading before bed."],
  ["routine/adjective", "He broke free from his monotonous routine and traveled the world."],
  ["same/adjective", "The twins look exactly the same."],
  ["seasoned/adjective", "The seasoned chef prepared a delicious meal."],
  ["seasoned/adjective", "She is a seasoned traveler and knows the best places to visit."],
  ["seasoned/adjective", "The seasoned politician delivered a powerful speech."],
  ["seasoned/adjective", "He is a seasoned player and always performs well."],
  ["secret/adjective", "She kept her secret hidden from everyone."],
  ["shocking/adjective", "I find it shocking that people still believe that."],
  ["shut/adjective", "She keeps her emotions shut and never shows them."],
  ["shut/adjective", "The shop will be shut for the holiday."],
  ["shut/adjective", "They kept their mouths shut about the incident."],
  ["slow/adjective", "My computer is running slow today."],
  ["south/adjective", "I love going on vacations in the south."],
  ["square/adjective", "The table has a square top."],
  ["square/adjective", "She drew a square shape on the paper."],
  ["square/adjective", "The building has a unique square design."],
  ["square/adjective", "The garden has a beautiful square fountain."],
  ["stable/adjective", "The price of the stock has been stable for months."],
  ["stable/adjective", "He keeps his emotions stable in stressful situations."],
  ["stable/adjective", "The bridge is built on stable foundations."],
  ["stunning/adjective", "The bride looked stunning in her white dress."],
  ["super/adjective", "The super cute puppy is playing in the park."],
  ["super/adjective", "My sister got a super exciting job offer."],
  ["super/adjective", "The movie had a super unexpected plot twist."],
  ["surprising/adjective", "It was surprising to see her there."],
  ["surprising/adjective", "Her sudden arrival was surprising to everyone."],
  ["swift/adjective", "The river flowed swiftly downstream."],
  ["tame/adjective", "He tamed his wild hair with gel."],
  ["testy/adjective", "He became testy after waiting in line for hours."],
  ["testy/adjective", "Her testy remark upset everyone at the meeting."],
  ["testy/adjective", "The testy customer complained about the slow service."],
  ["testy/adjective", "She had a testy response to his question."],
  ["tiring/adjective", "Working a full day can be tiring."],
  ["trifling/adjective", "The problem is trifling and can be easily solved."],
  ["trifling/adjective", "Don't waste your time on trifling matters."],
  ["trifling/adjective", "She dismissed his trifling comment with a wave of her hand."],
  ["trifling/adjective", "I'm tired of dealing with trifling people."],
  ["understood/adjective", "The meaning of the word was easily understood."],
  ["understood/adjective", "The concept is not fully understood by everyone."],
  ["understood/adjective", "Her explanation was clear and easily understood."],
  ["upcoming/adjective", "The restaurant is promoting its upcoming special menu."],
  ["welcome/adjective", "She received a warm welcome from everyone."],
  ["welcome/adjective", "The new students were given a friendly welcome."],
  ["wet/adjective", "The ground was wet after the rain."],
  ["willing/adjective", "She is always willing to help."],
  ["willing/adjective", "He was not willing to take risks."],
  ["willing/adjective", "They are willing to learn new things."],
  ["willing/adjective", "The volunteers were willing to lend a hand."],
  ["written/adjective", "The letter was beautifully written and very neat."],
  ["written/adjective", "The book is written in simple language and easy to understand."],
  ["written/adjective", "Her written English has improved a lot over the years."],
  ["against/adjective", "He defended himself against the accusations."],
  ["still/adjective", "She's still waiting for her bus."],
  ["still/adjective", "The noise from the construction site is still loud."],
  ["east/adjective", "The sun rises in the east."],
  ["north/adjective", "The compass always points to the north."],
  ["access/noun", "I forgot my password, so I can't access my account."],
  ["account/noun", "She manages the company's social media accounts."],
  ["adult/noun", "I am an adult and can make my own decisions."],
  ["adult/noun", "As an adult, I enjoy the freedom to make my own choices."],
  ["advertising/noun", "The company invested a lot of money in advertising."],
  ["alternative/noun", "She listens to alternative rock music in her free time."],
  ["arrest/noun", "He was placed under arrest for stealing."],
  ["average/noun", "The teacher calculated the average of the test scores."],
  ["average/noun", "The average temperature in this city is 20 degrees Celsius."],
  ["average/noun", "On average, cats sleep for around 12 to 16 hours a day."],
  ["average/noun", "The average lifespan of a butterfly is just a few weeks."],
  ["balance/noun", "She used a scale to measure her weight and balance."],
  ["billion/noun", "The company's revenue surpassed one billion dollars."],
  ["billion/noun", "The population of this country is over a billion."],
  ["billion/noun", "They donated a billion dollars to charity."],
  ["billion/noun", "The project cost billions of dollars to complete."],
  ["bit/noun", "I only have a small bit of money left."],
  ["blow/noun", "The wind blew softly through the trees."],
  ["blow/noun", "She blew out the candles on her birthday cake."],
  ["boot/noun", "My sister left her boots by the front door."],
  ["bottom/noun", "The cat jumped off the bottom step."],
  ["bowl/noun", "He won the bowling match with a strike."],
  ["brick/noun", "I need to buy more bricks for my project."],
  ["campaign/noun", "The advertising campaign increased sales by 20%."],
  ["campaign/noun", "The charity campaign raised thousands of dollars for a good cause."],
  ["cannibal/noun", "The cannibal prepared a feast with human flesh."],
  ["cannibal/noun", "There were rumors of a cannibal living in the forest."],
  ["cap/noun", "She threw her graduation cap into the air with joy."],
  ["case/noun", "In case of emergency, dial 911."],
  ["chair/noun", "The conference room has twenty chairs for the participants."],
  ["change/noun", "The weather can change quickly in spring."],
  ["channel/noun", "I watch a lot of cooking channels on YouTube."],
  ["channel/noun", "Please turn off the TV channel before you leave."],
  ["cheat/noun", "He was caught cheating during the exam."],
  ["cheat/noun", "She felt guilty after cheating on the test."],
  ["cheat/noun", "Cheating in a relationship can destroy trust."],
  ["chemical/noun", "The chemical reaction produced a colorful and vibrant solution."],
  ["close/noun", "The store is just a close walk from here."],
  ["close/noun", "She lives in the close next to ours."],
  ["close/noun", "The close of the concert was breathtaking."],
  ["close/noun", "They formed a close bond after working together."],
  ["clothing/noun", "The fashion industry plays a big role in clothing trends."],
  ["club/noun", "I joined a book club to meet new people."],
  ["club/noun", "We went to a night club and danced all night."],
  ["club/noun", "He is a member of the chess club at school."],
  ["coin/noun", "The vending machine accepts both bills and coins."],
  ["cold/noun", "I caught a cold and have a runny nose."],
  ["cold/noun", "The cold weather makes me want to stay indoors."],
  ["cold/noun", "I love drinking hot chocolate when it's cold outside."],
  ["cold/noun", "The cold wind made my hands freeze."],
  ["contact/noun", "She has many business contacts in the industry."],
  ["content/noun", "The content of the book was very informative."],
  ["content/noun", "She enjoyed creating digital content for her blog."],
  ["content/noun", "The website's content was well-organized and easy to navigate."],
  ["content/noun", "His presentation lacked substantive content and was not engaging."],
  ["coordinate/noun", "The map has grid lines to help with coordinates."],
  ["count/noun", "The teacher asked the students to count to ten."],
  ["criminal/noun", "The police arrested the criminal yesterday."],
  ["criminal/noun", "The judge sentenced the criminal to prison."],
  ["criminal/noun", "The criminal stole a valuable painting from the museum."],
  ["daily/noun", "I read the daily newspaper every morning."],
  ["daily/noun", "The daily routine includes exercise and meditation."],
  ["daily/noun", "She writes a daily journal to record her thoughts."],
  ["daily/noun", "The restaurant offers a delicious daily special."],
  ["dance/noun", "I love to watch ballet dances."],
  ["dare/noun", "I dare you to try the spicy food."],
  ["dear/noun", "My dear friend, thank you for your help."],
  ["dear/noun", "Please take care of my dear cat."],
  ["dear/noun", "I received a letter from my dear grandmother."],
  ["dear/noun", "The cost of living in this city is dear."],
  ["defeat/noun", "He felt a deep sense of defeat after failing the exam."],
  ["delight/noun", "The children's laughter filled the room with delight."],
  ["delight/noun", "She danced with such grace and delight."],
  ["detail/noun", "Can you provide more details about the project?"],
  ["detail/noun", "I love the attention to detail in this design."],
  ["doubt/noun", "She had doubts about her decision."],
  ["drink/noun", "The bartender served us drinks at the party."],
  ["echo/noun", "The sound of my footsteps echoed in the hallway."],
  ["echo/noun", "Her laughter echoed through the mountains."],
  ["export/noun", "China is a major exporter of electronics."],
  ["farm/noun", "The farmer grows crops and raises animals."],
  ["fast/noun", "He ate his breakfast very fast."],
  ["fast/noun", "She came in the room at a fast pace."],
  ["fast/noun", "He won the race with his fast running."],
  ["fast/noun", "The car drove by at a fast speed."],
  ["favorite/noun", "What is your favorite color?"],
  ["favorite/noun", "My favorite book is 'To Kill a Mockingbird'."],
  ["favorite/noun", "The beach is my favorite place to relax."],
  ["favorite/noun", "Ice cream is everyone's favorite dessert."],
  ["female/noun", "The female lion leads the pride."],
  ["female/noun", "The female bird builds a nest."],
  ["female/noun", "The female doctor is compassionate and skilled."],
  ["final/noun", "I'm really nervous about the final exam."],
  ["final/noun", "This is the final chapter of the book."],
  ["final/noun", "The final decision is up to you."],
  ["fine/noun", "In art, the fine lines add detail and texture."],
  ["first/noun", "She finished first in the race."],
  ["first/noun", "My first job was at a restaurant."],
  ["first/noun", "He made his first million at the age of 25."],
  ["first/noun", "The team won their first championship in 1998."],
  ["fishing/noun", "I enjoy fishing with my friends on weekends."],
  ["fishing/noun", "He caught a big fish while fishing in the lake."],
  ["fishing/noun", "She went fishing early in the morning and caught a few fish."],
  ["fishing/noun", "We will go fishing at the river tomorrow."],
  ["flow/noun", "The movement of Tai Chi is smooth and flowing."],
  ["flow/noun", "The lava flowed down the side of the volcano."],
  ["funding/noun", "The company received funding for its new project."],
  ["game/noun", "I love playing video games with my friends."],
  ["game/noun", "The children are having fun playing games in the park."],
  ["gear/noun", "I need to buy new camping gear."],
  ["gear/noun", "She loves to wear fashionable gears."],
  ["gear/noun", "They use specialized gear for rock climbing."],
  ["general/noun", "The general led the troops into battle."],
  ["general/noun", "In general, I prefer tea over coffee."],
  ["general/noun", "The general consensus was that the plan would succeed."],
  ["general/noun", "I met with the company's general manager to discuss the project."],
  ["giant/noun", "The giant towered over the city, casting a long shadow."],
  ["giant/noun", "The giant stomped its feet and made the ground shake."],
  ["giant/noun", "The giant had a kind heart and helped those in need."],
  ["gift/noun", "They exchanged gifts during the holiday season."],
  ["gold/noun", "I bought a gold necklace for my mom's birthday."],
  ["gold/noun", "The Olympic athlete won a gold medal in swimming."],
  ["good/noun", "I always try to do good for others."],
  ["good/noun", "She is not only smart but also has a good heart."],
  ["good/noun", "Having a good education is important for success."],
  ["good/noun", "He has a good chance of winning the competition."],
  ["grill/noun", "The chef is grilling some vegetables for the salad."],
  ["half/noun", "She cut the cake into two halves."],
  ["hate/noun", "Don't let hate consume your heart and cloud your judgement."],
  ["head/noun", "She shook her head in disbelief."],
  ["heaven/noun", "The view from the mountaintop was heavenly."],
  ["heaven/noun", "The smell of freshly baked bread was heavenly."],
  ["hold/noun", "She lost her hold on reality."],
  ["hoop/noun", "She expertly hula hooped for hours."],
  ["hope/noun", "I have hope that everything will work out."],
  ["host/noun", "The website is hosted on a reliable server."],
  ["inch/noun", "The ruler is twelve inches long."],
  ["justice/noun", "The court system ensures access to justice for all."],
  ["kick/noun", "She took a deep breath and kicked the door down."],
  ["lack/noun", "Despite his intelligence, he lacked the confidence to speak up."],
  ["leaf/noun", "She was collecting colorful autumn leaves."],
  ["leave/noun", "I need to ask for leave tomorrow."],
  ["leverage/noun", "He couldn't succeed without leveraging the power of teamwork."],
  ["lie/noun", "Don't believe everything you hear, some people lie."],
  ["loan/noun", "They paid off their student loans after graduation."],
  ["lock/noun", "Please don't forget to lock the door."],
  ["mean/noun", "What does the word 'mean' mean?"],
  ["mean/noun", "He is not being nice, that's a mean thing to say."],
  ["mean/noun", "Bullying is a form of mean behavior."],
  ["mean/noun", "She always plays mean tricks on her friends."],
  ["medium/noun", "He works as a freelance writer for various mediums."],
  ["mile/noun", "The marathon is 26.2 miles long."],
  ["minor/noun", "My sister is a minor and still goes to high school."],
  ["mistake/noun", "Making mistakes is a part of learning."],
  ["nail/noun", "She painted her nails with bright red polish."],
  ["need/noun", "There is no need to worry, everything will be fine."],
  ["network/noun", "I joined a professional network to expand my connections."],
  ["next/noun", "I will meet you next week."],
  ["next/noun", "The next train will arrive in five minutes."],
  ["next/noun", "What are your plans for the next holiday?"],
  ["next/noun", "The next chapter in the book is very exciting."],
  ["novel/noun", "The novel explores themes of love and loss."],
  ["now/noun", "I need to leave now."],
  ["now/noun", "He is busy right now."],
  ["now/noun", "I'm studying English now."],
  ["now/noun", "We can begin now."],
  ["official/noun", "The official document contains all the necessary information."],
  ["orange/noun", "I ate a juicy orange for breakfast."],
  ["orange/noun", "She peeled the orange and enjoyed the sweet taste."],
  ["orange/noun", "The orange tree was full of ripe fruits."],
  ["other/noun", "I want to try something other than pizza."],
  ["other/noun", "I will ask my teacher for other examples."],
  ["other/noun", "Do you have any other suggestions?"],
  ["other/noun", "I can't find my keys, let's check the other pockets."],
  ["pay/noun", "The company offers competitive pay for employees."],
  ["pay/noun", "His hard work is deserving of fair pay."],
  ["play/noun", "Playing board games is a fun way to spend time with friends and family."],
  ["play/noun", "She has a talent for playing the piano beautifully."],
  ["play/noun", "The children are out in the yard, playing with a ball."],
  ["practice/noun", "Practicing yoga helps me relax and destress."],
  ["premium/noun", "I bought a premium membership for exclusive access."],
  ["premium/noun", "The bottle of wine has a premium price."],
  ["premium/noun", "The company offers a premium service for VIP customers."],
  ["public/noun", "The newspaper reports on public opinion."],
  ["public/noun", "Public transportation is a convenient way to travel."],
  ["public/noun", "The public park is a popular recreational area."],
  ["rain/noun", "Don't forget your umbrella, it's raining outside."],
  ["rating/noun", "The hotel has a five-star rating."],
  ["reach/noun", "She stretched her arm to reach the top shelf."],
  ["reach/noun", "He made a great effort to reach his goals."],
  ["reach/noun", "The company's annual revenue reached new heights."],
  ["real/noun", "The painting is a real masterpiece."],
  ["real/noun", "He is a real gentleman, always polite and courteous."],
  ["real/noun", "Finding a real friend is rare."],
  ["real/noun", "The movie tells a real-life story of survival."],
  ["rent/noun", "She is looking for a place to rent."],
  ["representative/noun", "The company hired a representative to handle customer inquiries."],
  ["representative/noun", "The union appointed a representative to negotiate with the management."],
  ["rest/noun", "He found a comfortable spot to rest under the tree."],
  ["rib/noun", "She wore a ribbed sweater on a chilly day."],
  ["right/noun", "He always fights for what is right."],
  ["right/noun", "She doesn't have the right to speak to me like that."],
  ["right/noun", "I don't think that's the right answer."],
  ["right/noun", "Can you give me a right answer?"],
  ["ring/noun", "The phone rang just as she entered the room."],
  ["ruin/noun", "She was devastated when her house burned to ruins."],
  ["ruin/noun", "He was determined not to let his past ruin his future."],
  ["screen/noun", "He turned off the television screen before leaving."],
  ["second/noun", "He finished the race in second place."],
  ["second/noun", "I'll be with you in a second."],
  ["second/noun", "Can you wait a second, please?"],
  ["second/noun", "She hit the snooze button for a second time."],
  ["senior/noun", "She is a senior studying computer science."],
  ["senior/noun", "The senior team won the championship."],
  ["share/noun", "The siblings always share their toys with each other."],
  ["short/noun", "The little girl has short hair."],
  ["sink/noun", "I need to fix the kitchen sink."],
  ["smile/noun", "I couldn't help but smile at her joke."],
  ["smoke/noun", "Smoking is not allowed inside the building."],
  ["snake/noun", "I am scared of snakes, they're so creepy."],
  ["sort/noun", "What sort of music do you like?"],
  ["sort/noun", "He is not the sort of person you can trust."],
  ["sort/noun", "I need to find a better sort of job."],
  ["sort/noun", "We need to sort out this mess quickly."],
  ["spell/noun", "Can you help me with this spell?"],
  ["spell/noun", "The magician performed an incredible magic spell."],
  ["star/noun", "The Christmas tree was adorned with sparkling star-shaped ornaments."],
  ["stay/noun", "Her stay in the city was short but memorable."],
  ["storage/noun", "I need more storage space for my clothes."],
  ["strike/noun", "The striker scored a goal in the final minutes of the match."],
  ["support/noun", "She is seeking emotional support after the loss."],
  ["suspect/noun", "The suspect denied any involvement in the crime."],
  ["tap/noun", "I heard someone tapping on the window."],
  ["target/noun", "The company set ambitious sales targets."],
  ["thousand/noun", "I have a thousand dollars in my savings account."],
  ["thousand/noun", "The library has a thousand books available for borrowing."],
  ["thousand/noun", "It took me a thousand tries before I finally succeeded."],
  ["thousand/noun", "The population of the city is over a thousand."],
  ["tie/noun", "She tied a bow on the present."],
  ["today/noun", "I am going to the park today."],
  ["today/noun", "Today is a sunny day."],
  ["today/noun", "I have an important meeting today."],
  ["today/noun", "Today is my birthday."],
  ["tomorrow/noun", "I have a meeting tomorrow morning."],
  ["tomorrow/noun", "Tomorrow is my sister's birthday."],
  ["tomorrow/noun", "Don't worry, we'll finish the project tomorrow."],
  ["tomorrow/noun", "Let's go shopping for groceries tomorrow afternoon."],
  ["travel/noun", "I love to travel and explore new places."],
  ["travel/noun", "Travelling allows you to experience different cultures."],
  ["treat/noun", "The children enjoyed their Halloween treats."],
  ["try/noun", "His first try at cooking ended in disaster."],
  ["upgrade/noun", "She decided to upgrade her computer's memory."],
  ["use/noun", "I always make good use of my time."],
  ["volunteer/noun", "The organization is looking for volunteers to help with the event."],
  ["voting/noun", "She exercised her right to voting."],
  ["voting/noun", "Citizens can cast their vote during voting day."],
  ["voting/noun", "The voting process was fair and transparent."],
  ["wait/noun", "Please have a seat and wait for your turn."],
  ["walk/noun", "I enjoy taking long walks in the park."],
  ["walk/noun", "Walking is a great form of exercise."],
  ["warning/noun", "There was a warning about heavy rain."],
  ["weekend/noun", "I usually go hiking in the mountains on weekends."],
  ["well/noun", "She drank water from the well."],
  ["well/noun", "He threw a coin into the well."],
  ["well/noun", "The water in the well is cold."],
  ["well/noun", "The old well is located in the village."],
  ["whip/noun", "The chef whipped the cream until it was thick."],
  ["white/noun", "The cat is pure white."],
  ["white/noun", "I like to wear white clothes."],
  ["white/noun", "The snow is pure white."],
  ["white/noun", "The paper is clean and white."],
  ["whole/noun", "The whole family went on vacation together."],
  ["whole/noun", "He ate the whole pizza by himself."],
  ["whole/noun", "I read the whole book in one day."],
  ["whole/noun", "The whole class is going on a field trip."],
  ["wing/noun", "She ordered a plate of buffalo wings at the restaurant."],
  ["yesterday/noun", "What did you do yesterday evening?"],
  ["yesterday/noun", "I saw him at the supermarket yesterday."],
  ["yesterday/noun", "Yesterday was a very busy day at work."],
  ["yesterday/noun", "I forgot to call her yesterday."],
  ["free/noun", "I got a free sample from the store."],
  ["free/noun", "We offer a free trial for new users."],
  ["free/noun", "The website offers free shipping for orders over $50."],
  ["free/noun", "I got a free ticket to the show."],
  ["light/noun", "The sun provides light during the day."],
  ["light/noun", "She turned on the light in the room."],
  ["light/noun", "The light in the room was very bright."],
  ["light/noun", "Turn off the light when you leave."],
  ["measure/noun", "She used a measuring cup to pour the milk."],
  ["wood/noun", "The forest is filled with tall trees and lush woods."],
  ["wood/noun", "The forest is full of tall trees and thick woods."],
  ["birth/noun", "Her sister gave birth to twins."],
  ["abduct/verb", "The criminal used a van to abduct the child."],
  ["abuse/verb", "He abuses his power and controls everything."],
  ["abuse/verb", "They abuse animals by neglecting their needs."],
  ["abuse/verb", "He abuses drugs and it's ruining his life."],
  ["advocate/verb", "She advocates for environmental conservation."],
  ["advocate/verb", "He advocates for better healthcare policies."],
  ["age/verb", "Her hair started to gray as she aged."],
  ["age/verb", "He looks great for his age."],
  ["age/verb", "Exercise can help slow down the aging process."],
  ["aid/verb", "The organization provides financial aid to students."],
  ["appeal/verb", "The charity appeal raised a lot of money."],
  ["appear/verb", "The magician made a rabbit appear from his hat."],
  ["articulate/verb", "He is learning to articulate his thoughts."],
  ["articulate/verb", "She struggled to articulate her emotions in words."],
  ["articulate/verb", "The professor teaches students how to articulate their arguments."],
  ["articulate/verb", "She used her hands to articulate her ideas."],
  ["attack/verb", "The enemy forces launched a surprise attack."],
  ["attain/verb", "She is determined to attain her fitness goals."],
  ["attain/verb", "They are working hard to attain financial stability."],
  ["average/verb", "On average, people sleep for about eight hours."],
  ["average/verb", "They average five goals per game."],
  ["average/verb", "The temperature averages 25 degrees Celsius in summer."],
  ["average/verb", "On average, it takes two hours to complete the test."],
  ["bar/verb", "I bar the entrance to my house at night."],
  ["bar/verb", "The judge decided to bar his testimony."],
  ["bar/verb", "They bar visitors from taking photographs inside."],
  ["bark/verb", "The tree bark feels rough to the touch."],
  ["behead/verb", "The king ordered to behead the traitor."],
  ["behead/verb", "They threatened to behead the hostages."],
  ["behold/verb", "Behold the beauty of nature at sunset."],
  ["behold/verb", "Behold the majestic eagle soaring through the sky."],
  ["behold/verb", "Behold the stunning view from the mountaintop."],
  ["behold/verb", "Behold the sparkling stars in the night sky."],
  ["best/verb", "I always try my best in exams."],
  ["best/verb", "He always tries to best his personal records."],
  ["best/verb", "They are determined to do their best in the competition."],
  ["betray/verb", "She felt betrayed by her own family."],
  ["bill/verb", "Please bill me for the dinner tonight."],
  ["bill/verb", "The plumber will bill you for the repairs."],
  ["bill/verb", "They forgot to bill me for the subscription."],
  ["bill/verb", "I will bill you for the work done."],
  ["bomb/verb", "The explosion rocked the building as the bomb detonated."],
  ["bomb/verb", "The police were able to defuse the bomb before it exploded."],
  ["border/verb", "The garden borders the river, creating a beautiful view."],
  ["border/verb", "The country borders two different nations."],
  ["border/verb", "They are planning to build a fence to border the property."],
  ["brand/verb", "The company uses a unique branding strategy."],
  ["broadcast/verb", "The news is broadcast at 6 p.m."],
  ["caution/verb", "Please caution me if I make a mistake."],
  ["caution/verb", "The teacher cautions the students to be careful."],
  ["compel/verb", "I couldn't resist the compelling story."],
  ["constrain/verb", "The rules constrain us to follow certain procedures."],
  ["constrain/verb", "Don't let fear constrain you from pursuing your dreams."],
  ["convey/verb", "She used gestures to convey her thoughts."],
  ["convey/verb", "The pictures convey a sense of serenity."],
  ["convey/verb", "He used music to convey his emotions."],
  ["cost/verb", "How much does this shirt cost?"],
  ["cough/verb", "The doctor advised him to try cough syrup."],
  ["curb/verb", "The government is implementing measures to curb pollution."],
  ["curb/verb", "He struggled to curb his anger and remain calm."],
  ["curb/verb", "The company is trying to curb excessive spending."],
  ["curb/verb", "Parents need to curb their children's screen time."],
  ["damage/verb", "The accident caused serious damage to the car."],
  ["debut/verb", "He will debut his new song at the concert."],
  ["debut/verb", "The movie will debut in theaters next week."],
  ["delay/verb", "I apologize for the delay in my response."],
  ["delay/verb", "Traffic delays can be frustrating during rush hour."],
  ["delay/verb", "The flight was delayed due to bad weather."],
  ["delegate/verb", "She delegates the task to her assistant."],
  ["delegate/verb", "He delegates the responsibility to his team members."],
  ["deploy/verb", "The company plans to deploy new marketing strategies."],
  ["derive/verb", "The company derives its profits from international sales."],
  ["desert/verb", "He decided to desert the army."],
  ["desert/verb", "She promised not to desert her friend."],
  ["digest/verb", "I need some time to digest the information."],
  ["digest/verb", "It takes a while for your body to digest certain foods."],
  ["digest/verb", "He struggled to digest the news of her death."],
  ["digest/verb", "She found it hard to digest the criticism."],
  ["dine/verb", "I like to dine at fancy restaurants."],
  ["dine/verb", "He invited her to dine at his place."],
  ["dine/verb", "They decided to dine at the new restaurant."],
  ["disarm/verb", "The police officer was able to disarm the suspect."],
  ["disarm/verb", "The negotiator used empathy to disarm the situation."],
  ["disarm/verb", "The bomb squad worked quickly to disarm the explosive device."],
  ["displease/verb", "The restaurant's slow service is starting to displease customers."],
  ["displease/verb", "We need to find a solution that doesn't displease anyone."],
  ["dispose/verb", "Please dispose of your trash properly."],
  ["dispose/verb", "They are planning to dispose of the company's assets."],
  ["dog/verb", "I love to dog sit for my neighbors."],
  ["dog/verb", "She trained her dog to do tricks."],
  ["dog/verb", "We used to dog walk in the park every morning."],
  ["dog/verb", "He always forgets to dog-proof the house."],
  ["down/verb", "He drinks the milk down quickly."],
  ["down/verb", "Please write down your contact information."],
  ["down/verb", "I will bring the package down for you."],
  ["dream/verb", "I dream of becoming a doctor one day."],
  ["dream/verb", "They dream of owning their own business."],
  ["drill/verb", "I need to drill a hole in the wall."],
  ["drill/verb", "The teacher drills the students on grammar rules."],
  ["embalm/verb", "The embalming process preserves the body's appearance."],
  ["enroll/verb", "I want to enroll in a Spanish class."],
  ["enroll/verb", "She plans to enroll in university next year."],
  ["enroll/verb", "They are excited to enroll in the dance class."],
  ["enroll/verb", "We need to enroll our child in school."],
  ["examine/verb", "Doctors examine their patients to determine the cause of their illness."],
  ["examine/verb", "Scientists examine the evidence to support their research findings."],
  ["examine/verb", "Lawyers examine the contract before signing it."],
  ["exempt/verb", "The school exempts students from taking certain exams."],
  ["exempt/verb", "The company is exempt from certain regulations."],
  ["exhaust/verb", "The kids exhaust themselves playing outside all day."],
  ["exhaust/verb", "The teacher exhausts all the resources for the lesson."],
  ["exhume/verb", "The archaeologists exhume ancient artifacts from the site."],
  ["exhume/verb", "They planned to exhume the treasure hidden in the tomb."],
  ["explore/verb", "I want to explore new cultures and places."],
  ["explore/verb", "She decided to explore the forest on her own."],
  ["explore/verb", "We are planning to explore the ancient ruins."],
  ["explore/verb", "He loves to explore new hiking trails."],
  ["export/verb", "The country's main export is agricultural products."],
  ["fast/verb", "They will fast before the medical procedure."],
  ["filter/verb", "She used a coffee filter to make her morning coffee."],
  ["filter/verb", "Use a filter to remove impurities from the oil."],
  ["flatter/verb", "Don't flatter yourself, not everyone likes you."],
  ["float/verb", "The boat floats on the water."],
  ["float/verb", "She watched the cloud float away."],
  ["float/verb", "He filled the pool and watched the plastic duck float."],
  ["flower/verb", "The roses will flower in the spring."],
  ["flower/verb", "She loves to watch flowers blooming."],
  ["flower/verb", "Water the plants regularly for them to flower."],
  ["flower/verb", "The garden looks beautiful when it flowers."],
  ["forward/verb", "Please forward the email to the HR department."],
  ["forward/verb", "She pressed the button to forward the message."],
  ["franchise/verb", "Franchising can be a profitable business strategy."],
  ["giggle/verb", "She couldn't help but giggle at the funny video."],
  ["glue/verb", "Please glue the pieces together firmly."],
  ["glue/verb", "She loves to glue paper shapes onto cards."],
  ["glue/verb", "The label wouldn't glue onto the package."],
  ["grill/verb", "I like to grill hamburgers on the barbecue."],
  ["grill/verb", "She loves to grill vegetables for dinner."],
  ["grill/verb", "They're planning to grill some fish at the picnic."],
  ["gulp/verb", "Don't gulp your food, chew it slowly."],
  ["harass/verb", "The teacher warned the students not to harass each other."],
  ["harass/verb", "He felt harassed by the constant phone calls from telemarketers."],
  ["haunt/verb", "Ghosts haunt the old house every night."],
  ["help/verb", "I need help with my homework."],
  ["incline/verb", "She inclines towards a career in medicine."],
  ["install/verb", "I need to install a new app on my phone."],
  ["install/verb", "They are going to install a new air conditioner."],
  ["install/verb", "We should hire a professional to install the fence."],
  ["kid/verb", "I like to kid around with my friends."],
  ["kid/verb", "Don't kid yourself, he is not serious."],
  ["kid/verb", "She loves to kid her little brother."],
  ["kid/verb", "They always kid each other about their height."],
  ["kidnap/verb", "The criminals tried to kidnap the wealthy businessman."],
  ["kidnap/verb", "They planned to kidnap the famous actress for ransom."],
  ["kidnap/verb", "He was charged with attempting to kidnap a young girl."],
  ["lower/verb", "Please lower the volume of the music."],
  ["lower/verb", "They decided to lower the price of the product."],
  ["master/verb", "I am working hard to master English."],
  ["master/verb", "They are working together to master the dance routine."],
  ["mess/verb", "Please clean up your room. It's a mess."],
  ["mount/verb", "The climber mounts the steep mountain peak."],
  ["mow/verb", "We hired someone to mow the lawn."],
  ["nurse/verb", "She will nurse the baby to sleep."],
  ["nurse/verb", "The mother will nurse her sick child."],
  ["nurse/verb", "They nurse a hospice patient with compassion."],
  ["obey/verb", "The soldiers were ordered to obey their commanding officer."],
  ["obsess/verb", "Don't obsess over small mistakes. Move on."],
  ["obsess/verb", "He tends to obsess over every detail."],
  ["obsess/verb", "You shouldn't let your worries obsess you."],
  ["overwhelm/verb", "I feel overwhelmed with all the work."],
  ["park/verb", "I need to find a place to park my car."],
  ["park/verb", "The parking lot is full, let's find another spot."],
  ["perfect/verb", "He is trying to perfect his piano skills."],
  ["perfect/verb", "She practices every day to perfect her dance moves."],
  ["perfect/verb", "They are working hard to perfect their English pronunciation."],
  ["perfect/verb", "I need to practice more to perfect my cooking skills."],
  ["pity/verb", "He pities himself for making that mistake."],
  ["please/verb", "Please turn off the lights before leaving."],
  ["please/verb", "Could you please pass me the salt?"],
  ["please/verb", "Please wait for a moment, I'll be right there."],
  ["please/verb", "Can you please repeat that one more time?"],
  ["pollute/verb", "Burning fossil fuels pollutes the air we breathe."],
  ["pound/verb", "The hammer pounds the nail into the wood."],
  ["pound/verb", "I pound the dough to make bread."],
  ["pound/verb", "He pounds his fist on the table in frustration."],
  ["pound/verb", "The rain pounds against the window pane."],
  ["promote/verb", "The company promotes a positive work environment."],
  ["rain/verb", "The rain is falling gently, creating a peaceful atmosphere."],
  ["rain/verb", "I always love the smell of rain in the air."],
  ["rap/verb", "She enjoys listening to rap music."],
  ["rap/verb", "We went to a rap concert yesterday."],
  ["rape/verb", "It is important to educate people about rape."],
  ["rape/verb", "She was a victim of a brutal rape."],
  ["rape/verb", "They are working to prevent sexual assaults and rapes."],
  ["reap/verb", "Farmers reap the crops in autumn."],
  ["reap/verb", "The company is starting to reap the benefits."],
  ["refract/verb", "Light refracts when passing through different mediums."],
  ["refract/verb", "The glass lens refracts the light rays."],
  ["refract/verb", "The prism refracts white light into different colors."],
  ["refract/verb", "The index of refraction determines how much light refracts."],
  ["refund/verb", "The company policy allows customers to request a refund."],
  ["refund/verb", "She had to wait several days for the refund to process."],
  ["rejoice/verb", "He rejoices at the good news."],
  ["resemble/verb", "The twins resemble each other a lot."],
  ["resemble/verb", "The modern apartment buildings resemble each other."],
  ["resemble/verb", "Her new haircut resembles the one in the magazine."],
  ["resemble/verb", "The small seaside town resembles a postcard."],
  ["respect/verb", "She earns respect by treating others kindly."],
  ["riot/verb", "The crowd started to riot after the football match."],
  ["rot/verb", "Don't let food rot in the fridge."],
  ["rot/verb", "Leaves rot on the forest floor."],
  ["round/verb", "They round out their meal with dessert."],
  ["ruin/verb", "Don't let one mistake ruin your day."],
  ["safeguard/verb", "It is important to safeguard your privacy on social media."],
  ["safeguard/verb", "The security guard safeguards the entrance of the building."],
  ["sample/verb", "Can you please sample this dessert?"],
  ["shelter/verb", "The family decided to shelter from the rain."],
  ["shelter/verb", "They found shelter in a small cave."],
  ["shelter/verb", "The homeless people sought shelter for the night."],
  ["shelter/verb", "The trees provided shelter from the scorching sun."],
  ["smell/verb", "The bakery smells like freshly baked bread."],
  ["snow/verb", "I love watching the snow fall."],
  ["snow/verb", "We went skiing in the fresh snow."],
  ["snow/verb", "They love to play in the snow."],
  ["sob/verb", "Don't be afraid to sob openly, it can be cathartic."],
  ["sob/verb", "She tried to hide her sobs, but they were too powerful."],
  ["spam/verb", "She received a lot of spam emails in her inbox."],
  ["speed/verb", "The car is speeding down the highway."],
  ["sponsor/verb", "The NGO sponsors educational programs for underprivileged children."],
  ["sponsor/verb", "She was looking for a sponsor for her art project."],
  ["spy/verb", "The detective spies on the suspected criminal."],
  ["spy/verb", "She spies through the keyhole to listen."],
  ["stab/verb", "He made a fake knife and pretended to stab."],
  ["staff/verb", "We need to staff the new restaurant with experienced waiters."],
  ["stain/verb", "She uses a special detergent to remove stains."],
  ["steer/verb", "She learned to steer a car yesterday."],
  ["steer/verb", "They are trying to steer the conversation."],
  ["steer/verb", "We should steer clear of the danger."],
  ["stoop/verb", "The old man stoops to pet the cat."],
  ["suppress/verb", "The government tried to suppress the protest."],
  ["suppress/verb", "She tried to suppress her laughter during the meeting."],
  ["suppress/verb", "The medication helps to suppress the symptoms of the disease."],
  ["surface/verb", "Fish surface to breathe in oxygen."],
  ["surpass/verb", "Her talent surpasses that of her peers."],
  ["surpass/verb", "The new technology surpasses the previous models."],
  ["sway/verb", "The tree sways gently in the wind."],
  ["sway/verb", "The crowd sways to the music at the concert."],
  ["sway/verb", "The politician's speech sways the voters' opinions."],
  ["torture/verb", "The dictator used torture to silence dissent."],
  ["torture/verb", "Victims of war often suffer physical and emotional torture."],
  ["torture/verb", "It is important to stand against torture and advocate for human rights."],
  ["transform/verb", "The caterpillar transforms into a beautiful butterfly."],
  ["transform/verb", "Exercise can help transform your body."],
  ["trouble/verb", "I don't want to trouble you, but could you help me?"],
  ["trouble/verb", "He is always in trouble with his boss."],
  ["trouble/verb", "Don't trouble yourself, I can handle it."],
  ["uphold/verb", "As a judge, his duty is to uphold justice."],
  ["wed/verb", "The couple wed in a traditional church wedding."],
  ["welcome/verb", "I welcome you to our home."],
  ["welcome/verb", "They welcome all new members."],
  ["welcome/verb", "The teacher welcomes questions from students."],
  ["workshop/verb", "I attended a workshop on photography."],
  ["workshop/verb", "She organized a workshop for graphic designers."],
  ["workshop/verb", "They will be conducting a workshop on coding."],
  ["workshop/verb", "We are hosting a workshop on public speaking."],
  ["crumble/verb", "The old building started to crumble and collapse."],
  ["crumble/verb", "The cookies crumble easily when you touch them."],
  ["venture/verb", "We decided to venture into the city after dark."],
  ["venture/verb", "They want to venture into the world of entrepreneurship."],
  ["develop/verb", "She is developing a new product."],
  ["develop/verb", "They are working together to develop a plan."],
  ["develop/verb", "The company is developing a new product line."]
]
import nlp from './src/three.js'
let bad = 0
let good = 0
arr.forEach(a => {
  let doc = nlp(a[1])
  if (doc.has(`{${a[0]}}`)) {
    good += 1
  } else {
    bad += 1
    console.log(a[0], '  -  ', a[1])
  }
})
console.log('good', good)
console.log('bad', bad)