/* eslint-disable no-console, no-unused-vars */
import nlp from './src/four.js'


const arr = [
  //  %Plural|Verb% %Noun|Verb%
  // `[Shares] [finish] [lower] on [sustained] selling`,
  // `forward: appartment pricing`,
  // `[wear] [deserted] look`,
  // `[Place] items in the top`,

  // imperatives
  // `C'mon, Luisa, you have a chance`,
  // `would you mind watching Ben for me?`,
  // `i see the girl, respect the guard, and go right home`,
  // `if Chandler had kissed her, would you hear him out?`,
  // `Honey, would you like a snack?`,
  // `teach him five lessons`,
  // `Have things to occupy yourself during the trip.`,
  // `Service wise, no complaints`,

  // 'The Bill was passed',
  // 'give parents their power',
  // `were overrun by insurgents`,
  // `been overrun by insurgents`,
  // `would not give rise`,
  // `he will stroll downtown`,
  // `I wasn't born until he was`,
  // `people who will explore`,
  // 'Does he blink frequently?',
  // 'they have more product.',
  // `re-tool my exhaust`,


  // `soy green tea lattes are [amazing]`,
  // `Seeing them [drive] away`,
  // 'some require equity in order to qualify',
  // `[Light] [travels] [faster] than [sound]`,
  // `[this] [is] [a] [cool] [place] hang out`,
  // `Not, not more bureaucracy, not more red tape`,
  // `we'll soon make him shudder.`,
  // `just like a dream`,
  // `[Why] did [Jon] Snow [stand] in line`,
  // `he would [later] [confess] [that]`,
  // `why the job [matters] to you`,
  // `women never [like] Joey`,
  // `I let another one [get] [away]`,
  // `He was [shot] in the chest and arm and [received] shrapnel [wounds]`,
  // `[Compile] information about [claims] you filed`,
  // `The flounder and fungus are [prepared] Sichuan style`,
  // `a win-win situation`,
  // `[Browse] [to] the C:\\RealityFactory`,
  // `Uh-huh Jim [Carrey] is [challenged]`,
  // `Stand tall [hold] your head high`,
  // `Renovations at Union Station [reveal] pristine facade`,
  // `[Proofread] your writing`,
  // `And the word [spread] of Billy the Kid`,
  // `You can [soon] [drink] coffee`,
  // `[Advocates] [lock] court premises`,
  // `HC [calls] for CBI chargesheet`,
  // `where a train [stops]`,
  // `[estimates] [show] that by the end`,
  // `Spice [slashes] airtime [rates] for [cashcard] users`,
  // `And [more] Americans [finish] college`,
  // `[where] an ocean liner is [launched]`,

  // ^%Noun|Verb% %Plural|Verb%

  // `it's milk`,
  // `it's well known`,
  // `when's he coming`,
  // `it's well known for it's burger`,
  // `so that [workers] can take [time] [off]`,
  // `Statistics [show] [that] teen pregnancy`,
  // `were as [follows]`,
  // 'cake',
  // 'cupcakes',
  // 'earthquakes',
  // 'mistakes',
  // 'snakes',
  // '3 takes',

  // `hundred shots in my face and [hands]`,
  // `he'd make it right`,
  // `look more intimidating.`,
  // `Men are like bank accounts.`,
  // `can we account for earthquakes?`,
  // `back to my friends house`,
  // `a filling pita wrap.`,
  // `when it comes to grades.`,
  // `your education and training`,
  // `ensure privacy, and save lives.`,
  // `Air, air, air, air, air, air`,
  // ` previous games were generally mirrors`,
  // `the bird song was deafening.`,
  // ` side to side`,
  // 'their past mistakes',

  // `very runny and soup-like.`,
  // `bring you back`,
  // `community of cooperation, not conflict.`, //something wrong here?
  // `show you trigger discipline.`,
  // `show u trigger discipline.`,
  // `the medicines and stuff.`,
  // `Type your desired [name] into the box`,
  // 'the appalling chemical-weapons attack',
  // `[The] [housing] and employment crisis`,

  // 'then better bring dog too',
  // `brighter [lights] and [colours]`,
  // `during your Christmas [shopping] this year`,
  // `the sharing of electron [pairs] between atoms`,
  // `[Brainstorm] other ways of [understanding] your [appearance]`,
  // `[all] you [vegetarians]`,

  // `eating [in] the [parking] lot`,
  // `walked [hand] [in] hand`,
  // `Have a [back] up buddy`,
  // `from the [gravest] health threat that they face an [epidemic] of teen smoking`,
  // `Walk or [bike] everywhere you can`,
  // `I had a [roasted] chicken [craving] one day`,
  // `an [evidentiary] [hearing]`,
  // `a monopoly on East Coast [gambling]`,
  // 'Bite or [lick] your lower lip',
  // `suddenly [there] came a [tapping]`,
  // 'his break ups',
  // 'the fill up',
  // 'Fill up the tank',
  // 'we stood back so carefully',
  // `[Speed] Post [moves] at snail pace`,
  // 'use reverse psychology',
  // 'Hash Browns',
  // `a giant [glimmering] silver web`,
  // 'No walk in the park for us',
  // 'there was no wait on a Saturday morning.',
  // 'during my next stay in Orlando.',
  // 'an elaborate pick-up line',
  // 'It is an evil growing out of our institutions',
  // 'his best-known lyrics',
  // 'a thalidomide binding protein.',
  // 'wearing a moth-eaten suit.',
  // 'for the days ahead stay firm',
  // 'a new Act compelling registration',
  // 'The vet considered amputation',
  // 'with your hands up',
  // `you seem unapproachable and [closed] [off]`,
  // 'the instant he walked',
  // `make your girl [feel] greater`,
  // `what your Majesty [asks] of me`,
  // `did the sailor [ground] his son`,
  // `But before I do that [let] me put a hand on it`,
  // `if you [like] comics`,
  // `helped [marshal] support`,
  // `If a ball [hit] into play rolls foul before passing through the infield`,
  // `does my molecule [bind]`,

  // `Next, take a look`,
  // 'hella-boring meeting',
  // 'his best-known lyrics',
  // 'went right in',

  // missing nouns
  // `A little [make up] can go a long way`,
  // `Take your own personality and [values] into consideration`,
  // `this witch who turned men into [pigs]`,
  // `[Snow] White roommate who fits the category`,
  // ' when he was out hunting',


  // `like dinner [parties] or game nights`,
  // `Let me take you to [places]`,
  // `Guess who's doing [laundry] there too`,
  // `You've had [smoke] blown your way`,
  // `With more [holes] than a rug`,
  // `It's [buzzcut] season anyway`,

  // 'you are hugging parked cars',
  // 'recognizing written language',
  // 'For being organized',
  // 'a nearly overpowering feeling',
  // 'keep subsidizing skyrocketing tuition',
  // `Grimy [work] you guys do`,

  // `dump truck smashing into [overpass] on the 401`,
  // `[Iron] Maiden land in Beijing`,


  // missing adjectives
  // `The [holy] [well] of St Guron`,
  // `with many [key] commanders`,
  // `'Cause girl you're [amazing] just the way you are`,
  // `things turn [sour] really quick`,
  // `their [chosen] paths`,
  // `Are you [as] [confused] as I am`,
  // `I wish my [only] problem in life`,
  // `You and my sister, sittin’ in a tree.`,
  // `prepayment has taken 45 days alone`


  // `countries as a whole seem brighter`,
  // `four years of uninterrupted economic growth`,
  // `because people of varying ethnicities`,

  // 'designed to help use the newly written',
  // 'Power watchdog raps utility',
  // 'Boost user engagement',
  // 'To place close together',
  // 'Hash Browns',
  // 'Next, take a look at your dropsuit fittings',
  // 'NMDAR signaling increases RanBP1 expression',
  // 'in the room where you usually nurse',
  // 'call and reserve one',

  // 'to contact her in an emergency',
  // 'firms may face difficulties in raising',
  // 'her opera stage debut in 1957',
  // 'place tea bags in hot water',
  // 'Solar panels work fine in overcast conditions',
  // 'while the therapist watches',
  // 'All right relax',
  // `If you notice swelling`,
  // `and whisk to fully incorporate`,
  // 'gourmet burgers back home in LA',
  // `Going shopping alone`,
  // 'SO FREAKING GOOD!',
  // 'consider becoming a member',
  // 'would not work right.',
  // 'doing a holiday card together',
  // `when the killer strikes`,
  // `Your refusal may cause hurt and disappointment`,
  // 'Carpenter\'s one year of coaching',
  // `Holly objects to Nia's character`,
  // ' visa & travel assistance',
  // 'Let the dishwasher run for an entire cycle',
  // 'by encouraging carpooling',
  // 'Ohio beaver trapping season starts in late December ',
  // 'We Personally Guarantee Everything We Sell',
  // 'we personally guarantee',
  // // 'unless we win',
  // // 'and we offer',
  // "method for measuring",
  // "responsibility for setting",
  // "Attack and resolve your issues",
  // 'Co-accused denied bail',

  // 'they are stored unshelled in silos',
  // 'the liver is found associated with the kidneys',
  // 'over-joyous',
  // 'must-see movie',


  // 'some coarsely-ground peanut fragments included',
  // 'food scientists working in the US',
  // 'helping prepare',
  // 'selecting paste',
  // 'bringing hope',
  // 'getting time off',
  // 'for being born',
  // 'fans that are blowing feel amazing',
  // 'recognizing written language',
  // 'a process of milling roasted peanuts',
  // 'my racing snail',
  // 'a nearly overpowering feeling',
  // 'and so requires stirring',
  // 'a nearly overpowering feeling',
  // ' whilst being rocked to permit even roasting.',
  // '300 gang-related',
  // '5 must-try burgers',
  // 'vacuum-sealed',
  // 'raise standards of living',
  // 'sources of saturated and monounsaturated fats',
  // `I'm practising walking`,

  // 'going to stop posting schedules',
  // `Sports awards to be given on Tuesday`
  'A/B tester',
  'I watched the Twelve Days of Christmas',

  `how tasty something looks and ask if they have tried it.`,
  `besides the larger chains, Fairley's adds considerable value`,
  // "5. The signatories to this Declaration",
]

nlp.verbose('tagger')
const str = arr[0]
nlp(str).debug()