exports.data = [{
		"present": "arises",
		"gerund": "arising",
		"past": "arose",
		"infinitive": "arise",
		"participle": "arisen"
	}, {
		"infinitive": "babysit",
		"present": "babysits",
		"past": "babysat",
		"gerund": "babysitting",
		"participle": "babysat"
	}, {
		"infinitive": "be",
		"present": "is",
		"gerund": "being",
		"past": "were",
		"participle": "been"
	}, {
		"infinitive": "be",
		"present": "is",
		"gerund": "being",
		"past": "were",
		"participle": "been"
	}, {
		"infinitive": "beat",
		"present": "beats",
		"past": "beat",
		"gerund": "beating",
		"participle": "beaten"
	}, {
		"present": "becomes",
		"gerund": "becoming",
		"past": "became",
		"infinitive": "become",
		"participle": "become"
	}, {
		"present": "bends",
		"gerund": "bending",
		"past": "bent",
		"infinitive": "bend",
		"participle": "bent"
	}, {
		"infinitive": "begin",
		"present": "begins",
		"past": "began",
		"gerund": "begining",
		"participle": "begun"
	}, {
		"infinitive": "bet",
		"present": "bets",
		"past": "bet",
		"gerund": "betting",
		"participle": "bet"
	}, {
		"infinitive": "bind",
		"present": "binds",
		"past": "bound",
		"gerund": "binding",
		"participle": "bound"
	}, {
		"present": "bites",
		"gerund": "biting",
		"past": "bit",
		"infinitive": "bite",
		"participle": "bitten"
	}, {
		"infinitive": "bleed",
		"present": "bleeds",
		"past": "bled",
		"gerund": "bleeding",
		"participle": "bled"
	}, {
		"infinitive": "blow",
		"present": "blows",
		"past": "blew",
		"gerund": "blowing",
		"participle": "blown"
	}, {
		"infinitive": "break",
		"present": "breaks",
		"past": "broke",
		"gerund": "breaking",
		"participle": "broken"
	}, {
		"infinitive": "breed",
		"present": "breeds",
		"past": "bred",
		"gerund": "breeding",
		"participle": "bred"
	}, {
		"infinitive": "bring",
		"present": "brings",
		"past": "brought",
		"gerund": "bringing",
		"participle": "brought"
	}, {
		"infinitive": "broadcast",
		"present": "broadcasts",
		"past": "broadcast",
		"gerund": "broadcasting",
		"participle": "broadcast"
	}, {
		"infinitive": "build",
		"present": "builds",
		"past": "built",
		"gerund": "building",
		"participle": "built"
	}, {
		"infinitive": "buy",
		"present": "buys",
		"past": "bought",
		"gerund": "buying",
		"participle": "bought"
	}, {
		"present": "catches",
		"gerund": "catching",
		"past": "caught",
		"infinitive": "catch",
		"participle": "caught"
	}, {
		"infinitive": "choose",
		"present": "chooses",
		"past": "chose",
		"gerund": "choosing",
		"participle": "chosen"
	}, {
		"present": "comes",
		"gerund": "coming",
		"past": "came",
		"infinitive": "come",
		"participle": "come"
	}, {
		"infinitive": "cost",
		"present": "costs",
		"past": "cost",
		"gerund": "costing",
		"participle": "cost"
	}, {
		"infinitive": "cut",
		"present": "cuts",
		"past": "cut",
		"gerund": "cutting",
		"participle": "cut"
	}, {
		"infinitive": "deal",
		"present": "deals",
		"past": "dealt",
		"gerund": "dealing",
		"participle": "dealt"
	}, {
		"infinitive": "dig",
		"present": "digs",
		"past": "dug",
		"gerund": "digging",
		"participle": "dug"
	}, {
		"infinitive": "do",
		"present": "does",
		"past": "did",
		"gerund": "doing",
		"participle": "done"
	}, {
		"infinitive": "draw",
		"present": "draws",
		"past": "drew",
		"gerund": "drawing",
		"participle": "drawn"
	}, {
		"infinitive": "drink",
		"present": "drinks",
		"past": "drank",
		"gerund": "drinking",
		"participle": "drunk"
	}, {
		"infinitive": "drive",
		"present": "drives",
		"past": "drove",
		"gerund": "driving",
		"participle": "driven"
	}, {
		"infinitive": "eat",
		"present": "eats",
		"past": "ate",
		"gerund": "eating",
		"participle": "eaten"
	}, {
		"infinitive": "fall",
		"present": "falls",
		"past": "fell",
		"gerund": "falling",
		"participle": "fallen"
	}, {
		"infinitive": "feed",
		"present": "feeds",
		"past": "fed",
		"gerund": "feeding",
		"participle": "fed"
	}, {
		"infinitive": "feel",
		"present": "feels",
		"past": "felt",
		"gerund": "feeling",
		"participle": "felt"
	}, {
		"infinitive": "fight",
		"present": "fights",
		"past": "fought",
		"gerund": "fighting",
		"participle": "fought"
	}, {
		"infinitive": "find",
		"present": "finds",
		"past": "found",
		"gerund": "finding",
		"participle": "found"
	}, {
		"infinitive": "fly",
		"present": "flys",
		"past": "flew",
		"gerund": "flying",
		"participle": "flown"
	}, {
		"infinitive": "forbid",
		"present": "forbids",
		"past": "forbade",
		"gerund": "forbiding",
		"participle": "forbidden"
	}, {
		"infinitive": "forget",
		"present": "forgets",
		"past": "forgot",
		"gerund": "forgeting",
		"participle": "forgotten"
	}, {
		"infinitive": "forgive",
		"present": "forgives",
		"past": "forgave",
		"gerund": "forgiving",
		"participle": "forgiven"
	}, {
		"infinitive": "freeze",
		"present": "freezes",
		"past": "froze",
		"gerund": "freezing",
		"participle": "frozen"
	}, {
		"infinitive": "get",
		"present": "gets",
		"past": "got",
		"gerund": "getting",
		"participle": "gotten"
	}, {
		"infinitive": "give",
		"present": "gives",
		"past": "gave",
		"gerund": "giving",
		"participle": "given"
	}, {
		"infinitive": "go",
		"present": "goes",
		"gerund": "going",
		"past": "went",
		"participle": "gone"
	}, {
		"infinitive": "grow",
		"present": "grows",
		"past": "grew",
		"gerund": "growing",
		"participle": "grown"
	}, {
		"infinitive": "hang",
		"present": "hangs",
		"past": "hung",
		"gerund": "hanging",
		"participle": "hung"
	}, {
		"infinitive": "have",
		"present": "haves",
		"past": "had",
		"gerund": "having",
		"participle": "had"
	}, {
		"infinitive": "hear",
		"present": "hears",
		"past": "heard",
		"gerund": "hearing",
		"participle": "heard"
	}, {
		"infinitive": "hide",
		"present": "hides",
		"past": "hid",
		"gerund": "hiding",
		"participle": "hidden"
	}, {
		"infinitive": "hit",
		"present": "hits",
		"past": "hit",
		"gerund": "hitting",
		"participle": "hit"
	}, {
		"infinitive": "hold",
		"present": "holds",
		"past": "held",
		"gerund": "holding",
		"participle": "held"
	}, {
		"infinitive": "hurt",
		"present": "hurts",
		"past": "hurt",
		"gerund": "hurting",
		"participle": "hurt"
	}, {
		"present": "keeps",
		"gerund": "keeping",
		"past": "kept",
		"infinitive": "keep",
		"participle": "kept"
	}, {
		"infinitive": "know",
		"present": "knows",
		"past": "knew",
		"gerund": "knowing",
		"participle": "known"
	}, {
		"infinitive": "lay",
		"present": "lays",
		"past": "laid",
		"gerund": "laying",
		"participle": "laid"
	}, {
		"infinitive": "lead",
		"present": "leads",
		"past": "led",
		"gerund": "leading",
		"participle": "led"
	}, {
		"infinitive": "leave",
		"present": "leaves",
		"past": "left",
		"gerund": "leaving",
		"participle": "left"
	}, {
		"present": "lends",
		"gerund": "lending",
		"past": "lent",
		"infinitive": "lend",
		"participle": "lent"
	}, {
		"infinitive": "let",
		"present": "lets",
		"past": "let",
		"gerund": "letting",
		"participle": "let"
	}, {
		"infinitive": "lie",
		"present": "lies",
		"past": "lay",
		"gerund": "lying",
		"participle": "lied"
	}, {
		"infinitive": "light",
		"present": "lights",
		"past": "lit",
		"gerund": "lighting",
		"participle": "lit"
	}, {
		"infinitive": "lose",
		"present": "loses",
		"past": "lost",
		"gerund": "losing",
		"participle": "lost"
	}, {
		"infinitive": "make",
		"present": "makes",
		"past": "made",
		"gerund": "making",
		"participle": "made"
	}, {
		"infinitive": "mean",
		"present": "means",
		"past": "meant",
		"gerund": "meaning",
		"participle": "meant"
	}, {
		"infinitive": "meet",
		"present": "meets",
		"past": "met",
		"gerund": "meeting",
		"participle": "met"
	}, {
		"infinitive": "pay",
		"present": "pays",
		"past": "paid",
		"gerund": "paying",
		"participle": "paid"
	}, {
		"infinitive": "put",
		"present": "puts",
		"past": "put",
		"gerund": "putting",
		"participle": "put"
	}, {
		"infinitive": "quit",
		"present": "quits",
		"past": "quit",
		"gerund": "quitting",
		"participle": "quit"
	}, {
		"infinitive": "read",
		"present": "reads",
		"past": "read",
		"gerund": "reading",
		"participle": "read"
	}, {
		"infinitive": "ride",
		"present": "rides",
		"past": "rode",
		"gerund": "riding",
		"participle": "ridden"
	}, {
		"infinitive": "ring",
		"present": "rings",
		"past": "rang",
		"gerund": "ringing",
		"participle": "rung"
	}, {
		"present": "rises",
		"gerund": "rising",
		"past": "rose",
		"infinitive": "rise",
		"participle": "risen"
	}, {
		"infinitive": "run",
		"present": "runs",
		"past": "ran",
		"gerund": "runing",
		"participle": "run"
	}, {
		"infinitive": "say",
		"present": "says",
		"past": "said",
		"gerund": "saying",
		"participle": "said"
	}, {
		"infinitive": "see",
		"present": "sees",
		"past": "saw",
		"gerund": "seing",
		"participle": "seen"
	}, {
		"infinitive": "sell",
		"present": "sells",
		"past": "sold",
		"gerund": "selling",
		"participle": "sold"
	}, {
		"present": "sends",
		"gerund": "sending",
		"past": "sent",
		"infinitive": "send",
		"participle": "sent"
	}, {
		"infinitive": "set",
		"present": "sets",
		"past": "set",
		"gerund": "setting",
		"participle": "set"
	}, {
		"infinitive": "shake",
		"present": "shakes",
		"past": "shook",
		"gerund": "shaking",
		"participle": "shaken"
	}, {
		"infinitive": "shine",
		"present": "shines",
		"past": "shone",
		"gerund": "shining",
		"participle": "shone"
	}, {
		"infinitive": "shoot",
		"present": "shoots",
		"past": "shot",
		"gerund": "shooting",
		"participle": "shot"
	}, {
		"infinitive": "show",
		"present": "shows",
		"past": "showed",
		"gerund": "showing",
		"participle": "shown"
	}, {
		"infinitive": "shut",
		"present": "shuts",
		"past": "shut",
		"gerund": "shutting",
		"participle": "shut"
	}, {
		"infinitive": "sing",
		"present": "sings",
		"past": "sang",
		"gerund": "singing",
		"participle": "sung"
	}, {
		"infinitive": "sink",
		"present": "sinks",
		"past": "sank",
		"gerund": "sinking",
		"participle": "sunk"
	}, {
		"infinitive": "sit",
		"present": "sits",
		"past": "sat",
		"gerund": "sitting",
		"participle": "sat"
	}, {
		"present": "sleeps",
		"gerund": "sleepping",
		"past": "slept",
		"infinitive": "sleep",
		"participle": "slept"
	}, {
		"infinitive": "slide",
		"present": "slides",
		"past": "slid",
		"gerund": "sliding",
		"participle": "slid"
	}, {
		"infinitive": "speak",
		"present": "speaks",
		"past": "spoke",
		"gerund": "speaking",
		"participle": "spoken"
	}, {
		"present": "spends",
		"gerund": "spending",
		"past": "spent",
		"infinitive": "spend",
		"participle": "spent"
	}, {
		"infinitive": "spin",
		"present": "spins",
		"past": "spun",
		"gerund": "spinning",
		"participle": "spun"
	}, {
		"infinitive": "spread",
		"present": "spreads",
		"past": "spread",
		"gerund": "spreading",
		"participle": "spread"
	}, {
		"infinitive": "stand",
		"present": "stands",
		"past": "stood",
		"gerund": "standing",
		"participle": "stood"
	}, {
		"infinitive": "steal",
		"present": "steals",
		"past": "stole",
		"gerund": "stealing",
		"participle": "stolen"
	}, {
		"infinitive": "stick",
		"present": "sticks",
		"past": "stuck",
		"gerund": "sticking",
		"participle": "stuck"
	}, {
		"infinitive": "sting",
		"present": "stings",
		"past": "stung",
		"gerund": "stinging",
		"participle": "stung"
	}, {
		"infinitive": "strike",
		"present": "strikes",
		"past": "struck",
		"gerund": "striking",
		"participle": "struck"
	}, {
		"infinitive": "swear",
		"present": "swears",
		"past": "swore",
		"gerund": "swearing",
		"participle": "sworn"
	}, {
		"present": "sweeps",
		"gerund": "sweeping",
		"past": "swept",
		"infinitive": "sweep",
		"participle": "swept"
	}, {
		"infinitive": "swim",
		"present": "swims",
		"past": "swam",
		"gerund": "swiming",
		"participle": "swum"
	}, {
		"infinitive": "swing",
		"present": "swings",
		"past": "swung",
		"gerund": "swinging",
		"participle": "swung"
	}, {
		"infinitive": "take",
		"present": "takes",
		"past": "took",
		"gerund": "taking",
		"participle": "taken"
	}, {
		"infinitive": "teach",
		"present": "teachs",
		"past": "taught",
		"gerund": "teaching",
		"participle": "taught"
	}, {
		"infinitive": "tear",
		"present": "tears",
		"past": "tore",
		"gerund": "tearing",
		"participle": "torn"
	}, {
		"infinitive": "tell",
		"present": "tells",
		"past": "told",
		"gerund": "telling",
		"participle": "told"
	}, {
		"infinitive": "think",
		"present": "thinks",
		"past": "thought",
		"gerund": "thinking",
		"participle": "thought"
	}, {
		"infinitive": "throw",
		"present": "throws",
		"past": "threw",
		"gerund": "throwing",
		"participle": "thrown"
	}, {
		"infinitive": "understand",
		"present": "understands",
		"past": "understood",
		"gerund": "understanding",
		"participle": "understood"
	}, {
		"infinitive": "wake",
		"present": "wakes",
		"past": "woke",
		"gerund": "waking",
		"participle": "woken"
	}, {
		"infinitive": "wear",
		"present": "wears",
		"past": "wore",
		"gerund": "wearing",
		"participle": "worn"
	}, {
		"present": "wins",
		"gerund": "winning",
		"past": "won",
		"infinitive": "win",
		"participle": "won"
	}, {
		"infinitive": "withdraw",
		"present": "withdraws",
		"past": "withdrew",
		"gerund": "withdrawing",
		"participle": "withdrawn"
	}, {
		"present": "writes",
		"gerund": "writing",
		"past": "wrote",
		"infinitive": "write",
		"participle": "written"
	}, {
		"infinitive": 'tie',
		"present": 'ties',
		"past": 'tied',
		"gerund": 'tying'
	}


]