module.exports = [
  ['nah', 'no'],
  ['paw', 'foot'],
  ['jot', 'write'],
  ['aid', 'help'],
  ['mid', 'middle'],
  ['yup', 'yes'],
  ['pun', 'joke'],
  ['bin', 'box'],
  ['guy', 'man'],
  ['nab', 'take'],
  ['wee', 'small'],
  ['joy', 'happiness'],
  ['nay', 'no'],
  ['gal', 'girl'],
  ['gal', 'girl'],
  ['ply', 'layer'],
  ['cop', 'police officer'],
  ['nil', 'nothing'],
  ['nip', 'bite'],
  ['tho', 'though'],
  ['pic', 'picture'],
  ['clad', 'clothed'],
  ['snip', 'cut'],
  ['afar', 'far away'],
  ['slam', 'hit'],
  ['aint', 'is not'],
  ['snug', 'comfortable'],
  ['snug', 'tight'],
  ['soar', 'fly'],
  ['sofa', 'couch'],
  ['sore', 'painful'],
  ['zips', 'goes quickly'],
  ['slay', 'kill'],
  ['zany', 'crazy'],
  ['leap', 'jump'],
  ['spun', 'turned'],
  ['awry', 'wrong'],
  ['lard', 'fat'],
  ['bash', 'hit'],
  ['mock', 'make fun of'],
  ['i\'ve', 'I have'],
  ['i\'ll', 'I will'],
  ['i\'ll', 'I will'],
  ['hymn', 'song'],
  ['howl', 'yell'],
  ['bide', 'wait'],
  ['bids', 'offers'],
  ['lame', 'uncool'],
  ['swap', 'trade'],
  ['bold', 'strong'],
  ['mute', 'silent'],
  ['mute', 'silent'],
  ['hike', 'walk'],
  ['heed', 'attention'],
  ['wise', 'smart'],
  ['chop', 'cut'],
  ['rife', 'rich'],
  ['wimp', 'weak person'],
  ['hath', 'has'],
  ['whom', 'who'],
  ['harm', 'trouble'],
  ['lust', 'desire'],
  ['whim', 'sudden desire'],
  ['halt', 'stop'],
  ['guys', 'men'],
  ['slid', 'slipped'],
  ['grip', 'hold'],
  ['grin', 'smile'],
  ['grim', 'bad'],
  ['kook', 'crazy person'],
  ['glum', 'sad'],
  ['glad', 'happy'],
  ['wham', 'hit'],
  ['mane', 'hair'],
  ['weds', 'marries'],
  ['junk', 'garbage'],
  ['we\'d', 'we had'],
  ['reek', 'smell'],
  ['wash', 'clean'],
  ['pony', 'small horse'],
  ['gaze', 'look'],
  ['dire', 'bad'],
  ['ache', 'pain'],
  ['wail', 'cry'],
  ['fury', 'violence'],
  ['tale', 'story'],
  ['tame', 'kind'],
  ['task', 'job'],
  ['lush', 'rich'],
  ['task', 'job'],
  ['seek', 'search for'],
  ['veer', 'turn'],
  ['fend', 'fight'],
  ['vast', 'big'],
  ['vary', 'change'],
  ['vary', 'change'],
  ['jest', 'make fun of'],
  ['nigh', 'near'],
  ['jeer', 'make fun of'],
  ['fare', 'price'],
  ['ploy', 'trick'],
  ['cozy', 'comfortable'],
  ['reap', 'enjoy'],
  ['curt', 'short'],
  ['nope', 'no'],
  ['nosy', 'rude'],
  ['raze', 'burn'],
  ['thus', 'so'],
  ['tidy', 'clean'],
  ['odor', 'smell'],
  ['tiny', 'little'],
  ['toss', 'throw'],
  ['rage', 'anger'],
  ['deem', 'declare'],
  ['edit', 'change'],
  ['rsvp', 'respond'],
  ['duty', 'job'],
  ['oust', 'remove'],
  ['town', 'city'],
  ['pact', 'agreement'],
  ['memo', 'note'],
  ['paws', 'feet'],
  ['eager', 'excited'],
  ['motto', 'saying'],
  ['humor', 'comedy'],
  ['latch', 'lock'],
  ['as to', 'about'],
  ['large', 'big'],
  ['hound', 'dog'],
  ['jaunt', 'trip'],
  ['witty', 'smart'],
  ['acute', 'sharp'],
  ['adage', 'saying'],
  ['murky', 'dark'],
  ['honor', 'respect'],
  ['brink', 'edge'],
  ['hobby', 'interest'],
  ['burly', 'strong'],
  ['adept', 'expert'],
  ['jaded', 'tired'],
  ['hiked', 'walked'],
  ['razed', 'burned'],
  ['carve', 'cut'],
  ['muted', 'silenced'],
  ['cease', 'end'],
  ['hefty', 'strong'],
  ['hefty', 'large'],
  ['macro', 'large'],
  ['havoc', 'chaos'],
  ['silly', 'funny'],
  ['irate', 'angry'],
  ['haute', 'high'],
  ['admit', 'say'],
  ['ravel', 'twist'],
  ['abuse', 'hurt'],
  ['smash', 'hit'],
  ['adore', 'love'],
  ['hardy', 'strong'],
  ['smirk', 'smile'],
  ['adorn', 'decorate'],
  ['clasp', 'grip'],
  ['cleft', 'crack'],
  ['cling', 'hold'],
  ['muted', 'silenced'],
  ['abhor', 'hate'],
  ['clone', 'copy'],
  ['rifle', 'gun'],
  ['a few', 'some'],
  ['lager', 'beer'],
  ['gusto', 'great pleasure'],
  ['whiff', 'smell'],
  ['rigid', 'hard'],
  ['quite', 'truly'],
  ['rival', 'enemy'],
  ['comfy', 'comfortable'],
  ['laden', 'filled'],
  ['pouch', 'bag'],
  ['loner', 'loser'],
  ['sever', 'cut'],
  ['snout', 'nose'],
  ['gonna', 'going to'],
  ['queue', 'line'],
  ['glean', 'take'],
  ['query', 'question'],
  ['amend', 'change'],
  ['weepy', 'not strong'],
  ['weeps', 'cries'],
  ['amiss', 'wrong'],
  ['among', 'with'],
  ['among', 'with'],
  ['weary', 'tired'],
  ['we\'ve', 'we have'],
  ['we\'ll', 'we will'],
  ['among', 'with'],
  ['pooch', 'dog'],
  ['kooky', 'crazy'],
  ['slain', 'killed'],
  ['giddy', 'excited'],
  ['abode', 'living place'],
  ['gazed', 'looked'],
  ['arose', 'grew'],
  ['waist', 'middle'],
  ['as to', 'about'],
  ['knack', 'skill'],
  ['merry', 'happy'],
  ['as to', 'for'],
  ['funds', 'money'],
  ['a few', 'some'],
  ['speak', 'talk'],
  ['vowed', 'promised'],
  ['tardy', 'late'],
  ['lynch', 'kill'],
  ['jumbo', 'large'],
  ['shove', 'push'],
  ['tempo', 'speed'],
  ['folks', 'people'],
  ['reply', 'answer'],
  ['final', 'last'],
  ['vexed', 'confused'],
  ['plush', 'rich'],
  ['niche', 'place'],
  ['shout', 'yell'],
  ['spoke', 'talked'],
  ['shiny', 'bright'],
  ['singe', 'burn'],
  ['squad', 'team'],
  ['cools', 'gets colder'],
  ['stale', 'old'],
  ['punch', 'hit'],
  ['tenet', 'belief'],
  ['plump', 'round'],
  ['awful', 'very bad'],
  ['fared', 'did'],
  ['awful', 'terrible'],
  ['reset', 'restart'],
  ['shall', 'will'],
  ['fancy', 'special'],
  ['vague', 'unclear'],
  ['leapt', 'jumped'],
  ['rouse', 'excite'],
  ['terse', 'short'],
  ['route', 'path'],
  ['crass', 'rude'],
  ['crave', 'want'],
  ['thief', 'robber'],
  ['cruel', 'mean'],
  ['cruel', 'mean'],
  ['plead', 'beg'],
  ['based', 'built'],
  ['cyber', 'internet'],
  ['joted', 'wrote'],
  ['cycle', 'circle'],
  ['began', 'started'],
  ['begin', 'start'],
  ['belch', 'burp'],
  ['evade', 'avoid'],
  ['dandy', 'nice'],
  ['psalm', 'song'],
  ['timid', 'shy'],
  ['timid', 'shy'],
  ['yield', 'give'],
  ['onset', 'starting'],
  ['ennui', 'boredom'],
  ['scour', 'search'],
  ['decoy', 'fake'],
  ['inane', 'stupid'],
  ['tires', 'wheels'],
  ['title', 'name'],
  ['shall', 'will'],
  ['lunge', 'reach'],
  ['belly', 'stomach'],
  ['eject', 'remove'],
  ['below', 'under'],
  ['usurp', 'take'],
  ['abate', 'make less'],
  ['photo', 'picture'],
  ['yearn', 'desire'],
  ['rumor', 'story'],
  ['usage', 'use'],
  ['urban', 'city'],
  ['duvet', 'blanket'],
  ['moist', 'wet'],
  ['worry', 'fear'],
  ['dense', 'full'],
  ['outdo', 'beat'],
  ['dread', 'fear'],
  ['image', 'picture'],
  ['trail', 'path'],
  ['ached', 'hurt'],
  ['trash', 'garbage'],
  ['aches', 'pains'],
  ['skill', 'ability'],
  ['jolly', 'happy'],
  ['peril', 'great danger'],
  ['burley', 'strong'],
  ['devise', 'make'],
  ['tugged', 'pulled'],
  ['perils', 'dangers'],
  ['peered', 'looked'],
  ['device', 'tool'],
  ['trendy', 'popular'],
  ['tremor', 'shaking'],
  ['tussle', 'fight'],
  ['treaty', 'agreement'],
  ['dismal', 'sad'],
  ['sacred', 'important'],
  ['desire', 'want'],
  ['parody', 'make fun of'],
  ['rumour', 'story'],
  ['deride', 'make fun of'],
  ['donate', 'give'],
  ['rumors', 'stories'],
  ['depict', 'show'],
  ['depart', 'leave'],
  ['ousted', 'removed'],
  ['dreary', 'unhappy'],
  ['unjust', 'wrong'],
  ['untrue', 'wrong'],
  ['peruse', 'look at'],
  ['useful', 'helpful'],
  ['photos', 'pictures'],
  ['deemed', 'declared'],
  ['scheme', 'plan'],
  ['elated', 'excited'],
  ['tossed', 'threw'],
  ['deduct', 'take away'],
  ['titled', 'named'],
  ['deduct', 'remove'],
  ['pieced', 'put'],
  ['pistol', 'gun'],
  ['scorch', 'burn'],
  ['enable', 'let'],
  ['placed', 'put'],
  ['enigma', 'mystery'],
  ['placed', 'put'],
  ['enrich', 'improve'],
  ['decade', 'ten years'],
  ['tinker', 'play'],
  ['tinker', 'play'],
  ['entire', 'whole'],
  ['debris', 'broken parts'],
  ['obtain', 'get'],
  ['dazzle', 'impress'],
  ['placid', 'quiet'],
  ['novels', 'stories'],
  ['dangle', 'hang'],
  ['tidier', 'cleaner'],
  ['esteem', 'respect'],
  ['notion', 'idea'],
  ['notify', 'tell'],
  ['tidied', 'cleaned'],
  ['dainty', 'delicate'],
  ['thwack', 'hit'],
  ['dagger', 'knife'],
  ['exceed', 'pass'],
  ['thrive', 'live well'],
  ['dagger', 'knife'],
  ['cycled', 'circled'],
  ['vacate', 'leave'],
  ['expand', 'grow'],
  ['scurry', 'run'],
  ['extend', 'grow'],
  ['extent', 'amount'],
  ['craved', 'wanted'],
  ['theory', 'idea'],
  ['nipped', 'bit'],
  ['crafty', 'smart'],
  ['plenty', 'lots'],
  ['crabby', 'rude'],
  ['varies', 'changes'],
  ['varies', 'changes'],
  ['faring', 'doing'],
  ['fasten', 'lock'],
  ['fathom', 'understand'],
  ['nimble', 'quick'],
  ['faulty', 'broken'],
  ['costly', 'expensive'],
  ['plunge', 'fall'],
  ['corpse', 'dead body'],
  ['feeble', 'weak'],
  ['vastly', 'greatly'],
  ['fended', 'fought'],
  ['veered', 'turned'],
  ['vexing', 'confusing'],
  ['nibble', 'bite'],
  ['contra', 'against'],
  ['viable', 'possible'],
  ['fooled', 'tricked'],
  ['forked', 'split'],
  ['formal', 'nice'],
  ['formal', 'important'],
  ['viewed', 'watched'],
  ['tavern', 'bar'],
  ['viewer', 'watcher'],
  ['visage', 'face'],
  ['voiced', 'said'],
  ['vowing', 'promising'],
  ['seldom', 'rarely'],
  ['voyage', 'trip'],
  ['frolic', 'play'],
  ['select', 'choose'],
  ['tactic', 'idea'],
  ['funded', 'paid for'],
  ['ponder', 'thought'],
  ['vulgar', 'gross'],
  ['futile', 'useless'],
  ['gabbed', 'talked'],
  ['ponder', 'give thought to'],
  ['wailed', 'cry'],
  ['gamble', 'bet'],
  ['wallop', 'hit'],
  ['warden', 'guard'],
  ['gazing', 'looking'],
  ['genial', 'warm of heart'],
  ['gentle', 'careful'],
  ['gently', 'carefully'],
  ['get-go', 'beginning'],
  ['warped', 'bent'],
  ['washer', 'cleaner'],
  ['naught', 'nothing'],
  ['giggle', 'laugh'],
  ['wedded', 'married'],
  ['portly', 'fat'],
  ['rotate', 'turn'],
  ['glitch', 'problem'],
  ['gloomy', 'sad'],
  ['comply', 'agree'],
  ['wheeze', 'breathe hard'],
  ['nagged', 'complained'],
  ['compel', 'force'],
  ['potent', 'strong'],
  ['gratis', 'free'],
  ['robust', 'strong'],
  ['common', 'normal'],
  ['mutter', 'say'],
  ['ripple', 'small wave'],
  ['grubby', 'dirty'],
  ['muting', 'silencing'],
  ['guffaw', 'laugh'],
  ['guided', 'led'],
  ['guided', 'led'],
  ['gullet', 'throat'],
  ['coined', 'created'],
  ['coerce', 'force'],
  ['whilst', 'while'],
  ['clique', 'group'],
  ['halted', 'stopped'],
  ['prefer', 'hope'],
  ['hardly', 'barely'],
  ['whimsy', 'light'],
  ['wholly', 'all'],
  ['harmed', 'hurt'],
  ['wildly', 'crazily'],
  ['choppy', 'rough'],
  ['wished', 'wanted'],
  ['hazard', 'danger'],
  ['cheery', 'happy'],
  ['wishes', 'wants'],
  ['ceased', 'ended'],
  ['carved', 'cut'],
  ['highly', 'very'],
  ['revise', 'change'],
  ['revere', 'respect'],
  ['hiking', 'walking'],
  ['cancel', 'stop'],
  ['cancel', 'stop'],
  ['devout', 'serious'],
  ['muster', 'get'],
  ['breach', 'break'],
  ['boldly', 'strongly'],
  ['bobbed', 'dipped'],
  ['severe', 'serious'],
  ['horrid', 'terrible'],
  ['reveal', 'show'],
  ['bidder', 'offerer'],
  ['humane', 'kind'],
  ['humble', 'simple'],
  ['propel', 'push'],
  ['bicker', 'argue'],
  ['humour', 'comedy'],
  ['proper', 'respectful'],
  ['bestow', 'give'],
  ['proper', 'right'],
  ['berate', 'criticize'],
  ['motive', 'reason'],
  ['supper', 'dinner'],
  ['retort', 'answer'],
  ['morsel', 'bit'],
  ['retain', 'keep'],
  ['impart', 'give'],
  ['impart', 'teach'],
  ['mocked', 'made fun of'],
  ['subset', 'part'],
  ['bellow', 'yell'],
  ['bellow', 'yell'],
  ['stored', 'kept'],
  ['retain', 'keep'],
  ['stated', 'said'],
  ['banish', 'ban'],
  ['yonder', 'there'],
  ['you\'ll', 'you will'],
  ['mishap', 'mistake'],
  ['attend', 'go'],
  ['infant', 'baby'],
  ['misery', 'sadness'],
  ['sprain', 'twist'],
  ['inform', 'tell'],
  ['inform', 'tell'],
  ['spoken', 'said'],
  ['ingest', 'eat'],
  ['you\'ll', 'you will'],
  ['you\'ve', 'you have'],
  ['shoddy', 'poor'],
  ['astray', 'wrong'],
  ['assist', 'help'],
  ['inject', 'put'],
  ['injure', 'hurt'],
  ['injure', 'hurt'],
  ['insane', 'crazy'],
  ['midway', 'half way'],
  ['pursue', 'go after'],
  ['zenith', 'top'],
  ['shoved', 'pushed'],
  ['sorrow', 'sadness'],
  ['method', 'way'],
  ['putrid', 'gross'],
  ['merely', 'only'],
  ['quaint', 'nice'],
  ['somber', 'serious'],
  ['solemn', 'serious'],
  ['arouse', 'excite'],
  ['intact', 'complete'],
  ['sobbed', 'cried'],
  ['intend', 'plan'],
  ['soared', 'flew'],
  ['resign', 'leave'],
  ['annual', 'yearly'],
  ['so far', 'until now'],
  ['quirky', 'weird'],
  ['merely', 'only'],
  ['snooze', 'sleep'],
  ['adrift', 'floating'],
  ['invent', 'create'],
  ['invent', 'create'],
  ['menace', 'danger'],
  ['raffle', 'ticket-competition'],
  ['mellow', 'soft'],
  ['adored', 'loved'],
  ['raging', 'angry'],
  ['admire', 'respect'],
  ['silent', 'quiet'],
  ['medley', 'mix'],
  ['meadow', 'field'],
  ['egg on', 'encourage'],
  ['issued', 'gave'],
  ['issued', 'gave'],
  ['jabbed', 'poked'],
  ['razing', 'burning'],
  ['jargon', 'idiom'],
  ['actual', 'real'],
  ['jaunty', 'happy'],
  ['reaped', 'enjoyed'],
  ['rebels', 'turn'],
  ['jiggle', 'shake'],
  ['simmer', 'boil'],
  ['jitter', 'shake'],
  ['sinful', 'bad'],
  ['reside', 'live'],
  ['aching', 'hurting'],
  ['reside', 'live'],
  ['joting', 'writing'],
  ['jotted', 'wrote'],
  ['jotted', 'wrote'],
  ['jovial', 'happy'],
  ['recent', 'new'],
  ['joyful', 'happy'],
  ['joyful', 'happy'],
  ['joyous', 'happy'],
  ['due to', 'because of'],
  ['reeked', 'smelt'],
  ['manner', 'act'],
  ['accost', 'trouble'],
  ['slight', 'small'],
  ['kidnap', 'take'],
  ['kindly', 'nicely'],
  ['accord', 'agreement'],
  ['mangle', 'damage'],
  ['get go', ' beginning'],
  ['slides', 'slips'],
  ['go bad', 'become bad'],
  ['refine', 'improve'],
  ['mallet', 'hammer'],
  ['malice', 'hate'],
  ['reform', 'change'],
  ['lacked', 'didn\'t have'],
  ['lacked', 'missed'],
  ['regain', 'get back'],
  ['of use', 'helpful'],
  ['lagoon', 'lake'],
  ['abused', 'hurt'],
  ['region', 'area'],
  ['absurd', 'strange'],
  ['sliced', 'cut'],
  ['larger', 'bigger'],
  ['absorb', 'take up'],
  ['malady', 'injury'],
  ['rescue', 'save'],
  ['lavish', 'rich'],
  ['rescue', 'save'],
  ['leaped', 'jumped'],
  ['abrupt', 'sudden'],
  ['learnt', 'learned'],
  ['legend', 'story'],
  ['slayer', 'killer'],
  ['lesion', 'wound'],
  ['liable', 'responsible'],
  ['mainly', 'mostly'],
  ['abroad', 'in another country'],
  ['remark', 'statement'],
  ['linked', 'connected'],
  ['liquor', 'alcohol'],
  ['mailed', 'sent'],
  ['aboard', 'on'],
  ['skinny', 'thin'],
  ['loathe', 'hate'],
  ['locals', 'people'],
  ['locate', 'find'],
  ['logged', 'recorded'],
  ['abhors', 'hates'],
  ['abduct', 'take away'],
  ['lovely', 'very nice'],
  ['lugged', 'pulled'],
  ['lyrics', 'words'],
  ['lumped', 'put'],
  ['repair', 'fix'],
  ['lunged', 'reached'],
  ['abates', 'makes less'],
  ['abated', 'made less'],
  ['purify', 'clean'],
  ['removes', 'takes away'],
  ['procure', 'get'],
  ['copious', 'large'],
  ['fooling', 'tricking'],
  ['forging', 'making'],
  ['cordial', 'nice'],
  ['forking', 'splitting'],
  ['briefed', 'taught'],
  ['corpses', 'dead bodies'],
  ['briefly', 'quickly'],
  ['show up', 'appear'],
  ['burglar', 'robber'],
  ['plucked', 'took'],
  ['frankly', 'basically'],
  ['frantic', 'excited'],
  ['frantic', 'crazy'],
  ['proceed', 'went'],
  ['in case', 'if'],
  ['segment', 'part'],
  ['segment', 'part'],
  ['hold on', 'wait'],
  ['bursted', 'broke'],
  ['proceed', 'go ahead'],
  ['blew up', 'exploded'],
  ['crafted', 'made'],
  ['tactful', 'respectful'],
  ['crafted', 'made'],
  ['funding', 'money'],
  ['abridge', 'shorten'],
  ['furious', 'very angry'],
  ['furnace', 'heater'],
  ['primary', 'first'],
  ['aroused', 'excited'],
  ['crashed', 'smashed'],
  ['gabbing', 'talking'],
  ['capture', 'get'],
  ['revered', 'respected'],
  ['arrange', 'prepare'],
  ['gambled', 'bet'],
  ['garment', 'clothing'],
  ['quarrel', 'fight'],
  ['craving', 'wanting'],
  ['created', 'made'],
  ['neglect', 'ignore'],
  ['seminar', 'class'],
  ['pleased', 'happy'],
  ['genteel', 'nice'],
  ['crowded', 'filled'],
  ['crucial', 'important'],
  ['genuine', 'real'],
  ['crucial', 'very important'],
  ['crucial', 'important'],
  ['resided', 'lived'],
  ['carving', 'cutting'],
  ['cruised', 'drove'],
  ['giggled', 'laughed'],
  ['pleaded', 'begged'],
  ['crumple', 'crush'],
  ['vacuous', 'empty'],
  ['gleaned', 'taken'],
  ['glimpse', 'quick look'],
  ['relaxed', 'comfortable'],
  ['nagging', 'complaining'],
  ['cursory', 'quick'],
  ['pursues', 'goes after'],
  ['wishing', 'wanting'],
  ['chapter', 'part'],
  ['gradual', 'slow'],
  ['gradual', 'slow'],
  ['revised', 'changed'],
  ['at once', 'immediately'],
  ['presume', 'assume'],
  ['mystify', 'amaze'],
  ['at odds', 'in disagreement'],
  ['cherish', 'love'],
  ['grinned', 'smiled'],
  ['plagued', 'troubled'],
  ['prey on', 'eat'],
  ['pursued', 'went after'],
  ['dangled', 'hanging'],
  ['aspects', 'parts'],
  ['several', 'some'],
  ['chopped', 'cut'],
  ['dazzled', 'impressed'],
  ['prepare', 'get ready'],
  ['adamant', 'sure'],
  ['decades', 'tens of years'],
  ['chuckle', 'laugh'],
  ['zipping', 'going quickly'],
  ['utopian', 'hopefull'],
  ['halting', 'stopping'],
  ['pivotal', 'important'],
  ['keep on', 'continue'],
  ['willing', 'ready'],
  ['piecing', 'putting'],
  ['rejoice', 'celebrate'],
  ['harming', 'hurting'],
  ['adeptly', 'expertly'],
  ['readily', 'quickly'],
  ['purport', 'claim'],
  ['haywire', 'crazy'],
  ['abducts', 'takes away'],
  ['clamber', 'climb'],
  ['usurper', 'taker'],
  ['defiled', 'dirtied'],
  ['heinous', 'terrible'],
  ['whimper', 'cry'],
  ['swapped', 'traded'],
  ['hideous', 'terrible'],
  ['usurped', 'took'],
  ['clarify', 'clear'],
  ['abandon', 'leave'],
  ['reeking', 'smelling'],
  ['cleaver', 'knife'],
  ['attempt', 'try'],
  ['hobbies', 'interests'],
  ['perused', 'looked at'],
  ['hoisted', 'lifted'],
  ['attempt', 'try'],
  ['replied', 'answered'],
  ['honored', 'respected'],
  ['upscale', 'nice'],
  ['hand in', 'give in'],
  ['surname', 'family name'],
  ['raveled', 'twisted'],
  ['respond', 'answer'],
  ['severed', 'cut'],
  ['supreme', 'best'],
  ['removed', 'took away'],
  ['howâd', 'how did'],
  ['cobbler', 'shoe maker'],
  ['drop by', 'visit'],
  ['drop in', 'visit'],
  ['undergo', 'do'],
  ['abating', 'making less'],
  ['collate', 'organize'],
  ['uncanny', 'weird'],
  ['suppose', 'guess'],
  ['persist', 'continue'],
  ['collide', 'hit'],
  ['desired', 'wanted'],
  ['suppose', 'guess'],
  ['rumours', 'stories'],
  ['despair', 'worry'],
  ['rupture', 'break'],
  ['tussled', 'fought'],
  ['admired', 'respected'],
  ['immense', 'very big'],
  ['immoral', 'bad'],
  ['turnout', 'crowd'],
  ['turmoil', 'trouble'],
  ['mocking', 'making fun of'],
  ['turmoil', 'trouble'],
  ['awfully', 'terribly'],
  ['whether', 'if'],
  ['drag on', 'last too long'],
  ['mixture', 'mix'],
  ['storing', 'keeping'],
  ['devised', 'made'],
  ['on duty', 'working'],
  ['stating', 'saying'],
  ['mistook', 'confused'],
  ['perhaps', 'maybe'],
  ['pensive', 'thoughtful'],
  ['shatter', 'break'],
  ['comical', 'funny'],
  ['pending', 'waiting'],
  ['tugging', 'pulling'],
  ['precise', 'tight'],
  ['shifted', 'moved'],
  ['whether', 'if'],
  ['infants', 'babies'],
  ['trivial', 'unimportant'],
  ['discard', 'drop'],
  ['peering', 'looking'],
  ['rescued', 'saved'],
  ['misdeed', 'crime'],
  ['triumph', 'success'],
  ['poultry', 'chicken'],
  ['pouches', 'bags'],
  ['inhabit', 'live in'],
  ['inhabit', 'live in'],
  ['discuss', 'talk about'],
  ['initial', 'first'],
  ['tremors', 'shaking'],
  ['commute', 'travel'],
  ['shouted', 'yelled'],
  ['commute', 'travel'],
  ['mingled', 'mixed'],
  ['speaker', 'talker'],
  ['barring', 'ignoring'],
  ['rapidly', 'quickly'],
  ['rescued', 'saved'],
  ['injured', 'hurt'],
  ['injured', 'hurt'],
  ['migrate', 'move'],
  ['migrate', 'move'],
  ['inquire', 'ask'],
  ['migrate', 'move'],
  ['inquiry', 'question'],
  ['trashed', 'destroyed'],
  ['posture', 'body position'],
  ['partook', 'took part'],
  ['display', 'show'],
  ['psyched', 'excited'],
  ['spawned', 'created'],
  ['whereby', 'by which'],
  ['inspire', 'excite'],
  ['inspire', 'excite'],
  ['shoving', 'pushing'],
  ['whereas', 'but'],
  ['overdue', 'late'],
  ['tracked', 'followed'],
  ['where\'d', 'where did'],
  ['donated', 'gave'],
  ['outrage', 'anger'],
  ['drastic', 'extreme'],
  ['sobbing', 'crying'],
  ['drastic', 'dramatic'],
  ['integer', 'whole number'],
  ['accords', 'agreements'],
  ['absolve', 'make free from'],
  ['intense', 'very strong'],
  ['interim', 'temporary'],
  ['soaring', 'flying'],
  ['dreaded', 'feared'],
  ['belated', 'late'],
  ['ousting', 'removing'],
  ['compose', 'make'],
  ['compose', 'make'],
  ['possess', 'have'],
  ['snoozed', 'slept'],
  ['rescuer', 'saver'],
  ['belched', 'burped'],
  ['snicker', 'laugh'],
  ['shrivel', 'shrink'],
  ['mention', 'talk about'],
  ['smuggle', 'sneak'],
  ['smirked', 'smiled'],
  ['adoring', 'loving'],
  ['yielded', 'gave'],
  ['accosts', 'troubles'],
  ['ejected', 'removed'],
  ['adorned', 'decorated'],
  ['in lieu', 'instead'],
  ['elegant', 'nice'],
  ['remorse', 'regret'],
  ['conceal', 'hide'],
  ['smacked', 'hit'],
  ['conceal', 'hide'],
  ['wealthy', 'rich'],
  ['slumber', 'sleep'],
  ['sillier', 'funnier'],
  ['isolate', 'separate'],
  ['isolate', 'separate'],
  ['blew up', 'exploded'],
  ['concern', 'worry'],
  ['orifice', 'hole'],
  ['issuing', 'giving'],
  ['issuing', 'giving'],
  ['massive', 'large'],
  ['yearned', 'desired'],
  ['jackpot', 'prize'],
  ['opulent', 'rich'],
  ['marched', 'walked'],
  ['optimum', 'best'],
  ['optimal', 'best'],
  ['optimal', 'best'],
  ['concoct', 'make'],
  ['jeering', 'making fun of'],
  ['slipped', 'fell'],
  ['enabled', 'let'],
  ['jesting', 'making fun of'],
  ['reigned', 'ruled'],
  ['jiggled', 'shook'],
  ['washing', 'cleaning'],
  ['condone', 'support'],
  ['scoured', 'searched'],
  ['beneath', 'under'],
  ['affable', 'nice'],
  ['affable', 'kind'],
  ['warping', 'bending'],
  ['prosper', 'do well'],
  ['ominous', 'scary'],
  ['warfare', 'war'],
  ['tiniest', 'littlest'],
  ['obvious', 'clear'],
  ['conform', 'agree'],
  ['joyless', 'sad'],
  ['prosaic', 'common'],
  ['congeal', 'solidify'],
  ['jumbled', 'mixed'],
  ['mansion', 'large house'],
  ['blow up', 'explode'],
  ['tidying', 'cleaning'],
  ['ponders', 'gives thought to'],
  ['situate', 'place'],
  ['absorbs', 'takes up'],
  ['sliding', 'slipping'],
  ['kidding', 'joking'],
  ['require', 'need'],
  ['wailing', 'crying'],
  ['berated', 'criticized'],
  ['mangled', 'broken'],
  ['receive', 'get'],
  ['berserk', 'crazy'],
  ['evening', 'night'],
  ['bestial', 'animal-like'],
  ['prey on', 'eat'],
  ['labored', 'worked'],
  ['laborer', 'worker'],
  ['notably', 'importantly'],
  ['voyager', 'traveler'],
  ['sizable', 'big'],
  ['skidded', 'slipped'],
  ['exceeds', 'passes'],
  ['thrived', 'lived well'],
  ['betwixt', 'between'],
  ['lacking', 'missing'],
  ['lacking', 'missing'],
  ['slicing', 'cutting'],
  ['notable', 'important'],
  ['nod off', 'fall asleep'],
  ['exclude', 'leave out'],
  ['consise', 'neat'],
  ['worries', 'scared'],
  ['thieves', 'robbers'],
  ['worried', 'scared'],
  ['largely', 'mostly'],
  ['pompous', 'self-important'],
  ['largest', 'biggest'],
  ['section', 'part'],
  ['look up', 'search for'],
  ['consume', 'eat'],
  ['viewing', 'watching'],
  ['pompous', 'rude'],
  ['nipping', 'biting'],
  ['leaping', 'jumping'],
  ['texture', 'feeling'],
  ['replied', 'answered'],
  ['skilled', 'good'],
  ['abolish', 'end'],
  ['legible', 'clear'],
  ['slaying', 'killing'],
  ['terrify', 'scare'],
  ['dawn on', 'come to'],
  ['abusive', 'hurtful'],
  ['contour', 'outline'],
  ['project', 'gas'],
  ['acquire', 'get'],
  ['linkage', 'connection'],
  ['tenuous', 'unsure'],
  ['linking', 'connecting'],
  ['queries', 'questions'],
  ['vehicle', 'car'],
  ['academy', 'school'],
  ['veering', 'turning'],
  ['favored', 'liked'],
  ['profess', 'claim'],
  ['plunged', 'fell'],
  ['madness', 'craziness'],
  ['locator', 'finder'],
  ['amusing', 'funny'],
  ['logging', 'recording'],
  ['bobbing', 'dipping'],
  ['resided', 'lived'],
  ['varying', 'changing'],
  ['fending', 'fighting'],
  ['lugging', 'pulling'],
  ['festive', 'happy'],
  ['fevered', 'excited'],
  ['lumping', 'putting'],
  ['varying', 'changing'],
  ['on duty', 'working'],
  ['lunging', 'reaching'],
  ['nibbled', 'bit'],
  ['fixated', 'obsessed'],
  ['product', 'thing'],
  ['predict', 'guess'],
  ['lukewarm', 'warm'],
  ['locating', 'finding'],
  ['listless', 'weak'],
  ['liberate', 'free'],
  ['maintain', 'keep'],
  ['lecturer', 'teacher'],
  ['lavatory', 'bathroom'],
  ['skidding', 'slipping'],
  ['majestic', 'beautiful'],
  ['laudable', 'good'],
  ['laboured', 'worked'],
  ['laboured', 'worked'],
  ['sixtieth', '60th'],
  ['laboring', 'working'],
  ['laborers', 'workers'],
  ['know-how', 'knowledge'],
  ['maneuver', 'move'],
  ['situated', 'placed'],
  ['knickers', 'shorts'],
  ['knapsack', 'backpack'],
  ['mangling', 'damaging'],
  ['slighted', 'hurt'],
  ['junction', 'cross'],
  ['mannerly', 'respectful'],
  ['jumbling', 'mixing'],
  ['jubilant', 'happy'],
  ['jittered', 'shook'],
  ['simmered', 'boiled'],
  ['jiggling', 'shaking'],
  ['jamboree', 'party'],
  ['iterated', 'repeated'],
  ['isolated', 'separated'],
  ['silliest', 'funniest'],
  ['maternal', 'motherly'],
  ['slipping', 'falling'],
  ['irrigate', 'water'],
  ['slumbers', 'sleeps'],
  ['smacking', 'hitting'],
  ['shutting', 'closing'],
  ['inventor', 'creator'],
  ['invented', 'created'],
  ['invented', 'created'],
  ['smuggled', 'snook'],
  ['inundate', 'fill'],
  ['snoozing', 'sleeping'],
  ['instruct', 'teach'],
  ['sorority', 'club'],
  ['inspired', 'excited'],
  ['shredded', 'ripped'],
  ['inspired', 'excited'],
  ['inserted', 'put'],
  ['inscribe', 'write'],
  ['insanity', 'craziness'],
  ['migraine', 'headache'],
  ['inquired', 'asked'],
  ['injuring', 'hurting'],
  ['injuring', 'hurting'],
  ['migrated', 'moved'],
  ['migrated', 'moved'],
  ['initiate', 'start'],
  ['speaking', 'talking'],
  ['shouting', 'yelling'],
  ['specimen', 'example'],
  ['spinning', 'turning'],
  ['spiraled', 'twisted'],
  ['ingested', 'ate'],
  ['informed', 'told'],
  ['shifting', 'moving'],
  ['shifting', 'moving'],
  ['inferior', 'poor'],
  ['shifting', 'moved'],
  ['sprained', 'twisted'],
  ['industry', 'business'],
  ['indicate', 'show'],
  ['shameful', 'bad'],
  ['mistaken', 'wrong'],
  ['mistaken', 'wrong'],
  ['indicate', 'show'],
  ['increase', 'raise'],
  ['struggle', 'fight'],
  ['mobilize', 'prepare'],
  ['improper', 'bad'],
  ['impelled', 'forced'],
  ['imparted', 'gave'],
  ['imparted', 'tought'],
  ['severing', 'cutting'],
  ['modified', 'changed'],
  ['suitable', 'ok'],
  ['moisture', 'wetness'],
  ['severely', 'seriously'],
  ['suitable', 'ok'],
  ['motivate', 'excite'],
  ['supplied', 'brought'],
  ['motorway', 'highway'],
  ['humorous', 'funny'],
  ['munchies', 'snacks'],
  ['horrific', 'terrible'],
  ['horrible', 'terrible'],
  ['murdered', 'killed'],
  ['murdered', 'killed'],
  ['murderer', 'killer'],
  ['honoured', 'respected'],
  ['hoisting', 'lifting'],
  ['hitherto', 'until now'],
  ['hitherto', 'untill now'],
  ['swapping', 'trading'],
  ['hardiest', 'strongest'],
  ['mutilate', 'destroy'],
  ['guffawed', 'laughed'],
  ['gruesome', 'terrible'],
  ['grinning', 'smiling'],
  ['muttered', 'said'],
  ['grievous', 'terrible'],
  ['grateful', 'thankful'],
  ['granting', 'giving'],
  ['gracious', 'thankful'],
  ['glitches', 'problems'],
  ['giggling', 'laughing'],
  ['namesake', 'name'],
  ['narrowly', 'barely'],
  ['gigantic', 'very big'],
  ['gigantic', 'very big'],
  ['synopsis', 'summary'],
  ['selected', 'chose'],
  ['generate', 'make'],
  ['frontier', 'edge'],
  ['frenzied', 'crazy'],
  ['frenzied', 'excited'],
  ['frenetic', 'excited'],
  ['newcomer', 'new person'],
  ['flourish', 'grow'],
  ['fixation', 'obsession'],
  ['financed', 'paid for'],
  ['nibbling', 'biting'],
  ['fiendish', 'bad'],
  ['favoured', 'liked'],
  ['favoring', 'liking'],
  ['fatigued', 'tired'],
  ['terrific', 'great'],
  ['tertiary', 'third'],
  ['theories', 'ideas'],
  ['nominate', 'suggest'],
  ['thievery', 'robbery'],
  ['expanded', 'grew'],
  ['excludes', 'leaves out'],
  ['excluded', 'left out'],
  ['thorough', 'complete'],
  ['thriving', 'living well'],
  ['scurried', 'ran'],
  ['notified', 'tell'],
  ['notified', 'told'],
  ['notified', 'told'],
  ['notifies', 'tells'],
  ['evacuate', 'empty'],
  ['estimate', 'guess'],
  ['escalate', 'increase'],
  ['nowadays', 'today'],
  ['numerous', 'many'],
  ['objected', 'disagreed'],
  ['scrolled', 'rolled'],
  ['equipped', 'prepared'],
  ['obtained', 'got'],
  ['envisage', 'see'],
  ['occasion', 'time'],
  ['entirely', 'completely'],
  ['entirely', 'very'],
  ['enriched', 'improved'],
  ['enormous', 'very big'],
  ['enabling', 'letting'],
  ['employee', 'worker'],
  ['tinkered', 'played'],
  ['optimize', 'improve'],
  ['empathic', 'strong'],
  ['tinkered', 'played'],
  ['scorches', 'burns'],
  ['eloquent', 'smooth'],
  ['ordinary', 'normal'],
  ['elongate', 'stretch'],
  ['ejecting', 'removing'],
  ['duration', 'length'],
  ['dreading', 'fearing'],
  ['dreadful', 'terrible'],
  ['dreadful', 'terrible'],
  ['donating', 'giving'],
  ['outraged', 'angry'],
  ['outweigh', 'weigh more than'],
  ['tracking', 'following'],
  ['trailing', 'following'],
  ['salivate', 'drool'],
  ['parodied', 'made fun of'],
  ['tranquil', 'quiet'],
  ['transmit', 'send'],
  ['paternal', 'fatherly'],
  ['treatise', 'book'],
  ['trekking', 'travelling'],
  ['triggers', 'starts'],
  ['disclose', 'tell'],
  ['disclose', 'tell'],
  ['diminish', 'lessen'],
  ['devotion', 'respect'],
  ['perceive', 'see'],
  ['ruptured', 'broke'],
  ['devising', 'making'],
  ['devising', 'making'],
  ['perilous', 'dangerous'],
  ['devilish', 'very bad'],
  ['tussling', 'fighting'],
  ['desiring', 'wanting'],
  ['ultimate', 'best'],
  ['derision', 'disrespect'],
  ['skillful'],
  ['pertains', 'matters'],
  ['updating', 'choosing'],
  ['demolish', 'destroy'],
  ['perusing', 'looking at'],
  ['demolish', 'destroy'],
  ['demeanor', 'behavior'],
  ['delicate', 'special'],
  ['definite', 'sure'],
  ['deducted', 'removed'],
  ['decrepit', 'broken'],
  ['usurping', 'taking'],
  ['utilized', 'used'],
  ['utilizes', 'uses'],
  ['deciding', 'choosing'],
  ['deceased', 'dead'],
  ['dangling', 'hanging'],
  ['placidly', 'quietly'],
  ['damnable', 'bad'],
  ['currency', 'money'],
  ['cruising', 'driving'],
  ['pleasant', 'nice'],
  ['pleasant', 'good'],
  ['creating', 'making'],
  ['pleasing', 'good'],
  ['pleasing', 'nice'],
  ['crashing', 'smashing'],
  ['crafting', 'making'],
  ['crafting', 'making'],
  ['covenant', 'promise'],
  ['couldn\'t', 'could not'],
  ['plugging', 'putting'],
  ['corridor', 'hall'],
  ['corridor', 'hall'],
  ['converge', 'come together'],
  ['plunging', 'falling'],
  ['vehement', 'violent'],
  ['contains', 'has'],
  ['polished', 'cleaned'],
  ['contains', 'has'],
  ['vitality', 'liveliness'],
  ['voyaging', 'traveling'],
  ['consider', 'think about'],
  ['pondered', 'gave thought to'],
  ['walloped', 'hit'],
  ['wardrobe', 'clothes'],
  ['condoned', 'supported'],
  ['populace', 'public'],
  ['composed', 'made'],
  ['composed', 'made'],
  ['whatâd', 'what did'],
  ['robustly', 'strongly'],
  ['commuter', 'traveler'],
  ['commuter', 'traveler'],
  ['commuted', 'traveled'],
  ['rivalled', 'competed with'],
  ['commuted', 'traveled'],
  ['communal', 'group'],
  ['commonly', 'normally'],
  ['powerful', 'strong'],
  ['praising', 'thanking'],
  ['preceded', 'came before'],
  ['commence', 'start'],
  ['abandons', 'leaves'],
  ['colossal', 'big'],
  ['collides', 'hits'],
  ['collided', 'hit'],
  ['coalesce', 'form'],
  ['clinging', 'holding'],
  ['chuckled', 'laughed'],
  ['ridicule', 'make fun of'],
  ['preluded', 'came before'],
  ['chopping', 'making cuts'],
  ['prepared', 'ready'],
  ['prepared', 'ready'],
  ['preserve', 'keep'],
  ['revision', 'change'],
  ['cheerful', 'happy'],
  ['revising', 'changing'],
  ['chastise', 'criticize'],
  ['cardigan', 'sweater'],
  ['captured', 'got'],
  ['previous', 'earlier'],
  ['withdraw', 'remove'],
  ['revealed', 'showed'],
  ['canceled', 'stopped'],
  ['bursting', 'exploding'],
  ['burglary', 'robbery'],
  ['proclaim', 'say'],
  ['breached', 'broke'],
  ['procured', 'got'],
  ['procures', 'gets'],
  ['produced', 'made'],
  ['withdrew', 'removed'],
  ['products', 'things'],
  ['blissful', 'great'],
  ['billiard', 'pool-table'],
  ['wondrous', 'good'],
  ['prolific', 'everywhere'],
  ['promptly', 'quickly'],
  ['promptly', 'quickly'],
  ['bickered', 'argued'],
  ['retrieve', 'get'],
  ['bewilder', 'confuse'],
  ['berating', 'criticizing'],
  ['retrieve', 'get'],
  ['bequeath', 'give'],
  ['retained', 'kept'],
  ['benefits', 'helps'],
  ['worrying', 'fearing'],
  ['wouldn\'t', 'would not'],
  ['yearning', 'desire'],
  ['protocol', 'rules'],
  ['belching', 'burping'],
  ['beatific', 'good'],
  ['banished', 'banned'],
  ['yielding', 'giving'],
  ['punching', 'hitting'],
  ['puncture', 'get in'],
  ['attended', 'went to'],
  ['purifies', 'cleans'],
  ['youthful', 'young'],
  ['assisted', 'helped'],
  ['purposes', 'reasons'],
  ['assemble', 'build'],
  ['all ears', 'listening carefully'],
  ['arrogant', 'rude'],
  ['pursuing', 'going after'],
  ['at times', 'sometimes'],
  ['cash cow', 'easy way to make money'],
  ['quaintly', 'nicely'],
  ['resigned', 'left'],
  ['quantity', 'number'],
  ['quantity', 'amount'],
  ['arranged', 'prepared'],
  ['appalled', 'disgusted'],
  ['residing', 'living'],
  ['residing', 'living'],
  ['announce', 'say'],
  ['amputate', 'remove'],
  ['allowing', 'letting'],
  ['querying', 'questing'],
  ['allocate', 'give'],
  ['alarming', 'surprising'],
  ['affluent', 'rich'],
  ['radiated', 'spread'],
  ['adorning', 'decorating'],
  ['adorable', 'cute'],
  ['cheer up', 'become happier'],
  ['count on', 'trust'],
  ['admitted', 'said'],
  ['find out', 'learn'],
  ['raveling', 'twisting'],
  ['adjacent', 'nearest'],
  ['adhesive', 'glue'],
  ['adherent', 'strong'],
  ['adequate', 'enough'],
  ['actually', 'really'],
  ['laid off', 'fired'],
  ['activate', 'start'],
  ['reasoned', 'thought'],
  ['acquires', 'gets'],
  ['acquired', 'got'],
  ['pass out', 'faint'],
  ['accurate', 'TRUE'],
  ['received', 'got'],
  ['receives', 'gets'],
  ['accuracy', 'amount of error'],
  ['reclined', 'rested'],
  ['the wild', 'nature'],
  ['chew out', 'tell off'],
  ['accosted', 'troubled'],
  ['goes bad', 'becomes bad'],
  ['prior to', 'before'],
  ['enrol in', 'enter'],
  ['reformed', 'changed'],
  ['let down', 'disappoint'],
  ['regained', 'got back'],
  ['regiment', 'plan'],
  ['absurdly', 'foolishly'],
  ['rehearse', 'practice'],
  ['absorbed', 'taken up'],
  ['reigning', 'ruling'],
  ['reignite', 'restart'],
  ['resemble', 'look like'],
  ['rescuing', 'saving'],
  ['rescuing', 'saving'],
  ['absolved', 'made free from'],
  ['due time', 'some time'],
  ['absolute', 'complete'],
  ['absolute', 'complete'],
  ['abruptly', 'suddenly'],
  ['required', 'needed'],
  ['abridges', 'shortens'],
  ['abridged', 'shortened'],
  ['relocate', 'move'],
  ['pine for', 'miss'],
  ['doze off', 'fall asleep'],
  ['abnormal', 'not normal'],
  ['abhorred', 'hated'],
  ['abducted', 'taken away'],
  ['removing', 'taking away'],
  ['renounce', 'give up'],
  ['renovate', 'change'],
  ['abdicate', 'give up'],
  ['repaired', 'fixed'],
  ['repaired', 'fixed'],
  ['reporter', 'writer'],
  ['preys on', 'eats'],
  ['abide by', 'follow'],
  ['depicted', 'shown'],
  ['courteous', 'polite'],
  ['displayed', 'showed'],
  ['transform', 'change'],
  ['narrative', 'story'],
  ['sensation', 'feeling'],
  ['courteous', 'nice'],
  ['courteous', 'nice'],
  ['inventing', 'creating'],
  ['inventing', 'creating'],
  ['selection', 'choice'],
  ['selecting', 'choosing'],
  ['nefarious', 'very bad'],
  ['variation', 'change'],
  ['inventory', 'list'],
  ['generated', 'made'],
  ['commuting', 'traveling'],
  ['segregate', 'separate'],
  ['commuting', 'traveling'],
  ['negotiate', 'argue'],
  ['companion', 'friend'],
  ['authorize', 'let'],
  ['newcomers', 'new people'],
  ['compelled', 'forced'],
  ['slumbered', 'slept'],
  ['allocated', 'gave'],
  ['irrigated', 'water'],
  ['genuinely', 'truly'],
  ['abhorring', 'hating'],
  ['irritable', 'annoyed'],
  ['alongside', 'beside'],
  ['ninetieth', '90th'],
  ['ambiguous', 'unclear'],
  ['compliant', 'agreeable'],
  ['whatâve', 'what have'],
  ['byproduct', 'result'],
  ['nominated', 'suggested'],
  ['component', 'part'],
  ['scurrying', 'running'],
  ['calculate', 'find'],
  ['of no use', 'not helpful'],
  ['iteration', 'time'],
  ['itinerary', 'plan'],
  ['abides by', 'follows'],
  ['get along', 'be friends'],
  ['canceling', 'stopping'],
  ['composing', 'making'],
  ['educating', 'teaching'],
  ['cancelled', 'stopped'],
  ['found out', 'learned'],
  ['notifying', 'telling'],
  ['notifying', 'telling'],
  ['synergize', 'combine'],
  ['crucially', 'importantly'],
  ['crucially', 'importantly'],
  ['in motion', 'moving'],
  ['scrolling', 'rolling'],
  ['gradually', 'slowly'],
  ['objecting', 'disagreeing'],
  ['gradually', 'slowly'],
  ['elegantly', 'nicely'],
  ['elemental', 'basic'],
  ['bona fide', 'real'],
  ['obviously', 'clearly'],
  ['grievance', 'complaint'],
  ['jittering', 'shaking'],
  ['capturing', 'getting'],
  ['eliminate', 'remove'],
  ['comprised', 'made'],
  ['amputated', 'removed'],
  ['praise on', 'eats'],
  ['pass away', 'die'],
  ['groceries', 'food'],
  ['analogous', 'similar'],
  ['elongated', 'stretched'],
  ['tinkering', 'playing'],
  ['concealed', 'hidden'],
  ['customary', 'normal'],
  ['emmigrate', 'move'],
  ['slightest', 'smallest'],
  ['concealed', 'hid'],
  ['weariness', 'tiredness'],
  ['preyed on', 'ate'],
  ['pined for', 'missed'],
  ['ceaseless', 'endless'],
  ['juxtapose', 'compare'],
  ['outskirts', 'edge'],
  ['juxtapose', 'compare'],
  ['concerned', 'worried'],
  ['overjoyed', 'very happy'],
  ['oversight', 'mistake'],
  ['pet peeve', 'most unknowing thing'],
  ['salivated', 'drooled'],
  ['switching', 'changing'],
  ['appalling', 'disgusting'],
  ['concocted', 'made'],
  ['apparatus', 'machine'],
  ['bellicose', 'mean'],
  ['bellicose', 'mean'],
  ['absorbent', 'able to take'],
  ['condoning', 'supporting'],
  ['of course', 'certainly'],
  ['cherished', 'loved'],
  ['rupturing', 'breaking'],
  ['yearnings', 'desires'],
  ['accompany', 'go with'],
  ['hazardous', 'dangerous'],
  ['heartless', 'unkind'],
  ['accompany', 'come with'],
  ['eradicate', 'remove'],
  ['brand-new', 'very new'],
  ['labouring', 'working'],
  ['utilizing', 'using'],
  ['permitted', 'let'],
  ['decompose', 'breakdown'],
  ['escalated', 'increased'],
  ['persisted', 'continued'],
  ['blast off', 'shoot into the sky'],
  ['hideously', 'terriblly'],
  ['establish', 'make'],
  ['pertinent', 'important'],
  ['black out', 'faint'],
  ['decreased', 'lowered'],
  ['decreases', 'lowers'],
  ['congealed', 'solidified'],
  ['estimated', 'guessed'],
  ['difficult', 'simple'],
  ['evacuated', 'emptied'],
  ['physician', 'doctor'],
  ['abridging', 'shortening'],
  ['chuckling', 'laughing'],
  ['pipe down', 'quiet'],
  ['consensus', 'general agreement'],
  ['deducting', 'taking away'],
  ['deducting', 'removing'],
  ['consensus', 'agreement'],
  ['acquiring', 'getting'],
  ['defective', 'bad'],
  ['excellent', 'great'],
  ['plausible', 'possible'],
  ['horrified', 'terrified'],
  ['excellent', 'very good'],
  ['deference', 'respect'],
  ['exchanged', 'traded'],
  ['exchanged', 'traded'],
  ['deference', 'respect'],
  ['absurdity', 'strange thing'],
  ['humiliate', 'embarrass'],
  ['liability', 'danger'],
  ['plentiful', 'full'],
  ['supposing', 'if'],
  ['whosoever', 'whoever'],
  ['liberated', 'freed'],
  ['bear with', 'to be patient with'],
  ['activated', 'started'],
  ['excluding', 'leaving out'],
  ['supposing', 'assuming'],
  ['thirtieth', '30th'],
  ['excrement', 'poo'],
  ['excursion', 'trip'],
  ['exemplary', 'excellent'],
  ['polishing', 'cleaning'],
  ['literally', 'actually'],
  ['exemplary', 'great'],
  ['pompously', 'self-importantly'],
  ['livestock', 'animals'],
  ['supplying', 'bringing'],
  ['exemplary', 'great'],
  ['pondering', 'thinking about'],
  ['pondering', 'giving thought to'],
  ['exhausted', 'very tired'],
  ['abducting', 'taking away'],
  ['whimsical', 'not strong'],
  ['arranging', 'preparing'],
  ['expanding', 'growing'],
  ['immigrate', 'move'],
  ['expressed', 'said'],
  ['postponed', 'delayed'],
  ['postponed', 'delay'],
  ['delighted', 'happy'],
  ['exquisite', 'very nice'],
  ['delighted', 'nice'],
  ['extensive', 'big'],
  ['imparting', 'teaching'],
  ['imparting', 'giving'],
  ['arrogance', 'rudeness'],
  ['struggled', 'fought'],
  ['demeanour', 'behaviour'],
  ['impending', 'nearing'],
  ['therefore', 'so'],
  ['luxurious', 'nice'],
  ['fabricate', 'make up'],
  ['predicted', 'guessed'],
  ['predicted', 'guessed'],
  ['strenuous', 'hard'],
  ['preyed on', 'ate'],
  ['clarifies', 'clears'],
  ['construct', 'make'],
  ['stipulate', 'saying'],
  ['inception', 'beginning'],
  ['ridiculed', 'made fun of'],
  ['stimulate', 'excite'],
  ['testimony', 'statement'],
  ['preluding', 'coming before'],
  ['premature', 'early'],
  ['revolving', 'turning'],
  ['incorrect', 'wrong'],
  ['construct', 'build'],
  ['actuality', 'fact'],
  ['preparing', 'getting ready'],
  ['preparing', 'getting  ready'],
  ['upgrading', 'improving'],
  ['preserved', 'kept'],
  ['revolting', 'terrible'],
  ['terrified', 'scared'],
  ['indicated', 'showed'],
  ['presuming', 'assuming'],
  ['indicated', 'showed'],
  ['malignity', 'hate'],
  ['advancing', 'moving forward'],
  ['reverence', 'respect'],
  ['mandatory', 'necessary'],
  ['visualize', 'see'],
  ['fantastic', 'amazing'],
  ['situating', 'placing'],
  ['primarily', 'mostly'],
  ['terminate', 'end'],
  ['principle', 'idea'],
  ['spraining', 'twisting'],
  ['visualize', 'see'],
  ['unethical', 'bad'],
  ['ascertain', 'find'],
  ['manifesto', 'statement'],
  ['fascinate', 'interest'],
  ['procuring', 'getting'],
  ['violation', 'crime'],
  ['producing', 'making'],
  ['producing', 'making'],
  ['departing', 'leaving'],
  ['ascertain', 'learn'],
  ['advocated', 'argued'],
  ['professed', 'claimed'],
  ['simmering', 'boiling'],
  ['professor', 'teacher'],
  ['retrieved', 'got'],
  ['informing', 'telling'],
  ['retrieved', 'got'],
  ['informing', 'telling'],
  ['prominent', 'major'],
  ['infuriate', 'anger'],
  ['fatiguing', 'tiring'],
  ['massively', 'largely'],
  ['propelled', 'pushed'],
  ['similarly', 'also'],
  ['ingenious', 'smart'],
  ['ingenious', 'smart'],
  ['depicting', 'showing'],
  ['maternity', 'pregnancy'],
  ['underwent', 'did'],
  ['ingesting', 'eating'],
  ['underlies', 'is under'],
  ['depressed', 'sad'],
  ['inhabited', 'lived in'],
  ['abandoned', 'left'],
  ['favouring', 'liking'],
  ['spiralled', 'twisted'],
  ['mentality', 'thinking'],
  ['spiraling', 'twisting'],
  ['mentioned', 'talked about'],
  ['abolished', 'ended'],
  ['punctured', 'entered'],
  ['responded', 'answered'],
  ['purchased', 'bought'],
  ['shredding', 'ripping'],
  ['abysmally', 'very badly'],
  ['speculate', 'guess'],
  ['purifying', 'cleaning'],
  ['contented', 'happy'],
  ['purported', 'claimed'],
  ['resilient', 'strong'],
  ['specifies', 'decides'],
  ['abdicates', 'gives up'],
  ['initially', 'at first'],
  ['bickering', 'argueing'],
  ['initiated', 'started'],
  ['coalesced', 'formed'],
  ['affection', 'love'],
  ['adamantly', 'strongly'],
  ['assembled', 'built'],
  ['turned in', 'gave'],
  ['bifurcate', 'split'],
  ['wonderful', 'great'],
  ['migrating', 'moving'],
  ['migrating', 'moving'],
  ['tenderize', 'soften'],
  ['miniature', 'many'],
  ['womankind', 'all women'],
  ['bilateral', 'two-sided'],
  ['inquiring', 'asking'],
  ['turbulent', 'shaky'],
  ['shouldn\'t', 'should not'],
  ['converged', 'came together'],
  ['prefer to', 'like to'],
  ['radiating', 'spreading'],
  ['radically', 'greatly'],
  ['shimmered', 'danced'],
  ['colliding', 'hitting'],
  ['agonizing', 'very hard'],
  ['associate', 'group'],
  ['miserable', 'very sad'],
  ['inserting', 'putting'],
  ['formulate', 'make'],
  ['converted', 'changed'],
  ['converted', 'changed'],
  ['shattered', 'broke'],
  ['converted', 'changed'],
  ['realistic', 'real'],
  ['converted', 'changed'],
  ['combining', 'mixing'],
  ['inspiring', 'exciting'],
  ['instigate', 'excite'],
  ['reasoning', 'thinking'],
  ['comforter', 'blanket'],
  ['agreeable', 'nice'],
  ['varieties', 'types'],
  ['mobilized', 'prepared'],
  ['fraternal', 'brotherly'],
  ['tantalize', 'excite'],
  ['receiving', 'getting'],
  ['accosting', 'troubling'],
  ['such time', 'the time'],
  ['reclining', 'rest'],
  ['reclining', 'resting'],
  ['recognize', 'remember'],
  ['resetting', 'restarting'],
  ['recollect', 'remember'],
  ['insurgent', 'rebel'],
  ['deal with', 'handle'],
  ['modifying', 'changing'],
  ['disclosed', 'told'],
  ['aleatoric', 'random'],
  ['corporate', 'business'],
  ['momentous', 'important'],
  ['reforming', 'changing'],
  ['momentous', 'important'],
  ['intending', 'planning'],
  ['regaining', 'getting back'],
  ['triggered', 'started'],
  ['motivated', 'excited'],
  ['resembles', 'is like'],
  ['resembles', 'looks like'],
  ['resembled', 'was like'],
  ['rehearsal', 'practice'],
  ['intensely', 'strongly'],
  ['rehearsed', 'practiced'],
  ['resembled', 'looked like'],
  ['intensity', 'strength'],
  ['bombastic', 'loud'],
  ['attempted', 'tried'],
  ['reignited', 'restarted'],
  ['municipal', 'city'],
  ['reimburse', 'paid back'],
  ['discussed', 'talked about'],
  ['internals', 'insides'],
  ['discusses', 'talks about'],
  ['disembark', 'leave'],
  ['reinstate', 'put back'],
  ['corpulent', 'fat'],
  ['murdering', 'killing'],
  ['murdering', 'killing'],
  ['reiterate', 'repeat'],
  ['requisite', 'necessary'],
  ['requiring', 'needing'],
  ['furiously', 'violently'],
  ['intersect', 'cross'],
  ['rejoicing', 'celebrating'],
  ['mustering', 'getting'],
  ['corrected', 'fixed'],
  ['relocated', 'moved'],
  ['alleviate', 'ease'],
  ['took over', 'took control'],
  ['remarking', 'saying'],
  ['take over', 'take control'],
  ['requested', 'asked for'],
  ['repulsive', 'terrible'],
  ['snickered', 'laughed'],
  ['mutilated', 'destroyed'],
  ['intricate', 'complex'],
  ['rendition', 'version'],
  ['intrigued', 'interested'],
  ['repugnant', 'terrible'],
  ['varieties', 'kinds'],
  ['renovated', 'changed'],
  ['reprimand', 'criticize'],
  ['smuggling', 'sneaking'],
  ['muttering', 'saying'],
  ['mystified', 'amazed'],
  ['repairing', 'fixing'],
  ['repairing', 'fixing'],
  ['replenish', 'refill'],
  ['deal with', 'handle'],
  ['inundated', 'filled'],
  ['authentic', 'real'],
  ['authentic', 'real'],
  ['gracefully', 'nicely'],
  ['to and fro', 'around'],
  ['renouncing', 'giving up'],
  ['remorseful', 'regretful'],
  ['requesting', 'asking for'],
  ['remarkable', 'amazing'],
  ['reiterated', 'repeated'],
  ['reinstates', 'puts back'],
  ['reinstated', 'put back'],
  ['abandoning', 'leaving'],
  ['reimbursed', 'paid back'],
  ['researched', 'studied'],
  ['reigniting', 'restarting'],
  ['rehearsing', 'practicing'],
  ['abiding by', 'following'],
  ['regulation', 'rule'],
  ['resembling', 'looking like'],
  ['recognized', 'remembered'],
  ['abbreviate', 'make shorter'],
  ['preying on', 'eating'],
  ['quarrelled', 'font'],
  ['quarrelled', 'font'],
  ['quarreling', 'fighting'],
  ['quantities', 'amounts'],
  ['purporting', 'claiming'],
  ['purchasing', 'buying'],
  ['puncturing', 'getting in'],
  ['prosperous', 'rich'],
  ['prospering', 'doing well'],
  ['proprietor', 'owner'],
  ['retreating', 'getting'],
  ['propelling', 'pushing'],
  ['profoundly', 'very'],
  ['retrieving', 'getting'],
  ['professing', 'claiming'],
  ['previously', 'earlier'],
  ['previously', 'earlier'],
  ['presuppose', 'assume'],
  ['presuppose', 'assume'],
  ['presumably', 'probably'],
  ['preserving', 'keeping'],
  ['preference', 'choice'],
  ['ridiculing', 'making fun of'],
  ['preferably', 'hopefully'],
  ['abdicating', 'giving up'],
  ['prediction', 'des'],
  ['prediction', 'guess'],
  ['predicting', 'guessing'],
  ['postponing', 'delaying'],
  ['possessing', 'having'],
  ['phenomenal', 'great'],
  ['persisting', 'continuing'],
  ['permitting', 'letting'],
  ['pejorative', 'mean'],
  ['opposed to', 'against'],
  ['salivating', 'drooling'],
  ['sanctified', 'important'],
  ['satisfying', 'good'],
  ['satisfying', 'nice'],
  ['originally', 'first'],
  ['ordinarily', 'normally'],
  ['ordinarily', 'normally'],
  ['adverse to', 'against'],
  ['objectives', 'goals'],
  ['obfuscated', 'confusing'],
  ['scrutinize', 'criticize'],
  ['noteworthy', 'important'],
  ['nominating', 'suggesting'],
  ['newfangled', 'different'],
  ['negligible', 'unimportant'],
  ['negligible', 'unimportant'],
  ['segregated', 'separated'],
  ['neglectful', 'careless'],
  ['abnormally', 'not normally'],
  ['narratives', 'stories'],
  ['mystifying', 'amazing'],
  ['mutilating', 'destroying'],
  ['abolishing', 'ending'],
  ['mobilizing', 'preparing'],
  ['mistakenly', 'wrongly'],
  ['abominable', 'very bad'],
  ['shattering', 'breaking'],
  ['misfortune', 'bad luck'],
  ['shimmering', 'dancing'],
  ['misconduct', 'crime'],
  ['a nuisance', 'annoying'],
  ['pertain to', 'involve'],
  ['miscellany', 'things'],
  ['miraculous', 'amazing'],
  ['miraculous', 'amazing'],
  ['metropolis', 'city'],
  ['methodical', 'careful'],
  ['mentioning', 'talking about'],
  ['shrivelled', 'shrunk'],
  ['melancholy', 'sadness'],
  ['manuscript', 'book'],
  ['in a pinch', 'in an emergency'],
  ['abominably', 'very badly'],
  ['manifestly', 'clearly'],
  ['maneuvered', 'moved'],
  ['pining for', 'missing'],
  ['malefactor', 'wrongdoer'],
  ['maintained', 'kept'],
  ['livelihood', 'money'],
  ['listlessly', 'weakly'],
  ['likelihood', 'chance'],
  ['liberating', 'freeing'],
  ['legitimate', 'real'],
  ['lackluster', 'boring'],
  ['laceration', 'wound'],
  ['juxtaposed', 'compared'],
  ['jubilation', 'happiness'],
  ['jeopardize', 'risk'],
  ['irrigation', 'watering'],
  ['irrigating', 'watering'],
  ['irreverent', 'not serious'],
  ['slumbering', 'sleeping'],
  ['irresolute', 'uncertain'],
  ['irrelevant', 'not useful'],
  ['invigorate', 'strengthen'],
  ['invariably', 'always'],
  ['invariably', 'always'],
  ['invariably', 'always'],
  ['abridgment', 'shorter form'],
  ['intriguing', 'interesting'],
  ['track down', 'find'],
  ['snickering', 'laughing'],
  ['partake in', 'do'],
  ['interlaced', 'twisted'],
  ['insurgency', 'rebellion'],
  ['instructor', 'teacher'],
  ['solicitous', 'respectful'],
  ['instructed', 'taught'],
  ['instigated', 'excited'],
  ['insinuated', 'suggested'],
  ['inscribing', 'writing'],
  ['initiating', 'starting'],
  ['specialist', 'expert'],
  ['specifying', 'deciding'],
  ['initialize', 'prepare'],
  ['speculated', 'guessed'],
  ['initialise', 'prepare'],
  ['absolutely', 'completely'],
  ['spiralling', 'twisting'],
  ['inhabiting', 'living in'],
  ['infuriated', 'angry'],
  ['absolutely', 'certainly'],
  ['inebriated', 'drunk'],
  ['indicating', 'showing'],
  ['indicating', 'showing'],
  ['increasing', 'raising'],
  ['incoherent', 'senseless'],
  ['stimulated', 'excited'],
  ['stipulated', 'said'],
  ['stipulates', 'says'],
  ['inaccurate', 'wrong'],
  ['inaccurate', 'wrong'],
  ['impeccably', 'perfectly'],
  ['struggling', 'fighting'],
  ['subsequent', 'following'],
  ['impeccable', 'perfect'],
  ['immaculate', 'perfect'],
  ['hands down', 'definitely'],
  ['illegality', 'crime'],
  ['hypothesis', 'guess'],
  ['humiliated', 'embarrassed'],
  ['horrifying', 'terrible'],
  ['horrendous', 'terrible'],
  ['henceforth', 'from now on'],
  ['henceforth', 'from now on'],
  ['hands-down', 'definitely'],
  ['renovating', 'changing'],
  ['generating', 'making'],
  ['frequently', 'often'],
  ['fraudulent', 'fake'],
  ['fraternity', 'club'],
  ['tantalized', 'excited'],
  ['formulated', 'made'],
  ['tenderized', 'softened'],
  ['favourable', 'good'],
  ['abstractly', 'in thoughts'],
  ['terminated', 'ended'],
  ['fallacious', 'wrong'],
  ['terrifying', 'scaring'],
  ['facilitate', 'help'],
  ['fabricates', 'makes up'],
  ['fabricated', 'made up'],
  ['thereafter', 'from that time on'],
  ['extinguish', 'stop'],
  ['expressing', 'saying'],
  ['exhausting', 'very tiring'],
  ['exchanging', 'trading'],
  ['exchanging', 'trading'],
  ['thoroughly', 'completely'],
  ['thoughtful', 'respectful'],
  ['excellence', 'greatness'],
  ['throughout', 'during'],
  ['exasperate', 'tire'],
  ['evacuating', 'leaving'],
  ['escalating', 'growing'],
  ['eradicated', 'removed'],
  ['entrenched', 'stuck'],
  ['enthusiasm', 'excitement'],
  ['eloquently', 'smoothly'],
  ['elongating', 'stretching'],
  ['eliminator', 'remover'],
  ['eliminated', 'removed'],
  ['elementary', 'basic'],
  ['elementary', 'basic'],
  ['accelerate', 'increase in speed'],
  ['displaying', 'showing'],
  ['transition', 'change'],
  ['disparaged', 'insulted'],
  ['disgusting', 'terrible'],
  ['tremendous', 'great'],
  ['discretion', 'decision'],
  ['triggering', 'starting'],
  ['disclosing', 'telling'],
  ['triumphant', 'successful'],
  ['disastrous', 'and very bad'],
  ['diminished', 'lowered'],
  ['detestable', 'terrible'],
  ['despicable', 'disgusting'],
  ['despicable', 'terrible'],
  ['despicable', 'terrible'],
  ['despairing', 'worrying'],
  ['derogatory', 'mean'],
  ['unbearable', 'not ok'],
  ['derisively', 'meanly'],
  ['undeniable', 'sure'],
  ['undeniably', 'surely'],
  ['depression', 'sadness'],
  ['undergoing', 'doing'],
  ['deplorable', 'terrible'],
  ['deplorable', 'terrible'],
  ['unemployed', 'jobless'],
  ['unilateral', 'one-sided'],
  ['unprepared', 'not ready'],
  ['unsuitable', 'wrong'],
  ['demolishes', 'destroys'],
  ['demolished', 'destroyed'],
  ['demolished', 'destroyed'],
  ['decreasing', 'lowering'],
  ['decreasing', 'lowering'],
  ['cyberspace', 'internet'],
  ['cumbersome', 'difficult'],
  ['cracked in', 'fixing'],
  ['figure out', 'learn'],
  ['couldâve', 'could have'],
  ['convocated', 'graduated'],
  ['converting', 'changing'],
  ['converting', 'changing'],
  ['conversion', 'change'],
  ['conversion', 'change'],
  ['conversion', 'change'],
  ['converging', 'coming together'],
  ['vehemently', 'violently'],
  ['veneration', 'respect'],
  ['ventilated', 'aired'],
  ['continuous', 'unbroken'],
  ['vice versa', 'the other way round'],
  ['containing', 'having'],
  ['visualized', 'saw'],
  ['visualized', 'saw'],
  ['consenting', 'agreeing'],
  ['congregate', 'come together'],
  ['accentuate', 'stress'],
  ['congealing', 'solidifying'],
  ['conforming', 'aggreeing'],
  ['confiscate', 'take'],
  ['concurrent', 'simultaneous'],
  ['concocting', 'creating'],
  ['concerning', 'about'],
  ['conception', 'understanding'],
  ['concealing', 'hiding'],
  ['concealing', 'hiding'],
  ['compulsory', 'necessary'],
  ['compressed', 'squeezed'],
  ['comprehend', 'understand'],
  ['components', 'parts'],
  ['compliance', 'agreement'],
  ['compelling', 'strong'],
  ['commitment', 'promise'],
  ['colloquial', 'everyday'],
  ['coalescing', 'forming'],
  ['clarifying', 'clearing'],
  ['clambering', 'climbing'],
  ['had a talk', 'talked'],
  ['come about', 'happen'],
  ['circumvent', 'get around'],
  ['cherishing', 'loving'],
  ['chastising', 'criticizing'],
  ['cancelling', 'stopping'],
  ['bifurcated', 'split'],
  ['wonderment', 'surprise'],
  ['biennially', 'every two years'],
  ['bewildered', 'confused'],
  ['benevolent', 'good'],
  ['beneficial', 'good'],
  ['worthwhile', 'important'],
  ['wouldâve', 'would have'],
  ['beneficial', 'good'],
  ['beneficent', 'good'],
  ['belongings', 'things'],
  ['automobile', 'car'],
  ['authorized', 'let'],
  ['attempting', 'trying'],
  ['attempting', 'trying'],
  ['youthfully', 'young'],
  ['associated', 'grouped'],
  ['assembling', 'building'],
  ['preying on', 'eating'],
  ['accessible', 'usable'],
  ['articulate', 'say'],
  ['arrogantly', 'rudely'],
  ['accomplice', 'friend'],
  ['accomplish', 'do'],
  ['as soon as', 'when'],
  ['right away', 'immediately'],
  ['amputation', 'removal'],
  ['stick with', 'continue'],
  ['alleviated', 'eased'],
  ['take place', 'happen'],
  ['took place', 'happened'],
  ['have a cow', 'get upset'],
  ['advocating', 'arguing'],
  ['bone up on', 'study'],
  ['called off', 'cancelled'],
  ['adolescent', 'child'],
  ['admissible', 'allowed'],
  ['admiration', 'respect'],
  ['feel up to', 'feel strong enough for'],
  ['adjudicate', 'judge'],
  ['activating', 'starting'],
  ['look after', 'take care of'],
  ['accustomed', 'used to'],
  ['accusation', 'claim'],
  ['accurately', 'correctly'],
  ['accordance', 'agreement'],
  ['accumulate', 'group'],
  ['cut it out', 'stop'],
  ['spare some', 'give some'],
  ['facilitated', 'helped'],
  ['accelerated', 'increased in speed'],
  ['pandemonium', 'craziness'],
  ['momentarily', 'quickly'],
  ['knucklehead', 'idiot'],
  ['immediately', 'very soon'],
  ['juxtaposing', 'comparing'],
  ['superficial', 'cheap'],
  ['superfluous', 'unnecessary'],
  ['superfluous', 'unnecessary'],
  ['undesirable', 'unwanted'],
  ['taken aback', 'surprised'],
  ['accelerates', 'increases'],
  ['out of date', 'old'],
  ['figured out', 'learned'],
  ['preferences', 'desires'],
  ['illuminated', 'lit'],
  ['unrelenting', 'unending'],
  ['reiterating', 'repeating'],
  ['demonstrate', 'show'],
  ['demolishing', 'destroying'],
  ['demolishing', 'destroying'],
  ['hypothesize', 'guess'],
  ['proposition', 'choice'],
  ['reinforcing', 'supporting'],
  ['degenerated', 'broke down'],
  ['deferential', 'nice'],
  ['detrimental', 'bad'],
  ['utilization', 'use'],
  ['misdemeanor', 'crime'],
  ['decomposing', 'breaking down'],
  ['declaration', 'statement'],
  ['reimbursing', 'paying back'],
  ['reinstating', 'putting back'],
  ['opportunity', 'chance'],
  ['courteously', 'politely'],
  ['counterfeit', 'fake'],
  ['shouldâve', 'should have'],
  ['reiteration', 'repetition'],
  ['convocation', 'graduation'],
  ['fundamental', 'basic'],
  ['functioning', 'working'],
  ['potentially', 'maybe'],
  ['potentially', 'maybe'],
  ['researching', 'studying'],
  ['microscopic', 'very small'],
  ['tantalizing', 'exciting'],
  ['contributor', 'giver'],
  ['frantically', 'almost'],
  ['fortunately', 'luckily'],
  ['formulating', 'making'],
  ['contributed', 'gave'],
  ['contraption', 'machine'],
  ['scrutinized', 'criticized'],
  ['flourishing', 'growing'],
  ['continually', 'constantly'],
  ['presupposed', 'assumed'],
  ['tenderizing', 'softening'],
  ['intersperse', 'spread'],
  ['visualizing', 'seeing'],
  ['visualizing', 'seeing'],
  ['constructed', 'built'],
  ['constructed', 'made'],
  ['constituent', 'inner'],
  ['considerate', 'nice'],
  ['considerate', 'thoughtful'],
  ['consequence', 'effect'],
  ['fascinating', 'interesting'],
  ['intersected', 'crossed'],
  ['merchandise', 'products'],
  ['accentuated', 'stressed'],
  ['terminating', 'ending'],
  ['interrogate', 'question'],
  ['confiscated', 'taken'],
  ['attached to', 'put the'],
  ['interlacing', 'twisting'],
  ['response to', 'answer'],
  ['nondescript', 'normal'],
  ['facetiously', 'jokingly'],
  ['fabrication', 'fiction'],
  ['intelligent', 'smart'],
  ['concatenate', 'join'],
  ['shrivelling', 'shrinking'],
  ['compressing', 'squeezing'],
  ['rather than', 'instead of'],
  ['adjacent to', 'aside'],
  ['pleasurable', 'nice'],
  ['have a talk', 'talk'],
  ['instructing', 'teaching'],
  ['complaisant', 'nice'],
  ['compilation', 'collection'],
  ['exclusively', 'only'],
  ['wherewithal', 'smarts'],
  ['melancholic', 'sad'],
  ['mathematics', 'math'],
  ['collaborate', 'work together'],
  ['insinuating', 'suggesting'],
  ['aversion to', 'dislike of'],
  ['materialize', 'happen'],
  ['pleasurable', 'good'],
  ['circumvents', 'gets around'],
  ['exasperated', 'tired'],
  ['negotiation', 'argument'],
  ['initialized', 'prepared'],
  ['established', 'made'],
  ['challenging', 'difficult'],
  ['rudimentary', 'basic'],
  ['withdrawing', 'removing'],
  ['one another', 'each other'],
  ['blameworthy', 'bad'],
  ['bifurcation', 'split'],
  ['eradicating', 'removing'],
  ['manufacture', 'make'],
  ['spectacular', 'amazing'],
  ['bewildering', 'confusing'],
  ['childs play', 'easy'],
  ['abbreviated', 'made shorter'],
  ['initialised', 'prepared'],
  ['maneuvering', 'moving'],
  ['elimination', 'removal'],
  ['eliminating', 'removing'],
  ['perspective', 'view'],
  ['segregating', 'separating'],
  ['belligerent', 'mean'],
  ['belligerent', 'mean'],
  ['malfunction', 'error'],
  ['authorizing', 'letting'],
  ['drastically', 'dramatically'],
  ['resemblance', 'similarity'],
  ['distinguish', 'separate'],
  ['associating', 'grouping'],
  ['disregarded', 'ignored'],
  ['transferred', 'moved'],
  ['such a time', 'the time'],
  ['transformed', 'changed'],
  ['assassinate', 'kill'],
  ['maintaining', 'keeping'],
  ['ascertained', 'found'],
  ['at any rate', 'anyway'],
  ['dispiriting', 'sad'],
  ['transmitted', 'sent'],
  ['accompanied', 'was with'],
  ['accompanies', 'is with'],
  ['enrolled in', 'entered'],
  ['bargain for', 'anticipate'],
  ['barge in on', 'to interrupt'],
  ['make amends', 'become friends'],
  ['transparent', 'clear'],
  ['appropriate', 'ok'],
  ['account for', 'explain'],
  ['disparaging', 'insulting'],
  ['pretty much', 'almost'],
  ['treacherous', 'difficult'],
  ['appreciable', 'large'],
  ['treacherous', 'dangerous'],
  ['inexpensive', 'cheap'],
  ['alleviating', 'easing'],
  ['maintaining', 'keeping'],
  ['disgraceful', 'bad'],
  ['nefariously', 'very wrongly'],
  ['attached to', 'put the'],
  ['disembarked', 'left'],
  ['long winded', 'wordy'],
  ['proprietors', 'owners'],
  ['brush up on', 'improve'],
  ['discontinue', 'stop'],
  ['adolescents', 'children'],
  ['chicken out', 'loose the courage'],
  ['incompetent', 'stupid'],
  ['necessitate', 'need'],
  ['performance', 'show'],
  ['administers', 'gives'],
  ['dropped out', 'left'],
  ['diminishing', 'lessening'],
  ['adjudicator', 'judge'],
  ['adjudicated', 'judged'],
  ['get down to', 'now do'],
  ['slaughtered', 'killed'],
  ['replenished', 'refilled'],
  ['quarrelling', 'fighting'],
  ['deteriorate', 'break'],
  ['accusations', 'claims'],
  ['stipulating', 'saying'],
  ['prematurely', 'early'],
  ['pretty much', 'almost'],
  ['legislation', 'law'],
  ['impropriety', 'crime'],
  ['embarked on', 'began'],
  ['by means of', 'by'],
  ['adjacent to', 'beside'],
  ['accumulated', 'grouped'],
  ['by means of', 'by'],
  ['large scale', 'big'],
  ['passed away', 'died'],
  ['a couple of', 'some'],
  ['unambiguous', 'clear'],
  ['accumulates', 'groups'],
  ['unambiguous', 'clear'],
  ['in order to', 'to'],
  ['in light of', 'with'],
  ['declarations', 'statements'],
  ['irrespective', 'independant'],
  ['modification', 'change'],
  ['transmitting', 'sending'],
  ['subsequently', 'consequently'],
  ['subsequently', 'after'],
  ['initializing', 'preparing'],
  ['facilitating', 'helping'],
  ['substantiate', 'support'],
  ['substituting', 'switching'],
  ['subterranean', 'underground'],
  ['rehabilitate', 'recover'],
  ['remorsefully', 'regretfully'],
  ['tremendously', 'greatly'],
  ['disembarking', 'leaving'],
  ['investigated', 'studied'],
  ['on awful lot', 'a lot'],
  ['accelerating', 'increasing in speed'],
  ['conventional', 'normal'],
  ['belligerents', 'fighters'],
  ['belligerents', 'fighters'],
  ['discontinued', 'stopped'],
  ['neglectfully', 'carelessly'],
  ['contributing', 'giving'],
  ['extinguished', 'stopped'],
  ['preferred to', 'liked to'],
  ['misinterpret', 'misunderstand'],
  ['triumphantly', 'successfully'],
  ['illustration', 'picture'],
  ['child\'s play', 'easy'],
  ['illustrating', 'drawing'],
  ['contemporary', 'recent'],
  ['responded to', 'answered'],
  ['assassinated', 'killed'],
  ['constructive', 'helping'],
  ['ascertaining', 'finding'],
  ['construction', 'building'],
  ['constructing', 'building'],
  ['constructing', 'making'],
  ['scrutinizing', 'criticizing'],
  ['initialising', 'preparing'],
  ['for instance', 'for example'],
  ['replenishing', 'refilling'],
  ['arrangements', 'plans'],
  ['exasperating', 'tiring'],
  ['arrangements', 'plans'],
  ['misfortunate', 'unlucky'],
  ['accompanying', 'going with'],
  ['slaughtering', 'killing'],
  ['bear in mind', 'to consider'],
  ['arrangements', 'plans'],
  ['acceleration', 'increase in speed'],
  ['accompanying', 'coming with'],
  ['horrendously', 'terribly'],
  ['appropriated', 'bought'],
  ['interspersed', 'spread'],
  ['considerably', 'very'],
  ['considerable', 'much'],
  ['accomplishes', 'does'],
  ['considerable', 'big'],
  ['apprehensive', 'worried'],
  ['apprehension', 'worry'],
  ['appreciative', 'thankful'],
  ['establishing', 'making'],
  ['misdemeanour', 'crime'],
  ['intersecting', 'crossing'],
  ['periodically', 'sometimes'],
  ['pull through', 'survive'],
  ['undergarment', 'underwear'],
  ['materialized', 'happened'],
  ['confiscating', 'taking'],
  ['enthusiastic', 'excited'],
  ['to the teeth', 'heavily'],
  ['for instance', 'for example'],
  ['from scratch', 'from the beginning'],
  ['interrogated', 'questioned'],
  ['affectionate', 'loving'],
  ['in the wrong', 'wrong'],
  ['confidential', 'secret'],
  ['emphatically', 'heavily'],
  ['misconstrued', 'misunderstood'],
  ['necessitated', 'needed'],
  ['unemployment', 'joblessness'],
  ['abbreviating', 'making shorter'],
  ['manufactured', 'made'],
  ['unfathomable', 'amazing'],
  ['unfavourable', 'bad'],
  ['abridgements', 'shorter forms'],
  ['administered', 'gave'],
  ['abbreviation', 'short form'],
  ['in the right', 'right'],
  ['adjudicating', 'judging'],
  ['accentuating', 'stressing'],
  ['demonstrated', 'shown'],
  ['what matters', 'what\'s important'],
  ['inapropriate', 'not ok'],
  ['additionally', 'also'],
  ['unrecognized', 'unknown'],
  ['foundational', 'basic'],
  ['manufactured', 'made'],
  ['sought after', 'look for'],
  ['phenomenally', 'very'],
  ['what matters', 'what\'s important'],
  ['accumulation', 'group'],
  ['disregarding', 'ignoring'],
  ['inadequacies', 'problems'],
  ['municipality', 'town'],
  ['deliberately', 'purposely'],
  ['degenerating', 'breaking'],
  ['transferring', 'moving'],
  ['pertained to', 'involved'],
  ['presupposing', 'assuming'],
  ['transforming', 'changing'],
  ['circumvented', 'got around'],
  ['recollection', 'memory'],
  ['circumstance', 'situation'],
  ['circumstance', 'situation'],
  ['identical to', 'the same as'],
  ['circumstance', 'situation'],
  ['accumulating', 'getting'],
  ['chesterfield', 'couch'],
  ['transmission', 'message'],
  ['complimentary', 'free'],
  ['materializing', 'happening'],
  ['reprehensible', 'terrible'],
  ['reinforcement', 'support'],
  ['abided by its', 'followed'],
  ['in respect of', 'for'],
  ['manufacturers', 'makers'],
  ['juxtaposition', 'comparison'],
  ['subsequent to', 'after'],
  ['over and over', 'many times'],
  ['introspective', 'thoughtful'],
  ['pertaining to', 'involving'],
  ['interspersing', 'spreading'],
  ['weaselled out', 'got out'],
  ['get over with', 'end'],
  ['accomplishing', 'doing'],
  ['interrogation', 'questioning'],
  ['recapitulates', 'repeat'],
  ['realistically', 'really'],
  ['appropriating', 'buying'],
  ['birthday suit', 'completely naked body'],
  ['proliferation', 'spreading'],
  ['bargained for', 'anticipated'],
  ['interrogating', 'questioning'],
  ['spectacularly', 'amazingly'],
  ['predominately', 'mostly'],
  ['accommodation', 'room'],
  ['accommodating', 'nice'],
  ['paternalistic', 'fatherly'],
  ['assassinating', 'killing'],
  ['bombastically', 'loudly'],
  ['paraphernalia', 'things'],
  ['circumventing', 'getting around'],
  ['non-compliant', 'disagreeable'],
  ['necessitating', 'needing'],
  ['be obliged to', 'be happy to'],
  ['spectacularly', 'very'],
  ['preferring to', 'liking to'],
  ['gave her word', 'promised'],
  ['gave his word', 'promised'],
  ['responding to', 'answering'],
  ['civilizations', 'societies'],
  ['infinitesimal', 'very small'],
  ['comprehension', 'understanding'],
  ['inexpressible', 'unsayable'],
  ['comprehensive', 'complete'],
  ['superficially', 'lightly'],
  ['superfluously', 'unnecessarily'],
  ['supplementary', 'extra'],
  ['consideration', 'thought'],
  ['fantastically', 'amazingly'],
  ['non compliant', 'disagreeable'],
  ['misconception', 'misunderstanding'],
  ['misconception', 'confusion'],
  ['accounted for', 'included'],
  ['unfortunately', 'unluckily'],
  ['unexpressible', 'unsayable'],
  ['demonstrating', 'showing'],
  ['unambiguously', 'clearly'],
  ['disparagement', 'insult'],
  ['dissemination', 'sharing'],
  ['exceptionally', 'very'],
  ['presupposition', 'assumption'],
  ['distinguishing', 'separating'],
  ['conglomeration', 'organization'],
  ['conglomeration', 'mass'],
  ['in the name of', 'for'],
  ['misinterpreted', 'misunderstood'],
  ['with regard to', 'about'],
  ['initialisation', 'preparation'],
  ['gave your word', 'promised'],
  ['initialization', 'preparation'],
  ['municipalities', 'towns'],
  ['conventionally', 'normally'],
  ['back and forth', 'backwards and forwards'],
  ['affectionately', 'lovingly'],
  ['by the wayside', 'away'],
  ['refrained from', 'avoided'],
  ['recapitulation', 'repetition'],
  ['on the part of', 'by'],
  ['malfunctioning', 'breaking'],
  ['simultaneously', 'at the same time'],
  ['rehabilitation', 'recovery'],
  ['counterfactual', 'wrong'],
  ['all of a sudden', 'immediately'],
  ['out of the loop', 'not connected'],
  ['all of a sudden', 'suddenly'],
  ['instrumentation', 'tools'],
  ['ophthalmologist', 'eye-expert'],
  ['failing to have', 'organizing'],
  ['being facetious', 'joking'],
  ['as a precaution', 'for safety'],
  ['until such time', 'until'],
  ['the majority of', 'most of'],
  ['per se', 'really'],
  ['bear the burden', 'have the trouble'],
  ['confidentiality', 'secretly'],
  ['misinterpreting', 'misunderstanding'],
  ['misapprehension', 'confusion'],
  ['as a last resort', 'if everything else fails'],
  ['in opposition to', 'against'],
  ['during such time', 'while'],
  ['don\'t mention it', 'it\'s ok'],
  ['a great deal less', 'a lot less'],
  ['take into account', 'include'],
  ['a great deal more', 'a lot more'],
  ['push the envelope', 'push the rules'],
  ['down in the dumps', 'sad'],
  ['in the event that', 'if'],
  ['taken for granted', 'not appreciated'],
  ['sexual intercourse', 'sex'],
  ['nooks and crannies', 'small parts'],
  ['taken into account', 'included'],
  ['the gross majority', 'most'],
  ['in the near future', 'soon'],
  ['scene of the crime', 'place of the crime'],
  ['in view of the fact', 'because'],
  ['as a matter of fact', 'actually'],
  ['come to a stop', 'stop'],
  ['come to an agreement', 'agree'],
  ['was hard up for cash', 'had no money'],
  ['at the drop of a hat', 'immediately'],
  ['came to an agreement', 'agreed'],
  ['come to a stop', 'stop'],
  ['beat around the bush', 'to speak indirectly'],
  ['full blast', 'top speed'],
  ['under the provisions of', 'under'],
  ['came to a stop', 'stopped'],
  ['at the top of one\'s lungs', 'with a very loud voice'],
  ['coming to a stop', 'stopping'],
  ['in retrospect', 'looking back'],
  ['just slightly', 'just a little']
];
