var carlgary_test = (function() {
	var nlp = require("../index")
	var txt = "" +
		"Calgary is a city in the province of Alberta, Canada. It is situated at the confluence of the Bow River and the Elbow River in the south of the province, in an area of foothills and prairie, approximately 80 km (50 mi) east of the front ranges of the Canadian Rockies. As of the 2011 census, the City of Calgary had a population of 1,096,833 and a metropolitan population of 1,214,839, making it the largest city in Alberta, and the third-largest municipality and fifth-largest census metropolitan area (CMA) in Canada. " +
		"The economy of Calgary includes activity in the energy, financial services, film and television, transportation and logistics, technology, manufacturing, aerospace, health and wellness, retail, and tourism sectors. The Calgary CMA is home to the second-most corporate head offices in Canada among the country's 800 largest corporations. " +
		"Calgary anchors the south end of what Statistics Canada defines as the Calgary–Edmonton Corridor. " +
		"In 1988, Calgary became the first Canadian city to host the Olympic Winter Games. " +
		"The Calgary area was inhabited by pre-Clovis people whose presence has been traced back at least 11,000 years. Prior to the arrival of Europeans, the area was inhabited by the Blackfoot, Blood, Peigan and the Tsuu T'ina First Nations peoples, all of which were part of the Blackfoot Confederacy. In 1787, cartographer David Thompson spent the winter with a band of Peigan encamped along the Bow River. He was a Hudson's Bay Company trader and the first recorded European to visit the area. John Glenn was the first documented European settler in the Calgary area, in 1873. " +
		"The site became a post of the North-West Mounted Police (now the Royal Canadian Mounted Police or RCMP). The NWMP detachment was assigned in 1875 to protect the western plains from U.S. whisky traders, and protect the fur trade. Originally named Fort Brisebois, after NWMP officer Éphrem-A. Brisebois, it was renamed Fort Calgary in 1876 by Colonel James Macleod. It was named after Calgary on the Isle of Mull, Scotland. While there is some disagreement on the naming of the town, the museum on the Isle of Mull explains that kald and gart are similar Old Norse words, meaning 'cold' and 'garden', that were likely used when named by the Vikings who inhabited the Inner Hebrides. Alternatively, the name might come from the Gaelic, Cala ghearraidh, meaning 'beach of the meadow (pasture)'.[citation needed]" +
		"When the Canadian Pacific Railway reached the area in 1883, and a rail station was constructed, Calgary began to grow into an important commercial and agricultural centre. The Canadian Pacific Railway headquarters moved to Calgary from Montreal in 1996. Calgary was officially incorporated as a town in 1884, and elected its first mayor, George Murdoch. In 1894, it was incorporated as 'The City of Calgary' in what was then the North-West Territories. " +
		"The Calgary Fire of 1886 occurred on November 7, 1886. Fourteen buildings were destroyed with losses estimated at $103,200. Although no one was killed or injured, city officials drafted a law requiring all large downtown buildings to be built with Paskapoo sandstone, to prevent this from happening again. " +
		"Calgary experiences a dry humid continental climate (Köppen climate classification Dwb, USDA Plant Hardiness Zone 3a). " +
		"According to Environment Canada, average daytime high temperatures in Calgary range from 24 °C (75 °F) in late July to −3 °C (27 °F) in mid-January. " +
		"Calgary has the warmest winters of all the major prairie cities, based on the average nighttime temperatures from December to February. The climate is greatly influenced by the city's elevation and proximity to the Rocky Mountains. Calgary's winters are broken up by warm, dry Chinook winds that routinely blow into the city from over the mountains during the winter months. These winds are known to raise the winter temperature by 20 °C (36 °F), and as much as 30 °C (54 °F) in just a few hours, and may last several days. " +
		"In summer, daytime temperatures can exceed 29 °C (84 °F) anytime in June, July and August, and occasionally as late as September or as early as May. As a consequence of Calgary's high elevation and aridity, summer evenings tend to cool off. " +
		"Calgary has the most sunny days year round of Canada's 100-largest cities, with just over 332 days of sun. The city is among the sunniest in Canada, with 2,405 hours of annual sunshine, on average. " +
		"The City of Calgary's 2013 municipal census counted a population of 1,149,552, a 2.6% increase over its 2012 municipal census population of 1,120,225. " +
		"In the 2011 Census, the City of Calgary had a population of 1,096,833 living in 423,417 of its 445,848 total dwellings, a 10.9% change from its 2006 adjusted population of 988,812. With a land area of 825.29 km2 (318.65 sq mi), it had a population density of 1,329.0/km2 (3,442.2/sq mi) in 2011. According to the 2011 Statistics Canada Census, persons aged 14 years and under made up 17.9% of the population, and those aged 65 and older made up 9.95%. The median age was 36.4 years. In 2011, the city's gender population was 49.9% male and 50.1% female. " +
		"The Calgary census metropolitan area (CMA) is the fifth-largest CMA in Canada and largest in Alberta. It had a population of 1,214,839 in the 2011 Census compared to its 2006 population of 1,079,310. Its five-year population change of 12.6 percent was the highest among all CMAs in Canada between 2006 and 2011. With a land area of 5,107.55 km2 (1,972.04 sq mi), the Calgary CMA had a population density of 237.9/km2 (616.0/sq mi) in 2011. Statistics Canada's latest estimate of the Calgary CMA population, as of July 1, 2013, is 1,364,827. " +
		"Between 2001 and 2006, Calgary's population grew by 12.4%. During the same time period, the population of Alberta increased by 10.6%, while that of Canada grew by 5.4%. " +
		"Calgary is recognized as a Canadian leader in the oil and gas industry as well as for being a leader in economic expansion. Its high personal and family incomes, low unemployment and high GDP per capita have all benefited from increased sales and prices due to a resource boom, and increasing economic diversification. Because of these strengths, Calgary is designated as a global city by the Globalization and World Cities Research Network. Also, Calgary was one of the top 200 cities worldwide, by the Brookings Institution, that had a top performing local economy for 2011. The city was ranked first nationally, and 51st in the world, in that aspect. Additionally, Calgary was voted third in quality of life among North American cities by the 2011-2012 issue of American Cities of the Future. The Conference Board of Canada forecasts Calgary to lead the country in GDP growth through to 2016. " +
		"Calgary benefits from a relatively strong job market in Alberta, is part of the Calgary–Edmonton Corridor, one of the fastest growing regions in the country. It is the head office for many major oil and gas related companies, and many financial service business have grown up around them. " +
		"In the 2011-2012 school year, 100,632 K-12 students enrolled in 221 schools in the English language public school system run by the Calgary Board of Education.[146] With other students enrolled in the associated CBe-learn and Chinook Learning Service programs, the school system's total enrollment is 104,182 students.[146] Another 43,000 attend about 95 schools in the separate English language Calgary Catholic School District board.[147] The much smaller Francophone community has their own French language school boards (public and Catholic), which are both based in Calgary, but serve a larger regional district. There are also several public charter schools in the city. "

	var sentences = nlp.pos(txt)

	sentences.forEach(function(s) {
		console.log(s.text())
		s.to_past()
		console.log(s.text())
		console.log('  ')
		console.log('  ')
	})


	if (typeof module !== "undefined" && module.exports) {
		module.exports = sentences;
	}
	return sentences;
})();