const units = {
  'Temperature': {
    '°c': 'Celsius',
    '°f': 'Fahrenheit',
    'k': 'Kelvin',
    '°re': 'Reaumur',
    '°n': 'Newton',
    '°ra': 'Rankine',
  },
  'Volume': {
    'm³': 'cubic meter',
    'm3': 'cubic meter',
    'dm³': 'cubic decimeter',
    'dm3': 'cubic decimeter',
    'cm³': 'cubic centimeter',
    'cm3': 'cubic centimeter',
    'l': 'liter',
    'dl': 'deciliter',
    'cl': 'centiliter',
    'ml': 'milliliter',
    'in³': 'cubic inch',
    'in3': 'cubic inch',
    'ft³': 'cubic foot',
    'ft3': 'cubic foot',
    'yd³': 'cubic yard',
    'yd3': 'cubic yard',
    'gal': 'gallon',
    'bbl': 'petroleum barrel',
    'pt': 'pint',
  },
  'Distance': {
    'km': 'kilometer',
    'm': 'meter',
    'dm': 'decimeter',
    'cm': 'centimeter',
    'mm': 'millimeter',
    'mi': 'mile',
    'in': 'inch',
    'ft': 'foot',
    'feet': 'foot',
    'yd': 'yard',
  },
  'Weight': {
    't': 'tonne',
    'kg': 'kilogram',
    'hg': 'hectogram',
    'g': 'gram',
    'dg': 'decigram',
    'cg': 'centigram',
    'mg': 'milligram',
    'µg': 'microgram',
    'carat': 'carat',
    'grain': 'grain',
    'oz': 'ounce',
    'lb': 'pound',
    'ton': 'tonne',
    'st': 'stone',
  },
  'Area': {
    'km²': 'square kilometer',
    'km2': 'square kilometer',
    'm²': 'square meter',
    'm2': 'square meter',
    'dm²': 'square decimeter',
    'dm2': 'square decimeter',
    'cm²': 'square centimeter',
    'cm2': 'square centimeter',
    'mm²': 'square millimeter',
    'mm2': 'square millimeter',
    'ha': 'hectare',
    'ca': 'centiare',
    'mile²': 'square mile',
    'mile2': 'square mile',
    'in²': 'square inch',
    'in2': 'square inch',
    'yd²': 'square yard',
    'yd2': 'square yard',
    'ft²': 'square foot',
    'ft2': 'square foot',
    'acre': 'acre',
  },
  'Frequency': {
    'hz': 'hertz'
  },
  'Speed': {
    'km/h': 'kilometer per hour',
    'kmph': 'kilometer per hour',
    'mps': 'meter per second',
    'm/s': 'meter per second',
    'mph': 'mile per hour',
    'mi/h': 'mile per hour',
    'knot': 'knot',
  },
  'Data': {
    'b': 'byte',
    'kb': 'kilobyte',
    'mb': 'megabyte',
    'gb': 'gigabyte',
    'tb': 'terabyte',
    'pt': 'petabyte',
    'eb': 'exabyte',
    'zb': 'zettabyte',
    'yb': 'yottabyte',
  },
  'Energy': {
    'j': 'joule',
    'pa': 'pascal',
    'bar': 'bar',
    'w': 'watt',
    'n': 'newton',
    'wb': 'weber',
    't': 'tesla',
    'h': 'henry',
    'c': 'coulomb',
    'v': 'volt',
    'f': 'farad',
    's': 'siemens',
    'o': 'ohm',
    'lx': 'lux',
    'lm': 'lumen'
  },
  'Time': {
    'year': 'year',
    'week': 'week',
    'day': 'day',
    'h': 'hour',
    'min': 'minute',
    's': 'second',
    'ms': 'millisecond',
    'µs': 'microsecond',
    'nanosecond': 'nanosecond',
    'picosecond': 'picosecond',
    'femtosecond': 'femtosecond',
    'attosecond': 'attosecond'
  },
  'Money': {
    //ISO currency codes
    'afn': 'currency',
    'dzd': 'currency',
    'ars': 'currency',
    'amd': 'currency',
    'awg': 'currency',
    'aud': 'currency',
    'azn': 'currency',
    'bsd': 'currency',
    'bhd': 'currency',
    'thb': 'currency',
    'pab': 'currency',
    'bbd': 'currency',
    'byr': 'currency',
    'bzd': 'currency',
    'bmd': 'currency',
    'vef': 'currency',
    'bob': 'currency',
    'xba': 'currency',
    'xbb': 'currency',
    'xbd': 'currency',
    'xbc': 'currency',
    'brl': 'currency',
    'bnd': 'currency',
    'bgn': 'currency',
    'bif': 'currency',
    'cve': 'currency',
    'cad': 'currency',
    'kyd': 'currency',
    'clp': 'currency',
    'cop': 'currency',
    'kmf': 'currency',
    'cdf': 'currency',
    'bam': 'currency',
    'nio': 'currency',
    'crc': 'currency',
    'cup': 'currency',
    'czk': 'currency',
    'gmd': 'currency',
    'dkk': 'currency',
    'mkd': 'currency',
    'djf': 'currency',
    'std': 'currency',
    'dop': 'currency',
    'vnd': 'currency',
    'xcd': 'currency',
    'egp': 'currency',
    'svc': 'currency',
    'etb': 'currency',
    'eur': 'currency',
    'fkp': 'currency',
    'fjd': 'currency',
    'huf': 'currency',
    'ghs': 'currency',
    'gip': 'currency',
    'xau': 'currency',
    'htg': 'currency',
    'pyg': 'currency',
    'gnf': 'currency',
    'gyd': 'currency',
    'hkd': 'currency',
    'uah': 'currency',
    'isk': 'currency',
    'inr': 'currency',
    'irr': 'currency',
    'iqd': 'currency',
    'jmd': 'currency',
    'jod': 'currency',
    'kes': 'currency',
    'pgk': 'currency',
    'lak': 'currency',
    'hrk': 'currency',
    'kwd': 'currency',
    'aoa': 'currency',
    'mmk': 'currency',
    'gel': 'currency',
    'lbp': 'currency',
    'all': 'currency',
    'hnl': 'currency',
    'sll': 'currency',
    'lrd': 'currency',
    'lyd': 'currency',
    'szl': 'currency',
    'lsl': 'currency',
    'mga': 'currency',
    'mwk': 'currency',
    'myr': 'currency',
    'mur': 'currency',
    'mxn': 'currency',
    'mxv': 'currency',
    'mdl': 'currency',
    'mad': 'currency',
    'mzn': 'currency',
    'bov': 'currency',
    'ngn': 'currency',
    'ern': 'currency',
    'nad': 'currency',
    'npr': 'currency',
    'ang': 'currency',
    'ils': 'currency',
    'twd': 'currency',
    'nzd': 'currency',
    'btn': 'currency',
    'kpw': 'currency',
    'nok': 'currency',
    'mro': 'currency',
    'top': 'currency',
    'pkr': 'currency',
    'xpd': 'currency',
    'mop': 'currency',
    'cuc': 'currency',
    'uyu': 'currency',
    'php': 'currency',
    'xpt': 'currency',
    'gbp': 'currency',
    'bwp': 'currency',
    'qar': 'currency',
    'gtq': 'currency',
    'zar': 'currency',
    'omr': 'currency',
    'khr': 'currency',
    'ron': 'currency',
    'mvr': 'currency',
    'idr': 'currency',
    'rub': 'currency',
    'rwf': 'currency',
    'shp': 'currency',
    'sar': 'currency',
    'xdr': 'currency',
    'rsd': 'currency',
    'scr': 'currency',
    'xag': 'currency',
    'sgd': 'currency',
    'pen': 'currency',
    'sbd': 'currency',
    'kgs': 'currency',
    'sos': 'currency',
    'tjs': 'currency',
    'ssp': 'currency',
    'lkr': 'currency',
    'xsu': 'currency',
    'sdg': 'currency',
    'srd': 'currency',
    'sek': 'currency',
    'chf': 'currency',
    'syp': 'currency',
    'bdt': 'currency',
    'wst': 'currency',
    'tzs': 'currency',
    'kzt': 'currency',
    'ttd': 'currency',
    'mnt': 'currency',
    'tnd': 'currency',
    'try': 'currency',
    'tmt': 'currency',
    'aed': 'currency',
    'ugx': 'currency',
    'clf': 'currency',
    'cou': 'currency',
    'uyi': 'currency',
    'usd': 'currency',
    'usn': 'currency',
    'uzs': 'currency',
    'vuv': 'currency',
    'che': 'currency',
    'chw': 'currency',
    'krw': 'currency',
    'yer': 'currency',
    'jpy': 'currency',
    'cny': 'currency',
    'zmw': 'currency',
    'zwl': 'currency',
    'pln': 'currency',
    //ISO currencies names
    'afghani': 'currency',
    'algerian dinar': 'currency',
    'argentine peso': 'currency',
    'armenian dram': 'currency',
    'aruban florin': 'currency',
    'australian dollar': 'currency',
    'azerbaijanian manat': 'currency',
    'bahamian dollar': 'currency',
    'bahraini dinar': 'currency',
    'baht': 'currency',
    'balboa': 'currency',
    'barbados dollar': 'currency',
    'belarusian ruble': 'currency',
    'belize dollar': 'currency',
    'bermudian dollar': 'currency',
    'bolívar': 'currency',
    'boliviano': 'currency',
    'brazilian real': 'currency',
    'brunei dollar': 'currency',
    'bulgarian lev': 'currency',
    'burundi franc': 'currency',
    'cabo verde escudo': 'currency',
    'canadian dollar': 'currency',
    'cayman islands dollar': 'currency',
    'chilean peso': 'currency',
    'colombian peso': 'currency',
    'comoro franc': 'currency',
    'congolese franc': 'currency',
    'convertible mark': 'currency',
    'cordoba oro': 'currency',
    'costa rican colon': 'currency',
    'cuban peso': 'currency',
    'czech koruna': 'currency',
    'dalasi': 'currency',
    'danish krone': 'currency',
    'denar': 'currency',
    'djibouti franc': 'currency',
    'dobra': 'currency',
    'dominican peso': 'currency',
    'dong': 'currency',
    'east caribbean dollar': 'currency',
    'egyptian pound': 'currency',
    'el salvador colon': 'currency',
    'ethiopian birr': 'currency',
    'euro': 'currency',
    'falkland islands pound': 'currency',
    'fiji dollar': 'currency',
    'forint': 'currency',
    'ghana cedi': 'currency',
    'gibraltar pound': 'currency',
    'gold': 'currency',
    'gourde': 'currency',
    'guarani': 'currency',
    'guinea franc': 'currency',
    'guyana dollar': 'currency',
    'hong kong dollar': 'currency',
    'hryvnia': 'currency',
    'iceland krona': 'currency',
    'indian rupee': 'currency',
    'iranian rial': 'currency',
    'iraqi dinar': 'currency',
    'jamaican dollar': 'currency',
    'jordanian dinar': 'currency',
    'kenyan shilling': 'currency',
    'kina': 'currency',
    'kip': 'currency',
    'kuna': 'currency',
    'kuwaiti dinar': 'currency',
    'kwanza': 'currency',
    'kyat': 'currency',
    'lari': 'currency',
    'lebanese pound': 'currency',
    'lek': 'currency',
    'lempira': 'currency',
    'leone': 'currency',
    'liberian dollar': 'currency',
    'libyan dinar': 'currency',
    'lilangeni': 'currency',
    'loti': 'currency',
    'malagasy ariary': 'currency',
    'malawi kwacha': 'currency',
    'malaysian ringgit': 'currency',
    'mauritius rupee': 'currency',
    'mexican peso': 'currency',
    'moldovan leu': 'currency',
    'moroccan dirham': 'currency',
    'mozambique metical': 'currency',
    'mvdol': 'currency',
    'naira': 'currency',
    'nakfa': 'currency',
    'namibia dollar': 'currency',
    'nepalese rupee': 'currency',
    'netherlands antillean guilder': 'currency',
    'new israeli sheqel': 'currency',
    'new taiwan dollar': 'currency',
    'new zealand dollar': 'currency',
    'ngultrum': 'currency',
    'north korean won': 'currency',
    'norwegian krone': 'currency',
    'ouguiya': 'currency',
    'pa’anga': 'currency',
    'pakistan rupee': 'currency',
    'palladium': 'currency',
    'pataca': 'currency',
    'peso convertible': 'currency',
    'peso uruguayo': 'currency',
    'philippine peso': 'currency',
    'platinum': 'currency',
    'pound sterling': 'currency',
    'pula': 'currency',
    'qatari rial': 'currency',
    'quetzal': 'currency',
    'rand': 'currency',
    'rial omani': 'currency',
    'riel': 'currency',
    'romanian leu': 'currency',
    'rufiyaa': 'currency',
    'rupiah': 'currency',
    'russian ruble': 'currency',
    'rwanda franc': 'currency',
    'saint helena pound': 'currency',
    'saudi riyal': 'currency',
    'serbian dinar': 'currency',
    'seychelles rupee': 'currency',
    'silver': 'currency',
    'singapore dollar': 'currency',
    'sol': 'currency',
    'solomon islands dollar': 'currency',
    'som': 'currency',
    'somali shilling': 'currency',
    'somoni': 'currency',
    'south sudanese pound': 'currency',
    'sri lanka rupee': 'currency',
    'sucre': 'currency',
    'sudanese pound': 'currency',
    'surinam dollar': 'currency',
    'swedish krona': 'currency',
    'swiss franc': 'currency',
    'syrian pound': 'currency',
    'taka': 'currency',
    'tala': 'currency',
    'tanzanian shilling': 'currency',
    'tenge': 'currency',
    'trinidad and tobago dollar': 'currency',
    'tugrik': 'currency',
    'tunisian dinar': 'currency',
    'turkish lira': 'currency',
    'turkmenistan new manat': 'currency',
    'uae dirham': 'currency',
    'uganda shilling': 'currency',
    'unidad de fomento': 'currency',
    'unidad de valor real': 'currency',
    'us dollar': 'currency',
    'uzbekistan sum': 'currency',
    'vatu': 'currency',
    'wir euro': 'currency',
    'wir franc': 'currency',
    'won': 'currency',
    'yemeni rial': 'currency',
    'yen': 'currency',
    'yuan renminbi': 'currency',
    'zambian kwacha': 'currency',
    'zimbabwe dollar': 'currency',
    'zloty': 'currency',
    //colloquial currency names
    'dollar': 'currency',
    'cent': 'currency',
    'penny': 'currency',
    'dime': 'currency',
    'dinar': 'currency',
    'euro': 'currency',
    'lira': 'currency',
    'pound': 'currency',
    'GBP': 'currency',
    'pence': 'currency',
    'peso': 'currency',
    'sterling': 'currency',
    'rand': 'currency',
    'rouble': 'currency',
    'shekel': 'currency',
    'sheqel': 'currency',
    'yuan': 'currency',
    'franc': 'currency',
    'rupee': 'currency',
    'shilling': 'currency',
    'krona': 'currency',
    'dirham': 'currency',
    'real': 'currency',
    //currency symbols
    '€': 'currency',
    '$': 'currency',
    '¥': 'currency',
    '£': 'currency',
    'лв': 'currency',
    '₡': 'currency',
    'kn': 'currency',
    'kr': 'currency',
    '¢': 'currency',
    'Ft': 'currency',
    'Rp': 'currency',
    '﷼': 'currency',
    '₭': 'currency',
    'ден': 'currency',
    '₨': 'currency',
    'zł': 'currency',
    'lei': 'currency',
    'руб': 'currency',
    '฿': 'currency',
    //other
    'bitcoin': 'currency',
  }
};

module.exports = Object.keys(units).reduce(function(h, k) {
  Object.keys(units[k]).forEach(function(u) {
    h[u] = {
      name: units[k][u],
      category: k
    };
    h[units[k][u]] = {
      name: units[k][u],
      category: k
    };
  });
  return h;
}, {});
