//just a few named-organizations
//no acronyms needed. no product/brand pollution.
module.exports = [
  'abc',
  'academy of sciences',
  'acer',
  'activision',
  'adidas',
  'aig',
  'al jazeera',
  'al qaeda',
  'alcatel-lucent',
  'alcatel',
  'altair',
  'amc',
  'amd',
  'american express',
  'amt',
  'amtrak',
  'anheuser-busch',
  'aol',
  'apple computers',
  "applebee's",
  "arby's",
  'argos',
  'armco',
  'ashland oil',
  'associated press',
  'at&t',
  'avis',
  'avon',
  'ayer',
  'banana republic',
  'basf',
  'baskin robbins',
  'baxter',
  'bayer',
  'bbc',
  'bechtel',
  "ben & jerry's",
  'berkshire hathaway',
  'bf goodrich',
  'bfgoodrich',
  'black & decker',
  'blockbuster video',
  'bloomingdale',
  'blue cross',
  'bmw',
  'bni',
  'boeing',
  'bombardier',
  'boston globe',
  'boston pizza',
  'bp',
  'capital one',
  'cadbury',
  "carl's jr",
  'cbc',
  'chevron',
  'chevy',
  'chick fil-a',
  'china daily',
  'cia',
  'cisco systems',
  'cisco',
  'citigroup',
  'cnn',
  'coca cola',
  'colgate',
  'comcast',
  'compaq',
  'coors',
  'costco',
  'craigslist',
  'daimler',
  'dea',
  'dell',
  'der spiegel',
  'disney',
  'doj',
  'dow jones',
  'dunkin donuts',
  'dupont',
  'ebay',
  'esa',
  'eu',
  'exxon mobil',
  'exxonmobil',
  'facebook',
  'fannie mae',
  'fbi',
  'fda',
  'fedex',
  'fiat',
  'financial times',
  'firestone',
  'ford',
  'frito-lay',
  'general electric',
  'general motors',
  'ghq',
  'glaxo smith kline',
  'glencore',
  'goldman sachs',
  'goodyear',
  'google',
  'gucci',
  'h & m',
  'hasbro',
  'hewlett-packard',
  'hitachi',
  'hizbollah',
  'home depot',
  'honda',
  'hsbc',
  'hyundai',
  'ibm',
  'ihop',
  'ing',
  'intel',
  'interpol',
  'itv',
  'jiffy lube',
  'johnson & johnson',
  'jpmorgan chase',
  'jpmorgan',
  'jsa',
  'katv',
  'kfc',
  'kkk',
  'kmart',
  'kodak',
  "l'oreal",
  'la presse',
  'la-z-boy',
  'lenovo',
  'lexis',
  'lexmark',
  'lg',
  'little caesars',
  "mac's milk",
  'mattel',
  'mazda',
  "mcdonald's",
  'mcdonalds',
  'medicaid',
  'medicare',
  'mercedes-benz',
  'mercedes',
  'microsoft',
  'mitas',
  'mitsubishi',
  'mlb',
  'mobil',
  'monsanto',
  'motorola',
  'mtv',
  'myspace',
  'nandos',
  'nasa',
  'nascar',
  'nasdaq',
  'national academy of sciences',
  'nato',
  'natwest',
  'nba',
  'nbc',
  'nestle',
  'nestlé',
  'netflix',
  'new york times',
  'newsweek',
  'nfl',
  'nhl',
  'nhs',
  'nike',
  'nintendo',
  'nissan',
  'nokia',
  'notre dame',
  'novartis',
  'nsa',
  'nwa',
  'old navy',
  'opec',
  'orange julius',
  'oxfam',
  'pan am',
  'panasonic',
  'panda express',
  'pbs',
  'pepsico',
  'petrobras',
  'petrochina',
  'petronas',
  'peugeot',
  'pfizer',
  'philip morris',
  'pizza hut',
  'premier oil',
  'procter & gamble',
  'prudential',
  'quantas',
  "quizno's",
  'rbc',
  'rbs',
  're/max',
  'readers digest',
  'red bull',
  'red cross',
  'red lobster',
  'revlon',
  'royal bank',
  'royal dutch shell',
  'ryanair',
  'safeway',
  "sainsbury's",
  'samsung',
  'sears',
  'siemens',
  'sony',
  'starbucks',
  'statoil',
  'subaru',
  't mobile',
  'taco bell',
  'td bank',
  'telefonica',
  'telus',
  'tesco',
  'tesla motors',
  'tgi fridays',
  'the daily mail',
  'tim hortons',
  'tmz',
  'toshiba',
  'toyota',
  'toys r us',
  'twitter',
  'ubs',
  'unesco',
  'unilever',
  'united nations',
  'ups',
  'usa today',
  'usps',
  'verizon',
  'visa',
  'vodafone',
  'volkswagen',
  'volvo',
  'wal-mart',
  'walgreens',
  'wall street journal',
  'walmart',
  'warner bros',
  'wells fargo',
  'westfield',
  'westinghouse',
  'world trade organization',
  'yahoo!',
  'yamaha',
  'ymca',
  'youtube',
  'ywca',

  //some bands
  'abba',
  'ac/dc',
  'aerosmith',
  'bee gees',
  'coldplay',
  'creedence clearwater revival',
  'def leppard',
  'depeche mode',
  "destiny's child",
  'duran duran',
  'fleetwood mac',
  'green day',
  'guns n roses',
  'joy division',
  'metallica',
  'moody blues',
  'motley crue',
  'new kids on the block',
  'pink floyd',
  'r.e.m.',
  'radiohead',
  'red hot chili peppers',
  'sex pistols',
  'soundgarden',
  'spice girls',
  'the beach boys',
  'the beatles',
  'the black eyed peas',
  'the byrds',
  'the carpenters',
  'the guess who',
  'the hollies',
  'the rolling stones',
  'the smashing pumpkins',
  'the supremes',
  'the who',
  'thin lizzy',
  'u2',
  'van halen'
];
