export default {

  verb: {
    "make": "create/compell",
    "have": "possess/experience",
    "see": "perceive/understand",
    "come": "arrive/occur",
    "look": "gaze/search",
    "run": "sprint/operate",
    "believe": "accept/trust",
    "feel": "perceive/experience",
    "call": "summon/name",
    "work": "labor/function",
  },

  "want": "desire/wish",
  "give": "provide/offer",
  "use": "utilize/employ",
  "find": "discover/locate",
  "tell": "instruct/inform",
  "ask": "request/inquire",
  "seem": "appear/imply",
  "feel": "perceive/experience",
  "try": "attempt/endeavor",
  "leave": "depart/abandon",
  "need": "require/necessitate",
  "become": "transform/develop",
  "mean": "signify/imply",
  "keep": "retain/maintain",
  "turn": "rotate/change",
  "show": "display/demonstrate",
  "hear": "perceive/listen",
  "play": "participate/perform",
  "move": "shift/proceed",
  "like": "enjoy/appreciate",
  "live": "reside/exist",
  "hold": "grasp/maintain",
  "bring": "deliver/introduce",
  "happen": "occur/take place",
  "write": "record/compose",
  "provide": "supply/offer",
  "sit": "perch/be seated",
  "stand": "be upright/endure",
  "lose": "misplace/suffer",
  "pay": "remunerate/compensate",
  "meet": "encounter/convene",





  // "break": "separate/rest/fail",
  // "cast": "act/throw/group",
  // "check": "examine/stop/chess",
  // "cut": "sever/shape/reduced",
  // "drop": "fall/let go/decrease",
  // "face": "front/expression",
  // "fast": "quick/secure",
  // "figure": "number/shape/person",
  // "fine": "good/penalty",
  // "fly": "insect/travel",
  // "frame": "structure/picture/blame",
  // "ground": "earth/reason/electrical",
  // "hit": "strike/success",
  // "hook": "bent/catch",
  // "bank": "financial institution/land alongside a river",
  // "blue": "color/feeling sad",
  // "bow": "bend at the waist/weapon",
  // "bowl": "dish for serving food/to participate in a game",
  // "brush": "tool for cleaning or painting/to lightly touch",
  // "button": "fastener on clothing/to fasten",
  // "can": "container/ability to do something",
  // "change": "to become different/coins used as money",
  // "character": "person in a story/distinctive qualities",
  // "charge": "to ask for payment/to rush forward",
  // "clean": "free of dirt or marks/to make something clean",
  // "cold": "low temperature/lacking in affection",
  // "comb": "tool for grooming hair/to search thoroughly",
  // "content": "what is contained/satisfied with what one has",
  // "cover": "to put something over/outer part of a book",
  // "crane": "bird with long neck/machine used for lifting heavy objects",


  adjective: {
    "great": "fantastic/important",
    "low": "short/inferior",
    "hard": "firm/difficult",
    "easy": "simple/effortless",
    "rich": "wealthy/abundant",
    "healthy": "fit/wholesome",
    "long": "extended/lengthy",
    "short": "brief/small",
    "miserable": "unhappy/woeful",
    "cheap": "inexpensive/inferior",
    "busy": "occupied/hectic",
    "weak": "frail/inadequate",
    "poor": "destitute/scant",
    "happy": "content/cheerful",
    "soft": "yielding/gentle",
  },




  noun: {
    "bark": "sound/tree",
    "bat": "animal/sports",
    "man": "male/human",
    "state": "condition/political",
    "country": "nation/rural",
    "case": "instance/legal",
    "value": "quantity/virtue",
    "school": "education/fish",
    "point": "dot/idea",
    "business": "trade/company",
    "power": "energy/authority",
    "child": "young/descendant",
    "order": "arrangement/request",
    "management": "control/job-title",
    "organ": "anatomy/music",
    "product": "goods/result",
    "crane": "bird/machine",
    "bore": "dullness/drill",
    "bow": "weapon/knot/reverence",
    "brush": "tool/touch",
    "grade": "level/slope",
    "head": "body/leader",
    "issue": "topic/release/problem",
  },
}