// Generated by CoffeeScript 1.6.3
var arr, data;

require("dirtyjs");

data = require("./data").data;

arr = data.map('infinitive').filter(function(r) {
  return r.match(/[aiou]$/);
});

console.log(arr);
