import test from 'tape'
import nlp from '../_lib.js'
const here = '[three/adj-noun] '

let arr = [
  ['dramatic', 'drama'],
  ['deep', 'depth'],
  ['ironic', 'irony'],

  ['desperate', 'desperation'],
  ['imperfect', 'imperfection'],
  ['affectionate', 'affection'],
  // ['perceptible', 'perception'],
  // ['perceptive', 'perception'],
  ['automatic', 'automation'],

  ['tenuous', 'tenuousness'],
  ['full', 'fullness'],
  ['beautiful', 'beauty'],
  ['earnest', 'earnestness'],
  ['cheap', 'cheapness'],
  ['sharp', 'sharpness'],
  ['gentle', 'gentleness'],

  ['vertical', 'verticality'],
  ['simple', 'simplicity'],
  ['creative', 'creativity'],
  ['legal', 'legality'],
  ['physical', 'physicality'],

  // ['inspiring', 'inspiration'],
  ['boring', 'boredom'],

  ['passionate', 'passion'],
  ['compassionate', 'compassion'],
  ['proportionate', 'proportion'],
  ['desperate', 'desperation'],
  ['fortunate', 'fortune'],

  ['friendly', 'friendliness'],
  ['full', 'fullness'],
  ['funny', 'funniness'],
  ['furry', 'furriness'],
  ['gaudy', 'gaudiness'],
  ['gay', 'gayness'],
  ['ghastly', 'ghastliness'],

  ['superficial', 'superficiality'],
  ['swift', 'swiftness'],
  ['tall', 'tallness'],
  ['tame', 'tameness'],
  ['tart', 'tartness'],
  ['tawdry', 'tawdriness'],
  ['tense', 'tenseness'],
  ['thirsty', 'thirstiness'],
  ['tidy', 'tidiness'],
  ['timely', 'timeliness'],
  ['tiny', 'tininess'],
  ['tired', 'tiredness'],
  ['random', 'randomness'],
  ['credible', 'credibility'],
  ['impossible', 'impossibility'],
  ['annoying', null],

  ['moist', 'moistness'],
  ['quick', 'quickness'],
  ['quiet', 'quiet'],
  ['red', 'redness'],
  ['ripe', 'ripeness'],
  ['rough', 'roughness'],
  ['sad', 'sadness'],
  ['sharp', 'sharpness'],

  // ['curious', 'curiosity'],
  // ['loyal', 'loyalty'],
  // ['quiet', 'quietness'],
  // ['desperate', 'desperation'],
  // ['brave', 'bravery'],
  // ['confident', 'confidence'],
  // ['resilient', 'resilience'],
  // ['determined', 'determination'],
  // ['ambitious', 'ambition'],
  // ['joyful', 'joy'],
  // ['generous', 'generosity'],
  // ['compassionate', 'compassion'],
  // ['fearless', 'fearlessness'],
  // ['patient', 'patience'],
  // ['cooperative', 'cooperation'],
  // ['outgoing', 'outgoingness'],
  // ['successful', 'success'],
  // ['sensitive', 'sensitivity'],
  // ['energetic', 'energy'],
  // ['flexible', 'flexibility'],
  // ['organized', 'organization'],
  // ['passionate', 'passion'],
  // ['positive', 'positivity'],
  // ['resourceful', 'resourcefulness'],
  // ['reliable', 'reliability'],
  // ['independent', 'independence'],
  // ['inspiring', 'inspiration'],
  // ['respectful', 'respect'],
  // ['accurate', 'accuracy'],
  // ['active', 'activity'],
  // ['amiable', 'amiability'],
  // ['brave', 'bravery'],
  // ['bright', 'brightness'],
  // ['creative', 'creativity'],
  // ['caring', 'care'],
  // ['eager', 'eagerness '],
  // ['generous', 'generosity'],
  // ['gracious', 'grace'],
  // ['humble', 'humility'],
  // ['kind', 'kindness'],
  // ['modest', 'modesty'],
  // ['optimistic', 'optimism'],
  // ['practical', 'practicality'],
  // ['sensible', 'sensibility'],
  // ['sincere', 'sincerity'],
  // ['amusing', 'amusement'],
  // ['imaginative', 'imagination'],
  // ['insightful', 'insight'],
  // ['intelligent', 'intelligence'],
  // ['inquisitive', 'inquisitiveness'],
  // ['joyful', 'joy'],
  // ['loving', 'love'],
  // ['mature', 'maturity'],
  // ['receptive', 'receptiveness'],
  // ['selfless', 'selflessness'],
  // ['talented', 'talent'],
  // ['tolerant', 'tolerance'],
  // ['trustworthy', 'trust'],
  // ['artistic', 'art'],
  // ['competent', 'competency'],
  // ['expressive', 'expressiveness'],
  // ['friendly', 'friendliness'],
  // ['gentle', 'gentleness'],
  // ['humorous', 'humor'],
  // ['noble', 'nobility'],
  // ['perceptive', 'perception'],
  // ['powerful', 'power'],
  // ['responsible', 'responsibility'],
  // ['skillful', 'skill'],
  // ['thoughtful', 'thoughtfulness'],
  // ['wise', 'wisdom'],
  // ['amiable', 'amiability'],
  // ['quick', 'quickness'],
  // ['slow', 'slowness'],
  // ['heavy', 'heaviness'],
  // ['thin', 'thinness'],
  // ['rich', 'richness'],
  // ['poor', 'poverty'],
  // ['strong', 'strength'],
  // ['weak', 'weakness'],
  // ['fast', 'fastness'],
  // ['slow', 'slowness'],
  // ['good', 'goodness'],
  // ['bad', 'badness'],
  // ['calm', 'calmness'],
  // ['eager', 'eagerness'],
  // ['joyful', 'joyfulness'],
  // ['humble', 'humbleness'],
  // ['certain', 'certainty'],
  // ['hot', 'heat'],
  // ['cold', 'coldness'],
  // ['long', 'length'],
  // ['short', 'shortness'],
  // ['round', 'roundness'],
  // ['straight', 'straightness'],
  // ['cheap', 'cheapness'],
  // ['expensive', 'expensiveness'],
  // ['short', 'shortness'],
  // ['tall', 'tallness'],
  // ['brave', 'bravery'],
  // ['soft', 'softness'],
  // ['hard', 'hardness'],
  // ['clear', 'clarity'],
  // ['dull', 'dullness'],
  // ['bright', 'brightness'],
  // ['empty', 'emptiness'],
  // ['ancient', 'antiquity'],
  // ['young', 'youth'],
  // ['sweet', 'sweetness'],
  // ['sour', 'sourness'],
  // ['light', 'lightness'],
  // ['dark', 'darkness'],
  // ['clever', 'cleverness'],
  // ['brave', 'bravery'],
  // ['lost', 'loss'],
  // ['tough', 'toughness'],
  // ['polite', 'politeness'],
  // ['honest', 'honesty'],
  // ['silent', 'silence'],
  // ['busy', 'busincess'],
  // ['rich', 'richness'],
  // ['smooth', 'smoothness'],
  // ['rough', 'roughness'],
  // ['clean', 'cleanliness'],
  // ['dirty', 'dirtiness'],
  // ['lazy', 'laziness'],
  // ['elegant', 'elegance'],
  // ['loud', 'loudness'],
  // ['tiny', 'tininess'],
  // ['huge', 'hugeness'],
]

test('toNoun:', function (t) {
  let { toNoun } = nlp().methods.two.transform.adjective
  arr.forEach(a => {
    let res = toNoun(a[0])
    t.equal(res, a[1], here + ` [toNoun] ${a[1]}`)
  })
  t.end()
})
