//two-way us/uk transitions with no patterns
module.exports = [
  ['axe', 'ax'],
  ['jewellery', 'jewelry'],
  ['almanack', 'almanac'],
  ['aluminium', 'aluminum'],
  ['axe', 'ax'],
  ['artefact', 'artifact'],
  ['buses', 'busses'],
  ['chequered', 'checkered'],
  ['cypher', 'cipher'],
  ['disc', 'disk'],
  ['chilli', 'chili'],
  ['inflexion', 'inflection'],
  ['storey', 'story'],
  ['pyjama', 'pajama'],
  ['tyre', 'tire'],
  ['waggon', 'wagon'],
  ['woollen', 'woolen'],
  ['woolly', 'wooly'],
  ['woollies', 'woolies'],
  ['yoghourt', 'yogurt'],
  ['yoghurt', 'yogurt'],







  ['aerogramme', 'aerogram'],
  ['aerogrammes', 'aerograms'],
  ['anaesthetise', 'anesthetize'],
  ['anaesthetised', 'anesthetized'],
  ['anaesthetises', 'anesthetizes'],
  ['anaesthetising', 'anesthetizing'],
  ['appal', 'appall'],
  ['appals', 'appalls'],
  ['armourers', 'armorers'],
  ['bannister', 'banister'],
  ['bannisters', 'banisters'],
  ['battleaxe', 'battleax'],
  ['behaviourists', 'behaviorists'],
  ['bevvies', 'bevies'],
  ['bevvy', 'bevy'],
  ['biassing', 'biasing'],
  ['busing', 'bussing'],
  ['calliper', 'caliper'],
  ['callipers', 'calipers'],
  ['callisthenics', 'calisthenics'],
  ['cancellation', 'cancelation'],
  ['cancellations', 'cancelations'],
  ['catalogued', 'cataloged'],
  ['centred', 'centered'],
  ['clarinettist', 'clarinetist'],
  ['clarinettists', 'clarinetists'],
  ['connexion', 'connection'],
  ['connexions', 'connections'],
  ['cosy', 'cozy'],
  ['councillors', 'councilors'],
  ['counsellors', 'counselors'],
  ['crenellated', 'crenelated'],
  ['crueller', 'crueler'],
  ['cruellest', 'cruelest'],
  ['dialled', 'dialed'],
  ['dialling', 'dialing'],
  ['distill', 'distil'],
  ['distills', 'distils'],
  ['enrol', 'enroll'],
  ['enrols', 'enrolls'],
  ['enthral', 'enthrall'],
  ['enthrals', 'enthralls'],
  ['epaulette', 'epaulet'],
  ['epaulettes', 'epaulets'],
  ['favourites', 'favorites'],
  ['favouritism', 'favoritism'],
  ['flautist', 'flutist'],
  ['flautists', 'flutists'],
  ['flavourings', 'flavorings'],
  ['flavoursome', 'flavorsome'],
  ['gases', 'gasses'],
  ['gauging', 'gaging'],
  ['ghettoise', 'ghettoize'],
  ['ghettoised', 'ghettoized'],
  ['ghettoises', 'ghettoizes'],
  ['gipsies', 'gypsies'],
  ['groyne', 'groin'],
  ['groynes', 'groins'],
  ['gruelling', 'grueling'],
  ['gruellingly', 'gruelingly'],
  ['gryphon', 'griffin'],
  ['gryphons', 'griffins'],
  ['instal', 'install'],
  ['instalment', 'installment'],
  ['instalments', 'installments'],
  ['instals', 'installs'],
  ['instil', 'instill'],
  ['instils', 'instills'],
  ['jewellers', 'jewelers'],
  ['labourers', 'laborers'],
  ['levellers', 'levelers'],
  ['libellous', 'libelous'],
  ['licencing', 'licensing'],
  ['louvred', 'louvered'],
  ['louvres', 'louvers'],
  ['manoeuvrability', 'maneuverability'],
  ['manoeuvrable', 'maneuverable'],
  ['manoeuvre', 'maneuver'],
  ['manoeuvred', 'maneuvered'],
  ['manoeuvres', 'maneuvers'],
  ['manoeuvring', 'maneuvering'],
  ['manoeuvrings', 'maneuverings'],
  ['minibuses', 'minibusses'],
  ['modellers', 'modelers'],
  ['moult', 'molt'],
  ['moulted', 'molted'],
  ['moulting', 'molting'],
  ['moults', 'molts'],
  ['moustache', 'mustache'],
  ['moustached', 'mustached'],
  ['moustaches', 'mustaches'],
  ['moustachioed', 'mustachioed'],
  ['neighbourhood', 'neighborhood'],
  ['neighbourhoods', 'neighborhoods'],
  ['neighbourliness', 'neighborliness'],
  ['outmanoeuvre', 'outmaneuver'],
  ['outmanoeuvred', 'outmaneuvered'],
  ['outmanoeuvres', 'outmaneuvers'],
  ['outmanoeuvring', 'outmaneuvering'],
  ['panellist', 'panelist'],
  ['panellists', 'panelists'],
  ['philtre', 'filter'],
  ['philtres', 'filters'],
  ['ploughshare', 'plowshare'],
  ['ploughshares', 'plowshares'],
  ['pouffe', 'pouf'],
  ['pouffes', 'poufs'],
  ['practise', 'practice'],
  ['practised', 'practiced'],
  ['practises', 'practices'],
  ['practising', 'practicing'],
  ['pretence', 'pretense'],
  ['pretences', 'pretenses'],
  ['pummelled', 'pummel'],
  ['pummelling', 'pummeled'],
  ['pzazz', 'pizzazz'],
  ['recognisably', 'recognizably'],
  ['recognisance', 'recognizance'],
  ['reconnoitred', 'reconnoitered'],
  ['reconnoitring', 'reconnoitering'],
  ['revellers', 'revelers'],
  ['snowploughs', 'snowplow'],
  ['storeys', 'stories'],
  ['theatregoer', 'theatergoer'],
  ['theatregoers', 'theatergoers'],
  ['tranquillise', 'tranquilize'],
  ['tranquillised', 'tranquilized'],
  ['tranquilliser', 'tranquilizer'],
  ['tranquillisers', 'tranquilizers'],
  ['tranquillises', 'tranquilizes'],
  ['tranquillising', 'tranquilizing'],
  ['tranquilly', 'tranquility'],
  ['travellers', 'travelers'],
  ['videodiscs', 'videodisks'],







];
