// Generated by CoffeeScript 1.6.3
var o, obj, r, rules, w, _i, _len;

rules = require("./rules").rules;

o = {
  "infinitive": "convolute",
  "present": "convolutes",
  "gerund": "convoluting",
  "past": "convoluted"
};

w = "convoluted";

w = "overthrew";

w = "overthrowing";

w = "convolutes";

w = "relays";

w = "relays";

w = "present";

w = "angulate";

w = "regularize";

for (_i = 0, _len = rules.length; _i < _len; _i++) {
  r = rules[_i];
  if (w.match(r.reg)) {
    obj = Object.keys(r.repl).reduce(function(h, k) {
      h[k] = w.replace(r.reg, r.repl[k]);
      return h;
    }, {});
    console.log(obj);
    break;
  }
}
