// Generated by CoffeeScript 1.6.3
var data, evaluate, rules, tmp;

require('dirtyjs');

data = require("./data").data;

rules = require("./rules").data;

evaluate = function(w) {
  var r, _i, _len;
  for (_i = 0, _len = rules.length; _i < _len; _i++) {
    r = rules[_i];
    if (w.match(r.reg)) {
      return r.tense;
    }
  }
};

console.log(data.length + "in total");

tmp = data.filter(function(a) {
  return evaluate(a[0]);
});

console.log(tmp.length + (" with results (" + ((tmp.length / data.length).toFixed(2)) + "%)"));

tmp = data.filter(function(a) {
  return evaluate(a[0]) === a[1];
});

console.log(tmp.length + (" with correct results (" + ((tmp.length / data.length).toFixed(2)) + "%)"));

tmp = data.filter(function(a) {
  return evaluate(a[0]) !== a[1];
});

console.log("most misses:");

console.log(tmp.map(1).topk());
