module.exports = [
  { text: '@', out: ['at'] },
  { text: 'alot', out: ['a', 'lot'] },
  { text: 'brb', out: ['be', 'right', 'back'] },
  { text: 'cannot', out: ['can', 'not'] },
  { text: 'cant', out: ['can', 'not'] },
  { text: 'dont', out: ['do', 'not'] },
  { text: 'dun', out: ['do', 'not'] },
  { text: 'dunno', out: ['do', 'not', 'know'] },
  { text: 'gonna', out: ['going', 'to'] },
  { text: 'gtg', out: ['got', 'to', 'go'] },
  { text: 'howd', out: ['how', 'did'] },
  { text: 'im', out: ['i', 'am'] },
  { text: 'imma', out: ['I', 'will'] },
  { text: 'imo', out: ['in', 'my', 'opinion'] },
  { text: 'irl', out: ['in', 'real', 'life'] },
  { text: 'ive', out: ['i', 'have'] },
  { text: 'rn', out: ['right', 'now'] },
  { text: 'tbh', out: ['to', 'be', 'honest'] },
  { text: 'til', out: ['today', 'i', 'learned'] },
  { text: 'twas', out: ['it', 'was'] },
  { text: 'wanna', out: ['want', 'to'] },
  { text: 'whatd', out: ['what', 'did'] },
  { text: 'whend', out: ['when', 'did'] },
  { text: 'whered', out: ['where', 'did'] },
  { text: 'wont', out: ['will', 'not'] },
  { text: "can't", out: ['can', 'not'] },
  { text: "shan't", out: ['should', 'not'] },
  { text: "when'd", out: ['when', 'did'] },
  { text: "where'd", out: ['where', 'did'] },
  { text: "won't", out: ['will', 'not'] },
]
