export default {
  'act up': `portarse mal`,
  'back up': `dar marcha atrás`,
  'blow up': `explotar`,
  'break down': `descomponerse`,
  'bring up': `criar`,
  'call off': `cancelar`,
  'carry on': `continuar`,
  'catch up': `alcanzar`,
  'cheer up': `alegrar`,
  'check in': `registrarse`,
  'check out': `echar un vistazo`,
  'come across': `encontrarse con`,
  'come up with': `idear`,
  'count on': `contar con`,
  'cross out': `tachar`,
  'cut down': `reducir`,
  'do over': `hacer de nuevo`,
  'drop off': `dejar caer`,
  'end up': `terminar`,
  'figure out': `descubrir`,
  'fill out': `rellenar`,
  'find out': `descubrir`,
  'fix up': `arreglar`,
  'get away': `escapar`,
  'get in': `subir`,
  'get off': `bajar`,
  'get on': `subir`,
  'get out': `salir`,
  'get over': `superar`,
  'give up': `rendirse`,
  'go ahead': `adelante`,
  'go away': `irse`,
  'go on': `continuar`,
  'grow up': `crecer`,
  'hang up': `colgar`,
  'hold on': `esperar`,
  'keep up': `mantener`,
  'knock out': `noquear`,
  'lay off': `despedir`,
  'leave out': `omitir`,
  'look after': `cuidar`,
  'look forward to': `esperar con ilusión`,
  'look up': `buscar`,
  'make up': `inventar`,
  'mess up': `estropear`,
  'pass out': `desmayarse`,
  'pick up': `recoger`,
  'point out': `señalar`,
  'put off': `posponer`,
  'put up with': `aguantar`,
  'run into': `encontrarse con`,
  'set up': `establecer`,
  'show off': `presumir`,
  'sort out': `resolver`,
  'stand out': `destacar`,
  'take after': `parecerse a`,
  'take off': `despegar`,
  'take up': `empezar a hacer`,
  'talk over': `discutir`,
  'think over': `reflexionar`,
  'throw away': `tirar`,
  'try on': `probarse`,
  'turn down': `rechazar`,
  'turn off': `apagar`,
  'turn on': `encender`,
  'turn up': `aparecer`,
  'use up': `agotar`,
  'wake up': `despertarse`,
  'walk out': `abandonar`,
  'warm up': `calentar`,
  'watch out': `cuidado`,
  'work out': `resolver`,
  'write down': `apuntar`,
  'back out': `echarse atrás`,
  'back up': `respaldar`,
  'beat up': `golpear`,
  'blow up': `hinchar`,
  'break down': `romper`,
  'bring about': `provocar`,
  'bring back': `devolver`,
  'bring down': `derribar`,
  'bring in': `introducir`,
  'break down': `tomber en panne`,
  'break in': `mettre à l'aise`,
  'break out': `éclater`,
  'break up': `se séparer`,
  'bring about': `provoquer`,
  'bring back': `rapporter`,
  'bring up': `élever`,
  'call off': `annuler`,
  'call up': `appeler`,
  'carry on': `continuer`,
  'catch on': `comprendre`,
  'check in': `s'enregistrer`,
  'check out': `quitter l'hôtel`,
  'check over': `vérifier`,
  'come across': `rencontrer par hasard`,
  'come down': `descendre`,
  'come in': `entrer`,
  'come off': `réussir`,
  'come on': `avancer`,
  'come out': `sortir`,
  'come up': `surgir`,
  'count on': `compter sur`,
  'cut down': `réduire`,
  'cut off': `couper`,
  'deal with': `traiter de`,
  'do away with': `se débarrasser de`,
  'do over': `refaire`,
  'drop off': `déposer`,
  'end up': `finir par`,
  'fall apart': `s'effondrer`,
  'fall down': `tomber`,
  'fall off': `diminuer`,
  'fall out': `se disputer`,
  'figure out': `comprendre`,
  'fill in': `remplir`,
  'find out': `découvrir`,
  'get along': `s'entendre`,
  'get away': `partir`,
  'get back': `rentrer`,
  'get in': `entrer`,
  'get off': `descendre`,
  'get on': `monter`,
  'get out': `sortir`,
  'get over': `surmonter`,
  'get up': `se lever`,
  'give up': `abandonner`,
  'go along': `continuer`,
  'go back': `retourner`,
  'go on': `continuer`,
  'go out': `sortir`,
  'go over': `passer en revue`,
  'grow up': `grandir`,
  'hang out': `traîner`,
  'hold on': `attendre`,
  'hold up': `retarder`,
  'keep on': `continuer`,
  'knock off': `arrêter`,
  'knock out': `mettre k.o.`,
  'lay off': `licencier`,
  'leave out': `laisser de côté`,
  'let down': `décevoir`,
  'let in': `laisser entrer`,
  'let off': `lâcher`,
  'let out': `libérer`,
  'look after': `s'occuper de`,
  'look for': `chercher`,
  'look out': `faire attention`,
  'look up': `chercher`,
  'make up': `inventer`,
  'mix up': `mélanger`,
  'pass out': `s'évanouir`,
  'pay back': `rembourser`,
  'pick out': `choisir`,
  'pick up': `ramasser`,
  'point out': `signaler`,
  'put away': `ranger`,
  'put off': `remettre à plus tard`,
  'put on': `mettre`,
  'put out': `éteindre`,
  'put up': `héberger`,
  'run away': `s'enfuir`,
  'run into': `rencontrer par hasard`,
  'run out': `s'épuiser`,
  'set up': `installer`,
  'show off': `frimer`,
  'break out': `éclater`,
  'call off': `annuler`,
  'carry out': `effectuer`,
  'catch up': `rattraper`,
  'come across': `rencontrer`,
  'come up with': `trouver`,
  'count on': `compter sur`,
  'drop off': `déposer`,
  'end up': `finir par`,
  'figure out': `comprendre`,
  'get along': `s'entendre`,
  'give up': `abandonner`,
  'go on': `continuer`,
  'keep up': `maintenir`,
  'look after': `s'occuper de`,
  'make up': `inventer`,
  'pick up': `récupérer`,
  'put off': `remettre à plus tard`,
  'set up': `installer`,
  'take off': `décoller.`,
  'look after': `s'occuper de`,
  'take after': `ressembler à`,
  'hold back': `retenir`,
  'break down': `tomber en panne`,
  'come across': `tomber sur`,
  'give in': `céder`,
  'put off': `repousser`,
  'stand up': `se lever`,
  'get over': `surmonter`,
  'call off': `annuler`,
  'put up': `héberger`,
  'look up': `chercher`,
  'carry on': `continuer`,
  'take off': `décoller`,
  'show off': `montrer`,
  'turn up': `apparaître`,
  'run out': `s'épuiser`,
  'bring up': `élever`,
  'cut off': `couper`,
  'keep up': `suivre`,
  'fill up': `remplir`,
  'find out': `découvrir`,
  'hang up': `raccrocher`,
  'break up': `rompre`,
  'look out': `faire attention`,
  'make up': `inventer`,
  'pass out': `s'évanouir`,
  'pick up': `ramasser`,
  'put on': `mettre`,
  'set up': `installer`,
  'take up': `prendre`,
  'throw away': `jeter`,
  'turn off': `éteindre`,
  'watch out': `faire attention`,
  'work out': `résoudre`,
  'break out': `éclater`,
  'catch up': `rattraper`,
  'come up with': `trouver`,
  'get away': `s'échapper`,
  'hold on': `attendre`,
  'let down': `décevoir`,
  'look forward to': `avoir hâte de`,
  'make out': `comprendre`,
  'put out': `éteindre`,
  'run away': `fuir`,
  'take back': `reprendre`,
  'turn on': `allumer`,
  'wake up': `se réveiller`,
  'blow up': `exploser`,
  'hold up': `retarder`,
  'break down': `tomber en panne`,
  'bring up': `évoquer`,
  'carry out': `effectuer`,
  'come across': `tomber sur`,
  'get along': `s'entendre`,
  'put off': `décourager`,
  'run into': `rencontrer par hasard`,
  'take up': `se mettre à`,
  'turn down': `refuser`,
  'wake up': `se réveiller`,
}