// Generated by CoffeeScript 1.6.3
var arr;

arr = ["./libs/jquery.js", "./libs/sugar.js", "./libs/oj.js", "./libs/easings.js", "./libs/dirty.js", "./libs/nlp.min.js", "./libs/bluebrowns.js"];

head.js.apply(this, arr);

head(function() {
  var articles, tags_to_html;
  oj.useGlobally();
  articles = ['chomsky', 'baudrillard', 'keanu'];
  tags_to_html = function(pos, parent) {
    var colour;
    colour = blues(0.4);
    return pos.map(function(sentence) {
      return sentence.tokens.map(function(word) {
        var line;
        if (word.pos.parent === parent) {
          line = "<span style='position:absolute; background-color:" + (bluebrowns(0.4)) + "; left:3px; bottom:2px; width:" + (word.text.length * 5) + "px; height:3px; display:inline-block;'></span>";
          return "<span style='position:relative; border-radius:3px;'>" + word.text + line + "</span>";
        } else {
          return "<span style='position:relative;'>" + word.text + "</span>";
        }
      }).join(' ');
    }).join('<div style="height:10px;"> </div>');
  };
  $("#main").oj(div(function() {
    h3({
      style: "color:grey;"
    }, function() {
      return "nlp comprimise - ";
    });
    table({
      style: "width:80%; padding:0px 10% 0px 10%; height:40px;"
    }, function() {
      return tr(function() {
        return ['adjectives', 'nouns', 'verbs', 'adverbs', 'values'].map(function(pos) {
          return td({
            style: "color:white; background-color:" + (bluebrowns(0.7)) + "; cursor:pointer;",
            click: function() {
              var html, parent, tags, txt;
              txt = $("#text").text();
              tags = nlp.pos(txt);
              parent = pos.replace(/s$/, '');
              html = tags_to_html(tags, parent);
              return $("#text").html(html);
            }
          }, function() {
            return pos;
          });
        });
      });
    });
    table({
      style: "width:80%; padding:0px 10% 0px 10%; height:20px;"
    }, function() {
      return tr({
        id: "second"
      });
    });
    div({
      style: "position:relative; left:50%; width:200px; color:grey;"
    }, function() {
      return articles.map(function(t) {
        return span({
          style: "color:steelblue; font-size:12px; cursor:pointer; padding:5px;",
          click: function() {
            return $.get("./" + t + ".txt", function(txt) {
              return $("#text").html(txt);
            });
          }
        }, function() {
          return t;
        });
      });
    });
    return div({
      id: "text",
      style: "display:block; padding: 5% 10% 5% 10%; text-align:left; width:80%; color:slategrey;"
    });
  }));
  return $.get("./" + (articles.random()) + ".txt", function(txt) {
    return $("#text").html(txt);
  });
});

/*
//@ sourceMappingURL=index.map
*/
