import test from 'tape'
import nlp from '../_lib.js'
const here = '[three/verb-toInfinitive] '

test('toInfinitive:', function (t) {
  let arr = [
    // known forms:
    ['he walked', 'he walk'],
    ['i walked', 'i walk'],
    ['we walked', 'we walk'],
    ['they walked', 'they walk'],
    ['the friends walked', 'the friends walk'],
    ['the friend walked', 'the friend walk'],
    ['our users walked', 'our users walk'],
    ['our user walked', 'our user walk'],
    ['the eye closed', 'the eye close'],
    ['the eyes closed', 'the eyes close'],

    ['their colloseum will open', 'their colloseum open'],
    ['their children will open', 'their children open'],

    ['he walks', 'he walk'],
    ['he walked', 'he walk'],
    ['he will walk', 'he walk'],
    ['he is walking', 'he walk'],
    ['he was walking', 'he walk'],
    ['i am walking', 'i walk'],
    ['he will be walking', 'he walk'],

    ['he has walked', 'he walk'],
    ['he had walked', 'he walk'],
    ['he will have walked', 'he walk'],
    ['he has been walking', 'he walk'],
    ['he had been walking', 'he walk'],
    ['he will have been walking', 'he walk'],
    ['got walked', 'walk'],
    ['was walked', 'walk'],
    ['were walked', 'walk'],
    ['i was being walked', 'i walk'],
    ['had been walked', 'walk'],
    ['have been walked', 'walk'],
    ['is walked', 'walk'],
    ['are walked', 'walk'],
    ['is being walked', 'walk'],
    ['she has been walked', 'she walk'],
    ['had been walked', 'walk'],
    ['will have been walked', 'walk'],
    ['will be walked', 'walk'],
    ['would be walked', 'walk'],
    ['would have been walked', 'walk'],
    ['is going to walk', 'walk'],
    ['did walk', 'walk'],
    ['used to walk', 'walk'],
    ['do walk', 'walk'],
    ['does walk', 'walk'],
    // adverbs
    ['i was really not being walked', 'i really not walk'],
    ['i was not really being walked', 'i not really walk'],
    ['i was being really not walked', 'i really not walk'],
    ['i was being not really walked', 'i not really walk'],
    ['he was not going to walk', 'he not walk'],
    ['we are putting', 'we put'],


    // want-infinitive
    // ['he wants to walk', 'he want to walk'],
    // ['he wanted to walk', 'he want to walk'],
    // ['he will want to walk', 'he want to walk'],

    // ["persuaded", "persuade"],
    // ["overcrowded", "overcrowd"],

    // ["lost", "lose"],
    // ["bereft", "bereave"],


    // ["sown", "sow"],
    // ["overthrown", "overthrow"],
    // ["thrown", "throw"],
    // ["overgrown", "overgrow"],
    // ["flown", "flow"],
    // ["shown", "show"],
    // ["sawn", "saw"],
    // ["withdrawn", "withdraw"],

    ["sworn", "swear"],
    ["worn", "wear"],


    // ["unfrozen", "unfreeze"],
    // ["quick-frozen", "quick-freeze"],
    // ["interwoven", "interweave"],
    // ["rewritten", "rewrite"],
    // ["stolen", "steal"],
    // ["awoken", "awake"],
    // ["broken", "break"],
    // ["mistaken", "mistake"],
    // ["overtaken", "overtake"],
    // ["undertaken", "undertake"],
    // ["taken", "take"],


    // ["overseen", "oversee"],
    // ["foreseen", "foresee"],
    // ["overridden", "override"],
    // ["forbidden", "forbid"],


    // ["shrunk", "shrink"],
    // ["blood-borne", "blood-bear"],
    // ["borne", "bear"],
    // ["outdone", "outdo"],
    // ["done", "do"],
    // ["withstood", "withstand"],
    // ["ground", "grind"],

    ["upheld", "uphold"],
    ["withheld", "withhold"],
    // ["resold", "resell"],
    // ["repaid", "repay"],
    ["dyed", "dye"],


    ["glutted", "glut"],
    ["gutted", "gut"],
    ["spotted", "spot"],
    ["slotted", "slot"],
    ["allotted", "allot"],
    ["dotted", "dot"],
    ["acquitted", "acquit"],
    ["knitted", "knit"],
    ["transmitted", "transmit"],
    ["permitted", "permit"],
    ["omitted", "omit"],
    ["committed", "commit"],
    ["remitted", "remit"],
    ["emitted", "emit"],
    ["admitted", "admit"],
    ["submitted", "submit"],
    ["outfitted", "outfit"],
    ["refitted", "refit"],
    ["benefitted", "benefit"],
    ["fitted", "fit"],
    ["vetted", "vet"],
    // ["silhouetted", "silhouette"],
    ["netted", "net"],
    ["formatted", "format"],


    ["wasted", "waste"],
    ["tasted", "taste"],
    // ["quoted", "quote"],
    // ["piloted", "pilot"],


    // ["consulted", "consult"],
    // ["resulted", "result"],
    // ["catapulted", "catapult"],
    // ["defaulted", "default"],
    // ["wilted", "wilt"],
    // ["tilted", "tilt"],
    // ["melted", "melt"],
    // ["salted", "salt"],
    // ["malted", "malt"],

    // ["exited", "exit"],
    // ["deposited", "deposit"],
    // ["transited", "transit"],
    // ["revisited", "revisit"],
    // ["visited", "visit"],
    // ["inherited", "inherit"],
    // ["expedited", "expedite"],
    // ["solicited", "solicit"],

    // ["interpreted", "interpret"],
    // ["filleted", "fillet"],
    // ["pelleted", "pellet"],
    // ["marketed", "market"],
    // ["skyrocketed", "skyrocket"],
    // ["crocheted", "crochet"],
    // ["targeted", "target"],
    // ["acted", "act"],

    // ["accentuated", "accentuate"],
    // ["situated", "situate"],
    // ["perpetuated", "perpetuate"],
    // ["fluctuated", "fluctuate"],
    // ["evaluated", "evaluate"],
    // ["graduated", "graduate"],
    ["abbreviated", "abbreviate"],
    ["alleviated", "alleviate"],
    ["deviated", "deviate"],
    ["renegotiated", "renegotiate"],
    ["negotiated", "negotiate"],
    ["differentiated", "differentiate"],
    ["substantiated", "substantiate"],
    ["self-initiated", "self-initiate"],
    ["initiated", "initiate"],
    ["satiated", "satiate"],
    ["expropriated", "expropriate"],
    ["appropriated", "appropriate"],
    ["affiliated", "affiliate"],
    ["conciliated", "conciliate"],
    ["repudiated", "repudiate"],
    ["mediated", "mediate"],
    ["associated", "associate"],
    ["enunciated", "enunciate"],
    // ["appreciated", "appreciate"],
    // ["created", "create"],


    // ["warehoused", "warehouse"],
    // ["focused", "focus"],
    // ["focussed", "focus"],
    // ["biased", "bias"],


    // ["spurred", "spur"],
    // ["blurred", "blur"],
    // ["incurred", "incur"],
    // ["occurred", "occur"],
    // ["deterred", "deter"],
    // ["transferred", "transfer"],
    // ["conferred", "confer"],
    // ["inferred", "infer"],
    // ["preferred", "prefer"],
    // ["referred", "refer"],
    // ["deferred", "defer"],
    // ["marred", "mar"],
    // ["jarred", "jar"],
    // ["scarred", "scar"],
    // ["barred", "bar"],


    // ["flavored", "flavor"],
    // ["favored", "favor"],
    // ["monitored", "monitor"],
    // ["factored", "factor"],
    // ["co-sponsored", "co-sponsor"],
    // ["state-sponsored", "state-sponsor"],
    // ["sponsored", "sponsor"],
    // ["mirrored", "mirror"],
    // ["tailored", "tailor"],
    // ["anchored", "anchor"],


    // ["required", "require"],
    // ["acquired", "acquire"],
    // ["aired", "air"],
    // ["adhered", "adhere"],

    ["stopped", "stop"],
    ["topped", "top"],
    ["popped", "pop"],
    ["chopped", "chop"],
    // ["ill-equipped", "ill-equip"],
    // ["well-equipped", "well-equip"],
    // ["equipped", "equip"],
    ["sipped", "sip"],
    ["outstripped", "outstrip"],
    ["stripped", "strip"],
    ["whipped", "whip"],
    ["transshipped", "transship"],
    ["worshipped", "worship"],
    ["shipped", "ship"],
    ["dipped", "dip"],
    ["stepped", "step"],
    ["tapped", "tap"],
    ["unwrapped", "unwrap"],
    ["shrinkwrapped", "shrinkwrap"],
    ["wrapped", "wrap"],
    ["strapped", "strap"],
    ["trapped", "trap"],
    ["scrapped", "scrap"],
    ["snapped", "snap"],
    ["mapped", "map"],

    // ["underdeveloped", "underdevelop"],
    // ["well-developed", "well-develop"],

    // ["revamped", "revamp"],
    // ["stamped", "stamp"],
    // ["cramped", "cramp"],

    // ["helped", "help"],
    // ["seeped", "seep"],
    // ["reaped", "reap"],

    // ["frowned", "frown"],
    // ["drowned", "drown"],
    // ["crowned", "crown"],
    // ["browned", "brown"],
    // ["world-renowned", "world-renown"],
    // ["renowned", "renown"],
    // ["downed", "down"],
    // ["wholly-owned", "wholly-own"],
    // ["co-owned", "co-own"],
    // ["foreign-owned", "foreign-own"],
    // ["owned", "own"],
    // ["pawned", "pawn"],

    // ["attuned", "attune"],
    // ["tuned", "tune"],
    // ["postponed", "postpone"],
    // ["boned", "bone"],

    // ["stunned", "stun"],
    // ["twinned", "twin"],
    // ["underpinned", "underpin"],
    // ["skinned", "skin"],
    // ["thinned", "thin"],
    // ["spanned", "span"],
    // ["panned", "pan"],
    // ["planned", "plan"],
    // ["scanned", "scan"],
    // ["canned", "can"],

    // ["condemned", "condemn"],
    // ["intertwined", "intertwine"],
    // ["entwined", "entwine"],
    // ["destined", "destine"],
    // ["quarantined", "quarantine"],
    // ["enshrined", "enshrine"],
    // ["predetermined", "predetermine"],
    // ["determined", "determine"],
    // ["undermined", "undermine"],
    // ["examined", "examine"],
    // ["mined", "mine"],

    ["outlined", "outline"],
    ["underlined", "underline"],
    ["streamlined", "streamline"],
    ["sidelined", "sideline"],
    ["inclined", "incline"],
    ["declined", "decline"],
    ["lined", "line"],

    // ["machined", "machine"],
    // ["imagined", "imagine"],
    // ["confined", "confine"],
    // ["refined", "refine"],
    // ["defined", "define"],
    // ["fined", "fine"],
    // ["dined", "dine"],
    // ["combined", "combine"],
    // ["convened", "convene"],
    // ["planed", "plane"],
    // ["caned", "cane"],


    // ["accustomed", "accustom"],
    // ["blossomed", "blossom"],
    // ["programmed", "programme"],


    // ["annulled", "annul"],
    // ["extolled", "extol"],
    // ["computer-controlled", "computer-control"],
    // ["voice-controlled", "voice-control"],
    // ["controlled", "control"],
    // ["distilled", "distil"],
    // ["levelled", "level"],
    // ["travelled", "travel"],
    // ["fuelled", "fuel"],
    // ["expelled", "expel"],
    // ["dispelled", "dispel"],
    // ["compelled", "compel"],
    // ["funnelled", "funnel"],
    // ["channelled", "channel"],
    // ["modelled", "model"],
    // ["cancelled", "cancel"],
    // ["labelled", "label"],
    // ["rivalled", "rival"],
    // ["totalled", "total"],
    // ["profiled", "profil"],
    // ["scaled", "scale"],
    // ["baled", "bale"],

    ["invoked", "invoke"],
    ["revoked", "revoke"],
    ["smoked", "smoke"],
    ["choked", "choke"],
    ["spiked", "spike"],
    ["mimicked", "mimic"],
    ["flaked", "flake"],
    ["baked", "bake"],

    // ["stymied", "stymie"],
    // ["clothed", "clothe"],
    // ["wronged", "wrong"],
    // ["tinged", "ting"],


    ["guaranteed", "guarantee"],
    ["agreed", "agree"],
    ["freed", "free"],
    ["fed", "feed"],


    // ["overcrowded", "overcrowd"],
    // ["crowded", "crowd"],
    ["reworded", "reword"],
    ["worded", "word"],
    ["afforded", "afford"],
    ["recorded", "record"],
    ["forwarded", "forward"],
    ["rewarded", "reward"],
    ["awarded", "award"],
    ["guarded", "guard"],
    // ["well-regarded", "well-regard"],
    ["regarded", "regard"],
    ["discarded", "discard"],
    ["carded", "card"],
    ["bombarded", "bombard"],
    ["ended", "end"],
    // ["aided", "aid"],
    ["plodded", "plod"],
    ["skidded", "skid"],
    ["embedded", "embed"],
    ["dissuaded", "dissuade"],
    ["persuaded", "persuade"],

    // ["combed", "comb"],
    ["dubbed", "dub"],
    ["bobbed", "bob"],
    ["ribbed", "rib"],
    ["swabbed", "swab"],
    ["stabbed", "stab"],
    ["nabbed", "nab"],
  ]
  arr.forEach(a => {
    let doc = nlp(a[0])
    doc.verbs().toInfinitive()
    t.equal(doc.text(), a[1], here + ' ' + a[0])
  })
  t.end()
})
