import test from 'tape'
import nlp from '../_lib.js'
const here = '[three/verb-toPastParticiple] '

test('toPastParticiple:', function (t) {
  let arr = [
    [`I eat breakfast every morning.`, `I have eaten breakfast every morning this week.`],
    [`She reads a book before bed.`, `She has read the entire book series.`],
    [`He teaches math to high school students.`, `He has taught math for 20 years.`],
    [`They walk their dog in the park.`, `They have walked their dog every day for a year.`],
    [`We watch a movie on Friday nights.`, `We have watched every movie in the theater this year.`],
    [`I eat pizza.`, `I have eaten pizza.`],
    [`He reads books.`, `He has read books.`],
    [`They run marathons.`, `They have run marathons.`],
    [`She sings songs.`, `She has sung songs.`],
    [`We write letters.`, `We have written letters.`],
    [`You speak Spanish.`, `You have spoken Spanish.`],
    [`He swims laps.`, `He has swum laps.`],
    [`They climb mountains.`, `They have climbed mountains.`],
    [`She dances ballet.`, `She has danced ballet.`],
    [`We paint pictures.`, `We have painted pictures.`],
    [`I play soccer.`, `I have played soccer.`],
    [`They study history.`, `They have studied history.`],
    [`He cooks dinner.`, `He has cooked dinner.`],
    [`She designs websites.`, `She has designed websites.`],
    [`We watch movies.`, `We have watched movies.`],
    [`You listen to music.`, `You have listened to music.`],
    [`They build houses.`, `They have built houses.`],
    [`I plant flowers.`, `I have planted flowers.`],
    [`He fixes cars.`, `He has fixed cars.`],
    [`She teaches math.`, `She has taught math.`],
    [`We clean the house.`, `We have cleaned the house.`],
    [`You drive a car.`, `You have driven a car.`],
    [`They ride bikes.`, `They have ridden bikes.`],
    [`I take photos.`, `I have taken photos.`],
    [`She does yoga.`, `She has done yoga.`],
    [`We sing in the choir.`, `We have sung in the choir.`],
    [`You draw pictures.`, `You have drawn pictures.`],
    [`They make cookies.`, `They have made cookies.`],
    [`He surfs the internet.`, `He has surfed the internet.`],
    [`She plays the guitar.`, `She has played the guitar.`],
    [`We travel the world.`, `We have traveled the world.`],
    [`You speak to friends.`, `You have spoken to friends.`],
    [`They fish in the river.`, `They have fished in the river.`],
    [`I write stories.`, `I have written stories.`],
    [`He takes a shower.`, `He has taken a shower.`],
    [`She sews clothes.`, `She has sewn clothes.`],
    [`We play board games.`, `We have played board games.`],
    [`You exercise at the gym.`, `You have exercised at the gym.`],
    [`They fly airplanes.`, `They have flown airplanes.`],
    [`He studies science.`, `He has studied`],
    ["I sing in the shower.", "I have sung in the shower."],
    ["The sun shines brightly.", "The sun has shone brightly."],
    ["She reads a book every night.", "She has read many books."],
    ["He eats a lot of vegetables.", "He has eaten his vegetables."],
    ["We write a letter to our grandparents.", "We have written letters to our grandparents."],
    ["The dog barks loudly.", "The dog has barked all day."],
    ["I always forget my keys.", "I have forgotten my keys many times."],
    ["She paints beautiful pictures.", "She has painted many beautiful pictures."],
    ["He drives a fast car.", "He has driven many fast cars."],
    ["They play soccer every weekend.", "They have played soccer for years."],
    ["She speaks Spanish fluently.", "She has spoken Spanish since childhood."],
    ["He teaches math at the local college.", "He has taught math for over a decade."],
    ["The tree grows tall.", "The tree has grown taller."],
    ["I clean the house every weekend.", "I have cleaned the house many times."],
    ["She dances gracefully.", "She has danced in many competitions."],
    ["He flies to New York for business.", "He has flown to many cities for work."],
    ["We swim in the pool on hot days.", "We have swum in many pools."],
    ["They run a marathon every year.", "They have run many marathons."],
    ["The bird chirps early in the morning.", "The bird has chirped all day."],
    ["She sews her own clothes.", "She has sewn many outfits."],
    ["He builds houses for a living.", "He has built many homes."],
    ["We drink coffee every morning.", "We have drunk many cups of coffee."],
    ["They watch movies on Friday nights.", "They have watched many movies."],
    ["The flower smells sweet.", "The flower has smelled beautiful."],
    ["I play the guitar.", "I have played the guitar for years."],
    ["She designs jewelry for a living.", "She has designed many pieces of jewelry."],
    ["He studies biology in college.", "He has studied many subjects in college."],
    ["We take walks in the park.", "We have taken many walks in the park."],
    ["They listen to music on their way to work.", "They have listened to many songs."],
    ["The wind blows gently.", "The wind has blown fiercely."],
    ["She cooks dinner for her family.", "She has cooked many meals for her family."],
    ["the tree will grow", "the tree had grown"],
    ["the tree grows quickly", "the tree had grown quickly"],
    ["She will have eaten", "She had eaten"],
    ["They will have finished", "They had finished"],
    ["He will have written", "He had written"],
    ["We will have seen", "We had seen"],
    ["You will have spoken", "You had spoken"],
  ]
  arr.forEach(a => {
    let doc = nlp(a[0])
    doc.verbs().toPastParticiple()
    t.equal(doc.text(), a[1], here + ' ' + a[0])
  })
  t.end()
})
