export default [
  ['¢', 'cent'],
  ['$', 'dollar'],
  ['€', 'EUR'],
  ['£', 'GBP'],
  ['¥', 'JPY/YEN'],
  ['₹', 'INR'],
  ['₩', 'KRW'],
  ['₽', 'RUB'],
  ['₺', 'TRY'],
  ['฿', 'THB'],
  ['₪', 'ILS'],
  ['₫', 'VND'],
  ['₴', 'UAH'],
  ['₦', 'NGN'],
  ['₱', 'PHP'],
  ['₲', 'PYG'],
  ['₡', 'CRC'],
  ['﷼', 'SAR'],
  ['₮', 'MNT'],
  ['₭', 'LAK'],
  ['₸', 'KZT'],
]