const test = require('tape')
const nlp = require('./_lib')
//tests 'borrowed' from Travis Savo's lib 💝 https://github.com/TSavo/english2number-js
const cardinal = function (str) {
  return nlp(str).values().json(0).number
}

test('parse numbers', function (t) {
  t.equal(cardinal('0'), 0, '0')
  t.equal(cardinal('1'), 1, '1')
  t.equal(cardinal('2'), 2, '2')
  t.equal(cardinal('3'), 3, '3')
  t.equal(cardinal('4'), 4, '4')
  t.equal(cardinal('5'), 5, '5')
  t.equal(cardinal('6'), 6, '6')
  t.equal(cardinal('7'), 7, '7')
  t.equal(cardinal('8'), 8, '8')
  t.equal(cardinal('9'), 9, '9')
  t.equal(cardinal('10'), 10, '10')
  t.equal(cardinal('20'), 20, '20')
  t.equal(cardinal('30'), 30, '30')
  t.equal(cardinal('50'), 50, '50')
  t.equal(cardinal('90'), 90, '90')
  t.equal(cardinal('100'), 100, '100')
  t.end()
})
test('parse numbered ordinals', function (t) {
  t.equal(cardinal('0th'), 0, '0th')
  t.equal(cardinal('1st'), 1, '1st')
  t.equal(cardinal('2nd'), 2, '2nd')
  t.equal(cardinal('3rd'), 3, '3rd')
  t.equal(cardinal('4th'), 4, '4th')
  t.equal(cardinal('5th'), 5, '5th')
  t.equal(cardinal('6th'), 6, '6th')
  t.equal(cardinal('7th'), 7, '7th')
  t.equal(cardinal('8th'), 8, '8th')
  t.equal(cardinal('9th'), 9, '9th')
  t.equal(cardinal('10th'), 10, '10th')
  t.equal(cardinal('20th'), 20, '20th')
  t.equal(cardinal('30th'), 30, '30th')
  t.equal(cardinal('50th'), 50, '50th')
  t.equal(cardinal('77th'), 77, '77th')
  t.equal(cardinal('90th'), 90, '90th')
  t.equal(cardinal('100th'), 100, '100th')
  t.end()
})
test('parse english names of numbers', function (t) {
  t.equal(cardinal('zero'), 0, 'zero')
  t.equal(cardinal('one'), 1, 'one')
  t.equal(cardinal('two'), 2, 'two')
  t.equal(cardinal('three'), 3, 'three')
  t.equal(cardinal('four'), 4, 'four')
  t.equal(cardinal('five'), 5, 'five')
  t.equal(cardinal('six'), 6, 'six')
  t.equal(cardinal('seven'), 7, 'seven')
  t.equal(cardinal('eight'), 8, 'eight')
  t.equal(cardinal('nine'), 9, 'nine')
  t.equal(cardinal('ten'), 10, 'ten')
  t.equal(cardinal('eleven'), 11, 'eleven')
  t.equal(cardinal('twelve'), 12, 'twelve')
  t.equal(cardinal('thirteen'), 13, 'thirteen')
  t.equal(cardinal('fourteen'), 14, 'fourteen')
  t.equal(cardinal('fifteen'), 15, 'fifteen')
  t.equal(cardinal('sixteen'), 16, 'sixteen')
  t.equal(cardinal('seventeen'), 17, 'seventeen')
  t.equal(cardinal('eighteen'), 18, 'eighteen')
  t.equal(cardinal('nineteen'), 19, 'nineteen')
  t.equal(cardinal('twenty'), 20, 'twenty')
  t.equal(cardinal('twenty-five'), 25, 'twenty')
  t.equal(cardinal('twenty five'), 25, 'twenty')
  t.equal(cardinal('forty-four'), 44, 'forty')
  t.equal(cardinal('forty four'), 44, 'forty')
  t.equal(cardinal('fourty four'), 44, 'fourty') //typo
  t.equal(cardinal('seventy'), 70, 'seventy')
  t.equal(cardinal('seventy-seven'), 77, 'seventy')
  t.equal(cardinal('eighty eight'), 88, 'eighty')
  t.equal(cardinal('ninety nine'), 99, 'ninety')
  t.equal(cardinal('one-hundred'), 100, 'one-hundred')
  t.equal(cardinal('one hundred'), 100, 'one hundred')
  t.end()
})
test('parse english names of ordinal positions', function (t) {
  t.equal(cardinal('zeroth'), 0, 'zeroth')
  t.equal(cardinal('first'), 1, 'first')
  t.equal(cardinal('second'), 2, 'second')
  t.equal(cardinal('third'), 3, 'third')
  t.equal(cardinal('fourth'), 4, 'fourth')
  t.equal(cardinal('fifth'), 5, 'fifth')
  t.equal(cardinal('sixth'), 6, 'sixth')
  t.equal(cardinal('seventh'), 7, 'seventh')
  t.equal(cardinal('eighth'), 8, 'eighth')
  t.equal(cardinal('ninth'), 9, 'ninth')
  t.equal(cardinal('tenth'), 10, 'tenth')
  t.equal(cardinal('eleventh'), 11, 'eleventh')
  t.equal(cardinal('twelfth'), 12, 'twelfth')
  t.equal(cardinal('thirteenth'), 13, 'thirteenth')
  t.equal(cardinal('fourteenth'), 14, 'fourteenth')
  t.equal(cardinal('fifteenth'), 15, 'fifteenth')
  t.equal(cardinal('sixteenth'), 16, 'sixteenth')
  t.equal(cardinal('seventeenth'), 17, 'seventeenth')
  t.equal(cardinal('eighteenth'), 18, 'eighteenth')
  t.equal(cardinal('nineteenth'), 19, 'nineteenth')
  t.equal(cardinal('twentieth'), 20, 'twentieth')
  t.equal(cardinal('twenty first'), 21, 'twenty first')
  t.equal(cardinal('twenty second'), 22, 'twenty second')
  t.equal(cardinal('twenty third'), 23, 'twenty third')
  t.equal(cardinal('twenty fourth'), 24, 'twenty fourth')
  t.equal(cardinal('twenty-fifth'), 25, 'twenty fifth')
  t.equal(cardinal('forty-fourth'), 44, 'forty-fourth')
  t.equal(cardinal('seventieth'), 70, 'seventieth')
  t.equal(cardinal('seventy-seventh'), 77, 'seventy')
  t.equal(cardinal('ninetieth'), 90, 'ninetieth')
  t.equal(cardinal('ninety ninth'), 99, 'ninety')
  t.equal(cardinal('one-hundredth'), 100, 'one-hundredth')
  t.end()
})

test('parse negative numbers', function (t) {
  t.equal(cardinal('negative thirty eight thousand two hundred sixty three'), -38263, '-38263')
  t.equal(cardinal('negative thirty eight thousand two hundred sixty three'), -38263, '-38263')
  t.equal(cardinal('negative zero'), -0, '-0')
  t.end()
})
