// from university of Illinois`],
// http://cogcomp.cs.illinois.edu/Data/QA/QC/
module.exports = [
  ['How can I find a list of celebrities\' real names?', 'how'],
  ['How can I find a phone number of someone if I only know their email address?',
    'how'],
  ['How can I find online spelling, and punctuation drills for my 6th grader?',
    'how'],
  ['How can I find out what year a Beanie Baby was introduced?',
    'how'],
  ['How can I find out which cities have cable-modem access?',
    'how'],
  ['How can I get some free technical information on Electric Vehicle?',
    'how'],
  ['How can I register my website in Yahoo for free?', 'how'],
  ['How can I transport files from one computer to another?',
    'how'],
  ['How can you contact play producers and promoters on-line?',
    'how'],
  ['How can your school march in the Macy\'s Thanksgiving Parade?',
    'how'],
  ['How did Jayne Mansfield die?', 'how'],
  ['How did serfdom develop in and then leave Russia?', 'how'],
  ['How did shipyard inspector James J. Kilroy designate equipment as being satisfactory?',
    'how'],
  ['How did the tradition of best man start?', 'how'],
  ['How do chickens have baby chicks?', 'how'],
  ['How do doctors diagnose bone cancer?', 'how'],
  ['How do fuel injectors work?', 'how'],
  ['How do I find the balance of my social security account?',
    'how'],
  ['How do I get another city\'s newspaper?', 'how'],
  ['How do I log on to home page at Headquarters U.S. European Command?',
    'how'],
  ['How do I make fuel bricks from recycled newspaper?', 'how'],
  ['How do I start a bank?', 'how'],
  ['How do I start a web based business?', 'how'],
  ['How do I stop background noise in a car stereo?', 'how'],
  ['How do I tie dye clothes?', 'how'],
  ['How do Ouija Boards work?', 'how'],
  ['How do they find or choose witnesses to an execution?',
    'how'],
  ['How do you ask a total stranger out on a date?', 'how'],
  ['How do you correctly say the word \'qigong\'?', 'how'],
  ['How do you determine heating requirements for your home?',
    'how'],
  ['How do you find oxidation numbers?', 'how'],
  ['How do you get a broken cork out of a bottle?', 'how'],
  ['How do you get to the top of the Eiffel Tower?', 'how'],
  ['How do you look up criminal records on the Internet?',
    'how'],
  ['How do you make a paintball?', 'how'],
  ['How do you match a name to a social security number?',
    'how'],
  ['How do you say "fresh" in Spanish?', 'how'],
  ['How do you say 2 in Latin?', 'how'],
  ['How do you say I love you in Spanish?', 'how'],
  ['How do you solve "Rubik\'s Cube"?', 'how'],
  ['How does a copier work?', 'how'],
  ['How does a rainbow form?', 'how'],
  ['How is a hydrogen bomb different from a nuclear bomb?',
    'how'],
  ['How is Answers.com different from KnowPost.com?', 'how'],
  ['How is Easter Sunday\'s date determined?', 'how'],
  ['How is energy created?', 'how'],
  ['How is it correct to say \'qigong\'?', 'how'],
  ['How is silk screening done?', 'how'],
  ['How is the election of a new Pope announced to the world?',
    'how'],
  ['How successful is arometherapy?', 'how'],
  ['How was the element calcium named?', 'how'],
  ['How you can raise your IQ?', 'how'],
  ['The italian artist, Maurizio Pellegrin, is how old?', 'how'],
  ['How far can a man travel in outer space?', 'number'],
  ['How far do you have to run if you hit a home run?',
    'number'],
  ['How fast does the fastest car go?', 'number'],
  ['How fast is light?', 'number'],
  ['How long does it take for Spider-Man\'s web to evaporate?',
    'number'],
  ['How long does it take for your blood to make one complete trip through the body?',
    'number'],
  ['How long is the Coney Island boardwalk?', 'number'],
  ['How long should a person wash their hands before they are clean?',
    'number'],
  ['How many Americans fought for the British in the American Revolution?',
    'number'],
  ['How many astronauts manned each Project Mercury flight?',
    'number'],
  ['How many Beatles\' records went #1?', 'number'],
  ['How many bends are there in a standard paper clip?',
    'number'],
  ['How many boys play the game in Winslow Homer\'s 1872 painting Snap the Whip?',
    'number'],
  ['How many calories are there in a Big Mac?', 'number'],
  ['How many casinos are in Atlantic City, NJ?', 'number'],
  ['How many CDs has Garth Brooks sold?', 'number'],
  ['How many colleges are in Wyoming?', 'number'],
  ['How many colonies were involved in the American Revolution?',
    'number'],
  ['How many Community Chest cards are there in Monopoly?',
    'number'],
  ['How many degrees cooler is the inside of a cucumber than the air outside?',
    'number'],
  ['How many degrees cooler is the inside of a cucumber than the air outside?',
    'number'],
  ['How many dots make up the symbol for "because"?', 'number'],
  ['How many double-word-score spaces are there on a Scrabble Crossword Game board?',
    'number'],
  ['How many equal angles are there in an isosceles triangle?',
    'number'],
  ['How many feet are there in a fathom?', 'number'],
  ['How many fingers are used to draw a bow?', 'number'],
  ['How many Gutenberg Bibles are there?', 'number'],
  ['How many hands does Bjorn Borg use when hitting his forehand?',
    'number'],
  ['How many hearts does an octopus have?', 'number'],
  ['How many holes are there in a tenpin bowling ball?',
    'number'],
  ['How many home runs did Lou Gehrig have during his career?',
    'number'],
  ['How many hostages were killed in the Entebbe raid?',
    'number'],
  ['How many inches over six feet is the Venus de Milo?',
    'number'],
  ['How many innings are there in a regulation softball game?',
    'number'],
  ['How many Jews were executed in concentration camps during WWII?',
    'number'],
  ['How many layers of yellow paint is a Faber Mongol pencil lucky enough to be sprayed with?',
    'number'],
  ['How many miles is it to Ohio from North Carolina?',
    'number'],
  ['How many months does a normal human pregnancy last?',
    'number'],
  ['How many months does it take the moon to revolve around the Earth?',
    'number'],
  ['How many oceans are there and name them?', 'number'],
  ['How many pairs of legs does a lobster have?', 'number'],
  ['How many people are there in the world?', 'number'],
  ['How many people did Randy Craft kill?', 'number'],
  ['How many people died on D-Day?', 'number'],
  ['How many people in the world speak French?', 'number'],
  ['How many people on the ground were killed from the bombing of Pan Am Flight 103 over Lockerbie, Scotland, December 21, CD .',
    'number'],
  ['How many points make up a perfect fivepin bowling score?',
    'number'],
  ['How many quarters equal a pound?', 'number'],
  ['How many referees work a soccer game?', 'number'],
  ['How many revolutions does a standard LP make in three minutes?',
    'number'],
  ['How many shots can a stock M16 hold?', 'number'],
  ['How many sonnets did Shakespeare write?', 'number'],
  ['How many South American countries have the letter Z in their names?',
    'number'],
  ['How many species of sharks are there?', 'number'],
  ['How many species of the Great White shark are there?',
    'number'],
  ['How many sperm cells are in an average ejaculation?',
    'number'],
  ['How many students attend the University of Massachusetts?',
    'number'],
  ['How many times has "Louie, Louie" been recorded?', 'number'],
  ['How many types of dogs\' tails are there - three', 'number'],
  ['How many Vietnamese were there in the Soviet Union?',
    'number'],
  ['How many villi are found in the small intestine?', 'number'],
  ['How many wives did Brigham Young have?', 'number'],
  ['How many years ago did the ship Titanic sink?', 'number'],
  ['How many years did it take James Joyce to write Ulysses?',
    'number'],
  ['How many years do fossils take to form?', 'number'],
  ['How many years is Johnnie Walker Black Label aged?',
    'number'],
  ['How much does a new railroad coal car cost?', 'number'],
  ['How much money are Dumbo\'s ears insured for?', 'number'],
  ['How much money does a back injury lawsuit get?', 'number'],
  ['How much snow equals an inch of rain?', 'number'],
  ['How much was the minimum wage in 1991?', 'number'],
  ['How much would a black-and-white 1-cent stamp be worth, Thomas Jefferson on it,?',
    'number'],
  ['How much would it cost to purchase a 2-foot-square party tent, with sides,?',
    'number'],
  ['In what year did Ireland elect its first woman president?',
    'number'],
  ['In what year did Thatcher become prime minister?', 'number'],
  ['In what year was De Gaulle elected president of France?',
    'number'],
  ['In which year was New Zealand excluded from the ANZUS alliance?',
    'number'],
  ['On average, how many miles are there to the moon?',
    'number'],
  ['What year did Germany sign its nonaggression pact with the Soviet Union?',
    'number'],
  ['What year did Hitler die?', 'number'],
  ['What year did Jack Nicklaus join the Professional Golfers Association tour?',
    'number'],
  ['What year did the United States pass the Copyright law?',
    'number'],
  ['What year did the Vietnam War end?', 'number'],
  ['CNN is the abbreviation for what?', 'what'],
  ['What\'s an auberge in France?', 'what'],
  ['What\'s approaching when a cyclist shouts', 'what'],
  ['What\'s nature\'s purpose for tornadoes?', 'what'],
  ['What\'s the American dollar equivalent for 8 pounds in the U.K.?',
    'what'],
  ['What\'s the closest G2 Spectrum Yellow Dwarf to Earth?',
    'what'],
  ['What\'s the colored part of the eye called?', 'what'],
  ['What\'s the common name for acetylsalicylic acid?', 'what'],
  ['What\'s the first day of the week?', 'what'],
  ['What\'s the literary term for a play on words?', 'what'],
  ['What\'s the longest river in the world?', 'what'],
  ['What\'s the meaning of the Latin battle cry', 'what'],
  ['What\'s the most commonly-spoken language in Belgium?',
    'what'],
  ['What\'s the most powerful card in Euchre?', 'what'],
  ['What\'s the name of a golf course in Myrtle Beach?', 'what'],
  ['What\'s the name of the temple that is located near the capital city of Laos?',
    'what'],
  ['What\'s the nickname of oddsmaker Jimmy Snyder?', 'what'],
  ['What\'s the official animal of Canada?', 'what'],
  ['What\'s the Olympic motto?', 'what'],
  ['What\'s the only color Johnny Cash wears on stage?', 'what'],
  ['What\'s the only work by Michelangelo that bears his signature?',
    'what'],
  ['What\'s the origin of the word \'news\'?', 'what'],
  ['What\'s the sacred river of India?', 'what'],
  ['What\'s the second-largest island in the world?', 'what'],
  ['What\'s the second-most-used vowel in English?', 'what'],
  ['What\'s the slowest Olympic swimming stroke?', 'what'],
  ['What\'s the tallest building in New York City?', 'what'],
  ['What\'s the tallest piece on a chessboard?', 'what'],
  ['What\'s the term for a bet before cards are dealt?', 'what'],
  ['What\'s the term for a young fox?', 'what'],
  ['What\'s the word for broken glass or sharp rocks embedded in cement on top of a wall?',
    'what'],
  ['What "magic" does Mandrake employ?', 'what'],
  ['What 1920s cowboy star rode Tony the Wonder Horse?', 'what'],
  ['What 1966 boob tube bomb took astronauts back to prehistoric times?',
    'what'],
  ['What 19th-century painter died in the Marquesas Islands?',
    'what'],
  ['What 19th-century writer had a country estate on the Hudson dubbed Sunnyside?',
    'what'],
  ['What 2 statues did France give to other countries?', 'what'],
  ['What actor\'s autobiography is titled All My Yesterdays?',
    'what'],
  ['What actor first portrayed James Bond?', 'what'],
  ['What actor married John F. Kennedy\'s sister?', 'what'],
  ['What actor said in A Day at the Races', 'what'],
  ['What actor starred in 1980\'s Blue Lagoon, 1982\'s The Pirate Movie and 1983\'s A Night in Heaven?',
    'what'],
  ['What actress has received the most Oscar nominations?',
    'what'],
  ['What age followed the Bronze Age?', 'what'],
  ['What album put The Beatles on the cover of Time in 1967?',
    'what'],
  ['What American League baseball team\'s worst finish between 1926 and 1964 was fourth?',
    'what'],
  ['What American poet wrote', 'what'],
  ['What animal has killed the most people?', 'what'],
  ['What animal has the biggest eyes?', 'what'],
  ['What animals do you find in the stock market?', 'what'],
  ['What arch can you see from the Place de la Concorde?',
    'what'],
  ['What are amphibians?', 'what'],
  ['What are bear and bull markets?', 'what'],
  ['What are Cushman and Wakefield known for?', 'what'],
  ['What are equity securities?', 'what'],
  ['What are Halloween\'s colors?', 'what'],
  ['What are hook worms?', 'what'],
  ['What are liver enzymes?', 'what'],
  ['What are Maid-Rites?', 'what'],
  ['What are other ways of getting stretch marks besides pregnancy, weight loss, and weight lifting?',
    'what'],
  ['What are shooting stars?', 'what'],
  ['What are some interesting facts and information about dogsledding?',
    'what'],
  ['What are some of the significant historical events of the 1990s?',
    'what'],
  ['What are some tips for building a fire in a fireplace?',
    'what'],
  ['What are the 7 articles of the constitution?', 'what'],
  ['What are the Benelux countries?', 'what'],
  ['What are the chemicals used in glowsticks?', 'what'],
  ['What are the developmental stages of a swimmer?', 'what'],
  ['What are the different approaches of systems analysis?',
    'what'],
  ['What are the different types of plastic?', 'what'],
  ['What are the distinct physical characterstics of the Arabian horse?',
    'what'],
  ['What are the first names of Rowan and Martin, the stars of TV\'s Laugh-In?',
    'what'],
  ['What are the five most expensive cities in the world?',
    'what'],
  ['What are the four elements?', 'what'],
  ['What are the Greek numerals?', 'what'],
  ['What are the living conditions in Cuba?', 'what'],
  ['What are the most common breeding birds in the U.S.?',
    'what'],
  ['What are the most common elements in the Earth\'s crust?',
    'what'],
  ['What are the names of Richard Nixon\'s two daughters?',
    'what'],
  ['What are the names of the tourist attractions in Reims?',
    'what'],
  ['What are the Nordic nations?', 'what'],
  ['What are the powers and weaknesses of Green Lantern\'s ring?',
    'what'],
  ['What are the rites accompanying the circumcision of a newly born-child in Judaism called?',
    'what'],
  ['What are the seven virtues?', 'what'],
  ['What are the shortest and the longest songs ever produced?',
    'what'],
  ['What are the three winter months in the southern hemisphere?',
    'what'],
  ['What are the top ten most common girl names in the US?',
    'what'],
  ['What are the two languages of Malta?', 'what'],
  ['What are the world\'s four oceans?', 'what'],
  ['What are two plants that clothes are made from?', 'what'],
  ['What army was founded by William Booth and his wife Catherine?',
    'what'],
  ['What articles of clothing are tokens in Monopoly?', 'what'],
  ['What Asian country has a bill of rights for cows?', 'what'],
  ['What Asian leader was known as The Little Brown Saint?',
    'what'],
  ['What astronomical phenomenon takes place in Jan. 1999?',
    'what'],
  ['What athlete makes the most money from sports merchandise sales?',
    'what'],
  ['What attracts tourists to Reims?', 'what'],
  ['What author did photographer Yousuf Karsh call "the shiest man I ever met"?',
    'what'],
  ['What author landed a 468-pound marlin without harness in the early 193\'s?',
    'what'],
  ['What auto race was Wilbur Reed the first to win three times?',
    'what'],
  ['What barroom judge called himself The Law West of the Pecos?',
    'what'],
  ['What baseball star turned down a $1, 000-a-year contract because he felt he had n\'t earned it?',
    'what'],
  ['What beer advertised that it had "three rings"?', 'what'],
  ['What board game does a "wood-pusher" play poorly?', 'what'],
  ['What body of water does the Danube River flow into?',
    'what'],
  ['What Boris Pasternak book sold 5, 0 copies to become the fiction best-seller of 1958?',
    'what'],
  ['What breed of dog was the "Little Rascals" dog?', 'what'],
  ['What Broadway musical was inspired by Cervantes\'s Don Quixote?',
    'what'],
  ['What can I use to remove the stubborn gummed labels from some diskettes?',
    'what'],
  ['What card game has variations called Canfield, Klondike and Spider?',
    'what'],
  ['What caused Harry Houdini\'s death?', 'what'],
  ['What caused the Lynmouth floods?', 'what'],
  ['What causes pneumonia?', 'what'],
  ['What causes the body to shiver in cold temperatures?',
    'what'],
  ['What causes the redness in your cheeks when you blush?',
    'what'],
  ['What CBS soap opera was interrupted by the bulletin of John F. Kennedy\'s assassination?',
    'what'],
  ['What century does Captain Video live in?', 'what'],
  ['What chapter of the Bible has the most verses?', 'what'],
  ['What chemicals are used in lethal injection?', 'what'],
  ['What children\'s tale contains the line\'come hither\'?',
    'what'],
  ['What city boasts Penn\'s Landing, on the banks of the Delaware river?',
    'what'],
  ['What city did the Flintstones live in?', 'what'],
  ['What city gained renown for its pea-soup fogs?', 'what'],
  ['What city has the world\'s longest subway system?', 'what'],
  ['What city houses the U.S. headquarters of Procter and Gamble?',
    'what'],
  ['What city is Logan Airport in?', 'what'],
  ['What city is served by Logan International Airport?',
    'what'],
  ['What city is sometimes called Gotham?', 'what'],
  ['What city is the setting for Puccini\'s opera La Boheme?',
    'what'],
  ['What city was President William McKinley shot in?', 'what'],
  ['What classical Spanish writer warned "All that glitters is not gold"?',
    'what'],
  ['What cocktail do you concoct with whisky and sweet vermouth?',
    'what'],
  ['What cocktail inspired John Doxat to write the book Stirred-Not Shaken?',
    'what'],
  ['What college produced the most winning Super Bowl quarterbacks?',
    'what'],
  ['What color are school buses?', 'what'],
  ['What color are tennis balls?', 'what'],
  ['What color bottles do good Rhine wines come in?', 'what'],
  ['What color of dry wine should be served with veal roasts and chops?',
    'what'],
  ['What color were their horses?', 'what'],
  ['What company\'s logo is a "W" in a circle?', 'what'],
  ['What company is being bought by Yahoo and how much is the deal worth?',
    'what'],
  ['What company tabulates the ballots in voting for the Academy Awards?',
    'what'],
  ['What contemptible scoundrel stole the cork from my lunch?',
    'what'],
  ['What countries have the largest areas of forest?', 'what'],
  ['What country\'s capital is Tirana?', 'what'],
  ['What country\'s national passenger rail system is called Via?',
    'what'],
  ['What country\'s people are the top television watchers?',
    'what'],
  ['What country are Godiva chocolates from?', 'what'],
  ['What country contains Africa\'s northernmost point?',
    'what'],
  ['What country did King Gustav V reign over from 197 to 195?',
    'what'],
  ['What country did King Wenceslas rule?', 'what'],
  ['What country did the Nazis occupy for 1, CD NNS IN NNP NNP NNP .',
    'what'],
  ['What country did the Nile River originate in?', 'what'],
  ['What country do the Galapagos Islands belong to?', 'what'],
  ['What country has the best defensive position in the board game Diplomacy?',
    'what'],
  ['What country has the largest sheep population?', 'what'],
  ['What country has the most time zones, with 11?', 'what'],
  ['What country is the world\'s largest importer of cognac?',
    'what'],
  ['What county is Chicago in?', 'what'],
  ['What creature scares people in the film "Jaws"?', 'what'],
  ['What crooner joined The Andrews Sisters for Pistol Packin Mama?',
    'what'],
  ['What crop failure caused the Irish Famine?', 'what'],
  ['What dangles over the tongue from the palate?', 'what'],
  ['What day of the week sees the most fatal car accidents?',
    'what'],
  ['What day was Pearl Harbor attacked in 1942?', 'what'],
  ['What deck of cards includes the Wheel of Fortune, the Lovers, and Death?',
    'what'],
  ['What desert has been called The Garden of Allah?', 'what'],
  ['What dictator has the nickname "El Maximo"?', 'what'],
  ['What did brontosauruses eat?', 'what'],
  ['What did Dan Aykroyd and John Belushi quit Saturday Night Live to become?',
    'what'],
  ['What did Delilah do to Samson\'s hair?', 'what'],
  ['What did Richard Feynman say upon hearing he would receive the Nobel Prize in Physics?',
    'what'],
  ['What did Shostakovich write for Rostropovich?', 'what'],
  ['What did the only repealed amendment to the U.S. Constitution deal with?',
    'what'],
  ['What diminutive American female gymnast stole the show at the 1984 Olympics?',
    'what'],
  ['What disease is transmitted by the Anopheles mosquito?',
    'what'],
  ['What do bee hives do in cranberry bogs?', 'what'],
  ['What do bicornate animals have two of?', 'what'],
  ['What do economists do?', 'what'],
  ['What do flatfish eat?', 'what'],
  ['What do I need to do to take my dog with me to live in Dominica, West Indies for a year?',
    'what'],
  ['What do Italians call Florence?', 'what'],
  ['What do manatees eat?', 'what'],
  ['What do Mormons believe?', 'what'],
  ['What do players try to do when the music stops in a game of musical chairs?',
    'what'],
  ['What do you call a group of geese?', 'what'],
  ['What do you get by adding Lactobacillus bulgaricus to milk?',
    'what'],
  ['What does \'PSI\' stand for?', 'what'],
  ['What does "antidisestablishmentarianism" mean?', 'what'],
  ['What does "extended definition" mean and how would one write a paper on it?',
    'what'],
  ['What does "intractable plantar keratoma" mean?', 'what'],
  ['What does "Janelle" mean?', 'what'],
  ['What does a chairbound basophobic fear?', 'what'],
  ['What does a nihilist believe in?', 'what'],
  ['What does a spermologer collect?', 'what'],
  ['What does a topophobic actor suffer from?', 'what'],
  ['What does an average daycare provider get paid in New England?',
    'what'],
  ['What does an average daycare provider get paid in New England?',
    'what'],
  ['What does G.M.T. stand for?', 'what'],
  ['What does God create in the first sentence of the Bible?',
    'what'],
  ['What does gringo mean?', 'what'],
  ['What does INRI stand for when used on Jesus\' cross?',
    'what'],
  ['What does Inuit and Eskimo mean?', 'what'],
  ['What does it mean "Rupee Depreciates"?', 'what'],
  ['What does NAFTA stand for?', 'what'],
  ['What does NASDAQ stand for?', 'what'],
  ['What does NN O "mean when used as a prefix in Irish surnames?',
    'what'],
  ['What does ribavirin consist of?', 'what'],
  ['What does S.O.S. stand for?', 'what'],
  ['What does SIDS stand for?', 'what'],
  ['What does the abbreviation AIDS stand for?', 'what'],
  ['What does the Georgetown "Hoya" mean?', 'what'],
  ['What does the Latin ante mortem mean?', 'what'],
  ['What does the name "Anthony" mean?', 'what'],
  ['What does the name "Justin" mean?', 'what'],
  ['What does the name Billie mean?', 'what'],
  ['What does the name Gina mean?', 'what'],
  ['What does the name Shawn mean?', 'what'],
  ['What does the six-footed Musca domestica become when it enters a house?',
    'what'],
  ['What does the Statue of Liberty wear on her feet?', 'what'],
  ['What does the word camaro mean, from the GM car the Camaro?',
    'what'],
  ['What does the word LASER mean?', 'what'],
  ['What double talking "professor" holds a doctorate in Nothing?',
    'what'],
  ['What dummy received an honorary degree from Northwestern University?',
    'what'],
  ['What English word comes from the Old French covrefeu, meaning cover fire?',
    'what'],
  ['What European city do Nicois live in?', 'what'],
  ['What European country is home to the beer-producing city of Budweis?',
    'what'],
  ['What events happened January 26, 1978?', 'what'],
  ['What excuse did the NATO people give for hitting the Chinese embassy?',
    'what'],
  ['What explorer was nicknamed Iberia\'s Pilot?', 'what'],
  ['What explorers followed Columbus to the Americas?', 'what'],
  ['What facial feature typically contains about 55 hairs?',
    'what'],
  ['What famous model was married to Billy Joel?', 'what'],
  ['What fastener did Whitcomb Judson patent in 1893?', 'what'],
  ['What fictional character is known as the "melancholy Dane"?',
    'what'],
  ['What field sport did dentist William Beers promote and write a standard book of rules for?',
    'what'],
  ['What film did Lee Marvin win the 1965 best actor Oscar for?',
    'what'],
  ['What film marked Robert Redford\'s directorial debut?',
    'what'],
  ['What film or films has Jude Law appeared in?', 'what'],
  ['What films featured the character Popeye Doyle?', 'what'],
  ['What first name was Nipsy Russell given at birth?', 'what'],
  ['What former major-league left-handed baseball pitcher was known as "Space Man"?',
    'what'],
  ['What former president\'s daughter has written a book titled Murder in the White House?',
    'what'],
  ['What four forms does gold occur in?', 'what'],
  ['What fowl grabs the spotlight after the Chinese Year of the Monkey?',
    'what'],
  ['What fraction of a beaver\'s life is spent swimming?',
    'what'],
  ['What function does a community\'s water tower serve?',
    'what'],
  ['What game\'s board shows the territories of Irkutsk, Yakutsk and Kamchatka?',
    'what'],
  ['What game do Steve McQueen and Edward G. Robinson play in The Cincinnati Kid?',
    'what'],
  ['What gaming devices were dubbed "Mississippi marbles" and "Memphis dominoes"?',
    'what'],
  ['What girl\'s name is "Teddy" an affectionate form of?',
    'what'],
  ['What golfer has been called Ohio Fats and Blobbo?', 'what'],
  ['What golfing accessory was patented by George Grant on December 12',
    'what'],
  ['What happened during the Blackhawk Indian war of 1832?',
    'what'],
  ['What historical event happened in Dogtown in 1899?', 'what'],
  ['What holidays are celebrated in Ireland?', 'what'],
  ['What Hollywood dog died in the arms of Jean Harlow in 1932?',
    'what'],
  ['What horse did Zorro ride?', 'what'],
  ['What household facility contains a float ball, ballcock, and overflow tube?',
    'what'],
  ['What Indian tribe is F Troop perpetually doing battle with?',
    'what'],
  ['What infectious disease is the world\'s deadliest?', 'what'],
  ['What information can you get me on Fairground Park in St. Louis',
    'what'],
  ['What instrument is Ray Charles best known for playing?',
    'what'],
  ['What is "dew point"?', 'what'],
  ['What is "Nine Inch Nails"?', 'what'],
  ['What is "snoogans"?', 'what'],
  ['What is "the bear of beers"?', 'what'],
  ['What is a ball that hits the foul pole called?', 'what'],
  ['What is a caldera?', 'what'],
  ['What is a Canada two-penny black?', 'what'],
  ['What is a Certified Nurse Midwife?', 'what'],
  ['What is a dental root canal?', 'what'],
  ['What is a fear of bees?', 'what'],
  ['What is a fear of being alone?', 'what'],
  ['What is a fear of food?', 'what'],
  ['What is a fear of parasites?', 'what'],
  ['What is a fear of passing high objects?', 'what'],
  ['What is a fear of shadows?', 'what'],
  ['What is a fear of sleep?', 'what'],
  ['What is a fear of thunder?', 'what'],
  ['What is a fear of weakness?', 'what'],
  ['What is a female rabbit called?', 'what'],
  ['What is a film starring Jude Law?', 'what'],
  ['What is a firewall?', 'what'],
  ['What is a golf ball made of?', 'what'],
  ['What is a green bog?', 'what'],
  ['What is a Jellicle Cat?', 'what'],
  ['What is a language spoken by the Sioux?', 'what'],
  ['What is a nanometer?', 'what'],
  ['What is a rhomboideus minor?', 'what'],
  ['What is a transistor?', 'what'],
  ['What is a virtual IP address?', 'what'],
  ['What is a wop?', 'what'],
  ['What is an annotated bibliography?', 'what'],
  ['What is an example of an actual case of using the Fourteenth Amendment?',
    'what'],
  ['What is an isthmus?', 'what'],
  ['What is Answers.com\'s address?', 'what'],
  ['What is artificial intelligence?', 'what'],
  ['What is Australia Day?', 'what'],
  ['What is being done about the millennium bug?', 'what'],
  ['What is Betsy Ross famous for?', 'what'],
  ['What is Bill Gates of Microsoft E-mail address?', 'what'],
  ['What is Black Hills, South Dakota most famous for?', 'what'],
  ['What is Bombay duck?', 'what'],
  ['What is BPH?', 'what'],
  ['What is California\'s capital?', 'what'],
  ['What is Colin Powell best known for?', 'what'],
  ['What is color?', 'what'],
  ['What is considered the costliest disaster the insurance industry has ever faced?',
    'what'],
  ['What is D.B. Cooper known for?', 'what'],
  ['What is dry ice?', 'what'],
  ['What is Dudley Do-Right\'s horse\'s name?', 'what'],
  ['What is Eagle\'s syndrome styloid process?', 'what'],
  ['What is ethology?', 'what'],
  ['What is Grenada\'s main commodity export?', 'what'],
  ['What is gymnophobia?', 'what'],
  ['What is her profession?', 'what'],
  ['What is Jane Goodall known for?', 'what'],
  ['What is Latin for incompetent?', 'what'],
  ['What is measured in curies?', 'what'],
  ['What is Mississippi\'s state animal?', 'what'],
  ['What is molybdenum?', 'what'],
  ['What is Nebraska\'s most valuable resource?', 'what'],
  ['What is November\'s birthstone?', 'what'],
  ['What is Olestra?', 'what'],
  ['What is paracetamol?', 'what'],
  ['What is prepared mustard?', 'what'],
  ['What is Spumante?', 'what'],
  ['What is Stefan Edberg\'s native country?', 'what'],
  ['What is the "7-minute cigarette"?', 'what'],
  ['What is the "coppertop" battery?', 'what'],
  ['What is the 401, K, plan?', 'what'],
  ['What is the abbreviated expression for the National Bureau of Investigation?',
    'what'],
  ['What is the abbreviation for micro?', 'what'],
  ['What is the abbreviation of the company name \'General Motors\'?',
    'what'],
  ['What is the acreage of the Chappellet vineyard?', 'what'],
  ['What is the AIM-54C Phoenix?', 'what'],
  ['What is the Amish religion?', 'what'],
  ['What is the average cost for four years of medical school?',
    'what'],
  ['What is the belt of low pressure around the equator called?',
    'what'],
  ['What is the best college in the country?', 'what'],
  ['What is the best way to remove wallpaper?', 'what'],
  ['What is the brightest star visible from Earth?', 'what'],
  ['What is the busiest air travel season?', 'what'],
  ['What is the chromosome number of an elephant?', 'what'],
  ['What is the city in which Maurizio Pellegrin lives called?',
    'what'],
  ['What is the classic definition of tragic hero?', 'what'],
  ['What is the contents of proposition 98?', 'what'],
  ['What is the current ticket fare from from Cairo to Barbados?',
    'what'],
  ['What is the daily requirement of folic acid for an expectant mother?',
    'what'],
  ['What is the date of Boxing Day?', 'what'],
  ['What is the deepest area of the Arctic Ocean?', 'what'],
  ['What is the definition of a cascade?', 'what'],
  ['What is the definition of low island?', 'what'],
  ['What is the design of the ship Titanic?', 'what'],
  ['What is the dialogue circle in cartoons called?', 'what'],
  ['What is the difference between a generator and an alternator?',
    'what'],
  ['What is the difference between a median and a mean?',
    'what'],
  ['What is the difference between classical conditioning and operant conditioning?',
    'what'],
  ['What is the difference between Neoclassical art and Romanticism art?',
    'what'],
  ['What is the fastest commercial automobile that can be bought in the US?',
    'what'],
  ['What is the fear of being loved?', 'what'],
  ['What is the fear of cockroaches called?', 'what'],
  ['What is the filmmakers collabrative?', 'what'],
  ['What is the full form of .com?', 'what'],
  ['What is the full name of the man who invented the multicolored game cube that has 42.3 quintillion potential combinations?',
    'what'],
  ['What is the full name of the PLO?', 'what'],
  ['What is the function of RAM?', 'what'],
  ['What is the highest mountain in the world?', 'what'],
  ['What is the highest peak in Africa?', 'what'],
  ['What is the highest waterfall in the United States?',
    'what'],
  ['What is the historical relationship of Catholic Church and bingo?',
    'what'],
  ['What is the history of skateboarding?', 'what'],
  ['What is the history of Valentine\'s Day cards?', 'what'],
  ['What is the Jewish bible called?', 'what'],
  ['What is the Kashmir issue?', 'what'],
  ['What is the largest city on the Great Lakes?', 'what'],
  ['What is the largest snake in the world?', 'what'],
  ['What is the latitude and longitude of El Paso, Texas?',
    'what'],
  ['What is the leading pecan and peanut growing state?',
    'what'],
  ['What is the longest English word?', 'what'],
  ['What is the longest place name in the U.S.?', 'what'],
  ['What is the longest word in the English language?', 'what'],
  ['What is the longest-running television series?', 'what'],
  ['What is the lowest level of the American judiciary?',
    'what'],
  ['What is the mascot for Notre Dame University?', 'what'],
  ['What is the meaning of Jesus?', 'what'],
  ['What is the meaning of W.B. Yeat\'s poem, "The Three Hermits?"',
    'what'],
  ['What is the most advanced handheld calculator in the world?',
    'what'],
  ['What is the most common kind of skin cancer in the U.S.?',
    'what'],
  ['What is the most heavily caffeinated soft drink?', 'what'],
  ['What is the Motto for the State of Maryland?', 'what'],
  ['What is the name of the chronic neurological autoimmune disease which attacks the protein sheath that surrounds nerve cells causing a gradual loss of movement in the body?',
    'what'],
  ['What is the name of the city that Maurizio Pellegrin lives in?',
    'what'],
  ['What is the name of the managing director of Apricot Computer?',
    'what'],
  ['What is the name of the tallest mountain in the world?',
    'what'],
  ['What is the nature of learning?', 'what'],
  ['What is the nickname for the state of Mississippi?', 'what'],
  ['What is the normal resting heart rate of a healthy adult?',
    'what'],
  ['What is the occupation of Nicholas Cage?', 'what'],
  ['What is the oldest profession?', 'what'],
  ['What is the oldest website on the Internet?', 'what'],
  ['What is the only gland in humans that can regenerate itself?',
    'what'],
  ['What is the origin and the meaning of the name, "Hajo?"',
    'what'],
  ['What is the origin of head lice?', 'what'],
  ['What is the origin of the expression "tout de suite"?',
    'what'],
  ['What is the origin of the name \'Scarlett\'?', 'what'],
  ['What is the origin of the name Katie?', 'what'],
  ['What is the origin of the surname of Braun?', 'what'],
  ['What is the origin of the word, JJ .', 'what'],
  ['What is the origin of the word, magic?', 'what'],
  ['What is the origin of the word "attic"?', 'what'],
  ['What is the plural of gulf?', 'what'],
  ['What is the population of Ohio?', 'what'],
  ['What is the purpose of a car bra?', 'what'],
  ['What is the quantity of American soldiers still unaccounted for from the Vietnam war?',
    'what'],
  ['What is the rarest coin?', 'what'],
  ['What is the real name of disc jockey "Wolfman Jack"?',
    'what'],
  ['What is the second hardest substance?', 'what'],
  ['What is the size of the largest akita?', 'what'],
  ['What is the smallest country in Africa?', 'what'],
  ['What is the speed of the Mississippi River?', 'what'],
  ['What is the speed of the Mississippi River?', 'what'],
  ['What is the speed of the Mississippi River?', 'what'],
  ['What is the state nickname of Mississippi?', 'what'],
  ['What is the student population at the University of Massachusetts in Amherst?',
    'what'],
  ['What is the telephone number for the University of Kentucky?',
    'what'],
  ['What is the temperature for baking Peachy Oat Muffins?',
    'what'],
  ['What is the use of a 24-hour clock instead of a 12-hour clock?',
    'what'],
  ['What is the web address of the list of e-mail addresses of members of the House of Representatives?',
    'what'],
  ['What is the wingspan of a condor?', 'what'],
  ['What is titanium?', 'what'],
  ['What is viscosity?', 'what'],
  ['What is white chocolate?', 'what'],
  ['What ISPs exist in the Caribbean?', 'what'],
  ['What Italian liner was hijacked in 1985?', 'what'],
  ['What J.R.R. Tolkien book features Bilbo Baggins as the central character?',
    'what'],
  ['What Jewish holiday saw the start of the 1973 Mideast War?',
    'what'],
  ['What Judith Rossner novel was made into a film starring Diane Keaton?',
    'what'],
  ['What killed Bob Marley?', 'what'],
  ['What kind of animal is Babar?', 'what'],
  ['What kind of animals are Dorsets, Lincolns, Oxfords and Southdowns?',
    'what'],
  ['What kind of animals were in the Paleozoic era?', 'what'],
  ['What kind of books does Fodor\'s publish?', 'what'],
  ['What kind of education do I need to become a flight attendant?',
    'what'],
  ['What kind of file has the extension .dbf?', 'what'],
  ['What kind of sport is often associated with hooligans?',
    'what'],
  ['What kind of wine is Spumante?', 'what'],
  ['What language is mostly spoken in Brazil?', 'what'],
  ['What Las Vegas hotel burned in November, 1980, with the loss of 84 lives?',
    'what'],
  ['What lawyer won the largest divorce settlement, $85 million, in U.S. history for Sheika Dena Al-Farri?',
    'what'],
  ['What letter is to the right of K on a typewriter keyboard?',
    'what'],
  ['What level of government or governmental agency is responsible for dealing with racism?',
    'what'],
  ['What longtime game show host dropped dead while jogging in Central Park in 1984?',
    'what'],
  ['What makes a clitoris sensitive?', 'what'],
  ['What makes a tornado turn?', 'what'],
  ['What makes hamburgers taste like steakburgers?', 'what'],
  ['What makes popcorn pop?', 'what'],
  ['What makes thunder?', 'what'],
  ['What mammal of North America is the world\'s longest-lived for its size?',
    'what'],
  ['What mountain range is traversed by the highest railroad in the world?',
    'what'],
  ['What mountains lie between the Arkansas and Missouri rivers?',
    'what'],
  ['What movie did Madilyn Kahn star in with Gene Wilder?',
    'what'],
  ['What movie tour of the Roman empire features the admonition',
    'what'],
  ['What musical instrument did Prewitt play in James Jones\'s From Here to Eternity?',
    'what'],
  ['What Nevada center has been dubbed The Biggest Little City in the World?',
    'what'],
  ['What new middle school was built in Philadelphia, Pennsylvania last year?',
    'what'],
  ['What novel inspired the movie BladeRunner?', 'what'],
  ['What ocean is the largest in the world?', 'what'],
  ['What organization\'s offices were broken into at Watergate in 1972?',
    'what'],
  ['What organization was founded by the Rev. Jerry Falwell?',
    'what'],
  ['What other name were the "Little Rascals" known as?',
    'what'],
  ['What part did John Peter Zenger play in the deveopment of the newspaper in America?',
    'what'],
  ['What part of your body contains the corpus callosum?',
    'what'],
  ['What party was Winston Churchill a member of?', 'what'],
  ['What percent liked Thatcher after she had been in power for a decade?',
    'what'],
  ['What percentage of Americans own their homes?', 'what'],
  ['What percentage of the body is muscle?', 'what'],
  ['What piano company claims its product is the "Instrument of the immortals"?',
    'what'],
  ['What plant has the largest seed?', 'what'],
  ['What plant is rum made from?', 'what'],
  ['What poem contains the line, "grow old with me the best is yet to be" .',
    'what'],
  ['What Polynesian people inhabit New Zealand?', 'what'],
  ['What predators exist on Antarctica?', 'what'],
  ['What President lived at 219 North Delaware Street, Independence, Missouri?',
    'what'],
  ['What President-to-be was the first member of Congress to enlist following the attack on Pearl Harbor?',
    'what'],
  ['What product did Robert Conrad dare people to knock off his shoulder?',
    'what'],
  ['What product does "Mrs. Olsen" promote?', 'what'],
  ['What product on the market is good for hiding facial scars?',
    'what'],
  ['What relative of the racoon is sometimes known as the cat-bear?',
    'what'],
  ['What rum is so "mixable" it is a one-brand bar?', 'what'],
  ['What Russian city boasts the Hermitage Museum?', 'what'],
  ['What Russian composer\'s Prelude in C Sharp Minor brought him fame and fortune?',
    'what'],
  ['What Russian master spy lived in the U.S. under the name Emil Goldfus?',
    'what'],
  ['What Russian seaport has a name meaning "Lord of the East"?',
    'what'],
  ['What schools in the Washington, DC NN NN VBP NN NN NN NN .',
    'what'],
  ['What sea did the Romans call mare nostrum?', 'what'],
  ['What shrubs can be planted that will be safe from deer?',
    'what'],
  ['What sign is The Water Carrier the zodiacal symbol for?',
    'what'],
  ['What soap was touted as being "for people who like people"?',
    'what'],
  ['What soft drink would provide me with the biggest intake of caffeine?',
    'what'],
  ['What song served as the closing theme of The Johnny Cash Show?',
    'what'],
  ['What South American city has the world\'s highest commercial landing field?',
    'what'],
  ['What South Korean city is served by Kimpo International Airport?',
    'what'],
  ['What Soviet leader owned a Rolls-Royce?', 'what'],
  ['What Spanish artist painted Crucifixion?', 'what'],
  ['What species is a colt?', 'what'],
  ['What sport do you shag flies in?', 'what'],
  ['What sport is Chris Jogis a top player of?', 'what'],
  ['What sports event is Meyer Wolfsheim supposed to have fixed in The Great Gatsby?',
    'what'],
  ['What sprawling U.S. state boasts the most airports?',
    'what'],
  ['What spy novelist served as Moscow correspondent for Reuter and The Times of London?',
    'what'],
  ['What stadium do the Miami Dolphins play their home games in?',
    'what'],
  ['What state does Martha Stewart live in?', 'what'],
  ['What state in the U.S. has the most blacks?', 'what'],
  ['What state is John F. Kennedy buried in?', 'what'],
  ['What stereo manufacturer is "Slightly ahead of its time"?',
    'what'],
  ['What sun-blasted, 14-mile wide valley is just north of the Mojave desert?',
    'what'],
  ['What team did baseball\'s St. Louis Browns become?', 'what'],
  ['What Texas city got its name from the Spanish for "yellow"?',
    'what'],
  ['What then-derogatory term was applied to the painters Monet, Sisley, Pissarro, Renoir and Degas?',
    'what'],
  ['What therapy attempts to elicit the "primal scream"?',
    'what'],
  ['What time of day did Emperor Hirohito die?', 'what'],
  ['What toy company is the world\'s No.1 maker of female apparel?',
    'what'],
  ['What TV comediennes\'s characters include former movie star Nora Desmond, secretary Mrs. Wiggins and a housewife named Eunice?',
    'what'],
  ['What TV game show once saw a contestant admit to picking his toes in the shower?',
    'what'],
  ['What TV sitcom character had the maiden name Ethel Potter?',
    'what'],
  ['What two colors are you blind to if you suffer from protanopia?',
    'what'],
  ['What two countries share the Khyber Pass?', 'what'],
  ['What two European countries entered the War of American Independence against the British?',
    'what'],
  ['What two South American countries do n\'t border Brazil?',
    'what'],
  ['What type of bridge is the Golden Gate Bridge?', 'what'],
  ['What type of food makes you fat?', 'what'],
  ['What type of hunting are retrievers used for?', 'what'],
  ['What types of water pollution are there?', 'what'],
  ['What U.S. city is The Queen of the Pacific?', 'what'],
  ['What U.S. Congressman said "Keep the faith, baby"?', 'what'],
  ['What U.S. President showed a fondness for munching on bee pollen bars?',
    'what'],
  ['What U.S. state borders Illinois to the north?', 'what'],
  ['What U.S. state has an element named for it?', 'what'],
  ['What U.S. state is Fort Knox in?', 'what'],
  ['What U.S. state lived under six flags?', 'what'],
  ['What U.S. state records the least rainfall?', 'what'],
  ['What United States President had dreamed that he was assassinated?',
    'what'],
  ['What video game hero do some of his fans call Chomper?',
    'what'],
  ['What Vladimir Nabokov novel features Professor Humbert in love with a 12-year-old girl?',
    'what'],
  ['What war did Florence Nightingale tend the troops in?',
    'what'],
  ['What war did the Wanna-Go-Home Riots occur after?', 'what'],
  ['What was American folk hero John Chapman\'s nickname?',
    'what'],
  ['What was archy, and mehitabel?', 'what'],
  ['What was cash-conscious Colonel Edwin L. Drake the first to drill?',
    'what'],
  ['What was Connecticut\'s first constitution called?', 'what'],
  ['What was Einstein\'s IQ?', 'what'],
  ['What was her real name?', 'what'],
  ['What was introduced commercially by Bayer A.G. of Leverkusen, in 1899?',
    'what'],
  ['What was known as the Spice Island?', 'what'],
  ['What was Mao\'s second name?', 'what'],
  ['What was Mel Gibson\'s first movie?', 'what'],
  ['What was Michelangelo\'s last name?', 'what'],
  ['What was organized as a Confederate veterans\' social club in Pulaski, in Tennessee, in 1866?',
    'what'],
  ['What was Queen Victoria\'s title regarding India?', 'what'],
  ['What was the Bridge of San Luis Rey made of?', 'what'],
  ['What was the Chivington Massacre?', 'what'],
  ['What was the claim to fame of King Camp Gillette?', 'what'],
  ['What was the education system in the 1960\'s?', 'what'],
  ['What was the first domesticated bird?', 'what'],
  ['What was the first Lifesaver flavor?', 'what'],
  ['What was the highest mountain on earth before Mount Everest was discovered?',
    'what'],
  ['What was the name of Betty Boop\'s dog?', 'what'],
  ['What was the name of that popular song the Creeps sang?',
    'what'],
  ['What was the name of the "Little Rascals" dog?', 'what'],
  ['What was the name of the 187s Irish terrorist group in Pennsylvania mining areas?',
    'what'],
  ['What was the name of the cook on Rawhide?', 'what'],
  ['What was the name of the daughter of the Virginia chief Powhatan that married John Rolfe?',
    'what'],
  ['What was the name of the first Russian astronaut to do a spacewalk?',
    'what'],
  ['What was the name of the lawyer who represented Randy Craft?',
    'what'],
  ['What was the name of the movie that starred Sharon Stone and Arnold Schwarzenegger?',
    'what'],
  ['What was the name of the orca that died of a fungal infection?',
    'what'],
  ['What was the name of the sitcom that Alyssa Milano starred in with Tony Danza?',
    'what'],
  ['What was the number of people that Randy Steven Craft was convicted of killing?',
    'what'],
  ['What was the occupation of Mandy Rice-Davies?', 'what'],
  ['What was the only country you were allowed to drive into Israel from in 1979?',
    'what'],
  ['What was the price of Varian Associates\' vacuum products division?',
    'what'],
  ['What was the top box office movie in April 1998?', 'what'],
  ['What was the U.S. highway death toll in 1969?', 'what'],
  ['What weapon is the mythological character Apollo most proficient with?',
    'what'],
  ['What were popular songs and types of songs in the 1920s?',
    'what'],
  ['What wrestling star became "The Incredible Hulk"?', 'what'],
  ['Woodrow Wilson served as president of what university?',
    'what'],
  ['CNN began broadcasting in what year?', 'what'],
  ['Hazmat stands for what?', 'what'],
  ['In what medium is Stuart Hamblen considered to be the first singing cowboy?',
    'what'],
  ['In what Olympic Games did Nadia Comaneci become popular?',
    'what'],
  ['In what religion was Isis the nature goddess?', 'what'],
  ['In what sport are these following numbers relevant?',
    'what'],
  ['In what U.S. state was the first woman governor elected?',
    'what'],
  ['Italy is the largest producer of what?', 'what'],
  ['On what T.V. show could Tom Terrific be found?', 'what'],
  ['The corpus callosum is in what part of the body?', 'what'],
  ['To what does Microsoft\'s Windows 3 owe its success?',
    'what'],
  ['When are sheep shorn?', 'when'],
  ['When did beethoven die?', 'when'],
  ['When did CNN begin broadcasting?', 'when'],
  ['When did CNN go on the air?', 'when'],
  ['When did Mount St. Helen last have a significant eruption?',
    'when'],
  ['When did Muhammad live?', 'when'],
  ['When did Rococo painting and architecture flourish?',
    'when'],
  ['When did Spielberg direct "Jaws"?', 'when'],
  ['When did the Berlin Wall go up?', 'when'],
  ['When did the Bounty mutiny take place?', 'when'],
  ['When did the Dow first reach?', 'when'],
  ['When did the neanderthal man live?', 'when'],
  ['When did the royal wedding of Prince Andrew and Fergie take place?',
    'when'],
  ['When did World War I start?', 'when'],
  ['When does the average teenager first have intercourse?',
    'when'],
  ['When is Bastille Day?', 'when'],
  ['When is Boxing Day?', 'when'],
  ['When is the site www.questions.com going to open?', 'when'],
  ['When is the Tulip Festival in Michigan?', 'when'],
  ['When reading classified ads, what does EENTY stand for?',
    'when'],
  ['When was "the Great Depression"?', 'when'],
  ['When was Berlin\'s Brandenburg gate erected?', 'when'],
  ['When was Hurricane Hugo?', 'when'],
  ['When was Ozzy Osbourne born?', 'when'],
  ['When was the Battle of Hastings?', 'when'],
  ['When was the battle of the Somme fought?', 'when'],
  ['When was the first American encyclopedia published?',
    'when'],
  ['When was the first steel mill in the United States built?',
    'when'],
  ['When was the first Wall Street Journal published?', 'when'],
  ['When was the San Francisco fire?', 'when'],
  ['When was the women\'s suffrage amendment ratified?', 'when'],
  ['Where\'s the 19th hole on a golf course?', 'where'],
  ['Where\'s the Petrified Forest?', 'where'],
  ['Where are the 49 steps?', 'where'],
  ['Where are the leading medical groups specializing in lung diseases?',
    'where'],
  ['Where are the tropical rain forest distributions?', 'where'],
  ['Where can I buy movies on videotape online?', 'where'],
  ['Where can I find a "Fifth Element" screensaver?', 'where'],
  ['Where can I find a case on Individuals with Disabilities Education Act of 1991?',
    'where'],
  ['Where can I find a list of "classic" books 5th and 6th graders should read?',
    'where'],
  ['Where can I find a person\'s address from a telephone number?',
    'where'],
  ['Where can I find a review of Nightmare on Elm Street in a film journal?',
    'where'],
  ['Where can I find correct tabs for Third Eye Blind songs?',
    'where'],
  ['Where can I find information on George Bush?', 'where'],
  ['Where can I find information on the Narragansett Indians and other tribes in Rhode Island?',
    'where'],
  ['Where can I find out the top 1 singles?', 'where'],
  ['Where can I find pictorial directions on how to build a very simple treehouse?',
    'where'],
  ['Where can I find the best free evidence for debate about Russia?',
    'where'],
  ['Where can I find the names of all the 15 Pokemon?', 'where'],
  ['Where can stocks be traded on-line?', 'where'],
  ['Where did Indian Pudding come from?', 'where'],
  ['Where did Sarge Steel get his metal hand?', 'where'],
  ['Where did the myth of Santa Claus originate?', 'where'],
  ['Where did the term "86ed" come from?', 'where'],
  ['Where do chihuahuas come from?', 'where'],
  ['Where do hyenas live?', 'where'],
  ['Where do people mountain climb in Nepal?', 'where'],
  ['Where do rocks come from?', 'where'],
  ['Where do the adventures of "The Swiss Family Robinson" take place?',
    'where'],
  ['Where does Barney Rubble go to work after he drops Fred off in the "Flintstones" cartoon series?',
    'where'],
  ['Where does Buzz Aldrin want to build a permanent, manned space station?',
    'where'],
  ['Where does chocolate come from?', 'where'],
  ['Where does your hair grow the fastest?', 'where'],
  ['Where is Basque country located?', 'where'],
  ['Where is Logan Airport?', 'where'],
  ['Where is Mozambique located?', 'where'],
  ['Where is Procter & Gamble based in the U.S.?', 'where'],
  ['Where is Procter & Gamble headquartered in the U.S.?',
    'where'],
  ['Where is the Abominable Snowman said to wander?', 'where'],
  ['Where is the actress, Marion Davies, buried?', 'where'],
  ['Where is the Danube?', 'where'],
  ['Where is the highest point in Japan?', 'where'],
  ['Where is the Kalahari desert?', 'where'],
  ['Where is the Kentucky Horse Park located?', 'where'],
  ['Where is the Loop?', 'where'],
  ['Where is the Orinoco?', 'where'],
  ['Where is the Rose Bowl played?', 'where'],
  ['Where is Tornado Alley?', 'where'],
  ['Where is Trinidad?', 'where'],
  ['Where is Windsor Castle?', 'where'],
  ['Where must a soccer goalie stand to be permitted to handle the ball?',
    'where'],
  ['Where on the Internet can I find a song lyrics database similar to the International Lyrics Server?',
    'where'],
  ['Where on the Internet can I get information about the Fifth Amendment on the American Bill of Rights?',
    'where'],
  ['Where was Christopher Columbus born?', 'where'],
  ['Where was George Washington born?', 'where'],
  ['Where was Lincoln assassinated?', 'where'],
  ['Where was the Ligurian Republic, 1797-185,?', 'where'],
  ['In what area of the world was the Six Day War fought?',
    'where'],
  ['In what city is the headquarters of Sinn Fein?', 'where'],
  ['In What city or state do the most gay men live in?',
    'where'],
  ['McCarren Airport is located in what city?', 'where'],
  ['Which Bloom County resident wreaks havoc with a computer?',
    'which'],
  ['Which came first, according to Genesis 122 - the chicken or the egg?',
    'which'],
  ['Which city did Christian Crusaders fight to recapture from the Muslims?',
    'which'],
  ['Which city has the oldest relationship as a sister�city with Los Angeles?',
    'which'],
  ['Which company created the Internet browser Mosaic?',
    'which'],
  ['Which company that manufactures video-game hardware sells the "super system"?',
    'which'],
  ['Which condiment was once sold as a patent medicine?',
    'which'],
  ['Which country is Australia\'s largest export market?',
    'which'],
  ['Which Doonesbury character was likely to turn into a werewolf?',
    'which'],
  ['Which hair care product told us "hate that gray, wash it away"?',
    'which'],
  ['Which is the largest clock, diameter wise, in Europe?',
    'which'],
  ['Which is the wealthiest country in the world?', 'which'],
  ['Which Japanese car maker had its biggest percentage of sale in the domestic market?',
    'which'],
  ['Which killer whale died at Sea World of a fungal infection?',
    'which'],
  ['Which mosquito\'s bite draws blood, DT NN CC DT NN .',
    'which'],
  ['Which of the following men was not married to Rita Hayworth?',
    'which'],
  ['Which of the following was Rhodes Scholar?', 'which'],
  ['Which oil company almost picked a word that meant "stalled car" in Japanese as its new international name?',
    'which'],
  ['Which soft drink does Madonna advertise for?', 'which'],
  ['Which two products use a tiger as their symbol?', 'which'],
  ['Which two states enclose Chesapeake Bay?', 'which'],
  ['Which Ventura County police department seized the largest cocaine shipment in it\'s history?',
    'which'],
  ['Which way do you turn your Bic to increase the flame - clockwise or counterclockwise?',
    'which'],
  ['Who are the Challengers of the Unknown?', 'who'],
  ['Who are the two sons of Ozzie and Harriet Nelson?', 'who'],
  ['Who banned Peter Rose from baseball for betting on games?',
    'who'],
  ['Who came up with the name, El Nino?', 'who'],
  ['Who claimed he killed 4, 280 buffalo as food for the crew building the Kansas Pacific Railway?',
    'who'],
  ['Who coined the term NN cyberspace "in his novel NN Neuromancer"?',
    'who'],
  ['Who comprised the now-defunct comic book team known as the Champions?',
    'who'],
  ['Who created Dennis the Menace?', 'who'],
  ['Who created private detective Philip Marlowe?', 'who'],
  ['Who created the character of Scrooge?', 'who'],
  ['Who danced into stardom with Fred Astaire in 1941\'s You\'ll Never Get Rich?',
    'who'],
  ['Who declared "I am down on whores and I shan\'t stop ripping them"?',
    'who'],
  ['Who delivered his last newscast on March 6, 1981?', 'who'],
  ['Who died 1 feet from where John F. Kennedy did?', 'who'],
  ['Who directed "Jaws"?', 'who'],
  ['Who discovered electricity?', 'who'],
  ['Who do Herb and Tootsie live next door to?', 'who'],
  ['Who does data collection in tourism?', 'who'],
  ['Who does the advertizing for Frito-Lay?', 'who'],
  ['Who earns their money the hard way?', 'who'],
  ['Who fired Maria Ybarra from her position in San Diego council?',
    'who'],
  ['Who followed Caesar?', 'who'],
  ['Who founded the People\'s Temple Commune?', 'who'],
  ['Who graced the airwaves with such pearls as "Do ya lo-o-ove me? Get naked, baby !"?',
    'who'],
  ['Who has more DNA - a man or a woman?', 'who'],
  ['Who has the only speaking role in "Silent Movie"?', 'who'],
  ['Who has won the most Super Bowls?', 'who'],
  ['Who invented baseball?', 'who'],
  ['Who invented Make-up?', 'who'],
  ['Who invented silly putty?', 'who'],
  ['Who invented the radio?', 'who'],
  ['Who invented the toothbrush?', 'who'],
  ['Who is actress Goldie Hawn\'s current actor boyfriend?',
    'who'],
  ['Who is Barbara Jordan?', 'who'],
  ['Who is Colin Powell?', 'who'],
  ['Who is Coronado?', 'who'],
  ['Who is Desmond Tutu?', 'who'],
  ['Who is Snoopy\'s arch-enemy?', 'who'],
  ['Who is Stein Eriksen?', 'who'],
  ['Who is Terrence Malick?', 'who'],
  ['Who is the "Queen Mother"?', 'who'],
  ['Who is the fastest swimmer in the world?', 'who'],
  ['Who is the founder of Scientology?', 'who'],
  ['Who is the leading competitor of Trans Union Company?',
    'who'],
  ['Who is the man behind the pig-the man who pulls the strings and speaks for Miss Piggy?',
    'who'],
  ['Who is the mayor of Marbella?', 'who'],
  ['Who is the monarch of the United Kingdom?', 'who'],
  ['Who is the only prime minister of Canada to serve 22 years but not necessarily consecutively?',
    'who'],
  ['Who is the president of Stanford University?', 'who'],
  ['Who is the superstar in rent-a-cars?', 'who'],
  ['Who is the voice of Miss Piggy?', 'who'],
  ['Who is the worst US President ever?', 'who'],
  ['Who is the youngest of the Beatles?', 'who'],
  ['Who kept the most famous diary in the English language?',
    'who'],
  ['Who killed Gandhi?', 'who'],
  ['Who made a boat out of gopher wood?', 'who'],
  ['Who murdered Leno and Rosemary LaBianca on August 1', 'who'],
  ['Who painted Mother and Child?', 'who'],
  ['Who painted the Sistine Chapel?', 'who'],
  ['Who patented the first phonograph?', 'who'],
  ['Who played the original Charlie\'s Angels?', 'who'],
  ['Who played the Ringo Kid in the 1939 film Stagecoach?',
    'who'],
  ['Who portrayed "Rosanne Rosanna-Dana" on the television show "Saturday Night Live"?',
    'who'],
  ['Who portrayed Etta Place, companion to Butch Cassidey and the Sundance Kid?',
    'who'],
  ['Who portrayed portly criminologist Carl Hyatt on Checkmate?',
    'who'],
  ['Who produces Spumante?', 'who'],
  ['Who received the Will Rogers Award in 1989?', 'who'],
  ['Who replaced Bert Parks as the host of The Miss America Pageant?',
    'who'],
  ['Who said, "I shall return ." during World War Two?', 'who'],
  ['Who said of Super Bowl III in 1969 - "We\'ll win- I guarantee it"?',
    'who'],
  ['Who sings the song "Drink to me with thine eyes" by Ben Johnson?',
    'who'],
  ['Who sings the themes for "Dawson\'s Creek" and "Felicity"?',
    'who'],
  ['Who starred in Singing in the Rain and The Singing Nun?',
    'who'],
  ['Who was chairman of the Senate select committee that tried to get to the bottom of Watergate?',
    'who'],
  ['Who was Lauren Bacall\'s first husband?', 'who'],
  ['Who was named Admiral of the Ocean Seas and Viceroy and Governor General of all the islands he might discover, and also granted 10-?? of all profits of his voyage .',
    'who'],
  ['Who was nicknamed The Little Corporal?', 'who'],
  ['Who was President of Afghanistan in 1994?', 'who'],
  ['Who was President of Costa Rica in 1994?', 'who'],
  ['Who was Randy Steven Craft\'s lawyer?', 'who'],
  ['Who was shot in the back during a Poker game in Deadwood, the Dakota territory?',
    'who'],
  ['Who was the 16th President of the United States?', 'who'],
  ['Who was the author of "John Brown\'s Body"?', 'who'],
  ['Who was the author of the book about computer hackers called "The Cuckoo\'s Egg Tracking a Spy Through the Maze of Computer Espionage"?',
    'who'],
  ['Who was the Charlie perfume woman?', 'who'],
  ['Who was the Democratic nominee in the American presidential election?',
    'who'],
  ['Who was the first American in space?', 'who'],
  ['Who was the first American poet to win the Nobel Prize for literature, in 1948?',
    'who'],
  ['Who was the first black golfer to tee off in the Masters?',
    'who'],
  ['Who was the first coach of the Cleveland Browns?', 'who'],
  ['Who was the first Holy Roman Emperor?', 'who'],
  ['Who was the first host of Person to Person?', 'who'],
  ['Who was the first person inducted into the U.S. Swimming Hall of Fame?',
    'who'],
  ['Who was the first woman golfer to earn a million?', 'who'],
  ['Who was the founding member of the Pink Floyd band?', 'who'],
  ['Who was the inventor of silly putty?', 'who'],
  ['Who was the lead actress in the movie \'sleepless in Seattle\'?',
    'who'],
  ['Who was the mother of the man who would not be king, the duke of Windsor?',
    'who'],
  ['Who was the only U.S. President to wear a Nazi uniform?',
    'who'],
  ['Who was The Pride of the Yankees?', 'who'],
  ['Who was the prophet of the Muslim people?', 'who'],
  ['Who was the star of the 1965 Broadway hit Golden Boy?',
    'who'],
  ['Who were the "filthiest people alive?"', 'who'],
  ['Who were the five Marx brothers?', 'who'],
  ['Who were the four famous founders of United Artists?',
    'who'],
  ['Who won the Nobel Peace Prize in 1991?', 'who'],
  ['Who wrote NN DT NNP NNP"?', 'who'],
  ['Who wrote The Night of the Iguana?', 'who'],
  ['Who wrote the song, "Stardust"?', 'who'],
  ['Whom did the Chicago Bulls beat in the 1993 championship?',
    'who'],
  ['Whose autobiography is titled Yes I Can?', 'who'],
  ['Whose cover is that of an employee of Universal Import and Export?',
    'who'],
  ['Whose first presidential order was "Let\'s get this goddamn thing airborne"?',
    'who'],
  ['Why are electric cars less efficient in the northeast than in California?',
    'why'],
  ['Why are the ears your center of balance?', 'why'],
  ['Why did several San Diego schools stop serving apples to students?',
    'why'],
  ['Why did the chicken cross the road?', 'why'],
  ['Why did the world enter a global depression in 1929?',
    'why'],
  ['Why do heavier objects travel downhill faster?', 'why'],
  ['Why do horseshoes bring luck?', 'why'],
  ['Why do n\'t you guys have some sort of contest where you ask a question and whoever finds the answers wins a prize?',
    'why'],
  ['Why do people get calluses?', 'why'],
  ['Why do some clothing labels say "Use a nonchlorine bleach"?',
    'why'],
  ['Why doesn\'t www.answers.com have any answers to my questions?',
    'why'],
  ['Why is black the color of mourning in the West?', 'why'],
  ['Why is poop sometimes different colors?', 'why'],
  ['Why is the grass green?', 'why'],
  ['Why was the L.A. office of Shea and Gould closed?', 'why'],
  ['Why were people recruited for the Vietnam War?', 'why'],
  ['Why were the American soldiers in WWI called "Doughboys"',
    'why']
];
