var parts_of_speech = {
    "VB": {
        "description": "verb, base form",
        "example": "eat",
        "parent": "verb",
        "tag": "VB"
    },
    "CP": {
        "description": "copula",
        "example": "is, was, were",
        "parent": "verb",
        "tag": "CP"
    },
    "VBD": {
        "description": "verb, past tense",
        "example": "ate",
        "parent": "verb",
        "tense": "past",
        "tag": "VBD"
    },
    "VBN": {
        "description": "verb, past part",
        "example": "eaten",
        "parent": "verb",
        "tense": "past",
        "tag": "VBN"
    },
    "VBP": {
        "description": "Verb, present",
        "example": "eat",
        "parent": "verb",
        "tense": "present",
        "tag": "VBP"
    },
    "VBZ": {
        "description": "Verb, present",
        "example": "eats, swims",
        "tense": "present",
        "parent": "verb",
        "tag": "VBZ"
    },
    "MD": {
        "description": "Modal",
        "example": "can,should",
        "parent": "glue",
        "tag": "MD"
    },
    "RB": {
        "description": "Adverb",
        "example": "quickly, softly",
        "parent": "glue",
        "tag": "RB"
    },
    "JJ": {
        "description": "Adjective",
        "example": "big, nice",
        "parent": "adjective",
        "tag": "JJ"
    },
    "JJR": {
        "description": "Adj., comparative",
        "example": "bigger, cooler",
        "parent": "adjective",
        "tag": "JJR"
    },
    "JJS": {
        "description": "Adj., superlative",
        "example": "biggest, fattest",
        "parent": "adjective",
        "tag": "JJS"
    },
    "RBR": {
        "description": "Adverb, comparative",
        "example": "faster, cooler",
        "parent": "adjective",
        "tag": "RBR"
    },
    "RBS": {
        "description": "Adverb, superlative",
        "example": "fastest (driving), coolest (looking)",
        "parent": "adjective",
        "tag": "RBS"
    },
    "NN": {
        "description": "Noun, sing. or mass",
        "example": "dog, rain",
        "parent": "noun",
        "tag": "NN"
    },
    "NNP": {
        "description": "Proper noun, sing.",
        "example": "Edinburgh, skateboard",
        "parent": "noun",
        "tag": "NNP"
    },
    "NNPS": {
        "description": "Proper noun, plural",
        "example": "Smiths",
        "parent": "noun",
        "tag": "NNPS"
    },
    "NNS": {
        "description": "Noun, plural",
        "example": "dogs, foxes",
        "parent": "noun",
        "tag": "NNS"
    },
    "NNO": {
        "description": "Noun, possessive",
        "example": "spencer's, sam's",
        "parent": "noun",
        "tag": "NNO"
    },
    "PP": {
        "description": "Possessive pronoun",
        "example": "my,one's",
        "parent": "glue",
        "tag": "PP"
    },
    "FW": {
        "description": "foreign word",
        "example": "mon dieu, voila",
        "parent": "noun",
        "tag": "FW"
    },
    "CD": {
        "description": "Cardinal number",
        "example": "one,two",
        "parent": "glue", //may want to change this
        "tag": "CD"
    },
    "VBG": {
        "description": "verb, gerund",
        "example": "eating,winning",
        "parent": "verb",
        "tag": "VBG"
    },
    "NG": {
        "description": "noun, gerund",
        "example": "eating,winning - but used grammatically as a noun",
        "parent": "noun",
        "tag": "VBG"
    },
    "IN": {
        "description": "Preposition",
        "example": "of,in,by",
        "parent": "glue",
        "tag": "IN"
    },
    "UP": {
        "description": "dependent preposition",
        "example": "up, down",
        "parent": "glue",
        "tag": "UP"
    },
    "CC": {
        "description": "Coord Conjuncn",
        "example": "and,but,or",
        "parent": "glue",
        "tag": "CC"
    },
    "PRP": {
        "description": "Personal pronoun",
        "example": "I,you,she",
        "parent": "glue",
        "tag": "PRP"
    },
    "DT": {
        "description": "Determiner",
        "example": "the,some",
        "parent": "title",
        "tag": "DT"
    },
    "example": {
        "description": "Existential there",
        "example": "there",
        "parent": "glue",
        "tag": "EX"
    },
    "POS": {
        "description": "Possessive ending",
        "example": "s",
        "parent": "glue",
        "tag": "POS"
    },
    "PDT": {
        "description": "Predeterminer",
        "example": "all, both",
        "parent": "glue",
        "tag": "PDT"
    },
    "RP": {
        "description": "Particle",
        "example": "up,off",
        "parent": "glue",
        "tag": "RP"
    },
    "TO": {
        "description": "to",
        "example": "to",
        "parent": "glue",
        "tag": "TO"
    },
    "UH": {
        "description": "Interjection",
        "example": "oh, oops",
        "parent": "glue",
        "tag": "UH"
    },
    "WDT": {
        "description": "Wh-determiner",
        "example": "which,that",
        "parent": "glue",
        "tag": "WDT"
    },
    "WP": {
        "description": "Wh pronoun",
        "example": "who,what",
        "parent": "glue",
        "tag": "WP"
    },
    "WRB": {
        "description": "Wh-adverb",
        "example": "how,where",
        "parent": "glue",
        "tag": "WRB"
    },
    "LS": {
        "description": "List item marker",
        "example": "1,One",
        "parent": "glue",
        "tag": "LS"
    },
    "SYM": {
        "description": "Symbol",
        "example": "+,%,&",
        "parent": "glue",
        "tag": "SYM"
    }
}


var spot = (function() {

    var silly = {
        "a-z": true,
        "able": true,
        "about": true,
        "above": true,
        "abroad": true,
        "accessibility": true,
        "according": true,
        "accordingly": true,
        "across": true,
        "actor": true,
        "actress": true,
        "actually": true,
        "adjustment": true,
        "advertising": true,
        "after": true,
        "afterwards": true,
        "again": true,
        "against": true,
        "ago": true,
        "ah": true,
        "aha": true,
        "ahead": true,
        "ain't": true,
        "album": true,
        "all": true,
        "allow": true,
        "allows": true,
        "almost": true,
        "alone": true,
        "along": true,
        "alongside": true,
        "already": true,
        "also": true,
        "although": true,
        "always": true,
        "am": true,
        "amid": true,
        "amidst": true,
        "among": true,
        "amongst": true,
        "amoungst": true,
        "amount": true,
        "amplitude": true,
        "an": true,
        "and": true,
        "another": true,
        "any": true,
        "anybody": true,
        "anyhow": true,
        "anyone": true,
        "anything": true,
        "anyway": true,
        "anyways": true,
        "anywhere": true,
        "apart": true,
        "appear": true,
        "appreciate": true,
        "appropriate": true,
        "are": true,
        "area": true,
        "aren't": true,
        "around": true,
        "article": true,
        "as": true,
        "as to": true,
        "aside": true,
        "ask": true,
        "asking": true,
        "associated": true,
        "at": true,
        "available": true,
        "away": true,
        "awfully": true,
        "aye": true,
        "back": true,
        "backward": true,
        "backwards": true,
        "be": true,
        "became": true,
        "because": true,
        "become": true,
        "becomes": true,
        "becoming": true,
        "been": true,
        "before": true,
        "beforehand": true,
        "begin": true,
        "behind": true,
        "being": true,
        "believe": true,
        "below": true,
        "beside": true,
        "besides": true,
        "best": true,
        "better": true,
        "between": true,
        "beyond": true,
        "bill": true,
        "both": true,
        "bottom": true,
        "brief": true,
        "brother": true,
        "building": true,
        "but": true,
        "by": true,
        "bye": true,
        "c'mon": true,
        "c's": true,
        "call": true,
        "came": true,
        "can": true,
        "can't": true,
        "cannot": true,
        "cant": true,
        "capacity": true,
        "capital": true,
        "caption": true,
        "cause": true,
        "causes": true,
        "center": true,
        "century": true,
        "certain": true,
        "certainly": true,
        "change": true,
        "changes": true,
        "children": true,
        "citizens": true,
        "clearly": true,
        "co": true,
        "co.": true,
        "color": true,
        "colour": true,
        "com": true,
        "come": true,
        "comes": true,
        "comments": true,
        "complex": true,
        "computer": true,
        "con": true,
        "concerning": true,
        "consequently": true,
        "consider": true,
        "considering": true,
        "contain": true,
        "containing": true,
        "contains": true,
        "contestant": true,
        "corresponding": true,
        "could": true,
        "couldn't": true,
        "couldnt": true,
        "course": true,
        "cover": true,
        "cry": true,
        "currently": true,
        "dare": true,
        "daren't": true,
        "day": true,
        "de": true,
        "dear": true,
        "decade": true,
        "definitely": true,
        "density": true,
        "depth": true,
        "describe": true,
        "described": true,
        "despite": true,
        "detail": true,
        "did": true,
        "didn't": true,
        "different": true,
        "directly": true,
        "distance": true,
        "do": true,
        "does": true,
        "doesn't": true,
        "doing": true,
        "don't": true,
        "done": true,
        "doughter": true,
        "down": true,
        "downwards": true,
        "dr": true,
        "due": true,
        "due to": true,
        "during": true,
        "each": true,
        "edu": true,
        "eg": true,
        "eh": true,
        "eight": true,
        "eighty": true,
        "either": true,
        "eleven": true,
        "else": true,
        "elsewhere": true,
        "empty": true,
        "end": true,
        "ending": true,
        "enough": true,
        "entirely": true,
        "episode": true,
        "especially": true,
        "et": true,
        "etc": true,
        "even": true,
        "ever": true,
        "evermore": true,
        "every": true,
        "everybody": true,
        "everyone": true,
        "everything": true,
        "everywhere": true,
        "ex": true,
        "exactly": true,
        "example": true,
        "except": true,
        "fairly": true,
        "far": true,
        "farther": true,
        "feel": true,
        "few": true,
        "fewer": true,
        "fifteen": true,
        "fifth": true,
        "fify": true,
        "fill": true,
        "find": true,
        "fire": true,
        "first": true,
        "five": true,
        "folk": true,
        "followed": true,
        "follower": true,
        "following": true,
        "follows": true,
        "food": true,
        "for": true,
        "forever": true,
        "former": true,
        "formerly": true,
        "forth": true,
        "forty": true,
        "forward": true,
        "found": true,
        "four": true,
        "from": true,
        "front": true,
        "full": true,
        "further": true,
        "furthermore": true,
        "get": true,
        "gets": true,
        "getting": true,
        "girl": true,
        "give": true,
        "given": true,
        "gives": true,
        "go": true,
        "goes": true,
        "going": true,
        "gone": true,
        "goodbye": true,
        "got": true,
        "gotten": true,
        "greetings": true,
        "guy": true,
        "ha": true,
        "had": true,
        "hadn't": true,
        "half": true,
        "happens": true,
        "hardly": true,
        "has": true,
        "hasn't": true,
        "hasnt": true,
        "have": true,
        "haven't": true,
        "having": true,
        "he": true,
        "he'd": true,
        "he'll": true,
        "he's": true,
        "height": true,
        "hello": true,
        "help": true,
        "hence": true,
        "her": true,
        "here": true,
        "here's": true,
        "hereafter": true,
        "hereby": true,
        "herein": true,
        "hereupon": true,
        "hers": true,
        "herself": true,
        "hey": true,
        "hi": true,
        "high": true,
        "him": true,
        "himself": true,
        "his": true,
        "hither": true,
        "home": true,
        "hopefully": true,
        "house": true,
        "how": true,
        "how's": true,
        "howbeit": true,
        "however": true,
        "hue": true,
        "hundred": true,
        "i": true,
        "i'd": true,
        "i'll": true,
        "i'm": true,
        "i've": true,
        "ie": true,
        "if": true,
        "ignored": true,
        "im": true,
        "immediate": true,
        "in": true,
        "inasmuch": true,
        "inc": true,
        "inc.": true,
        "including": true,
        "indeed": true,
        "indicate": true,
        "indicated": true,
        "indicates": true,
        "inner": true,
        "inside": true,
        "insofar": true,
        "instead": true,
        "interest": true,
        "into": true,
        "inward": true,
        "is": true,
        "isn't": true,
        "it": true,
        "it'd": true,
        "it'll": true,
        "it's": true,
        "its": true,
        "itself": true,
        "jr": true,
        "just": true,
        "k": true,
        "keep": true,
        "keeps": true,
        "kept": true,
        "know": true,
        "known": true,
        "knows": true,
        "la": true,
        "lady": true,
        "last": true,
        "lastnight": true,
        "lastweek": true,
        "lately": true,
        "later": true,
        "latter": true,
        "latterly": true,
        "le": true,
        "league": true,
        "least": true,
        "length": true,
        "les": true,
        "less": true,
        "lest": true,
        "let": true,
        "let's": true,
        "like": true,
        "liked": true,
        "likely": true,
        "likewise": true,
        "little": true,
        "long": true,
        "look": true,
        "looking": true,
        "looks": true,
        "los": true,
        "low": true,
        "lower": true,
        "ltd": true,
        "made": true,
        "magnitude": true,
        "mainly": true,
        "make": true,
        "makes": true,
        "man": true,
        "many": true,
        "may": true,
        "maybe": true,
        "mayn't": true,
        "me": true,
        "mean": true,
        "meantime": true,
        "meanwhile": true,
        "member": true,
        "merely": true,
        "mhm": true,
        "might": true,
        "mightn't": true,
        "mill": true,
        "mine": true,
        "minus": true,
        "miss": true,
        "mm": true,
        "month": true,
        "more": true,
        "moreover": true,
        "most": true,
        "mostly": true,
        "move": true,
        "mr": true,
        "mrs": true,
        "ms": true,
        "much": true,
        "must": true,
        "mustn't": true,
        "my": true,
        "myself": true,
        "name": true,
        "namely": true,
        "nd": true,
        "near": true,
        "nearly": true,
        "necessary": true,
        "need": true,
        "needn't": true,
        "needs": true,
        "neither": true,
        "never": true,
        "neverf": true,
        "neverless": true,
        "nevertheless": true,
        "new": true,
        "next": true,
        "nine": true,
        "ninety": true,
        "no": true,
        "no-one": true,
        "nobody": true,
        "non": true,
        "none": true,
        "nonetheless": true,
        "noone": true,
        "nor": true,
        "normally": true,
        "not": true,
        "nothing": true,
        "notwithstanding": true,
        "novel": true,
        "now": true,
        "nowhere": true,
        "obviously": true,
        "of": true,
        "off": true,
        "often": true,
        "oh": true,
        "ok": true,
        "okay": true,
        "old": true,
        "on": true,
        "on to": true,
        "once": true,
        "one": true,
        "one's": true,
        "ones": true,
        "only": true,
        "onto": true,
        "ooh": true,
        "opposite": true,
        "or": true,
        "other": true,
        "others": true,
        "otherwise": true,
        "ought": true,
        "oughtn't": true,
        "our": true,
        "ours": true,
        "ourselves": true,
        "out": true,
        "out of": true,
        "outside": true,
        "over": true,
        "overall": true,
        "own": true,
        "part": true,
        "particular": true,
        "particularly": true,
        "past": true,
        "people": true,
        "per": true,
        "perhaps": true,
        "person": true,
        "pitch": true,
        "placed": true,
        "play": true,
        "please": true,
        "plus": true,
        "policy": true,
        "possible": true,
        "president": true,
        "presumably": true,
        "printable": true,
        "privacy": true,
        "probably": true,
        "program": true,
        "provided": true,
        "provides": true,
        "put": true,
        "quantity": true,
        "que": true,
        "quite": true,
        "qv": true,
        "rather": true,
        "rd": true,
        "re": true,
        "really": true,
        "reasonably": true,
        "recent": true,
        "recently": true,
        "recommend": true,
        "record": true,
        "regarding": true,
        "regardless": true,
        "regards": true,
        "relatively": true,
        "report": true,
        "respectively": true,
        "review": true,
        "right": true,
        "room": true,
        "round": true,
        "said": true,
        "same": true,
        "san": true,
        "saw": true,
        "say": true,
        "saying": true,
        "says": true,
        "season": true,
        "second": true,
        "secondly": true,
        "see": true,
        "seeing": true,
        "seem": true,
        "seemed": true,
        "seeming": true,
        "seems": true,
        "seen": true,
        "self": true,
        "selves": true,
        "send": true,
        "sensible": true,
        "sent": true,
        "serious": true,
        "seriously": true,
        "service": true,
        "seven": true,
        "several": true,
        "shade": true,
        "shall": true,
        "shan't": true,
        "shape": true,
        "she": true,
        "she'd": true,
        "she'll": true,
        "she's": true,
        "should": true,
        "shouldn't": true,
        "show": true,
        "side": true,
        "since": true,
        "sincere": true,
        "singer": true,
        "six": true,
        "sixty": true,
        "size": true,
        "so": true,
        "some": true,
        "somebody": true,
        "someday": true,
        "somehow": true,
        "someone": true,
        "something": true,
        "sometime": true,
        "sometimes": true,
        "somewhat": true,
        "somewhere": true,
        "son": true,
        "soon": true,
        "sorry": true,
        "specified": true,
        "specify": true,
        "specifying": true,
        "speed": true,
        "sr": true,
        "staff": true,
        "still": true,
        "sub": true,
        "such": true,
        "such as": true,
        "sup": true,
        "sure": true,
        "system": true,
        "take": true,
        "taken": true,
        "taking": true,
        "team": true,
        "tell": true,
        "ten": true,
        "tends": true,
        "terms": true,
        "text": true,
        "texture": true,
        "than": true,
        "thank": true,
        "thanks": true,
        "thanx": true,
        "that": true,
        "that'll": true,
        "that's": true,
        "that've": true,
        "thats": true,
        "the": true,
        "their": true,
        "theirs": true,
        "them": true,
        "themselves": true,
        "then": true,
        "thence": true,
        "there": true,
        "there'd": true,
        "there'll": true,
        "there're": true,
        "there's": true,
        "there've": true,
        "thereafter": true,
        "thereby": true,
        "therefore": true,
        "therein": true,
        "theres": true,
        "thereupon": true,
        "these": true,
        "they": true,
        "they'd": true,
        "they'll": true,
        "they're": true,
        "they've": true,
        "thick": true,
        "thin": true,
        "thing": true,
        "things": true,
        "think": true,
        "third": true,
        "thirty": true,
        "this": true,
        "thorough": true,
        "thoroughly": true,
        "those": true,
        "though": true,
        "three": true,
        "through": true,
        "throughout": true,
        "thru": true,
        "thus": true,
        "till": true,
        "time": true,
        "timing": true,
        "to": true,
        "today": true,
        "together": true,
        "tommorrow": true,
        "too": true,
        "took": true,
        "top": true,
        "toward": true,
        "towards": true,
        "tried": true,
        "tries": true,
        "truly": true,
        "try": true,
        "trying": true,
        "twelve": true,
        "twenty": true,
        "twice": true,
        "two": true,
        "un": true,
        "under": true,
        "underneath": true,
        "undoing": true,
        "unfortunately": true,
        "unit": true,
        "unless": true,
        "unlike": true,
        "unlikely": true,
        "until": true,
        "unto": true,
        "up": true,
        "up to": true,
        "update": true,
        "upon": true,
        "upwards": true,
        "us": true,
        "use": true,
        "used": true,
        "useful": true,
        "uses": true,
        "using": true,
        "usually": true,
        "uucp": true,
        "v": true,
        "value": true,
        "various": true,
        "version": true,
        "versus": true,
        "very": true,
        "via": true,
        "viz": true,
        "volume": true,
        "vs": true,
        "waiter": true,
        "waitress": true,
        "want": true,
        "wants": true,
        "was": true,
        "wasn't": true,
        "way": true,
        "we": true,
        "we'd": true,
        "we'll": true,
        "we're": true,
        "we've": true,
        "week": true,
        "weight": true,
        "welcome": true,
        "well": true,
        "went": true,
        "were": true,
        "weren't": true,
        "what": true,
        "what'll": true,
        "what's": true,
        "what've": true,
        "whatever": true,
        "when": true,
        "when's": true,
        "whence": true,
        "whenever": true,
        "where": true,
        "where's": true,
        "whereafter": true,
        "whereas": true,
        "whereby": true,
        "wherein": true,
        "whereupon": true,
        "wherever": true,
        "whether": true,
        "which": true,
        "whichever": true,
        "while": true,
        "whilst": true,
        "whither": true,
        "who": true,
        "who'd": true,
        "who'll": true,
        "who's": true,
        "whoever": true,
        "whole": true,
        "whom": true,
        "whomever": true,
        "whose": true,
        "why": true,
        "why's": true,
        "width": true,
        "wife": true,
        "will": true,
        "willing": true,
        "wish": true,
        "with": true,
        "within": true,
        "without": true,
        "won't": true,
        "wonder": true,
        "worth": true,
        "would": true,
        "wouldn't": true,
        "yeah": true,
        "year": true,
        "yep": true,
        "yes": true,
        "yesterday": true,
        "yet": true,
        "you": true,
        "you'd": true,
        "you'll": true,
        "you're": true,
        "you've": true,
        "your": true,
        "yours": true,
        "yourself": true,
        "yourselves": true,
        "zero": true,
        "a": true,
        "s": true,
        "n't": true,
        "years": true,
        "er": true,
        "ve": true,
        "good": true,
        "ll": true,
        "m": true,
        "erm": true,
        "world": true,
        "work": true,
        "life": true,
        "number": true,
        "local": true,
        "small": true,
        "case": true,
        "great": true,
        "social": true,
        "group": true,
        "party": true,
        "important": true,
        "place": true,
        "information": true,
        "men": true,
        "per cent": true,
        "school": true,
        "national": true,
        "fact": true,
        "night": true,
        "point": true,
        "company": true,
        "family": true,
        "hand": true,
        "d": true,
        "large": true,
        "business": true,
        "days": true,
        "john": true,
        "development": true,
        "state": true,
        "head": true,
        "ca": true,
        "council": true,
        "power": true,
        "of course": true,
        "thought": true,
        "young": true,
        "political": true,
        "members": true,
        "eyes": true,
        "public": true,
        "problem": true,
        "problems": true,
        "knew": true,
        "a few": true,
        "face": true,
        "at least": true,
        "times": true,
        "office": true,
        "door": true,
        "form": true,
        "services": true,
        "months": true,
        "big": true,
        "million": true,
        "health": true,
        "words": true,
        "period": true,
        "making": true,
        "main": true,
        "for example": true,
        "market": true,
        "began": true,
        "economic": true,
        "areas": true,
        "major": true,
        "gave": true,
        "real": true,
        "position": true,
        "process": true,
        "effect": true,
        "line": true,
        "moment": true,
        "community": true,
        "difficult": true,
        "action": true,
        "special": true,
        "international": true,
        "kind": true,
        "father": true,
        "age": true,
        "management": true,
        "idea": true,
        "so that": true,
        "evidence": true,
        "looked": true,
        "minister": true,
        "view": true,
        "sense": true,
        "level": true,
        "table": true,
        "death": true,
        "industry": true,
        "control": true,
        "sort": true,
        "clear": true,
        "range": true,
        "black": true,
        "general": true,
        "word": true,
        "history": true,
        "free": true,
        "road": true,
        "order": true,
        "wanted": true,
        "centre": true,
        "study": true,
        "programme": true,
        "result": true,
        "air": true,
        "hour": true,
        "committee": true,
        "experience": true,
        "white": true,
        "mind": true,
        "handshome": true,
        "rate": true,
        "section": true,
        "similar": true,
        "trade": true,
        "minutes": true,
        "reason": true,
        "authority": true,
        "cases": true,
        "role": true,
        "data": true,
        "working": true,
        "class": true,
        "felt": true,
        "central": true,
        "because of": true,
        "companies": true,
        "rather than": true,
        "simply": true,
        "early": true,
        "department": true,
        "asked": true,
        "called": true,
        "personal": true,
        "patient": true,
        "paper": true,
        "land": true,
        "systems": true,
        "TRUE": true,
        "told": true,
        "support": true,
        "act": true,
        "type": true,
        "city": true,
        "common": true,
        "friend": true,
        "countries": true,
        "care": true,
        "decision": true,
        "financial": true,
        "single": true,
        "price": true,
        "provide": true,
        "stage": true,
        "matter": true,
        "parent": true,
        "club": true,
        "practice": true,
        "based": true,
        "as well as": true,
        "private": true,
        "cos": true,
        "foreign": true,
        "wo": true,
        "town": true,
        "open": true,
        "situation": true,
        "strong": true,
        "b": true,
        "bed": true,
        "according to": true,
        "david": true,
        "higher": true,
        "as if": true,
        "quality": true,
        "european": true,
        "conditions": true,
        "at all": true,
        "ground": true,
        "weeks": true,
        "tax": true,
        "poor": true,
        "production": true,
        "friends": true,
        "shown": true,
        "na": true,
        "musicanyone": true,
        "game": true,
        "ways": true,
        "schools": true,
        "issue": true,
        "mr.": true,
        "royal": true,
        "workers": true,
        "american": true,
        "student": true,
        "knowledge": true,
        "art": true,
        "basis": true,
        "subject": true,
        "p.": true,
        "series": true,
        "natural": true,
        "coming": true,
        "bad": true,
        "bank": true,
        "feet": true,
        "greater": true,
        "south": true,
        "simple": true,
        "lot": true,
        "pay": true,
        "west": true,
        "rest": true,
        "security": true,
        "manager": true,
        "cost": true,
        "heart": true,
        "structure": true,
        "attention": true,
        "story": true,
        "&amp": true,
        "means": true,
        "letter": true,
        "question": true,
        "chapter": true,
        "field": true,
        "short": true,
        "studies": true,
        "movement": true,
        "union": true,
        "success": true,
        "figure": true,
        "united": true,
        "analysis": true,
        "news": true,
        "chance": true,
        "evening": true,
        "population": true,
        "boy": true,
        "modern": true,
        "theory": true,
        "legal": true,
        "approach": true,
        "final": true,
        "wrong": true,
        "finally": true,
        "performance": true,
        "human": true,
        "authorities": true,
        "rights": true,
        "relationship": true,
        "in order": true,
        "growth": true,
        "agreement": true,
        "parties": true,
        "account": true,
        "nice": true,
        "held": true,
        "space": true,
        "property": true,
        "project": true,
        "normal": true,
        "gon": true,
        "meeting": true,
        "set": true,
        "quickly": true,
        "behaviour": true,
        "left": true,
        "c": true,
        "previous": true,
        "peter": true,
        "giving": true,
        "couple": true,
        "energy": true,
        "sir": true,
        "term": true,
        "director": true,
        "current": true,
        "st": true,
        "east": true,
        "significant": true,
        "income": true,
        "leave": true,
        "as well": true,
        "pressure": true,
        "levels": true,
        "treatment": true,
        "north": true,
        "prime": true,
        "model": true,
        "suddenly": true,
        "pounds": true,
        "choice": true,
        "away from": true,
        "results": true,
        "scheme": true,
        "fine": true,
        "details": true,
        "takes": true,
        "bring": true,
        "design": true,
        "happy": true,
        "list": true,
        "defence": true,
        "parts": true,
        "bit": true,
        "points": true,
        "red": true,
        "loss": true,
        "industrial": true,
        "activities": true,
        "floor": true,
        "generally": true,
        "issues": true,
        "activity": true,
        "paul": true,
        "talking": true,
        "difference": true,
        "labour": true,
        "specific": true,
        "numbers": true,
        "lord": true,
        "relations": true,
        "understand": true,
        "contract": true,
        "turned": true,
        "product": true,
        "ideas": true,
        "george": true,
        "material": true,
        "wall": true,
        "dead": true,
        "arms": true,
        "easy": true,
        "basic": true,
        "reasons": true,
        "aware": true,
        "technology": true,
        "each other": true,
        "effects": true,
        "figures": true,
        "style": true,
        "date": true,
        "popular": true,
        "window": true,
        "forces": true,
        "showed": true,
        "more than": true,
        "resources": true,
        "sea": true,
        "events": true,
        "advice": true,
        "circumstance": true,
        "plan": true,
        "present": true,
        "event": true,
        "hon.": true,
        "thousand": true,
        "training": true,
        "stood": true,
        "picture": true,
        "sales": true,
        "village": true,
        "original": true,
        "investment": true,
        "thinking": true,
        "cup": true,
        "lines": true,
        "james": true,
        "goods": true,
        "blood": true,
        "opportunity": true,
        "prices": true,
        "professional": true,
        "conference": true,
        "extent": true,
        "interests": true,
        "application": true,
        "page": true,
        "operation": true,
        "film": true,
        "richard": true,
        "in terms of": true,
        "response": true,
        "majority": true,
        "rules": true,
        "shop": true,
        "effective": true,
        "press": true,
        "written": true,
        "york": true,
        "hard": true,
        "sat": true,
        "easily": true,
        "degree": true,
        "wrote": true,
        "statement": true,
        "risk": true,
        "force": true,
        "miles": true,
        "traditional": true,
        "site": true,
        "glass": true,
        "ready": true,
        "died": true,
        "street": true,
        "costs": true,
        "earlier": true,
        "playing": true,
        "stop": true,
        "scottish": true,
        "importance": true,
        "remember": true,
        "individual": true,
        "test": true,
        "complete": true,
        "jobs": true,
        "immediately": true,
        "standards": true,
        "talk": true,
        "considerable": true,
        "girls": true,
        "interesting": true,
        "physical": true,
        "species": true,
        "title": true,
        "michael": true,
        "start": true,
        "eye": true,
        "access": true,
        "brought": true,
        "employment": true,
        "buy": true,
        "fell": true,
        "daughter": true,
        "responsible": true,
        "competition": true,
        "plans": true,
        "medical": true,
        "purpose": true,
        "mouth": true,
        "piece": true,
        "wide": true,
        "heavy": true,
        "answer": true,
        "tomorrow": true,
        "leaving": true,
        "task": true,
        "responsibility": true,
        "arm": true,
        "eventually": true,
        "ability": true,
        "highly": true,
        "hotel": true,
        "pattern": true,
        "method": true,
        "source": true,
        "existing": true,
        "lost": true,
        "election": true,
        "ensure": true,
        "charles": true,
        "a lot": true,
        "region": true,
        "suppose": true,
        "total": true,
        "surface": true,
        "required": true,
        "older": true,
        "heard": true,
        "methods": true,
        "future": true,
        "campaign": true,
        "equipment": true,
        "fully": true,
        "disease": true,
        "machine": true,
        "lack": true,
        "independent": true,
        "slightly": true,
        "software": true,
        "hot": true,
        "peace": true,
        "charge": true,
        "types": true,
        "policies": true,
        "houses": true,
        "no longer": true,
        "direct": true,
        "even if": true,
        "windows": true,
        "stay": true,
        "teacher": true,
        "forms": true,
        "provision": true,
        "factors": true,
        "direction": true,
        "trouble": true,
        "ran": true,
        "beautiful": true,
        "leader": true,
        "civil": true,
        "officer": true,
        "status": true,
        "sound": true,
        "ii": true,
        "character": true,
        "variety": true,
        "considered": true,
        "light": true,
        "continue": true,
        "safety": true,
        "completely": true,
        "box": true,
        "fifty": true,
        "sector": true,
        "animal": true,
        "oxford": true,
        "culture": true,
        "a little": true,
        "obvious": true,
        "late": true,
        "increase": true,
        "include": true,
        "context": true,
        "station": true,
        "sale": true,
        "afternoon": true,
        "produce": true,
        "william": true,
        "positive": true,
        "king": true,
        "essential": true,
        "extra": true,
        "live": true,
        "condition": true,
        "families": true,
        "works": true,
        "appeal": true,
        "trees": true,
        "allowed": true,
        "argument": true,
        "demand": true,
        "principle": true,
        "run": true,
        "pupils": true,
        "chairman": true,
        "cash": true,
        "expected": true,
        "states": true,
        "hope": true,
        "sun": true,
        "involved": true,
        "duty": true,
        "countyrule": true,
        "concern": true,
        "environmental": true,
        "presence": true,
        "truth": true,
        "dog": true,
        "french": true,
        "board": true,
        "courses": true,
        "blue": true,
        "media": true,
        "exchange": true,
        "relevant": true,
        "balance": true,
        "robert": true,
        "turn": true,
        "slowly": true,
        "close": true,
        "players": true,
        "discussion": true,
        "huge": true,
        "paid": true,
        "letters": true,
        "budget": true,
        "protection": true,
        "collection": true,
        "speech": true,
        "smith": true,
        "born": true,
        "effort": true,
        "attempt": true,
        "nuclear": true,
        "survey": true,
        "failure": true,
        "people": true,
        "ability": true,
        "absence": true,
        "access": true,
        "accident": true,
        "accommodation": true,
        "account": true,
        "acid": true,
        "act": true,
        "action": true,
        "activity": true,
        "adam": true,
        "address": true,
        "administration": true,
        "advance": true,
        "advantage": true,
        "advice": true,
        "afternoon": true,
        "age": true,
        "agency": true,
        "agent": true,
        "agreement": true,
        "aid": true,
        "aim": true,
        "air": true,
        "aircraft": true,
        "alan": true,
        "amount": true,
        "analysis": true,
        "andrew": true,
        "anne": true,
        "answer": true,
        "appeal": true,
        "appearance": true,
        "application": true,
        "appointment": true,
        "approach": true,
        "approval": true,
        "area": true,
        "argument": true,
        "arm": true,
        "army": true,
        "arrival": true,
        "article": true,
        "artist": true,
        "aspect": true,
        "assembly": true,
        "assessment": true,
        "assistance": true,
        "association": true,
        "association": true,
        "attack": true,
        "attempt": true,
        "attention": true,
        "attitude": true,
        "audience": true,
        "author": true,
        "authority": true,
        "award": true,
        "awareness": true,
        "back": true,
        "background": true,
        "bag": true,
        "balance": true,
        "ball": true,
        "band": true,
        "bar": true,
        "base": true,
        "basis": true,
        "battle": true,
        "beauty": true,
        "beginning": true,
        "behaviour": true,
        "belief": true,
        "benefit": true,
        "bill": true,
        "bill": true,
        "bill": true,
        "birth": true,
        "bit": true,
        "block": true,
        "board": true,
        "board": true,
        "bob": true,
        "body": true,
        "book": true,
        "border": true,
        "bottle": true,
        "bottom": true,
        "box": true,
        "boy": true,
        "branch": true,
        "breath": true,
        "brian": true,
        "bridge": true,
        "brother": true,
        "brown": true,
        "budget": true,
        "building": true,
        "business": true,
        "cabinet": true,
        "call": true,
        "campaign": true,
        "candidate": true,
        "capacity": true,
        "capital": true,
        "car": true,
        "card": true,
        "care": true,
        "career": true,
        "case": true,
        "cash": true,
        "cause": true,
        "centre": true,
        "century": true,
        "chain": true,
        "chair": true,
        "chairman": true,
        "challenge": true,
        "chance": true,
        "change": true,
        "chapter": true,
        "character": true,
        "charge": true,
        "charles": true,
        "chest": true,
        "child": true,
        "choice": true,
        "chris": true,
        "city": true,
        "city": true,
        "claim": true,
        "class": true,
        "client": true,
        "club": true,
        "co-operation": true,
        "coast": true,
        "code": true,
        "collection": true,
        "colour": true,
        "combination": true,
        "commission": true,
        "commitment": true,
        "committee": true,
        "communication": true,
        "community": true,
        "company": true,
        "company": true,
        "competition": true,
        "concept": true,
        "concern": true,
        "conclusion": true,
        "condition": true,
        "conference": true,
        "confidence": true,
        "conflict": true,
        "connection": true,
        "consequence": true,
        "consideration": true,
        "constitution": true,
        "construction": true,
        "consumer": true,
        "contact": true,
        "content": true,
        "context": true,
        "contract": true,
        "contrast": true,
        "contribution": true,
        "control": true,
        "convention": true,
        "conversation": true,
        "copy": true,
        "corner": true,
        "corporation": true,
        "cost": true,
        "council": true,
        "country": true,
        "countryside": true,
        "county": true,
        "couple": true,
        "course": true,
        "court": true,
        "cover": true,
        "creation": true,
        "credit": true,
        "crime": true,
        "crisis": true,
        "criticism": true,
        "crowd": true,
        "culture": true,
        "cup": true,
        "curriculum": true,
        "customer": true,
        "dad": true,
        "damage": true,
        "danger": true,
        "darlington": true,
        "data": true,
        "database": true,
        "date": true,
        "date": true,
        "daughter": true,
        "david": true,
        "day": true,
        "de": true,
        "deal": true,
        "death": true,
        "debate": true,
        "debt": true,
        "decade": true,
        "decision": true,
        "decline": true,
        "defence": true,
        "definition": true,
        "degree": true,
        "delivery": true,
        "demand": true,
        "department": true,
        "deputy": true,
        "description": true,
        "design": true,
        "desire": true,
        "desk": true,
        "detail": true,
        "development": true,
        "diet": true,
        "difference": true,
        "difficulty": true,
        "dinner": true,
        "direction": true,
        "director": true,
        "discussion": true,
        "disease": true,
        "display": true,
        "distance": true,
        "distinction": true,
        "distribution": true,
        "district": true,
        "division": true,
        "doctor": true,
        "document": true,
        "dog": true,
        "door": true,
        "doubt": true,
        "dr": true,
        "dream": true,
        "dress": true,
        "drink": true,
        "drive": true,
        "driver": true,
        "drug": true,
        "duty": true,
        "east": true,
        "east": true,
        "ec": true,
        "edge": true,
        "editor": true,
        "education": true,
        "edward": true,
        "effect": true,
        "efficiency": true,
        "effort": true,
        "election": true,
        "element": true,
        "elizabeth": true,
        "emphasis": true,
        "employment": true,
        "end": true,
        "enemy": true,
        "energy": true,
        "engine": true,
        "engineering": true,
        "enterprise": true,
        "entry": true,
        "environment": true,
        "equipment": true,
        "error": true,
        "establishment": true,
        "estate": true,
        "evening": true,
        "event": true,
        "evidence": true,
        "examination": true,
        "example": true,
        "exchange": true,
        "executive": true,
        "exercise": true,
        "exhibition": true,
        "existence": true,
        "expansion": true,
        "expenditure": true,
        "experience": true,
        "explanation": true,
        "expression": true,
        "extension": true,
        "extent": true,
        "eye": true,
        "face": true,
        "fact": true,
        "factor": true,
        "factory": true,
        "failure": true,
        "fall": true,
        "family": true,
        "farm": true,
        "father": true,
        "fault": true,
        "fear": true,
        "feature": true,
        "feeling": true,
        "field": true,
        "fig.": true,
        "figure": true,
        "file": true,
        "film": true,
        "finance": true,
        "fire": true,
        "firm": true,
        "flight": true,
        "floor": true,
        "flow": true,
        "focus": true,
        "food": true,
        "foot": true,
        "force": true,
        "form": true,
        "formation": true,
        "foundation": true,
        "framework": true,
        "frank": true,
        "friend": true,
        "front": true,
        "fuel": true,
        "function": true,
        "fund": true,
        "future": true,
        "game": true,
        "garden": true,
        "gas": true,
        "general": true,
        "generation": true,
        "gentleman": true,
        "george": true,
        "goal": true,
        "graham": true,
        "ground": true,
        "group": true,
        "growth": true,
        "guide": true,
        "hair": true,
        "half": true,
        "hall": true,
        "hand": true,
        "harry": true,
        "head": true,
        "health": true,
        "heart": true,
        "heat": true,
        "height": true,
        "help": true,
        "henry": true,
        "hill": true,
        "history": true,
        "hole": true,
        "holiday": true,
        "home": true,
        "hope": true,
        "horse": true,
        "hospital": true,
        "hotel": true,
        "hour": true,
        "house": true,
        "household": true,
        "housing": true,
        "husband": true,
        "ian": true,
        "identity": true,
        "image": true,
        "impact": true,
        "importance": true,
        "impression": true,
        "improvement": true,
        "income": true,
        "increase": true,
        "independence": true,
        "index": true,
        "individual": true,
        "industry": true,
        "influence": true,
        "information": true,
        "initiative": true,
        "injury": true,
        "inquiry": true,
        "institute": true,
        "insurance": true,
        "intention": true,
        "interest": true,
        "interpretation": true,
        "interview": true,
        "introduction": true,
        "investigation": true,
        "investment": true,
        "involvement": true,
        "island": true,
        "issue": true,
        "item": true,
        "j.": true,
        "jack": true,
        "james": true,
        "jane": true,
        "jim": true,
        "job": true,
        "joe": true,
        "john": true,
        "jones": true,
        "journey": true,
        "judge": true,
        "kind": true,
        "king": true,
        "kingdom": true,
        "knowledge": true,
        "labour": true,
        "labour": true,
        "lack": true,
        "lady": true,
        "land": true,
        "language": true,
        "law": true,
        "lead": true,
        "leader": true,
        "leadership": true,
        "league": true,
        "lee": true,
        "leeds": true,
        "leg": true,
        "legislation": true,
        "length": true,
        "letter": true,
        "level": true,
        "lewis": true,
        "liability": true,
        "licence": true,
        "life": true,
        "lifespan": true,
        "light": true,
        "line": true,
        "link": true,
        "list": true,
        "literature": true,
        "location": true,
        "look": true,
        "lord": true,
        "loss": true,
        "lot": true,
        "lot": true,
        "luke": true,
        "machine": true,
        "magazine": true,
        "maintenance": true,
        "major": true,
        "majority": true,
        "man": true,
        "management": true,
        "manager": true,
        "manner": true,
        "map": true,
        "margaret": true,
        "mark": true,
        "market": true,
        "market": true,
        "martin": true,
        "mary": true,
        "master": true,
        "match": true,
        "material": true,
        "matter": true,
        "meal": true,
        "meaning": true,
        "means": true,
        "measure": true,
        "meeting": true,
        "meeting": true,
        "member": true,
        "membership": true,
        "memory": true,
        "message": true,
        "method": true,
        "michael": true,
        "middle": true,
        "mike": true,
        "mind": true,
        "minister": true,
        "ministry": true,
        "minority": true,
        "minute": true,
        "miss": true,
        "mistake": true,
        "model": true,
        "moment": true,
        "month": true,
        "mother": true,
        "motion": true,
        "motor": true,
        "mountain": true,
        "mouth": true,
        "move": true,
        "movement": true,
        "mr": true,
        "mr.": true,
        "mrs": true,
        "mum": true,
        "name": true,
        "nation": true,
        "need": true,
        "network": true,
        "new": true,
        "nigel": true,
        "night": true,
        "north": true,
        "north": true,
        "northern": true,
        "note": true,
        "notice": true,
        "notion": true,
        "number": true,
        "object": true,
        "occasion": true,
        "offence": true,
        "offer": true,
        "office": true,
        "officer": true,
        "operation": true,
        "opinion": true,
        "opportunity": true,
        "opposition": true,
        "option": true,
        "order": true,
        "organisation": true,
        "organization": true,
        "outcome": true,
        "output": true,
        "owner": true,
        "package": true,
        "page": true,
        "pair": true,
        "panel": true,
        "paper": true,
        "parent": true,
        "parish": true,
        "park": true,
        "part": true,
        "partner": true,
        "party": true,
        "passage": true,
        "past": true,
        "path": true,
        "patient": true,
        "pattern": true,
        "paul": true,
        "pay": true,
        "payment": true,
        "percent": true,
        "performance": true,
        "period": true,
        "person": true,
        "peter": true,
        "phase": true,
        "philip": true,
        "phone": true,
        "picture": true,
        "piece": true,
        "place": true,
        "plan": true,
        "plane": true,
        "planning": true,
        "planning": true,
        "plant": true,
        "play": true,
        "player": true,
        "pleasure": true,
        "point": true,
        "policy": true,
        "population": true,
        "position": true,
        "possibility": true,
        "post": true,
        "pound": true,
        "power": true,
        "practice": true,
        "presence": true,
        "president": true,
        "president": true,
        "press": true,
        "pressure": true,
        "price": true,
        "principle": true,
        "problem": true,
        "procedure": true,
        "process": true,
        "product": true,
        "production": true,
        "profit": true,
        "program": true,
        "programme": true,
        "progress": true,
        "project": true,
        "property": true,
        "proportion": true,
        "proposal": true,
        "protection": true,
        "provision": true,
        "public": true,
        "publication": true,
        "purpose": true,
        "quality": true,
        "quarter": true,
        "question": true,
        "race": true,
        "rail": true,
        "railway": true,
        "range": true,
        "rate": true,
        "reaction": true,
        "reader": true,
        "reality": true,
        "reason": true,
        "recession": true,
        "recognition": true,
        "record": true,
        "recovery": true,
        "reduction": true,
        "ref": true,
        "reference": true,
        "reform": true,
        "regime": true,
        "region": true,
        "relationship": true,
        "release": true,
        "relief": true,
        "report": true,
        "representation": true,
        "reputation": true,
        "request": true,
        "research": true,
        "resistance": true,
        "resolution": true,
        "respect": true,
        "response": true,
        "responsibility": true,
        "rest": true,
        "restaurant": true,
        "result": true,
        "return": true,
        "revenue": true,
        "review": true,
        "richard": true,
        "right": true,
        "ring": true,
        "rise": true,
        "risk": true,
        "river": true,
        "road": true,
        "signal": true,
        "replay": true,
        "robert": true,
        "rock": true,
        "role": true,
        "roof": true,
        "room": true,
        "route": true,
        "row": true,
        "rule": true,
        "run": true,
        "sale": true,
        "sample": true,
        "sarah": true,
        "scale": true,
        "scene": true,
        "scheme": true,
        "school": true,
        "scope": true,
        "screen": true,
        "sea": true,
        "search": true,
        "season": true,
        "seat": true,
        "second": true,
        "section": true,
        "sector": true,
        "security": true,
        "selection": true,
        "self": true,
        "sense": true,
        "sentence": true,
        "sequence": true,
        "series": true,
        "service": true,
        "session": true,
        "set": true,
        "settlement": true,
        "shape": true,
        "share": true,
        "sheet": true,
        "ship": true,
        "shock": true,
        "shop": true,
        "show": true,
        "side": true,
        "sight": true,
        "sign": true,
        "significance": true,
        "silence": true,
        "simon": true,
        "sir": true,
        "sir": true,
        "site": true,
        "situation": true,
        "size": true,
        "skin": true,
        "sky": true,
        "smile": true,
        "smith": true,
        "solution": true,
        "son": true,
        "song": true,
        "sort": true,
        "sound": true,
        "source": true,
        "south": true,
        "south": true,
        "soviet": true,
        "space": true,
        "spain": true,
        "speaker": true,
        "species": true,
        "speech": true,
        "speed": true,
        "spirit": true,
        "spokesman": true,
        "sport": true,
        "spot": true,
        "spring": true,
        "st": true,
        "staff": true,
        "stage": true,
        "standard": true,
        "star": true,
        "start": true,
        "state": true,
        "statement": true,
        "states": true,
        "station": true,
        "status": true,
        "step": true,
        "stephen": true,
        "steve": true,
        "stock": true,
        "stone": true,
        "store": true,
        "story": true,
        "strategy": true,
        "street": true,
        "street": true,
        "strength": true,
        "structure": true,
        "struggle": true,
        "student": true,
        "studio": true,
        "study": true,
        "stuff": true,
        "style": true,
        "subject": true,
        "success": true,
        "sum": true,
        "summer": true,
        "sun": true,
        "supply": true,
        "support": true,
        "support": true,
        "surface": true,
        "surprise": true,
        "survey": true,
        "system": true,
        "table": true,
        "talk": true,
        "tape": true,
        "target": true,
        "task": true,
        "taste": true,
        "taylor": true,
        "teacher": true,
        "team": true,
        "technique": true,
        "temperature": true,
        "term": true,
        "test": true,
        "text": true,
        "theme": true,
        "theory": true,
        "thing": true,
        "thomas": true,
        "thought": true,
        "threat": true,
        "tim": true,
        "title": true,
        "tom": true,
        "tone": true,
        "tony": true,
        "top": true,
        "total": true,
        "touch": true,
        "tour": true,
        "town": true,
        "track": true,
        "trade": true,
        "tradition": true,
        "traffic": true,
        "train": true,
        "training": true,
        "transfer": true,
        "transport": true,
        "treatment": true,
        "treaty": true,
        "tree": true,
        "trial": true,
        "trip": true,
        "trouble": true,
        "trust": true,
        "truth": true,
        "turn": true,
        "tv": true,
        "type": true,
        "un": true,
        "understanding": true,
        "unemployment": true,
        "union": true,
        "unit": true,
        "united": true,
        "university": true,
        "us": true,
        "use": true,
        "use": true,
        "user": true,
        "value": true,
        "variety": true,
        "vehicle": true,
        "version": true,
        "victim": true,
        "victory": true,
        "video": true,
        "view": true,
        "village": true,
        "violence": true,
        "vision": true,
        "visit": true,
        "voice": true,
        "volume": true,
        "vote": true,
        "wall": true,
        "way": true,
        "wealth": true,
        "weather": true,
        "week": true,
        "weekend": true,
        "weight": true,
        "welfare": true,
        "west": true,
        "west": true,
        "while": true,
        "white": true,
        "whole": true,
        "wife": true,
        "will": true,
        "william": true,
        "wilson": true,
        "wind": true,
        "window": true,
        "wood": true,
        "word": true,
        "work": true,
        "worker": true,
        "works": true,
        "world": true,
        "writer": true,
        "writing": true,
        "year": true,
        "youth": true,

        "monday": true,
        "tuesday": true,
        "wednesday": true,
        "thursday": true,
        "friday": true,
        "saturday": true,
        "sunday": true,
        "jan": true,
        "feb": true,
        "mar": true,
        "apr": true,
        "may": true,
        "june": true,
        "july": true,
        "aug": true,
        "sept": true,
        "oct": true,
        "nov": true,
        "dec": true,
        "january": true,
        "february": true,
        "march": true,
        "april": true,
        "august": true,
        "september": true,
        "october": true,
        "novermber": true,
        "december": true
    }


    //remove objects with a duplicate field from json, and count them
        function boost_dupes(a, field) {
            var r = new Array();
            o: for (var i = 0, n = a.length; i < n; i++) {
                a[i].count = 1;
                for (var x = 0, y = r.length; x < y; x++) {
                    if (r[x][field] == a[i][field]) {
                        r[x].count += 1;
                        continue o;
                    }
                }
                r[r.length] = a[i];
            }
            return r;
        }


        //sort out the good candidate topics before search
        function preprocess(results) {
            //trim whitespace
            for (var i in results) {
                results[i].word = results[i].word.replace(/^\s+|\s+$/g, '');
            }
            results = boost_dupes(results, 'word')
            return results
        }


        function endsWith(word, string) {
            if (!string || !word || string.length > word.length)
                return false;
            return word.indexOf(string) == word.length - string.length;
        }

    var notends = {
        "the": true,
        "los": true,
        "les": true,
        "san": true,
        "dr": true,
        "they": true,
        "he": true,
        "she": true,
        "a": true,
        "his": true,
        "an": true,
        "their": true,
        "its": true,
        "it's": true,
        "my": true,
        "your": true,
        "or": true,
        "if": true,
        "therefor": true,
        "therefore": true,
    };


    var dateword = [
        "july",
        "august",
        "september",
        "october",
        "november",
        "december",
        "january",
        "february",
        "march",
        "april",
        "may",
        "june",
        "monday",
        "tuesday",
        "wednesday",
        "thursday",
        "friday",
        "saturday",
        "sunday"
    ]

    var chunker = (function() {

        //merge word-tokens based on their grammar. forms a more maturely tokenized pos tag object.
        var chunker = function(data, options) {
            //some grammatical chunking..
            for (var i in data) {
                i = parseInt(i);
                //add an implicit preposition to possessive nouns
                if (data[i].pos.tag == "NNO") {
                    data = build(data.slice(0, i + 1), {
                        word: "",
                        pos: parts_of_speech["IN"]
                    }, data.slice(i + 1, data.length));
                }
                //sticky prepositions on gerunds  - waking up in..
                if (data[i].pos.tag == "VBG" && data[i + 2]) {
                    if (data[i + 1].pos.tag == "IN" && data[i + 2].pos.parent == "glue") {
                        data[i].word += ' ' + data[i + 1].word;
                        data[i + 1].word = null;
                        continue
                    }
                }
                //sticky prepositions on gerunds at end of phrase
                if (data[i].pos.tag == "VBG") {
                    if (data[i + 1] && data[i + 2] == null && data[i + 1].pos.tag == "IN") {
                        data[i].word += ' ' + data[i + 1].word;
                        data[i + 1].word = null;
                    }
                }
            }

            //make gerunds into a 'noun-gerund'
            if (options.gerund) {
                for (var i in data) {
                    if (data[i].pos.tag == "VBG") {
                        data[i].pos = parts_of_speech["NG"];
                    }
                }
            }

            //chunk same consecutive parents
            var chunked = [data[0]];
            for (var i = 1; i <= data.length - 1; i++) {
                if (chunked[chunked.length - 1].pos.parent == data[i].pos.parent) {
                    if (chunked[chunked.length - 1].word && !chunked[chunked.length - 1].word.match(/(,|")/)) { //dont chunk nouns with comma
                        chunked[chunked.length - 1].word += ' ' + data[i].word;
                        continue;
                    }
                }
                //implicit else
                chunked.push(data[i]);
            }

            return chunked;
        }


        //make a json

            function build(before, obj, after) {
                var all = before;
                all.push(obj);
                for (var i in after) {
                    all.push(after[i])
                }
                return all;
            }


        return chunker;


    })()



    //various sanitychecks
    var pass = function(gram) {
        if (!gram) {
            return false;
        }

        //length constraints
        if (gram.length < 3) {
            return false;
        }
        if (gram.length > 50) {
            return false;
        }

        //appropriate word-sizes
        var word = gram.match(/[a-z|_]*/i)[0]
        if (!word || word.length > 25) {
            return false;
        }
        if (!gram.match(/[a-z]{3}/i)) {
            return false
        }


        //stopwords
        gram = gram.toLowerCase();
        if (silly[gram]) {
            return false
        }
        //silly endings
        for (var i in notends) {
            i = ' ' + i;
            if (endsWith(gram, i)) {
                return false
            }
        }
        //ban dates
        for (var i in dateword) {
            if (gram.match(dateword[i])) {
                var reg = new RegExp('^[0-9]{1,4},? ' + dateword[i]);
                var reg1 = new RegExp(dateword[i] + ',? [0-9]{1,4}$');
                if (gram.match(reg) || gram.match(reg1)) {
                    return false;
                }
            }
        }
        //ban numerical words
        if (gram.match(/^[0-9]{1,4}(th|st|rd)$/)) {
            return false
        }
        //punctuation
        if (gram.match(/(\[|\]|\{|\}|\||_|;|\)|\(|\\|\>|\<|\+|\=|\")/)) {
            return false
        }
        //no vowel
        if (!gram.match(/(a|e|i|o|u)/)) {
            return false
        }

        return true;
    }



    var recognizer = (function() {

        //takes a pos tagged object and grabs the nouns for named-entity spotting
        var recognizer = function(tags, options) {

            if (!options) {
                options = {};
            }
            if (options.verbose) {
                options.gerund = true;
                options.stick_adjectives = true;
                options.stick_prepositions = true;
                options.stick_the = true;
                options.subnouns = true;
                options.match_whole = true;
            }

            //collect noun chunks
            var nouns = tags.filter(function(tag) {
                return tag.pos.parent == "noun";
            });

            // optionally treat 'ing' verbs as nouns
            if (options.gerund) {
                for (var i in tags) {
                    if (tags[i].pos.tag == "VBG") {
                        //    nouns.push({word:tags[i].word, pos:parts_of_speech["NN"], rule:"gerund"});
                    }
                }
            }

            //'obama health care' break noun-phrase into chunks
            if (options.subnouns) {
                for (var i in nouns) {
                    if (nouns[i].word.match(' ')) {
                        var ngrams = ngram(nouns[i].word.replace(/^(the|an?|dr\.|mrs?\.|sir) /i, '').split(' '), 1, 4);
                        for (var n in ngrams) {
                            nouns.push({
                                word: ngrams[n],
                                pos: parts_of_speech["NN"],
                                rule: "subnoun"
                            });
                        }
                    }
                }
            }

            // optionally treat 'the' as part of a noun
            if (options.stick_the) {
                for (var i in tags) {
                    i = parseInt(i);
                    if (tags[i].word == "the" && tags[i + 1] && tags[i + 1].pos.parent == "noun" && isplural(tags[i + 1].word)) {
                        nouns.push({
                            word: tags[i].word + ' ' + tags[i + 1].word,
                            pos: parts_of_speech["NN"],
                            rule: "sticky_the"
                        });
                    }
                }
            }

            //add sticky adjectives to results - black swan
            if (options.stick_adjectives) {
                //adjective - noun
                for (var i in tags) {
                    i = parseInt(i);
                    if (!tags[i].word) {
                        continue;
                    }
                    if (tags[i + 1] && tags[i].pos.parent == "adjective" && tags[i + 1].pos.parent == "noun") {
                        var word = tags[i].word + ' ' + tags[i + 1].word;
                        nouns.push({
                            word: word,
                            pos: parts_of_speech["NN"],
                            rule: "sticky_adj"
                        });
                    }
                }
                //noun - adjective
                for (var i in tags) {
                    i = parseInt(i);
                    if (!tags[i].word) {
                        continue;
                    }
                    if (tags[i + 1] && tags[i].pos.parent == "noun" && tags[i + 1].pos.parent == "adjective") {
                        var word = tags[i].word + ' ' + tags[i + 1].word;
                        nouns.push({
                            word: word,
                            pos: parts_of_speech["NN"],
                            rule: "sticky_after_adj"
                        });
                    }
                }
            }

            //add [noun phrase] and [noun phrase] - marks and spencers
            if (options.stick_prepositions) {
                var words = tags.map(function(t) {
                    return t.word
                })
                for (var i in tags) {
                    i = parseInt(i);
                    if (!tags[i].word) {
                        continue;
                    }
                    if (tags[i - 1] && tags[i + 1] && (tags[i].pos.tag == "CC" || tags[i].pos.tag == "IN")) { //&& tags[i-1].pos.parent=="noun"
                        for (var o = i; o < tags.length; o++) {
                            if (tags[o].pos.parent == "verb" || tags[o].word.match(/\W/)) {
                                break
                            }
                            if (tags[o].pos.parent == "noun") {
                                var word = words.slice(i - 1, parseInt(o) + 1).join(" ");
                                nouns.push({
                                    word: word,
                                    pos: parts_of_speech["NN"],
                                    rule: "group_prep"
                                });
                            }
                        }
                    }
                }
            }

            //search the whole string
            if (options.match_whole) {
                var text = tags.map(function(t) {
                    return t.word
                }).join(' ')
                nouns.push({
                    word: text,
                    pos: parts_of_speech["NN"],
                    rule: "whole"
                });
            }

            //remove number tokes
            if (options.kill_numbers) {
                nouns = nouns.filter(function(noun) {
                    return !noun.word.match(/([0-9]| \- )/)
                })
            }

            return nouns;
        }

            function isplural(word) {
                if (word.match(/.{3}(s|ice|eece)$/)) {
                    return true;
                } //hack but its ok
                return false;
            }


            //list all inline combinations for array element joins

            function ngram(arr, minwords, maxwords) {
                var keys = [, ];
                var results = [];
                maxwords++; //for human logic, we start counting at 1 instead of 0
                for (var i = 1; i <= maxwords; i++) {
                    keys.push({});
                }
                for (var i = 0, arrlen = arr.length, s; i < arrlen; i++) {
                    s = arr[i];
                    keys[1][s] = (keys[1][s] || 0) + 1;
                    for (var j = 2; j <= maxwords; j++) {
                        if (i + j <= arrlen) {
                            s += " " + arr[i + j - 1];
                            keys[j][s] = (keys[j][s] || 0) + 1;
                        } else break;
                    }
                }
                //collect results
                for (var k = 0; k < maxwords; k++) {
                    var key = keys[k];
                    for (var i in key) {
                        if (key[i] >= minwords) results.push(i);
                    }
                }
                return results
            }


        return recognizer;


    })()



        function set_options(options) {
            if (!options) {
                options = {};
            }
            if (options.verbose) {
                options.gerund = true;
                options.stick_adjectives = true;
                options.stick_prepositions = true;
                options.stick_the = true;
                options.want_quotations = true;
                options.subnouns = true;
                options.match_whole = true;
                options.case_sensitive = false;
                options.kill_numbers = false;
                options.kill_quotes = false;
            }
            if (options.big) {
                options.gerund = false;
                options.stick_adjectives = false;
                options.stick_prepositions = false;
                options.stick_the = false;
                options.subnouns = false;
                options.want_quotations = true;
                options.match_whole = false;
                options.kill_numbers = true;
                options.kill_quotes = true;
            }
            return options;
        }


        function flatten(arr) {
            return arr.reduce(function(a, b) {
                return a.concat(b);
            });
        }

        function isarray(x) {
            return Object.prototype.toString.call(x) === '[object Array]'
        }


    var main = function(tags, options) {

        if (!tags || !tags[0]) {
            return []
        }
        //ensure it is an array of arrays, for sentence support
        if (!isarray(tags[0])) {
            tags = [tags]
        }

        options = set_options(options);

        //chunk together meaningfully
        var nouns = [];
        for (var i in tags) {
            var chunks = chunker(tags[i], options);
            //collect named entities
            nouns.push(recognizer(chunks, options));
        }
        //flatten sentences
        nouns = flatten(nouns)

        //inflect, clean-up
        for (var i in nouns) {
            nouns[i].word = nouns[i].word.replace(/("|,|\)|\(|!)/g, '') //punctuation we want to keep
            nouns[i].word = nouns[i].word.replace(/'s$/, '');
            nouns[i].word = nouns[i].word.replace(/[\.\?,!:;\/\)]*$/, '');
            nouns[i].word = nouns[i].word.replace(/^[\(\/]*/g, '');
            nouns[i].word = nouns[i].word.replace(/[\(\/\)\\;:,]/g, ' ');
            nouns[i].word = nouns[i].word.replace(/  /g, ' ');
            nouns[i].word = nouns[i].word.replace(/\W*$/, ''); //punctuation
            nouns[i].word = nouns[i].word.replace(/^\W*/, '');
            if (!nouns[i].word.match(/^the ./)) {
                // nouns[i].word = singularize(nouns[i].word);
            }
            if (!options.case_sensitive) {
                nouns[i].word = nouns[i].word.toLowerCase();
            }
        }
        //pass the blacklist test
        var results = nouns.filter(function(noun) {
            return pass(noun.word)
        });
        results = preprocess(results);
        //rank results
        results = rank(results)
        return results;
    }

    var rank = function(results) {
        //rank results
        for (var i in results) {
            results[i].score = 0;
            results[i].score += results[i].count * 10;
            if (results[i].rule == "capital") {
                results[i].score += 10;
            }
            if (results[i].rule == "lexicon") {
                results[i].score += 7;
            }
            if (results[i].rule == "group_prep") {
                results[i].score -= 4;
            }
        }
        //results=results.sort(function(a,b){return b.score-a.score;})
        return results;
    }


    if (typeof module !== "undefined" && module.exports) {
        module.exports = main;
    }

    return main
})()