//from wikipedia's {{infobox currency}}, Dec 2020
module.exports = [
  {
    title: 'Greek drachma',
    iso: 'GRD',
    subUnit: 'leptοn',
    symbols: ['Δρχ.', 'Δρ.', '₯'],
  },
  { title: 'Euro', iso: 'EUR', subUnit: 'cent', symbols: ['€'] },
  {
    title: 'European Currency Unit',
    iso: 'XEU',
    symbols: ['₠'],
  },
  {
    title: 'Eastern Caribbean dollar',
    iso: 'XCD',
    subUnit: 'cent',
    symbols: ['$'],
  },
  { title: 'Swedish krona', iso: 'SEK', subUnit: 'öre', symbols: ['kr'] },
  {
    title: 'Finnish markka',
    iso: 'FIM',
    subUnit: 'penni',
    symbols: ['mk'],
  },
  {
    title: 'Special drawing rights',
    iso: 'XDR',
    symbols: ['SDR'],
  },
  { title: 'UIC franc', iso: 'XFU' },
  {
    title: 'Unidad de Valor Constante',
    iso: 'ECV',
  },
  {
    title: 'Japanese yen',
    iso: 'JPY',
    subUnit: 'sen',
    symbols: ['¥', '円', '圓'],
  },
  {
    title: 'Zambian kwacha',
    iso: 'ZMW',
    subUnit: 'ngwee',
    symbols: ['K'],
  },
  {
    title: 'Malawian kwacha',
    iso: 'MWK',
    subUnit: 'tambala',
    symbols: ['K'],
  },
  { title: 'Polish złoty', iso: 'PLN', subUnit: 'Grosz', symbols: ['zł'] },
  {
    title: 'Slovenian tolar',
    iso: 'SIT',
    subUnit: 'stotin',
  },
  {
    title: 'Norwegian krone',
    iso: 'NOK',
    subUnit: 'øre',
    symbols: ['kr'],
  },
  {
    title: 'Renminbi',
    iso: 'CNY',
    subUnit: 'yuán (元)',
    symbols: ['元', '¥'],
  },
  {
    title: 'Australian dollar',
    iso: 'AUD',
    subUnit: 'cent',
    symbols: ['$', 'A$', 'AU$'],
  },
  {
    title: 'Deutsche Mark',
    iso: 'DEM',
    subUnit: 'Pfennig',
    symbols: ['DM'],
  },
  { title: 'Thai baht', iso: 'THB', subUnit: 'satang', symbols: ['฿'] },
  {
    title: 'Canadian dollar',
    iso: 'CAD',
    subUnit: 'cent',
    symbols: ['$', 'Can$', 'C$', 'CA$', 'CAD'],
  },
  { title: 'Icelandic króna', iso: 'ISK', symbols: ['kr'] },
  {
    title: 'Mexican peso',
    iso: 'MXN',
    subUnit: 'centavo',
    symbols: ['$', 'Mex$'],
  },
  {
    title: 'Spanish peseta',
    iso: 'ESP',
    subUnit: 'céntimo (cent)',
    symbols: ['Pta'],
  },
  {
    title: 'New Zealand dollar',
    iso: 'NZD',
    subUnit: 'cent',
    symbols: ['$', 'NZ$'],
  },
  {
    title: 'Chilean peso',
    iso: 'CLP',
    subUnit: 'Centavo',
    symbols: ['Cifrão', '$'],
  },
  { title: 'Nigerian naira', iso: 'NGN', subUnit: 'kobo', symbols: ['₦'] },
  {
    title: 'Austrian schilling',
    iso: 'ATS',
    subUnit: 'groschen',
    symbols: ['S', 'öS'],
  },
  {
    title: 'Afghan afghani',
    iso: 'AFN',
    subUnit: 'pul',
    symbols: ['؋', 'Af', 'Afs'],
  },
  {
    title: 'Estonian kroon',
    iso: 'EEK',
    subUnit: 'sent',
    symbols: ['kr'],
  },
  {
    title: 'Guatemalan quetzal',
    iso: 'GTQ',
    subUnit: 'centavo',
    symbols: ['Q'],
  },
  {
    title: 'Philippine peso',
    iso: 'PHP',
    subUnit: 'Sentimo or centavo',
    symbols: ['₱'],
  },
  {
    title: 'Hungarian forint',
    iso: 'HUF',
    subUnit: 'fillér',
    symbols: ['Ft'],
  },
  {
    title: 'Russian ruble',
    iso: 'RUB',
    subUnit: 'kopeyka (копейка)',
    symbols: ['₽', 'руб', 'р.'],
  },
  {
    title: 'Kuwaiti dinar',
    iso: 'KWD',
    subUnit: 'fils',
    symbols: ['د.ك', 'KD'],
  },
  { title: 'Danish krone', iso: 'DKK', subUnit: 'øre', symbols: ['kr.'] },
  {
    title: 'Israeli new shekel',
    iso: 'ILS',
    subUnit: 'agora',
    symbols: ['₪'],
  },
  {
    title: 'Latvian lats',
    iso: 'LVL',
    subUnit: 'santīms',
    symbols: ['Ls'],
  },
  {
    title: 'Kazakhstani tenge',
    iso: 'KZT',
    subUnit: 'tıyn (тиын)',
    symbols: ['₸'],
  },
  { title: 'Iraqi dinar', iso: 'IQD', subUnit: 'fils', symbols: ['د.ع'] },
  {
    title: 'Bahamian dollar',
    iso: 'BSD',
    subUnit: 'cent',
    symbols: ['$', 'B$'],
  },
  {
    title: 'Seychellois rupee',
    iso: 'SCR',
    subUnit: 'cent',
    symbols: ['SCR', 'SR'],
  },
  {
    title: 'Albanian lek',
    iso: 'ALL',
    subUnit: 'qindarkë',
    symbols: ['L'],
  },
  {
    title: 'Bulgarian lev',
    iso: 'BGN',
    subUnit: 'stotinka',
    symbols: ['лв.'],
  },
  {
    title: 'Pound sterling',
    iso: 'GBP',
    subUnit: 'Penny',
    symbols: ['£'],
  },
  {
    title: 'Irish pound',
    iso: 'IEP',

    symbols: ['£', 'IR£'],
  },
  { title: 'Korean won', subUnit: 'chon (錢)' },
  { title: 'CFP franc', iso: 'XPF', symbols: ['F'] },
  {
    title: 'South African rand',
    iso: 'ZAR',
    subUnit: 'Cent',
    symbols: ['R'],
  },
  {
    title: 'North Korean won',
    iso: 'KPW',
    subUnit: 'chon',
    symbols: ['₩'],
  },
  {
    title: 'South Korean won',
    iso: 'KRW',
    subUnit: 'jeon',
    symbols: ['₩'],
  },
  {
    title: 'Portuguese escudo',
    iso: 'PTE',
    subUnit: 'centavo',
  },
  {
    title: 'Ghanaian cedi',
    iso: 'GHS',
    subUnit: 'pesewa',
    symbols: ['GH₵'],
  },
  {
    title: 'Hong Kong dollar',
    iso: 'HKD',
    subUnit: '毫',
    symbols: ['$'],
  },
  {
    title: 'New Taiwan dollar',
    iso: 'TWD',
    subUnit: 'dime',
    symbols: ['NT$'],
  },
  {
    title: 'Scandinavian Monetary Union',
    subUnit: 'øre',
    symbols: ['kr.'],
  },
  {
    title: 'East German mark',
    iso: 'DDM',
    subUnit: 'Pfennig',
    symbols: ['M'],
  },
  {
    title: 'Namibian dollar',
    iso: 'NAD',
    subUnit: 'cent',
    symbols: ['$'],
  },
  {
    title: 'Malaysian ringgit',
    iso: 'MYR',
    subUnit: 'sen',
    symbols: ['RM'],
  },
  {
    title: 'Swiss franc',
    iso: 'CHF',

    symbols: ['Rp.'],
  },
  {
    title: 'Panamanian balboa',
    iso: 'PAB',
    subUnit: 'Centésimo',
    symbols: ['B/.'],
  },
  {
    title: 'Indonesian rupiah',
    iso: 'IDR',
    subUnit: 'sen (obsolete)a',
    symbols: ['Rp'],
  },
  {
    title: 'Brunei dollar',
    iso: 'BND',
    subUnit: 'sen',
    symbols: ['$', 'B$'],
  },
  {
    title: 'Venezuelan bolívar',
    iso: 'VEF',
    subUnit: 'céntimo',
    symbols: ['Bs.F', 'Bs.'],
  },
  {
    title: 'Macedonian denar',
    iso: 'MKD',
    subUnit: 'deni',
    symbols: ['den'],
  },
  {
    title: 'Mauritanian ouguiya',
    iso: 'MRU',
    subUnit: 'khoums',
    symbols: ['UM'],
  },
  {
    title: 'Argentine peso',
    iso: 'ARS',
    subUnit: 'centavo',
    symbols: ['$'],
  },
  {
    title: 'Libyan dinar',
    iso: 'LYD',
    subUnit: 'dirham',
    symbols: ['LD', 'ل.د'],
  },
  {
    title: 'Jordanian dinar',
    iso: 'JOD',
    subUnit: 'dirham',
    symbols: ['د.أ'],
  },
  {
    title: 'French franc',
    iso: 'FRF',
    subUnit: 'centime',
    symbols: ['F', 'Fr', 'FF', '₣'],
  },
  {
    title: 'Syrian pound',
    iso: 'SYP',
    subUnit: 'piastre',
    symbols: ['LS', '£S'],
  },
  { title: 'Belize dollar', iso: 'BZD', subUnit: 'cent', symbols: ['$'] },
  {
    title: 'Saudi riyal',
    iso: 'SAR',
    subUnit: 'halalah',
    symbols: ['SAR', 'ر.س', ' ﷼'],
  },
  {
    title: 'Surinamese dollar',
    iso: 'SRD',
    subUnit: 'cent',
    symbols: ['$'],
  },
  {
    title: 'Singapore dollar',
    iso: 'SGD',
    subUnit: 'cent',
    symbols: ['S$', '$'],
  },
  {
    title: 'Nepalese rupee',
    iso: 'NPR',
    subUnit: 'Paisa',
    symbols: ['रु ₨', 'Re'],
  },
  {
    title: 'Macanese pataca',
    iso: 'MOP',
    subUnit: 'ho',
    symbols: ['MOP$'],
  },
  {
    title: 'Nicaraguan córdoba',
    iso: 'NIO',
    subUnit: 'centavo',
    symbols: ['C$'],
  },
  {
    title: 'Bangladeshi taka',
    iso: 'BDT',
    subUnit: 'poysha',
    symbols: ['৳'],
  },
  {
    title: 'Indian rupee',
    iso: 'INR',
    subUnit: 'paisa',
    symbols: ['₹'],
  },
  {
    title: 'Maldivian rufiyaa',
    iso: 'MVR',
    subUnit: 'laari',
    symbols: ['Rf', 'MRf', 'MVR', '.ރ '],
  },
  {
    title: 'Sri Lankan rupee',
    iso: 'LKR',
    subUnit: 'Cents',
    symbols: ['Rs', 'රු', 'ரூ'],
  },
  {
    title: 'Bhutanese ngultrum',
    iso: 'BTN',
    subUnit: 'chhertum',
    symbols: ['Nu.'],
  },
  {
    title: 'Revaluation of the Turkish lira',
    iso: 'TRY',
    subUnit: 'new kuruş',
    symbols: ['YTL'],
  },
  {
    title: 'Serbian dinar',
    iso: 'RSD',
    subUnit: 'para / пара (defunct)',
    symbols: ['din', 'дин'],
  },
  {
    title: 'Bosnia and Herzegovina convertible mark',
    iso: 'BAM',
    subUnit: 'Fening/Pfenig',
    symbols: ['KM'],
  },
  { title: 'Botswana pula', iso: 'BWP', subUnit: 'Thebe', symbols: ['P'] },
  {
    title: 'Swazi lilangeni',
    iso: 'SZL',
    subUnit: 'cent',
    symbols: ['L', 'E'],
  },
  {
    title: 'Lithuanian litas',
    iso: 'LTL',
    subUnit: 'centas',
    symbols: ['Lt', 'ct'],
  },
  {
    title: 'Mauritian rupee',
    iso: 'MUR',
    subUnit: 'cent',
    symbols: ['₨'],
  },
  {
    title: 'Pakistani rupee',
    iso: 'PKR',
    subUnit: 'Paisa',
    symbols: ['₨'],
  },
  {
    title: 'Maltese lira',
    iso: 'MTL',
    subUnit: 'cent',
    symbols: ['₤', 'Lm'],
  },
  {
    title: 'Ecuadorian sucre',
    iso: 'ECS',
    subUnit: 'centavo',
    symbols: ['S/.'],
  },
  {
    title: 'Sierra Leonean leone',
    iso: 'SLL',
    subUnit: 'cent',
    symbols: ['Le'],
  },
  { title: 'Cypriot pound', iso: 'CYP', subUnit: 'cent', symbols: ['£'] },
  { title: 'Moldovan leu', iso: 'MDL', subUnit: 'ban', symbols: ['L'] },
  { title: 'Croatian kuna', iso: 'HRK', subUnit: 'lipa', symbols: ['kn'] },
]
