//from wikipedia's {{infobox currency}}, Dec 2020
module.exports = [
  {
    title: 'Greek drachma',
    iso: 'GRD',
    subUnit: 'leptοn (Λ.)',
    symbol: 'Δρχ., Δρ. or ₯',
  },
  { title: 'Euro', iso: 'EUR', subUnit: 'cent', symbol: '€' },
  {
    title: 'European Currency Unit',
    iso: 'XEU',

    symbol: '₠',
  },
  {
    title: 'Eastern Caribbean dollar',
    iso: 'XCD',
    subUnit: 'cent',
    symbol: '$',
  },
  { title: 'Ithaca Hours' },
  { title: 'Swedish krona', iso: 'SEK', subUnit: 'öre', symbol: 'kr' },
  {
    title: 'Finnish markka',
    iso: 'FIM',
    subUnit: 'penni',
    symbol: 'mk',
  },
  {
    title: 'Special drawing rights',
    iso: 'XDR',

    symbol: 'SDR',
  },
  { title: 'UIC franc', iso: 'XFU' },
  {
    title: 'Unidad de Valor Constante',
    iso: 'ECV',
  },
  {
    title: 'Japanese yen',
    iso: 'JPY',
    subUnit: 'sen (錢 or 銭)',
    symbol: '¥ (international) 円 (Japan—present day) 圓 (Japan—traditional)',
  },
  {
    title: 'Zambian kwacha',
    iso: 'ZMW ZMK until December 31, 2012',
    subUnit: 'ngwee',
    symbol: 'K',
  },
  {
    title: 'Malawian kwacha',
    iso: 'MWK',
    subUnit: 'tambala',
    symbol: 'K',
  },
  { title: 'Polish złoty', iso: 'PLN', subUnit: 'Grosz', symbol: 'zł' },
  {
    title: 'Slovenian tolar',
    iso: 'SIT',
    subUnit: 'stotin',
  },
  {
    title: 'Norwegian krone',
    iso: 'NOK',
    subUnit: 'øre',
    symbol: 'kr',
  },
  {
    title: 'Renminbi',
    iso: 'CNY',
    subUnit: 'yuán (元)',
    symbol: '元 / ¥',
  },
  {
    title: 'Australian dollar',
    iso: 'AUD',
    subUnit: 'cent',
    symbol: '$, A$, AU$',
  },
  {
    title: 'Deutsche Mark',
    iso: 'DEM',
    subUnit: 'Pfennig',
    symbol: 'DM',
  },
  { title: 'Thai baht', iso: 'THB', subUnit: 'satang', symbol: '฿' },
  {
    title: 'Canadian dollar',
    iso: 'CAD',
    subUnit: 'cent',
    symbol: '$, Can$, C$, CA$ or CAD',
  },
  { title: 'Icelandic króna', iso: 'ISK', symbol: 'kr' },
  {
    title: 'Mexican peso',
    iso: 'MXN',
    subUnit: 'centavo',
    symbol: '$ or Mex$',
  },
  {
    title: 'Spanish peseta',
    iso: 'ESP',
    subUnit: 'céntimo (cent)',
    symbol: 'Pta',
  },
  {
    title: 'New Zealand dollar',
    iso: 'NZD',
    subUnit: 'cent',
    symbol: '$, NZ$',
  },
  {
    title: 'Chilean peso',
    iso: 'CLP',
    subUnit: 'Centavo',
    symbol: 'Cifrão symbol.svg or $',
  },
  { title: 'Nigerian naira', iso: 'NGN', subUnit: 'kobo', symbol: '₦' },
  {
    title: 'Austrian schilling',
    iso: 'ATS',
    subUnit: 'groschen',
    symbol: 'S or öS',
  },
  {
    title: 'Afghan afghani',
    iso: 'AFN',
    subUnit: 'pul',
    symbol: '؋ (U+060B) or Af (singular) and Afs (plural)',
  },
  {
    title: 'Estonian kroon',
    iso: 'EEK',
    subUnit: 'sent',
    symbol: 'kr',
  },
  {
    title: 'Guatemalan quetzal',
    iso: 'GTQ',
    subUnit: 'centavo',
    symbol: 'Q',
  },
  {
    title: 'Philippine peso',
    iso: 'PHP',
    subUnit: 'Sentimo or centavo',
    symbol: '₱',
  },
  {
    title: 'Hungarian forint',
    iso: 'HUF',
    subUnit: 'fillér',
    symbol: 'Ft',
  },
  {
    title: 'Russian ruble',
    iso: 'RUB',
    subUnit: 'kopeyka (копейка)',
    symbol: '₽, руб / р. (colloquially)',
  },
  {
    title: 'Kuwaiti dinar',
    iso: 'KWD',
    subUnit: 'fils',
    symbol: 'د.ك or KD',
  },
  { title: 'Danish krone', iso: 'DKK', subUnit: 'øre', symbol: 'kr.' },
  {
    title: 'Israeli new shekel',
    iso: 'ILS',
    subUnit: 'agora',
    symbol: '₪',
  },
  {
    title: 'Latvian lats',
    iso: 'LVL',
    subUnit: 'santīms',
    symbol: 'Ls (before numerals)',
  },
  {
    title: 'Kazakhstani tenge',
    iso: 'KZT',
    subUnit: 'tıyn (тиын)',
    symbol: '₸',
  },
  { title: 'Iraqi dinar', iso: 'IQD', subUnit: 'fils', symbol: 'د.ع' },
  {
    title: 'Bahamian dollar',
    iso: 'BSD',
    subUnit: 'cent',
    symbol: '$, B$',
  },
  {
    title: 'Seychellois rupee',
    iso: 'SCR',
    subUnit: 'cent',
    symbol: 'SCR or SR',
  },
  {
    title: 'Albanian lek',
    iso: 'ALL',
    subUnit: 'qindarkë',
    symbol: 'L',
  },
  {
    title: 'Bulgarian lev',
    iso: 'BGN',
    subUnit: 'stotinka',
    symbol: 'лв.',
  },
  {
    title: 'Pound sterling',
    iso: 'GBP',
    subUnit: 'Penny',
    symbol: '£',
  },
  {
    title: 'Irish pound',
    iso: 'IEP',

    symbol: '£\n(or IR£ to distinguish from other pounds)',
  },
  { title: 'Korean won', subUnit: 'chon (錢)' },
  { title: 'CFP franc', iso: 'XPF', symbol: 'F' },
  {
    title: 'South African rand',
    iso: 'ZAR',
    subUnit: 'Cent',
    symbol: 'R',
  },
  {
    title: 'North Korean won',
    iso: 'KPW',
    subUnit: 'chon (전/錢)',
    symbol: '₩',
  },
  {
    title: 'South Korean won',
    iso: 'KRW',
    subUnit: 'jeon (전/錢)',
    symbol: '₩',
  },
  {
    title: 'Portuguese escudo',
    iso: 'PTE',
    subUnit: 'centavo',
  },
  {
    title: 'Ghanaian cedi',
    iso: 'GHS',
    subUnit: 'pesewa',
    symbol: 'GH₵',
  },
  {
    title: 'Hong Kong dollar',
    iso: 'HKD',
    subUnit: '毫 (hòu) (Chinese)',
    symbol: '$',
  },
  {
    title: 'New Taiwan dollar',
    iso: 'TWD',
    subUnit: 'dime',
    symbol: 'NT$',
  },
  {
    title: 'Scandinavian Monetary Union',
    subUnit: 'øre/öre',
    symbol: 'kr.',
  },
  {
    title: 'East German mark',
    iso: 'DDM',
    subUnit: 'Pfennig',
    symbol: 'M',
  },
  { title: 'Chechen naxar' },
  { title: 'Mark (currency)' },
  {
    title: 'Namibian dollar',
    iso: 'NAD',
    subUnit: 'cent',
    symbol: '$',
  },
  {
    title: 'Malaysian ringgit',
    iso: 'MYR',
    subUnit: 'sen',
    symbol: 'RM',
  },
  {
    title: 'Swiss franc',
    iso: 'CHF',

    symbol: 'Rp.',
  },
  {
    title: 'Panamanian balboa',
    iso: 'PAB',
    subUnit: '1 centesimo de balboa.jpg Centésimo',
    symbol: 'B/.',
  },
  {
    title: 'Indonesian rupiah',
    iso: 'IDR',
    subUnit: 'sen (obsolete)a',
    symbol: 'Rp',
  },
  {
    title: 'Brunei dollar',
    iso: 'BND',
    subUnit: 'sen',
    symbol: '$, B$',
  },
  {
    title: 'Venezuelan bolívar',
    iso: 'VEF',
    subUnit: 'céntimo',
    symbol: 'Bs.F or Bs.',
  },
  {
    title: 'Macedonian denar',
    iso: 'MKD',
    subUnit: 'deni / дени (no longer used)',
    symbol: 'den / ден',
  },
  {
    title: 'Mauritanian ouguiya',
    iso: 'MRU',
    subUnit: 'khoums',
    symbol: 'UM',
  },
  { title: 'Gold franc', iso: 'XFO' },
  {
    title: 'Argentine peso',
    iso: 'ARS',
    subUnit: 'centavo',
    symbol: '$',
  },
  {
    title: 'Libyan dinar',
    iso: 'LYD',
    subUnit: 'dirham',
    symbol: 'LD and ل.د',
  },
  {
    title: 'Jordanian dinar',
    iso: 'JOD',
    subUnit: 'dirham',
    symbol: 'د.أ',
  },
  {
    title: 'French franc',
    iso: 'FRF (1960–2002)',
    subUnit: 'centime',
    symbol: 'F or Fr (briefly also NF during the 1960s; also unofficially FF and ₣)',
  },
  {
    title: 'Syrian pound',
    iso: 'SYP',
    subUnit: 'piastre',
    symbol: 'LS or £S',
  },
  { title: 'Belize dollar', iso: 'BZD', subUnit: 'cent', symbol: '$' },
  {
    title: 'Saudi riyal',
    iso: 'SAR',
    subUnit: 'halalah',
    symbol: 'SAR, ر.س or ﷼',
  },
  {
    title: 'Surinamese dollar',
    iso: 'SRD',
    subUnit: 'cent',
    symbol: '$',
  },
  {
    title: 'Singapore dollar',
    iso: 'SGD',
    subUnit: 'cent',
    symbol: 'S$ or $',
  },
  {
    title: 'Nepalese rupee',
    iso: 'NPR',
    subUnit: 'Paisa',
    symbol: 'रु ₨ (plural), Re (singular)',
  },
  {
    title: 'Macanese pataca',
    iso: 'MOP',
    subUnit: '(ho)',
    symbol: 'MOP$',
  },
  {
    title: 'Nicaraguan córdoba',
    iso: 'NIO',
    subUnit: 'centavo',
    symbol: 'C$',
  },
  {
    title: 'Bangladeshi taka',
    iso: 'BDT',
    subUnit: 'poysha',
    symbol: '৳',
  },
  {
    title: 'Indian rupee',
    iso: 'INR',
    subUnit: 'paisa',
    symbol: '₹ (formerly ₨)',
  },
  {
    title: 'Maldivian rufiyaa',
    iso: 'MVR',
    subUnit: 'laari',
    symbol: 'Rf, MRf, MVR, .ރ or /-',
  },
  {
    title: 'Sri Lankan rupee',
    iso: 'LKR',
    subUnit: 'Cents',
    symbol: 'Rs, රු, ரூ',
  },
  {
    title: 'Bhutanese ngultrum',
    iso: 'BTN',
    subUnit: 'chhertum',
    symbol: 'Nu.',
  },
  {
    title: 'Revaluation of the Turkish lira',
    iso: 'TRY',
    subUnit: 'new kuruş',
    symbol: 'YTL',
  },
  {
    title: 'Serbian dinar',
    iso: 'RSD',
    subUnit: 'para / пара (defunct)',
    symbol: 'din / дин',
  },
  {
    title: 'Bosnia and Herzegovina convertible mark',
    iso: 'BAM',
    subUnit: 'Fening/Pfenig',
    symbol: 'KM',
  },
  { title: 'Botswana pula', iso: 'BWP', subUnit: 'Thebe', symbol: 'P' },
  {
    title: 'Swazi lilangeni',
    iso: 'SZL',
    subUnit: 'cent',
    symbol: 'L or E (pl.)',
  },
  {
    title: 'Lithuanian litas',
    iso: 'LTL',
    subUnit: 'centas',
    symbol: 'Lt (litas), ct (centas)',
  },
  {
    title: 'Mauritian rupee',
    iso: 'MUR',
    subUnit: 'cent',
    symbol: '₨',
  },
  {
    title: 'Pakistani rupee',
    iso: 'PKR',
    subUnit: 'Paisa',
    symbol: '₨',
  },
  {
    title: 'Maltese lira',
    iso: 'MTL',
    subUnit: 'cent',
    symbol: '₤ and Lm',
  },
  {
    title: 'Ecuadorian sucre',
    iso: 'ECS',
    subUnit: 'centavo',
    symbol: 'S/.',
  },
  {
    title: 'Sierra Leonean leone',
    iso: 'SLL',
    subUnit: 'cent',
    symbol: 'Le',
  },
  { title: 'Cypriot pound', iso: 'CYP', subUnit: 'cent', symbol: '£' },
  { title: 'Moldovan leu', iso: 'MDL', subUnit: 'ban', symbol: 'L' },
  { title: 'Croatian kuna', iso: 'HRK', subUnit: 'lipa', symbol: 'kn' },
]
