// words that get mangled by the tagger
export default {
  'tiger woods': 'Person',
  'appeal court': 'Uncountable',
  'cold war': 'Uncountable',
  'gene pool': 'Uncountable',
  'machine learning': 'Uncountable',
  'nail polish': 'Uncountable',
  'time off': 'Uncountable',
  'excuse me': 'Expression',
  'prime minister': 'Actor',
  'living room': 'Singular',

  // three-word sports teams
  'kansas city royals': 'SportsTeam',
  'los angeles dodgers': 'SportsTeam',
  'san francisco giants': 'SportsTeam',
  'st. louis cardinals': 'SportsTeam',
  'tampa bay rays': 'SportsTeam',
  'new york mets': 'SportsTeam',
  'new york yankees': 'SportsTeam',
  'san diego padres': 'SportsTeam',

  'financial times': 'Organization',
  'guns n roses': 'Organization',
  'la z boy': 'Organization',
  'new york times': 'Organization',
  'the guess who': 'Organization',
  'thin lizzy': 'Organization',
  'labour party': 'Organization',
  'free market': 'Singular',
  'lay up': 'Singular',
  'spin off': 'Singular',

  'bill gates': 'Person',
  'doctor who': 'Person',
  'he man': 'Person',
  'iron man': 'Person',
  'kid cudi': 'Person',
  'run dmc': 'Person',
  'rush limbaugh': 'Person',
  'snow white': 'Person',
  'brand new': 'Adjective',
  'en route': 'Adjective',
  'off guard': 'Adjective',
  'on board': 'Adjective',
  'so called': 'Adjective',
  'spot on': 'Adjective',
  'straight forward': 'Adjective',
  'super duper': 'Adjective',
  'tip top': 'Adjective',
  'top notch': 'Adjective',
  'up to date': 'Adjective',
  'win win': 'Adjective',
  // 'atlanta united': 'SportsTeam',
  'fire marshals': 'Plural',
  'first ladies': 'Plural',
  'foster parents': 'Plural',
  'prime ministers': 'Plural',
  'role models': 'Plural',
  'senior citizens': 'Plural',
  'civil wars': 'Plural',
  'credit cards': 'Plural',
  'default rates': 'Plural',
  'free markets': 'Plural',
  'head starts': 'Plural',
  'home runs': 'Plural',
  'lay ups': 'Plural',
  'phone calls': 'Plural',
  'press releases': 'Plural',
  'record labels': 'Plural',
  'soft serves': 'Plural',
  'student loans': 'Plural',
  'tax returns': 'Plural',
  'tv shows': 'Plural',
  'video games': 'Plural',
  'iron maiden': 'ProperNoun',
  'prince edward island': 'Region',
  // 'new york state': 'Region',
  // "cote d'ivoire": 'Country',
  // 'isle of man': 'Country',
  // 'united states': 'Country',
  // 'u.s. virgin islands': 'Country',
  // 'united states of america': 'Country',
  'cedar breaks': 'Place',
  'cedar falls': 'Place',
  'point blank': 'Adverb',
  'tiny bit': 'Adverb',
  'as soon as': 'Conjunction',
  'by the time': 'Conjunction',
  'no matter': 'Conjunction',
  // 'will like': 'Verb',
  // 'will refine': 'Verb',
}
