export default {
  'able': 'more able',
  'abrasive': 'more abrasive',
  'abrupt': 'abrupter',
  'absent': 'more absent',
  'absolute': 'more absolute',
  'absurd': 'more absurd',
  'abundant': 'more abundant',
  'academic': 'more academic',
  'accurate': 'more accurate',
  'active': 'more active',
  'acute': 'more acute',
  'adamant': 'more adamant',
  'adaptable': 'more adaptable',
  'adept': 'more adept',
  'adorable': 'more adorable',
  'adventurous': 'more adventurous',
  'agile': 'more agile',
  'alert': 'more alert',
  'alive': 'aliver',
  'almighty': 'more almighty',
  'ambitious': 'more ambitious',
  'amiable': 'more amiable',
  'amused': 'more amused',
  'ancient': 'more ancient',
  'angelic': 'more angelic',
  'angry': 'angrier',
  'animated': 'more animated',
  'annoyed': 'more annoyed',
  'anxious': 'more anxious',
  'apathetic': 'more apathetic',
  'apparent': 'more apparent',
  'appealing': 'more appealing',
  'apprehensive': 'more apprehensive',
  'arrogant': 'more arrogant',
  'artificial': 'more artificial',
  'artistic': 'more artistic',
  'asleep': 'more asleep',
  'assured': 'more assured',
  'attentive': 'more attentive',
  'attractive': 'more attractive',
  'awake': 'awakener',
  'aware': 'more aware',
  'awful': 'more awful',
  'awkward': 'awkwarder',
  'bad': 'worse',
  'balanced': 'more balanced',
  'bald': 'balder',
  'barren': 'more barren',
  'bawdy': 'bawdier',
  'beautiful': 'more beautiful',
  'believable': 'more believable',
  'beneficial': 'more beneficial',
  'bewildered': 'more bewildered',
  'big': 'bigger',
  'bitter': 'more bitter',
  'bittersweet': 'more bittersweet',
  'black': 'blacker',
  'bland': 'blander',
  'blessed': 'more blessed',
  'blind': 'more blind',
  'blond': 'blonder',
  'bloody': 'bloodier',
  'blue': 'bluer',
  'bold': 'bolder',
  'bored': 'boreder',
  'boring': 'boriner',
  'bouncy': 'bouncier',
  'brash': 'brasher',
  'brave': 'braver',
  'brief': 'briefer',
  'bright': 'brighter',
  'brilliant': 'more brilliant',
  'brisk': 'brisker',
  'broad': 'broader',
  'buff': 'buffer',
  'bureaucratic': 'more bureaucratic',
  'burly': 'burlier',
  'busy': 'busier',
  'calculate': 'more calculate',
  'calm': 'calmer',
  'camp': 'camper',
  'capable': 'more capable',
  'careful': 'more careful',
  'careless': 'more careless',
  'catchy': 'catchier',
  'cautious': 'more cautious',
  'celestial': 'more celestial',
  'certain': 'more certain',
  'chaotic': 'more chaotic',
  'charitable': 'more charitable',
  'cheap': 'cheaper',
  'cheerful': 'more cheerful',
  'cheesy': 'cheesier',
  'cherished': 'more cherished',
  'chilly': 'chillier',
  'classic': 'more classic',
  'clean': 'cleaner',
  'cleansed': 'more cleansed',
  'clear': 'clearer',
  'clever': 'cleverer',
  'close': 'closer',
  'closed': 'closer',
  'cloudy': 'cloudier',
  'clumsy': 'clumsier',
  'coarse': 'coarser',
  'coastal': 'more coastal',
  'cold': 'colder',
  'colorful': 'more colorful',
  'colourful': 'more colourful',
  'comfortable': 'more comfortable',
  'committed': 'more committed',
  'common': 'more common',
  'compassionate': 'more compassionate',
  'competent': 'more competent',
  'complete': 'more complete',
  'complex': 'more complex',
  'concerned': 'more concerned',
  'confident': 'more confident',
  'confused': 'more confused',
  'considerate': 'more considerate',
  'consistent': 'more consistent',
  'containerized': 'more containerised',
  'content': 'more content',
  'convenient': 'more convenient',
  'cool': 'cooler',
  'cooperative': 'more cooperative',
  'costly': 'costlier',
  'courageous': 'more courageous',
  'courteous': 'more courteous',
  'cowardly': 'more cowardly',
  'cozy': 'cozier',
  'crazy': 'crazier',
  'creative': 'more creative',
  'credible': 'more credible',
  'crisp': 'crisper',
  'critical': 'more critical',
  'crowded': 'more crowded',
  'cruel': 'crueler',
  'cryptic': 'more cryptic',
  'cuddly': 'cuddlier',
  'curious': 'more curious',
  'curly': 'curlier',
  'custom': 'more custom',
  'cute': 'cuter',
  'cynical': 'more cynical',
  'damp': 'damper',
  'dangerous': 'more dangerous',
  'daring': 'more daring',
  'dark': 'darker',
  'dead': 'more dead',
  'deadly': 'deadlier',
  'deaf': 'more deaf',
  'dear': 'dearer',
  'deboned': 'more deboned',
  'dedicated': 'more dedicated',
  'deep': 'deeper',
  'delicate': 'more delicate',
  'delicious': 'more delicious',
  'delightful': 'more delightful',
  'demonstrative': 'more demonstrative',
  'dense': 'denser',
  'dependable': 'more dependable',
  'depressed': 'more depressed',
  'desolate': 'more desolate',
  'desperate': 'more desperate',
  'detailed': 'more detailed',
  'determined': 'more determined',
  'devout': 'more devout',
  'difficult': 'more difficult',
  'diffuse': 'diffuser',
  'digital': 'more digital',
  'diligent': 'more diligent',
  'dim': 'dimmer',
  'dire': 'direr',
  'direct': 'more direct',
  'dirty': 'dirtier',
  'disciplined': 'more disciplined',
  'discouraging': 'more discouraging',
  'discreet': 'more discreet',
  'disgruntled': 'more disgruntled',
  'disloyal': 'more disloyal',
  'disrespectful': 'more disrespectful',
  'distant': 'more distant',
  'distinct': 'more distinct',
  'distorted': 'more distorted',
  'distracted': 'more distracted',
  'disturbed': 'more disturbed',
  'diverse': 'more diverse',
  'divine': 'diviner',
  'domestic': 'more domestic',
  'drastic': 'more drastic',
  'drunk': 'drunker',
  'dry': 'drier',
  'dull': 'duller',
  'dumb': 'dumber',
  'dutiful': 'more dutiful',
  'dynamic': 'more dynamic',
  'eager': 'more eager',
  'early': 'earlier',
  'easy': 'easier',
  'eccentric': 'more eccentric',
  'eclectic': 'more eclectic',
  'edgy': 'edgier',
  'eerie': 'eerier',
  'efficient': 'more efficient',
  'effortless': 'more effortless',
  'effusive': 'more effusive',
  'elated': 'more elated',
  'electric': 'more electric',
  'elegant': 'more elegant',
  'emotional': 'more emotional',
  'empty': 'emptier',
  'encouraging': 'more encouraging',
  'energetic': 'more energetic',
  'enlightened': 'more enlightened',
  'entertaining': 'more entertaining',
  'enthusiastic': 'more enthusiastic',
  // 'entire': 'more entire',
  'equitable': 'more equitable',
  'erratic': 'more erratic',
  'essential': 'more essential',
  'eternal': 'more eternal',
  'ethical': 'more ethical',
  'eventful': 'more eventful',
  'evil': 'more evil',
  'exalted': 'more exalted',
  'excellent': 'more excellent',
  'excessive': 'more excessive',
  'excited': 'more excited',
  'exciting': 'more exciting',
  'exhausted': 'more exhausted',
  'exitless': 'more exitless',
  'exotic': 'more exotic',
  'expensive': 'more expensive',
  'expert': 'more expert',
  'explosive': 'more explosive',
  'extinct': 'more extinct',
  'extravagant': 'more extravagant',
  'faint': 'fainter',
  'fair': 'fairer',
  'faithful': 'more faithful',
  'fake': 'faker',
  'false': 'more false',
  'familiar': 'more familiar',
  'famous': 'more famous',
  'fancy': 'fancier',
  'far': 'farther',
  'farther': 'farther',
  'fast': 'faster',
  'fastidious': 'more fastidious',
  'fat': 'fatter',
  'fatalistic': 'more fatalistic',
  'faulty': 'faultier',
  'fearless': 'more fearless',
  'federal': 'more federal',
  'feeble': 'feebler',
  'female': 'more female',
  'fertile': 'more fertile',
  'festive': 'more festive',
  'few': 'fewer',
  'fierce': 'fiercer',
  'filthy': 'filthier',
  'final': 'more final',
  'fine': 'finer',
  'firm': 'firmer',
  'first': 'more first',
  'flaccid': 'more flaccid',
  'flamboyant': 'more flamboyant',
  'flat': 'flatter',
  'flawless': 'more flawless',
  'flexible': 'more flexible',
  'fluid': 'more fluid',
  'foamy': 'foamier',
  'focused': 'more focused',
  'foggy': 'foggier',
  'fond': 'fonder',
  'foolish': 'more foolish',
  'forceful': 'more forceful',
  'formal': 'formaler',
  'fortunate': 'more fortunate',
  'foul': 'fouler',
  'fragile': 'frail',
  'fragmented': 'more fragmented',
  'fragrant': 'more fragrant',
  'frail': 'frailer',
  'frank': 'franker',
  'frantic': 'more frantic',
  'fraudulent': 'more fraudulent',
  'free': 'freer',
  'frenzied': 'more frenzied',
  'frequent': 'more frequent',
  'fresh': 'fresher',
  'friendly': 'friendlier',
  'frightened': 'more frightened',
  'frozen': 'more frozen',
  'frugal': 'more frugal',
  'full': 'fuller',
  'fun': 'funer',
  'funny': 'funnier',
  'furry': 'furrier',
  'further': 'further',
  'garrulous': 'more garrulous',
  'gauche': 'gaucher',
  'gaudy': 'gaudier',
  'gay': 'gaier',
  'general': 'more general',
  'generous': 'more generous',
  'gentle': 'gentler',
  'gentlemanly': 'more gentlemanly',
  'genuine': 'more genuine',
  'ghastly': 'ghastlier',
  'ghostly': 'ghostlier',
  'giddy': 'giddier',
  'gifted': 'more gifted',
  'glad': 'gladder',
  'gleaming': 'more gleaming',
  'glib': 'glibber',
  'global': 'more global',
  'gloomy': 'gloomier',
  'glossy': 'more glossy',
  'gold': 'golder',
  'good': 'better',
  'goofy': 'goofier',
  'graceful': 'more graceful',
  'grand': 'grander',
  'grateful': 'more grateful',
  'grave': 'graver',
  'gray': 'grayer',
  'great': 'greater',
  'greedy': 'greedier',
  'green': 'greener',
  'grey': 'more grey',
  'grisly': 'grislier',
  'grizzled': 'more grizzled',
  'groovy': 'groovier',
  'gross': 'grosser',
  'gruesome': 'gruesomer',
  'half': 'more half',
  'handsome': 'handsomer',
  'handy': 'handier',
  'happy': 'happier',
  'hard': 'harder',
  // 'hardworking': 'harder working',
  'hardy': 'hardier',
  'harmful': 'more harmful',
  'harsh': 'harsher',
  'hasty': 'more hasty',
  'hateful': 'more hateful',
  'heady': 'headier',
  'healthy': 'healthier',
  'hearty': 'heartier',
  'heavy': 'heavier',
  'hefty': 'heftier',
  'helpful': 'more helpful',
  'high': 'higher',
  'hilly': 'hillier',
  'historical': 'more historical',
  'holistic': 'more holistic',
  'holy': 'holier',
  'homely': 'homelier',
  'hopeful': 'more hopeful',
  'hostile': 'more hostile',
  'hot': 'hotter',
  'huge': 'huger',
  'humble': 'humbler',
  'humid': 'humider',
  'humorous': 'more humorous',
  'hungry': 'hungrier',
  'hypocritical': 'more hypocritical',
  'icy': 'icier',
  'ideal': 'more ideal',
  'idealistic': 'more idealistic',
  'identical': 'more identical',
  'idyllic': 'more idyllic',
  'ignorant': 'more ignorant',
  'ill': 'more ill',
  'imaginative': 'more imaginative',
  'immature': 'more immature',
  'impatient': 'more impatient',
  'important': 'more important',
  'impressive': 'more impressive',
  'impulsive': 'more impulsive',
  'inattentive': 'more inattentive',
  'inclusive': 'more inclusive',
  'incomparable': 'more incomparable',
  'indecisive': 'more indecisive',
  'indefinable': 'more indefinable',
  'independent': 'more independent',
  'indescribable': 'more indescribable',
  'indifferent': 'more indifferent',
  'indispensable': 'more indispensable',
  'indivisible': 'more indivisible',
  'indulgent': 'more indulgent',
  'industrial': 'more industrial',
  'industrious': 'more industrious',
  'ineffable': 'more ineffable',
  'inept': 'more inept',
  'infallible': 'more infallible',
  'infamous': 'more infamous',
  'inferior': 'more inferior',
  'infinite': 'more infinite',
  'informative': 'more informative',
  'ingenious': 'more ingenious',
  'inherent': 'more inherent',
  'inimitable': 'more inimitable',
  'innocent': 'more innocent',
  'inoffensive': 'more inoffensive',
  'inscrutable': 'more inscrutable',
  'insensitive': 'more insensitive',
  'insightful': 'more insightful',
  'insurmountable': 'more insurmountable',
  'intact': 'more intact',
  'intangible': 'more intangible',
  'intelligent': 'more intelligent',
  'intense': 'more intense',
  'interesting': 'more interesting',
  'intolerant': 'more intolerant',
  'intransigent': 'more intransigent',
  'intrinsic': 'more intrinsic',
  'intuitive': 'more intuitive',
  'inventive': 'more inventive',
  'invincible': 'more invincible',
  'inviolable': 'more inviolable',
  'ironic': 'more ironic',
  'irreplaceable': 'more irreplaceable',
  'irresponsible': 'more irresponsible',
  'irrevocable': 'more irrevocable',
  'jealous': 'more jealous',
  'jewelled': 'more jewelled',
  'jolly': 'jollier',
  'jovial': 'more jovial',
  'joyful': 'more joyful',
  'jubilant': 'more jubilant',
  'juicy': 'juicier',
  'just': 'more just',
  'keen': 'keener',
  'key': 'more key',
  'kind': 'kinder',
  'knowledgeable': 'more knowledgeable',
  'lame': 'lamer',
  'languid': 'languider',
  'large': 'larger',
  'late': 'later',
  'lateral': 'more lateral',
  'lavish': 'more lavish',
  'lax': 'more lax',
  'lazy': 'lazier',
  'lean': 'leaner',
  'leery': 'leerier',
  'legal': 'more legal',
  'legendary': 'more legendary',
  'lengthy': 'lengthier',
  'lesser': 'lesser',
  'lethargic': 'more lethargic',
  'lewd': 'lewder',
  'liberal': 'more liberal',
  'lifeless': 'more lifeless',
  'light': 'lighter',
  'lighthearted': 'more lighthearted',
  'likeable': 'more likeable',
  'likely': 'likelier',
  'limited': 'more limited',
  'limp': 'limper',
  'liquid': 'more liquid',
  'little': 'littler',
  'lively': 'livelier',
  'local': 'more local',
  'lofty': 'loftier',
  'logical': 'more logical',
  'lonely': 'lonelier',
  'long': 'longer',
  'loose': 'looser',
  'loud': 'louder',
  'lousy': 'lousier',
  'lovable': 'more lovable',
  'lovely': 'lovelier',
  'loving': 'more loving',
  'low': 'lower',
  'loyal': 'more loyal',
  'lucky': 'luckier',
  'lukewarm': 'more lukewarm',
  'luscious': 'more luscious',
  'mad': 'madder',
  'magnetic': 'more magnetic',
  'magnificent': 'more magnificent',
  'majestic': 'more majestic',
  'male': 'more male',
  'manageable': 'more manageable',
  'manual': 'more manual',
  'martial': 'more martial',
  'massive': 'more massive',
  'mature': 'more mature',
  'mean': 'meaner',
  'measly': 'measlier',
  'meaty': 'meatier',
  'medieval': 'more medieval',
  'meek': 'meeker',
  'mellow': 'mellower',
  'messy': 'messier',
  'mild': 'milder',
  'military': 'more military',
  'miserly': 'more miserly',
  'modern': 'more modern',
  'moist': 'moister',
  'moody': 'moodier',
  'moral': 'more moral',
  'motivated': 'more motivated',
  'mundane': 'more mundane',
  'municipal': 'more municipal',
  'mysterious': 'more mysterious',
  'naive': 'more naive',
  'naked': 'more naked',
  'nappy': 'nappier',
  'narrow': 'narrower',
  'nasty': 'nastier',
  'national': 'more national',
  'natural': 'more natural',
  'naval': 'more naval',
  'near': 'nearer',
  'neat': 'neater',
  'nervous': 'more nervous',
  'new': 'newer',
  'nice': 'nicer',
  'nimble': 'nimbler',
  'noble': 'nobler',
  'noisy': 'noisier',
  'normal': 'more normal',
  'nosy': 'nosier',
  'nuclear': 'more nuclear',
  'numb': 'number',
  'obedient': 'more obedient',
  'objective': 'more objective',
  'odd': 'odder',
  'offensive': 'more offensive',
  'oily': 'oilier',
  'old': 'older',
  'opaque': 'more opaque',
  'open': 'more open',
  'optimistic': 'more optimistic',
  'oral': 'more oral',
  'organized': 'more organized',
  'outdoor': 'more outdoor',
  'outlandish': 'more outlandish',
  'outward': 'more outward',
  'overseas': 'more overseas',
  'overwhelming': 'more overwhelming',
  'pale': 'paler',
  'parallel': 'more parallel',
  'partial': 'more partial',
  'passionate': 'more passionate',
  'patient': 'more patient',
  'peaceful': 'more peaceful',
  'perfect': 'more perfect',
  'persistent': 'more persistent',
  'persuasive': 'more persuasive',
  'pessimistic': 'more pessimistic',
  'petite': 'more petite',
  'petty': 'pettier',
  'phony': 'phonier',
  'pink': 'pinker',
  'placid': 'more placid',
  'plain': 'more plain',
  'platonic': 'more platonic',
  'pleasant': 'more pleasant',
  'pleasing': 'more pleasing',
  'pliable': 'more pliable',
  'plural': 'more plural',
  'polite': 'more polite',
  'poor': 'poorer',
  'popular': 'more popular',
  'postal': 'more postal',
  'powerful': 'more powerful',
  'powerless': 'more powerless',
  'practical': 'more practical',
  'precise': 'more precise',
  'pregnant': 'more pregnant',
  'premier': 'premier',
  'present': 'more present',
  'pretty': 'prettier',
  'prickly': 'pricklier',
  'private': 'more private',
  'productive': 'more productive',
  'professional': 'more professional',
  'proficient': 'more proficient',
  'profound': 'more profound',
  'progressive': 'more progressive',
  'proper': 'more proper',
  'protective': 'more protective',
  'proud': 'prouder',
  'prudent': 'more prudent',
  'pungent': 'more pungent',
  'puny': 'punier',
  'pure': 'purer',
  'quick': 'quicker',
  'quiet': 'quieter',
  'radiant': 'more radiant',
  'ragged': 'more ragged',
  'rainy': 'rainier',
  'random': 'more random',
  'rapid': 'more rapid',
  'rare': 'rarer',
  'raw': 'rawer',
  'ready': 'readier',
  'real': 'more real',
  'realistic': 'more realistic',
  'reasonable': 'more reasonable',
  'rebellious': 'more rebellious',
  'reckless': 'more reckless',
  'relaxed': 'more relaxed',
  'reliable': 'more reliable',
  'remote': 'more remote',
  'resolute': 'more resolute',
  'resourceful': 'more resourceful',
  'respectful': 'more respectful',
  'responsible': 'more responsible',
  'restless': 'more restless',
  'restricted': 'more restricted',
  'reticent': 'more reticent',
  'rich': 'richer',
  'right': 'righter',
  'righteous': 'more righteous',
  'rigid': 'more rigid',
  'ripe': 'riper',
  'risky': 'riskier',
  'ritzy': 'ritzier',
  'romantic': 'more romantic',
  'roomy': 'roomier',
  'rosy': 'rosier',
  'rough': 'rougher',
  'round': 'rounder',
  'rude': 'ruder',
  'ruthless': 'more ruthless',
  'sad': 'sadder',
  'safe': 'safer',
  'saintly': 'saintlier',
  'salty': 'saltier',
  'satisfied': 'more satisfied',
  'savvy': 'savvier',
  'scanty': 'scantier',
  'scarce': 'scarcer',
  'scared': 'scarier',
  'scary': 'scarier',
  'scenic': 'more scenic',
  'scripted': 'more scripted',
  'scruffed': 'more scruffed',
  'secure': 'more secure',
  'self-assured': 'more self-assured',
  'selfish': 'more selfish',
  'selfless': 'more selfless',
  'sensible': 'more sensible',
  'sensitive': 'more sensitive',
  'serious': 'more serious',
  'severe': 'severer',
  'sexy': 'sexier',
  'shady': 'shadier',
  'shallow': 'shallower',
  'sharp': 'sharper',
  'shiny': 'shinier',
  'short': 'shorter',
  'shrewd': 'more shrewd',
  'shrill': 'shriller',
  'shy': 'shyer',
  'sick': 'sicker',
  'sickly': 'sicklier',
  'significant': 'more significant',
  'silky': 'silkier',
  'silly': 'sillier',
  // 'simple-minded': 'simpler-minded',
  'simple': 'simpler',
  'sincere': 'more sincere',
  'skillful': 'more skillful',
  'skinny': 'skinnier',
  'slack': 'slacker',
  'sleek': 'sleeker',
  'sleepy': 'sleepier',
  'slight': 'slighter',
  'slim': 'slimmer',
  'slimy': 'slimier',
  'slippery': 'more slippery',
  'sloppy': 'sloppier',
  'slow': 'slower',
  'sly': 'slier',
  'small': 'smaller',
  'smart': 'smarter',
  'smelly': 'smellier',
  'smooth': 'smoother',
  'snarling ': 'more snarling',
  'soft': 'softer',
  'solemn': 'solemner',
  'solid': 'more solid',
  'solitary': 'solitarer',
  'somber': 'more somber',
  'soon': 'sooner',
  'sophisticated': 'more sophisticated',
  'sore': 'sorer',
  'sorrowful': 'more sorrowful',
  'sorry': 'sorrier',
  'sound': 'sounder',
  'sparkly': 'sparklier',
  'sparse': 'sparser',
  'speedy': 'speedier',
  'spicy': 'spicier',
  'spiritual': 'more spiritual',
  'spoken': 'more spoken',
  'spontaneous': 'more spontaneous',
  'sprightly': 'sprightlier',
  'square': 'squarer',
  'stale': 'staler',
  'stark': 'starker',
  'steadfast': 'more steadfast',
  'steady': 'steadier',
  'steep': 'steeper',
  'stern': 'sterner',
  'stiff': 'stiffer',
  'stingy': 'stingier',
  'stoked-up': 'more stoked-up',
  'stoppable': 'more stoppable',
  'stout': 'stouter',
  'straight': 'straighter',
  'straightforward': 'more straightforward',
  'strict': 'stricter',
  'strong': 'stronger',
  'stunning': 'more stunning',
  'stupid': 'stupider',
  'sturdy': 'sturdier',
  'stylish': 'more stylish',
  'subtle': 'subtler',
  'successful': 'more successful',
  'sudden': 'more sudden',
  'supple': 'more supple',
  'supportive': 'more supportive',
  'supreme': 'more supreme',
  'surprising': 'more surprising',
  'surreal': 'more surreal',
  'suspect': 'more suspect',
  // 'sweet-smelling': 'sweeter-smelling',
  'sweet': 'sweeter',
  'swift': 'swifter',
  'talented': 'more talented',
  'tall': 'taller',
  'tame': 'tamer',
  'tart': 'more tart',
  'tawdry': 'tawdrier',
  'tender': 'more tender',
  'tense': 'tenser',
  'tentative': 'more tentative',
  'testable': 'more testable',
  'thankful': 'more thankful',
  'thick': 'thicker',
  'thin': 'thinner',
  'thirsty': 'thirstier',
  'thorough': 'more thorough',
  'thoughtful': 'more thoughtful',
  'thoughtless': 'more thoughtless',
  'tidy': 'tidier',
  'tight': 'tighter',
  'timely': 'timelier',
  'timid': 'more timid',
  'tiny': 'tinier',
  'tired': 'more tired',
  'tolerant': 'more tolerant',
  'tough': 'tougher',
  'tranquil': 'more tranquil',
  'translucent': 'more translucent',
  'trendy': 'trendier',
  'triangular': 'more triangular',
  'tricky': 'trickier',
  'trim': 'trimmer',
  'true': 'truer',
  'trusting': 'more trusting',
  'trustworthy': 'more trustworthy',
  'truthful': 'more truthful',
  'turbulent': 'more turbulent',
  'ugly': 'uglier',
  'ultimate': 'more ultimate',
  'unassailable': 'more unassailable',
  'unattainable': 'more unattainable',
  'unaware': 'more unaware',
  'unbearable': 'more unbearable',
  'unchangeable': 'more unchangeable',
  'uncompromising': 'more uncompromising',
  'unconditional': 'more unconditional',
  'unconscionable': 'more unconscionable',
  'uncontrollable': 'more uncontrollable',
  'uncouth': 'more uncouth',
  'uncreative': 'more uncreative',
  'undeniable': 'more undeniable',
  'understanding': 'more understanding',
  'undiminished': 'more undiminished',
  'uneasy': 'more uneasy',
  'unenlightened': 'more unenlightened',
  'unenthusiastic': 'more unenthusiastic',
  'unequal': 'more unequal',
  'unfaithful': 'more unfaithful',
  'unfathomable': 'more unfathomable',
  'unfocused': 'more unfocused',
  'unforgettable': 'more unforgettable',
  'unfortunate': 'more unfortunate',
  'unfriendly': 'unfriendlier',
  'ungrateful': 'more ungrateful',
  'unimaginative': 'more unimaginative',
  'unimportant': 'less important',
  'unique': 'more unique',
  'united': 'more united',
  'universal': 'more universal',
  'unknown': 'more unknown',
  'unlikely': 'unlikelier',
  'unlucky': 'unluckier',
  'unmanageable': 'more unmanageable',
  'unmistakable': 'more unmistakable',
  'unnatural': 'more unnatural',
  'unparalleled': 'more unparalleled',
  'unpleasant': 'more unpleasant',
  'unprecedented': 'more unprecedented',
  'unprepared': 'more unprepared',
  'unrecoverable': 'more unrecoverable',
  'unrelenting': 'more unrelenting',
  'unreliable': 'more unreliable',
  'unspeakable': 'more unspeakable',
  'untamed': 'more untamed',
  'untidy': 'untidier',
  'untouchable': 'more untouchable',
  'untrue': 'more untrue',
  'unusual': 'more unusual',
  'unyielding': 'more unyielding',
  'useful': 'more useful',
  'useless': 'more useless',
  'vague': 'vaguer',
  'vain': 'vainer',
  'valiant': 'more valiant',
  'valuable': 'more valuable',
  'valuble': 'more valuble',
  'vast': 'vaster',
  'verbose': 'more verbose',
  'versatile': 'more versatile',
  'vibrant': 'more vibrant',
  'vigilant': 'more vigilant',
  'vigorous': 'more vigorous',
  'virtuous': 'more virtuous',
  'vivid': 'more vivid',
  'vulnerable': 'more vulnerable',
  'warm': 'warmer',
  'wary': 'warier',
  'weak': 'weaker',
  'weakly': 'weaklier',
  'wealthy': 'wealthier',
  'weary': 'wearier',
  'weird': 'weirder',
  'wet': 'wetter',
  'white': 'whiter',
  'wicked': 'wickeder',
  'wide-eyed': 'more wide-eyed',
  'wide': 'wider',
  'wild': 'wilder',
  'wily': 'wilier',
  'wise': 'wiser',
  'wisely': 'wiselier',
  'witty': 'wittier',
  'wonderful': 'more wonderful',
  'worried': 'more worried',
  'worthy': 'more worthy',
  'wrong': 'wronger',
  'young': 'younger',
  'zany': 'zanier',
  'zealous': 'more zealous',
}