// Generated by CoffeeScript 1.6.3
var chunker, recognizer, spot, tagger, tokenizer;

tagger = require("./tagger");

recognizer = require("./helpers/recognizer");

chunker = require("./helpers/chunker");

tokenizer = require("./helpers/tokenizer");

spot = (function() {
  var cleanup, rank, set_options;
  set_options = function(options) {
    if (options == null) {
      options = {
        big: true
      };
    }
    if (options.verbose) {
      options.gerund = true;
      options.stick_adjectives = true;
      options.stick_prepositions = true;
      options.stick_the = true;
      options.want_quotations = true;
      options.subnouns = true;
      options.match_whole = true;
      options.case_sensitive = false;
      options.kill_numbers = false;
      options.kill_quotes = false;
    }
    if (options.big) {
      options.gerund = false;
      options.stick_adjectives = false;
      options.stick_prepositions = false;
      options.stick_the = false;
      options.subnouns = false;
      options.want_quotations = true;
      options.match_whole = false;
      options.kill_numbers = true;
      options.kill_quotes = true;
    }
    return options;
  };
  cleanup = function(nouns) {
    var i;
    for (i in nouns) {
      nouns[i].word = nouns[i].word.replace(/("|,|\)|\(|!)/g, "");
      nouns[i].word = nouns[i].word.replace(/'s$/, "");
      nouns[i].word = nouns[i].word.replace(/[\.\?,!:;\/\)]*$/, "");
      nouns[i].word = nouns[i].word.replace(/^[\(\/]*/g, "");
      nouns[i].word = nouns[i].word.replace(/[\(\/\)\\;:,]/g, " ");
      nouns[i].word = nouns[i].word.replace(RegExp("  ", "g"), " ");
      nouns[i].word = nouns[i].word.replace(/\W*$/, "");
      nouns[i].word = nouns[i].word.replace(/^\W*/, "");
      if (!nouns[i].word.match(/^the ./)) {
        nouns[i].word = singularize(nouns[i].word);
      }
      if (!options.case_sensitive) {
        nouns[i].word = nouns[i].word.toLowerCase();
      }
    }
    return nouns;
  };
  rank = function(results) {
    var i;
    for (i in results) {
      results[i].score = 0;
      results[i].score += results[i].count * 10;
      if (results[i].rule === "capital") {
        results[i].score += 10;
      }
      if (results[i].rule === "lexicon") {
        results[i].score += 7;
      }
      if (results[i].rule === "group_prep") {
        results[i].score -= 4;
      }
    }
    results = results.sort(function(a, b) {
      return b.score - a.score;
    });
    return results;
  };
  spot = function(str, options) {
    var chunks, nouns, results, tags, words;
    if (str == null) {
      str = "";
    }
    if (options == null) {
      options = {
        big: true
      };
    }
    options = set_options(options);
    words = tokenizer(str, options);
    tags = tagger(words);
    chunks = chunker(tags, options);
    nouns = recognizer(chunks, options);
    nouns = cleanup(nouns);
    nouns = rank(nouns);
    results = nouns.filter(function(noun) {
      return pass(noun.word);
    });
    return results;
  };
  if (typeof define !== "undefined" && define.amd) {
    define([], function() {
      return spot;
    });
  } else {
    if (typeof module !== "undefined" && module.exports) {
      module.exports = spot;
    }
  }
  return spot;
})();

spot("sally is a great diver");
