// generated in ./lib/pairs
export default {
  "Comparative": {
    "fwd": "3:ser,ier¦1er:h,t,f,l,n¦1r:e¦2er:ss,or,om",
    "both": "3er:ver,ear,alm¦3ner:hin¦3ter:lat¦2mer:im¦2er:ng,rm,mb¦2ber:ib¦2ger:ig¦1er:w,p,k,d¦ier:y",
    "rev": "1:tter,yer¦2:uer,ver,ffer,oner,eler,ller,iler,ster,cer,uler,sher,ener,gher,aner,adder,nter,eter,rter,hter,rner,fter¦3:oser,ooler,eafer,user,airer,bler,maler,tler,eater,uger,rger,ainer,urer,ealer,icher,pler,emner,icter,nser,iser¦4:arser,viner,ucher,rosser,somer,ndomer,moter,oother,uarer,hiter¦5:nuiner,esser,emier¦ar:urther",
    "ex": "worse:bad¦better:good¦4er:fair,gray,poor¦1urther:far¦3ter:fat,hot,wet¦3der:mad,sad¦3er:shy,fun¦4der:glad¦:¦4r:cute,dire,fake,fine,free,lame,late,pale,rare,ripe,rude,safe,sore,tame,wide¦5r:eerie,stale"
  },
  "Gerund": {
    "fwd": "1:nning,tting,rring,pping,eing,mming,gging,dding,bbing,kking¦2:eking,oling,eling,eming,oging¦3:velling,siting,uiting,fiting,loting,geting¦4:graming",
    "both": "1:aing,iing,fing,xing,ying,oing,hing,wing¦2:tzing,rping,auing,izzing,bting,mning,sping,wling,rling,wding,rbing,uping,lming,wning,mping,oning,lting,mbing,lking,fting,hting,sking,gning,pting,cking,ening,nking,eping,ering,rting,rming,cting,lping,ssing,nting,nding,lding,sting,rning,rding,rking¦3:belling,aiting,oating,oaning,auling,ooping,aiding,naping,euring,tolling,uzzing,ganing,haning,ualing,halling,oiding,ficking,ouling,voring,ralling,micking,ooding,garing,cilling,meting,joring,oaming,oaking,eeting,roring,nelling,ooring,uelling,eaming,eaping,oiling,eiling,ooming,xiting,keting,ooking,ulling,airing,biting,eiting,outing,ooting,naling,oading,earing,eeding,ailing,ouring,aiming,illing,oining,eaning,onging,eaking,ealing,aining,eading¦4:thoming,ayaking,melling,aboring,ivoting,weating,onoring,eriting,imiting,heating,preting,rgining,lauding,otoring,aceting,linging,winging,lleting,louding,spelling,mpelling,xcelling,feating,opelling,choring,welling,ctoring,calling,peating,iloring,ncelling,utoring,iciting,loiting,mbating,ntoring,otalling,nsoring,nselling,ocusing,itoring,eloping¦5:ustoming,rselling,umpeting,atrolling,treating,itialling,pringing,uthoring,ossoming,eselling,rediting,nrolling,stalling,ntrolling¦5e:severing,shrining,nbathing,erouting,ecreting,ephoning,ravening,epleting,reathing,pediting,erfering,fringing,ombining,ompeting,mpleting¦4e:eething,twining,rruling,scuring,eciting,chuting,xciting,edoring,pinging,agining,craping,ploding,writing,eleting,nciting,nduring,ncoding,tponing,ocuring,ecoding,esaling,nvening,gnoring,evoting,mpeding,rvening,storing,nviting,ecuring,ploring¦3e:making,uaking,tining,nuring,saking,miring,haling,ceding,rading,nuting,seding,taking,coping,caring,miling,riding,hoking,lading,laking,liging,uading,noting,taping,futing,paring,raking,biding,puting,piring,siring,guring,vading,voking,niting,laning,coring,caping,luting,muting,ruding,ciding,juring,laming,caling,hining,uoting,liding,loning,ciling,duling,tuting,siding,cuting,piling,laring,uiding,tiring,turing,filing,enging,haping,buting,lining,fining,anging,haring,uiring,coming,mining,moting,suring,viding,luding¦2e:tring,zling,uging,gling,vring,fling,lging,obing,psing,pling,ubing,cling,dling,wsing,iking,rsing,dging,kling,yping,ysing,tling,rging,eging,nsing,uning,osing,uming,using,ibing,bling,aging,ising,asing,ating¦2ie:rlying¦1e:zing,uing,cing,ving",
    "rev": "ying:ie¦1ing:se,ke,te,we,re,de,pe,me,ne,le,he¦2ing:ll,ng,dd,ee,ye,oe,sc,gg,us¦2ning:un¦2ging:ag,ug,ig,eg¦2ming:um¦2ping:ip¦2bing:ub,ab,eb,ob¦3ning:lan,can,hin,pin,win¦3ring:cur,lur,tir,tar,pur,car¦3ping:rop,rap,top,lap,hop,cap¦3ing:del,eel,oar,dit,eat,eem,lel,iet,ias,kel,ool,sip,ein,uin¦3ming:tem,rim,kim,lim¦3ting:mat,cut,lit,lot,hat,set,pit,rot,put¦3ding:hed,bed,bid,red¦3king:rek¦3bing:rib¦3ling:pel¦4ning:egin¦4ing:isit,ruit,ilot,nsit,dget,lunge,ival,rcel¦4ring:efer,nfer¦4ting:rmit,mmit,ysit,dmit,emit,bmit,tfit,gret¦4ling:evel,ivel¦5ing:arget,posit,rofit,talog¦5ring:nsfer¦5ting:nsmit,orget,cquit¦5ling:istil",
    "ex": "3:adding,eating,aiming,aiding,airing,outing,gelling,egging,oiling,gassing,setting,getting,putting,cutting,winning,sitting,betting,mapping,logging,tapping,letting,bidding,hitting,tanning,netting,popping,fitting,capping,lapping,barring,banning,vetting,topping,rotting,potting,jogging,wetting,pitting,budding,fogging,hemming,pinning,jetting,kidding,padding,podding,wedding,bedding,donning,warring,penning,gutting,cueing,wadding,petting,napping,matting,tinning,binning,bitting,dimming,hopping,mopping,nodding,panning,rapping,ridding,sinning¦4:selling,falling,calling,editing,telling,rolling,heating,soaring,hanging,beating,singing,dialing,tolling,felling,polling,discing,seating,roaring,dieting,biasing,lauding,yelling,reining,ruining,seeking,spanning,stepping,spotting,knitting,emitting,swimming,quitting,omitting,swapping,clogging,shutting,skinning,abutting,cramming,fretting,suiting¦5:bringing,treating,auditing,spelling,stalling,trolling,expelling,rivaling,wringing,deterring,singeing,befitting,refitting¦6:distilling,scrolling,strolling,caucusing,gossiping,travelling¦7:overeating,outselling,benefiting,unraveling,programing¦9:reprogramming¦is:being¦2e:using,aging,owing¦3e:making,taking,coming,noting,hiring,filing,coding,citing,doping,baking,coping,hoping,lading,caring,naming,voting,riding,mining,curing,lining,ruling,boring,dining,firing,hiding,piling,taping,waning,baling,boning,faring,honing,wiping,luring,timing,wading,piping,fading,biting,zoning,daring,waking,gaming,raking,ceding,tiring,coking,wining,joking,paring,gaping,poking,pining,coring,liming,toting,roping,wiring,aching¦4e:writing,storing,eroding,framing,smoking,tasting,wasting,phoning,shaking,shading,pasting,priming,shoring,sloping,exuding,withing,hinging¦1ie:dying,tying,lying,vying¦5e:adhering,renaming,plunging,swathing,fringing"
  },
  "Participle": {
    "fwd": "1:mt,ned¦2:ved,llen¦3:aken,iven¦:ne¦y:in",
    "both": "1:wn¦2:me,aten¦3:bidden,isen¦4:rseen,eseen¦3l:pilt¦3d:uilt¦2e:itten¦1im:wum¦1eak:poken¦1ine:hone¦1ose:osen¦1in:gun¦1ake:woken¦ear:orn¦eal:olen¦eeze:ozen¦et:otten¦ink:unk¦ing:ung",
    "rev": "2:un¦oken:eak¦ought:eek¦oven:eave¦1ne:o¦1own:ly¦1den:de¦1in:ay¦2t:am¦2ed:en¦2n:ee¦3en:all¦3n:ove¦4n:rive,sake,take¦5n:rgive",
    "ex": "2:been¦3:seen,run¦4:dived,given,taken¦5:proven,shaken¦2eak:broken¦2y:flown¦3e:hidden,ridden¦1eek:sought¦1ake:woken¦1eave:woven"
  },
  "PastTense": {
    "fwd": "1:tted,wed,yed,gged,nned,rred,pped,mmed,bbed,oed,dded,rd¦2:et,ad,eed,nded,hted,st,oled,ut,emed,eled,lded,rt,nked,apt,ant,eped,eked¦3:eared,eat,eaded,nelled,ealed,ealt,ialed,eeded,ooted,eaked,eaned,eeted,mited,bid,loted,uit,eaped,belled,uited,velled,geted¦4:ebuted,hined,odelled,comed¦y:ied¦ome:ame¦ear:ore¦ind:ound¦ing:ung,ang¦ep:pt¦ink:ank,unk¦ig:ug¦all:ell¦ee:aw¦ive:ave¦ake:ook¦eeze:oze¦old:eld¦ave:ft¦ide:ode¦ell:old¦ite:ote¦ine:one¦in:un,on¦eal:ole¦im:am¦ie:ay¦and:ood¦1ise:rose¦1eak:roke¦1ing:rought¦1ive:rove¦1el:elt¦1id:bade¦1et:got¦1y:aid¦3d:pent",
    "both": "1:aed,fed,xed,hed¦2:xted,lked,kied,sged,lmed,lped,uped,sped,bted,rbed,rked,wned,rled,wded,mped,fted,mned,mbed,rped,zzed,tzed,ened,cked,gned,lted,sked,ued,zed,nted,ered,rted,rmed,ced,sted,rned,ssed,omed,rded,pted,ved,cted¦3:oided,eiled,yped,ficked,taled,moned,yled,eamed,lit,kled,oiled,oaked,gled,zled,naled,fled,uined,oamed,ioted,ymed,eined,koned,aided,obed,ibed,meted,nicked,iged,mured,rored,micked,keted,jored,oaded,tilled,soned,rited,lged,aired,ooned,auled,owled,oaned,filled,ouled,ooded,ceted,tolled,oited,xited,tled,vored,dled,aped,nsed,rsed,sited,ubed,pled,sored,rged,pelled,oured,psed,bited,osed,aimed,cled,eured,tred,ioned,celled,bled,wsed,ooked,oated,iked,iased,onged,ased,ailed,uned,umed,ained,auded,nulled,ysed,eged,ised,aged,oined,ated,used,dged,doned¦4:cored,welled,seded,roked,talled,uared,pouted,pilled,naked,miled,houted,helled,hared,duled,caled,culed,tired,peated,ciled,buked,uoted,uaked,moted,rimed,sided,poned,leated,honed,lleted,huted,ruled,pined,cured,named,sured,uvred,vaded,preted,jured,haled,peded,gined,nited,onored,roped,lared,ramed,ocused,laked,gured,ctored,unged,pired,cuted,voked,eloped,ralled,rined,dured,amelled,icited,rilled,vided,uaded,voted,mined,sired,noted,lined,nselled,luted,tuted,fined,fided,puted,piled,pared,olored,cided,loned,hoked,hilled,enged,tured,cined,geoned,cotted,lamed,uiled,caded,waited,udited,anged,luded,mired,uired,raded¦5:umpeted,ailored,prouted,creted,stored,efuted,ecalled,ntined,ofiled,eceded,atrolled,nitored,rshalled,basted,rvened,itialled,ncited,gnored,ossiped,rfeited,ploded,xcited,twined,ncoded,ibuted,plored,efeated,redited,ntrolled,avened,pleted,llided,eathed,nefited,uthored,nchored,dhered,cceded¦3ad:sled¦3it:bysat¦2aw:drew¦2ot:hot¦2ke:made¦2d:ilt¦2ow:hrew,grew¦2ose:hose¦1go:rwent,ewent¦1ink:hought¦1ick:tuck¦1ike:ruck¦1eak:poke,nuck¦1it:pat¦1o:did¦1un:ran¦1ow:new¦1in:gan¦1ake:woke",
    "rev": "3:set,rst,hed,cut¦4:cast,tbid¦5:sread,eread,pread,erbid¦ought:uy,eek¦1ied:ny,ly,dy,ry,fy,py,ty,cy,vy,by¦1ung:ling,ting¦1pt:eep¦1ank:rink¦1ore:bear,wear¦1ave:give¦1ook:sake,take,hake¦1oze:reeze¦1ound:rind,wind¦1aw:see¦1old:sell¦1ote:rite¦1ole:teal¦1am:wim¦1ay:lie¦1ood:tand¦1eld:hold¦2d:he,ge,re,le,leed,ne,reed,ye,pe,lee,peed¦2ed:dd,oy,ew,ud,ey,gg,rr,to¦2ame:ecome,rcome¦2ged:eg,ag,og,ug¦2ped:ap¦2bed:ub,ab,ib,ob¦2lt:neel¦2ode:rride¦2id:pay¦2ang:pring¦2ove:trive¦2med:um¦3ted:mit,hat,mat,lat,pot¦3ed:low,end,tow,ill,und,ond,cay,lay,cho,bow,dow,ual,eld,eat,ald,oop,uld,law,lel,oll,ray,ull,ank,ool,eem,oar,tay,way,haw,ait¦3d:ste,ede,ime,ode,ete,ree,ude,ame,oke,ote,ute,tie¦3red:lur,cur,pur¦3ped:rop,rip,hop,tep,top¦3ade:orbid¦3led:uel,val¦3ned:lan,can,hun,kin,pan,tun,win¦3ded:lod,rod,red,kid¦3med:lim,rim¦4ted:quit,llot,mbat,gret¦4ed:pear,ssay,link,rrow,rand,lean,ceal,ovet,mand,band,dear,ceed,reet,abel,evel,imit,ilot,uell,peal,veal,cout,hear,riek,mell,head,weak¦4led:nnel,nrol,ebel,ivel¦4red:efer,nfer,sfer¦4ded:mbed¦4d:dite,ntee,amme,cite,pite¦4ned:rpin¦5ed:light,right,panel,xpand,rtial,eboot,cruit,emind,arget,hread,eight¦5d:nvite¦5led:ravel",
    "ex": "2:upped¦3:added,aged,aided,aimed,aired,bid,died,dyed,egged,erred,eyed,fit,gassed,gelled,hit,lied,oiled,outed,owed,pent,pied,tied,used,vied,banned,barred,bet,binned,bowed,canned,cut,dimmed,dipped,donned,ended,feed,hopped,inked,jammed,jarred,let,manned,mopped,mowed,netted,nodded,padded,panned,pinned,pitted,popped,potted,put,rigged,set,sinned,sowed,tanned,tipped,topped,towed,vetted,vowed¦4:ached,baked,baled,banged,billed,boned,bored,caked,called,caned,cared,ceded,cited,coded,cored,culled,cured,dared,dined,edited,faded,faked,fared,filed,filled,fined,fired,fuelled,gamed,heated,hired,honed,hoped,joked,killed,lined,looped,mined,mired,named,noted,piled,poked,polled,pored,pulled,raked,roared,rolled,roped,ruled,seated,shed,sided,soared,tamed,timed,tolled,toned,voted,waited,waked,walled,waned,welled,winged,wiped,wired,yelled,zoned,abutted,banded,beat,blotted,cast,cost,dealt,dialed,feared,folded,footed,fretted,handed,headed,healed,heard,heeded,hurt,knitted,landed,leaked,leapt,linked,meant,minded,molded,neared,needed,peaked,peeled,plotted,quit,read,reaped,reeled,rooted,scarred,sealed,seeded,seeped,shipped,showed,shut,skimmed,slammed,slipped,sparred,stemmed,stirred,suited,thinned,trotted,weeded,winked¦5:basted,cheated,chimed,clouded,coveted,eloped,enrolled,equaled,eroded,exiled,guided,prided,quelled,rivalled,routed,scared,scouted,shored,sloped,smelled,smoked,sniped,spelled,spited,staked,stared,stored,sweated,tasted,treated,untied,wasted,breaded,cleared,debuted,deterred,equipped,freaked,modeled,pleaded,rebutted,refitted¦6:cringed,deleted,impaled,invited,recited,revered,strolled,thrust,unfolded¦7:combined,competed,conceded,convened,destined,extruded,retreated,remodelled,rescinded,welcomed¦8:backfired,expedited,infringed¦9:interfered,persevered,programmed,proofread¦eat:ate¦is:was¦go:went¦are:were¦3d:bent,lent,rent,sent¦3e:bit,fled,hid,lost¦3ed:bled,bred,sped¦2ow:blew,grew¦1uy:bought¦2tch:caught¦1o:did¦1ive:dove,gave¦2aw:drew¦2ed:fed¦2y:flew,laid,paid,said¦1ight:fought¦1et:got¦2ve:had¦1ang:hung¦2ad:led¦2ght:lit¦2ke:made¦2et:met¦1un:ran¦1ise:rose¦1it:sat¦4e:slid¦1eek:sought¦1each:taught¦1eave:wove¦2ise:arose¦1ear:bore,tore,wore¦1ind:bound,found,wound¦2eak:broke¦2ing:brought,swung,wrung¦1ome:came¦2ive:drove¦1ig:dug¦1all:fell¦2el:felt¦4et:forgot¦1old:held¦2ave:left¦1ing:rang,sang¦1ide:rode¦1ink:sank¦1ee:saw¦2ine:shone¦1ell:sold,told¦4d:spent¦2in:spun¦2ink:stunk¦1ake:took¦1in:won"
  },
  "PresentTense": {
    "fwd": "1:oes¦1ve:as",
    "both": "1:xes¦2:zzes,ches,shes,sses¦3:iases¦4:ocuses¦2y:llies,plies¦1y:cies,bies,ties,vies,nies,pies,dies,ries,fies¦:s",
    "rev": "1ies:ly¦2es:go,do¦3es:cho,eto",
    "ex": "2:does,goes¦3:gasses¦is:are¦3y:relies¦2y:flies¦2ve:has"
  },
  "Superlative": {
    "fwd": "1st:e¦1est:l,m,f,s¦1iest:cey¦2est:or,ir¦3est:ver",
    "both": "4:east¦5:hwest¦5lest:erful¦4est:weet,lgar,tter,oung¦4most:uter¦3est:ger,der,rey,iet,ong,ear¦3test:lat¦3most:ner¦2est:pt,ft,nt,ct,rt,ht¦2test:it¦2gest:ig¦1est:b,k,n,p,h,d,w¦iest:y",
    "rev": "1:ttest,nnest,yest¦2:sest,stest,rmest,cest,vest,lmest,olest,ilest,ulest,ssest,imest,uest¦3:rgest,eatest,oorest,plest,allest,urest,iefest,uelest,blest,ugest,amest,yalest,ealest,illest,tlest,itest¦4:cerest,eriest,somest,rmalest,ndomest,motest,uarest,tiffest¦5:leverest,rangest¦ar:urthest¦3ey:riciest",
    "ex": "best:good¦worst:bad¦5est:great¦4est:fast,full,fair,dull¦3test:hot,wet,fat¦4nest:thin¦1urthest:far¦3est:gay,shy,ill¦4test:neat¦4st:late,wide,fine,safe,cute,fake,pale,rare,rude,sore,ripe,dire¦6st:severe"
  },
  "AdjToNoun": {
    "fwd": "1:tistic,eable,lful,sful,ting,tty¦2:onate,rtable,geous,ced,seful,ctful¦3:ortive,ented¦arity:ear¦y:etic¦fulness:begone¦1ity:re¦1y:tiful,gic¦2ity:ile,imous,ilous,ime¦2ion:ated¦2eness:iving¦2y:trious¦2ation:iring¦2tion:vant¦3ion:ect¦3ce:mant,mantic¦3tion:irable¦3y:est,estic¦3m:mistic,listic¦3ess:ning¦4n:utious¦4on:rative,native,vative,ective¦4ce:erant",
    "both": "1:king,wing¦2:alous,ltuous,oyful,rdous¦3:gorous,ectable,werful,amatic¦4:oised,usical,agical,raceful,ocused,lined,ightful¦5ness:stful,lding,itous,nuous,ulous,otous,nable,gious,ayful,rvous,ntous,lsive,peful,entle,ciful,osive,leful,isive,ncise,reful,mious¦5ty:ivacious¦5ties:ubtle¦5ce:ilient,adiant,atient¦5cy:icient¦5sm:gmatic¦5on:sessive,dictive¦5ity:pular,sonal,eative,entic¦5sity:uminous¦5ism:conic¦5nce:mperate¦5ility:mitable¦5ment:xcited¦5n:bitious¦4cy:brant,etent,curate¦4ility:erable,acable,icable,ptable¦4ty:nacious,aive,oyal,dacious¦4n:icious¦4ce:vient,erent,stent,ndent,dient,quent,ident¦4ness:adic,ound,hing,pant,sant,oing,oist,tute¦4icity:imple¦4ment:fined,mused¦4ism:otic¦4ry:dantic¦4ity:tund,eral¦4edness:hand¦4on:uitive¦4lity:pitable¦4sm:eroic,namic¦4sity:nerous¦3th:arm¦3ility:pable,bable,dable,iable¦3cy:hant,nant,icate¦3ness:red,hin,nse,ict,iet,ite,oud,ind,ied,rce¦3ion:lute¦3ity:ual,gal,volous,ial¦3ce:sent,fensive,lant,gant,gent,lent,dant¦3on:asive¦3m:fist,sistic,iastic¦3y:terious,xurious,ronic,tastic¦3ur:amorous¦3e:tunate¦3ation:mined¦3sy:rteous¦3ty:ain¦3ry:ave¦3ment:azed¦2ness:de,on,ue,rn,ur,ft,rp,pe,om,ge,rd,od,ay,ss,er,ll,oy,ap,ht,ld,ad,rt¦2inousness:umous¦2ity:neous,ene,id,ane¦2cy:bate,late¦2ation:ized¦2ility:oble,ible¦2y:odic¦2e:oving,aring¦2s:ost¦2itude:pt¦2dom:ee¦2ance:uring¦2tion:reet¦2ion:oted¦2sion:ending¦2liness:an¦2or:rdent¦1th:ung¦1e:uable¦1ness:w,h,k,f¦1ility:mble¦1or:vent¦1ement:ging¦1tiquity:ncient¦1ment:hed¦verty:or¦ength:ong¦eat:ot¦pth:ep¦iness:y",
    "rev": "",
    "ex": "5:forceful,humorous¦8:charismatic¦13:understanding¦5ity:active¦11ness:adventurous,inquisitive,resourceful¦8on:aggressive,automatic,perceptive¦7ness:amorous,fatuous,furtive,ominous,serious¦5ness:ample,sweet¦12ness:apprehensive,cantankerous,contemptuous,ostentatious¦13ness:argumentative,conscientious¦9ness:assertive,facetious,imperious,inventive,oblivious,rapacious,receptive,seditious,whimsical¦10ness:attractive,expressive,impressive,loquacious,salubrious,thoughtful¦3edom:boring¦4ness:calm,fast,keen,tame¦8ness:cheerful,gracious,specious,spurious,timorous,unctuous¦5sity:curious¦9ion:deliberate¦8ion:desperate¦6e:expensive¦7ce:fragrant¦3y:furious¦9ility:ineluctable¦6ism:mystical¦8ity:physical,proactive,sensitive,vertical¦5cy:pliant¦7ity:positive¦9ity:practical¦12ism:professional¦6ce:prudent¦3ness:red¦6cy:vagrant¦3dom:wise"
  }
}