import test from 'tape'
import nlp from '../_lib.js'

test('fromSpec ignores or uses supplied tags', t => {
  const normal = nlp.fromSpec('dog {Verb}')
  t.ok(normal.has('#Noun'), 'default uses normal tagging')
  t.deepEqual(normal.failures, [], 'default skips validation')
  const supplied = nlp.fromSpec('dog {Past}', { tags: 'use' })
  t.ok(supplied.has('#PastTense'), 'alias applied')
  t.ok(supplied.has('#Verb'), 'parent tag inherited')
  t.notOk(supplied.has('#Noun'), 'normal tagger did not run')
  const partial = nlp.fromSpec('dog slept {.,Vb|Past}', { tags: 'use' })
  t.equal(partial.docs[0][0].tags.size, 0, 'wildcard adds no tags')
  t.ok(partial.match('slept').has('#PastTense'), 'multiple tags applied')
  t.equal(nlp.fromSpec('dog', { tags: 'use' }).docs[0][0].tags.size, 0, 'tagless text stays untagged')
  t.throws(() => nlp.fromSpec('dog slept {Vb}', { tags: 'use' }), /expected 1 terms, got 2/, 'cannot assign a misaligned spec')
  t.throws(() => nlp.fromSpec('dog {Vb?}', { tags: 'use' }), /invalid slot/, 'cannot assign invalid syntax')
  t.end()
})

test('fromSpec failure modes and testSpec agree', t => {
  const spec = 'dog {Noun}\nslept {Adj}\nplain text'
  const retained = nlp.fromSpec(spec, { failures: 'retain' })
  t.equal(retained.failures.length, 1, 'retain reports mismatch')
  t.notOk(retained.has('dog'), 'passing line omitted')
  t.ok(retained.has('slept'), 'failing line retained')
  t.ok(retained.has('plain text'), 'tagless line retained')
  t.deepEqual(retained.failures, nlp.testSpec(spec, false).failures, 'wrapper shares diagnostics')
  t.equal(retained.text(), nlp.testSpec(spec, false).text(), 'wrapper shares returned text')
  t.throws(() => nlp.fromSpec(spec, { failures: 'throw' }), /missing #Adj/, 'throw validates')
  t.ok(nlp.fromSpec('dog {Noun}', { failures: 'throw' }).has('dog'), 'throw retains successful text')
  t.ok(nlp.fromSpec(spec).has('dog'), 'ignore keeps successful text')
  t.ok(nlp.fromSpec(spec).has('slept'), 'ignore keeps mismatching text')
  t.end()
})

test('using supplied tags validates the resulting document', t => {
  const used = nlp.fromSpec('dog {Verb}', { tags: 'use', failures: 'retain' })
  t.deepEqual(used.failures, [], 'supplied tags satisfy validation')
  t.equal(used.found, false, 'passing constructed line omitted')
  const negative = nlp.fromSpec('dog {!Noun}', { tags: 'use', failures: 'throw' })
  t.equal(negative.docs[0][0].tags.size, 0, 'negative constraint adds no tag')
  const contradictory = nlp.fromSpec('dog {Noun|!Noun}', { tags: 'use', failures: 'retain' })
  t.equal(contradictory.failures.length, 1, 'contradiction fails')
  t.ok(contradictory.has('#Noun'), 'retained View preserves assigned tags')
  const contraction = nlp.fromSpec("she didn't walk {Noun,Vb,Negative,Vb}", { tags: 'use', failures: 'throw' })
  t.equal(contraction.docs.flat().length, 4, 'contraction split once')
  t.deepEqual(contraction.failures, [], 'constructed contraction validates')
  t.end()
})
